release-notes/latest.md
Noticed that the issue links from the email and on the GitHub repo don't
point to the correct place. This change uses an absolute link to the
VSCode site.
=> Pointed issue links to the correct issue page

editor/tasks.md
Addressed some spelling and punctuation problems in the Editor --> Tasks documentation
=> Corrected some spelling and punctuation mistakes in editor/tasks.md

docs/editor/tasks.md
Removed a trailing comma from the JSON code snippet provided in the "Variables in tasks.json" section of the Editor --> Tasks page.
=> Remove trailing comma from code snippet

docs/editor/tasks.md
Removed an unnecessary, empty object literal from the code snippet provided in the Task Specific Properties section of the Editor --> Tasks page.
=> Remove empty object literal from code snippet

docs/runtimes/ASPnet5.md
Changed the word "you" to "your".
=> Fix minor typo in 'Commands with Ease' section

docs/runtimes/ASPnet5.md
Added Gulp to the list of npm modules to be installed globally, per the installation recommendations [here](http://yeoman.io/learning/index.html). By default, generator-aspnet will use Gulp instead of Grunt.
=> Add gulp to npm install -g command

docs/editor/codebasics.md
As Q&A'd at http://stackoverflow.com/questions/33271488/shortcut-key-for-switching-between-split-panes/33276179#33276179
=> Added instructions for keyboard switching between editors

docs/editor/codebasics.md, docs/languages/csharp.md
Minor change to make an ASP.NET 5 reference consistent with other references throughout the documentation. Changed "ASP .Net v5" to "ASP.NET 5".
=> Fix inconsistent references to ASP.NET

docs/languages/markdown.md
Added 2 missing semi-colons and a return statement. See [this PR](https://github.com/aspnet/Templates/pull/206) for more info on the return statement.
=> Add missing semi-colons and return statement to gulpfile.js

docs/languages/javascript.md
Removed some unnecessary dashes and addressed a few consistency problems in the Languages --> JavaScript documentation page.
=> Fix typos and consistency problems in JS Language docs

docs/languages/javascript.md
Changed a "jshint" and an "eslint" reference to "JSHint" and "ESLint", respectively. This makes the documentation consistent with how it's used elsewhere on the Languages --> JavaScript page.
=> Fix consistency issue with JSHint and ESLint references

docs/customization/keybindings.md
The key binding for the Git button on the view bar was missing, yet the key bindings for the view bar's other 3 buttons are listed. This PR adds the key binding for Git.
=> Add key binding for Git view

docs/languages/json.md
Corrected a misspelling of the word "referred" in the JSON language documentation.
=> Fix minor spelling mistake in JSON language docs

docs/languages/javascript.md
With today's VS Code release, JSHint and ESLint support is now provided via extensions in the marketplace. The docs needed to be updated to make it clear that the settings to enable these linters are only available after installing the extensions. This PR addresses the following issue: https://github.com/Microsoft/vscode-docs/issues/40
=> Update JS linting docs for JSHint and ESLint extensions

docs/runtimes/ASPnet5.md
The `dnx: web` command listed in the "Commands with Ease" section for ASP.NET 5 is invalid. The colon must be removed to make it match what appears in Command Palette.
=> Remove colon from ASP.NET 5 dnx web command

docs/languages/javascript.md
The explanation of the code snippet in the "Run Babel inside VS Code" section is misleading. The text makes it seem as though there's a directory named "lib-directory" and another one named "src-directory".
=> Fix src and lib directory verbiage

docs/languages/javascript.md
This PR fixes some small problems with the descriptions of the `curlyBracketsMustNotBeOmitted`, `primitivesInInstanceOf`, `tripleSlashReferenceAlike`, and `unknownTypeOfResults` JS validation settings.
=> Remove unnecessary characters from JS Validation Settings table

docs/editor/versioncontrol.md
Declaring that git must be installed, not that in spite of it not being installed you still need to install it.
=> Use "so" instead of "but"

docs/editor/codebasics.md
There's a colon missing from the first paragraph of the "Basic Layout" section of EDITOR --> The Basics docs.
=> Add missing colon to Basic Layout paragraph

docs/editor/codebasics.md
"Spelled out" the meaning of the PATH environment variable and the concept of "dirty" files to make this introductory document more accessible to a beginner-level programmer/developer audience.
Added the Oxford comma where needed, since Microsoft specifies that it should be included (see Microsoft Manual of Style, 4th Edition (2012), p. 190).
Added a space between images and text within the "Quick File Navigation" section to make it easier to understand which instruction corresponds to which image.
Placed several additional file names / examples in the "code/monospace" style to help their presence be more noticeable to readers scanning a section of this document.
=> Minor style, grammatical, and info changes

docs/languages/javascript.md
There is an unnecessary dash between the words "ES6" and "types" in the "ES6 Support" section.
=> Remove unnecessary dash in ES6 Support section

docs/editor/codebasics.md
Clarify the documentation for the Ctrl-Tab switcher to make it clear you need to hold down Ctrl to show, then hit Tab to select and release to open. This also removes an incorrect reference to Cmd-Tab on Macs instead of Ctrl (Cmd-Tab gets you the system application switcher).
=> Clarify documentation for Ctrl-Tab switcher

docs/editor/editingevolved.md
On windows, the Intel driver (didn't test others) by default overwrites the multi-line shortcuts with screen rotate.
=> added note about existing shortcuts

docs/editor/extension-gallery.md
Users are not sure how to install extensions when they land on this page from the gallery. This commit adds more focus to installing from the product.
=> Updated landing page from extensions gallery.

README.md, docs/customization/colorizer.md, docs/customization/themes.md, docs/customization/userdefinedsnippets.md, docs/editor/debugging.md, docs/editor/extension-gallery.md, docs/editor/setup.md, docs/editor/tasks.md, docs/editor/versioncontrol.md, docs/extensions/example-debuggers.md, docs/languages/javascript.md, docs/languages/overview.md, docs/runtimes/office.md, docs/supporting/errors.md, docs/supporting/faq.md, docs/supporting/howtoupdate.md, docs/tools/vscecli.md
These patches change http links to https for domains that support HTTPS, for better privacy and security.
=> Use https wherever possible

docs/tools/vscecli.md
Update the docs to reflect that the `vsce` options `--baseContentUrl` and `--baseImagesUrl` belong to the `package` command, not the `publish` command. 
reference: https://github.com/Microsoft/vscode-vsce/blob/master/src/main.ts
=> Fix vsce steps for packaging with baseImagesUrl or baseContentUrl

docs/editor/setup.md
The advice to use `--args $*` is bad for any filename with spaces in it:
```
touch 'a b'
touch 'c d'
code 'a b' 'c d'
```
The results are:
* `--args $*`: VSC opens four files named `a`, `b`, `c`, and `d`
* `--args "$*"`: VSC opens one file named `a b c d`
* `--args "$@"`: VSS opens two files named `a b` and `c d` (correct)
The `fish` examples might also need checking.
=> Fix args expansion for code function in profile

docs/languages/typescript.md, docs/runtimes/nodejs.md
This is a fix of a typo in "target": "es5".
=> fixed ES5 in "target": "es5"

docs/editor/setup.md
The section in [Setting up Visual Studio Code](https://code.visualstudio.com/docs/editor/setup) on OS X has a problem. Specifically, the tip for running VS Code from the OS X terminal contains a bug. The code in question:
function code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; }
There are two issues here. First, the unquoted `$*` is subject to word splitting and globbing. As is, this function will not work with file names containing spaces, something well within the user domain on OS X. For example, `code foo\ bar` will cause VS Code to open windows to two new buffers, one for `foo` and one for `bar`, when the intent was to open the file `foo bar` (note the embedded space).
The fix is simple. Replace `$*` with `"$@"`, which treats `foo\ bar` (or `'foo bar'` for …
=> Fixed bash functions to support names with spaces

docs/editor/codebasics.md
* ~~Linked `files.exclude` to settings details~~ leaving for #163 
* Added JavaScript exclusion for matching TypeScript files to the Tip
=> TS example for exclusion

release-notes/latest.md
Blog link now works from Github as well.
=> Absolute link

docs/extensionAPI/vscode-api.md
Change the word `das` to `has` in the description of
`onDidChangeTextEditorViewColumn` event.
=> Fix a typo in the window events section

docs/runtimes/nodejs.md
The doc says "Notice how the warnings no longer appear for`__dirname`" but the doc doesn't call attention to the warnings _before_ having the user install the fix with "typings install node --ambient".
A screenshot including the hover message might be helpful here.
=> Notice the warnings, before they go away!

docs/languages/json.md
The "JSON Schemas & Settings" section of the Languages --> JSON docs reference a `$scheme` attribute which doesn't exist. This PR corrects the problem by changing it to `$schema`.
=> Correct invalid $scheme attribute

docs/supporting/faq.md
=> Improve advice around fs.inotify.max_user_watches

docs/extensionAPI/extension-points.md
The example configuration shown contains an invalid type specifier that does not allow for a default value of null (the default value used in the example). Corrected this example to match the actual value used in the real typescript.tsdk setting definition.
=> Correcting invalid type value in configuration example.

release-notes/latest.md
In release-notes/latest.md It says: "operation system", it should say: "operating system"
=> Typo in "operating system"

blogs/2016/04/14/vscode-1.0.md, scripts/gulpfile.blog.js, scripts/templates/blog-template.html, scripts/templates/portaldocs-template.html
Includes images and other meta-data.
Must be included with the [corresponding PR](https://github.com/Microsoft/vscode-website/pull/284) in the vscode-website repo.
=> Add docs and blog page-specific OpenGraph social metadata

docs/customization/keybindings.md
This functionality already exists but isn't documented. See also https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/9508236-selection-split-into-lines-multi-cursor
=> Add documentation for editor.action.insertCursorAtEndOfEachLineSelected

docs/languages/typescript.md
The previous link pointed to an old wiki page; I have updated the link to the new handbook page.
The previous link also mistakenly referred to `tsconfig.json` as `typescript.json`.
=> Fix link and link text to tsconfig.json

docs/languages/javascript.md
The JavaScript language docs reference a `Reload Java Script` command, which doesn't exist in Command Palette. This PR changes the command reference to `Reload JavaScript Project`, which does exist in Command Palette.
=> Correct an invalid command name

docs/customization/keybindings.md
There's no way to preview how the docs are going to render on the website, right?
There's no default key binding for hiding the explorer?
=> Explain that Show Explorer key binding also toggles focus

docs/languages/csharp.md
The C# page referenced only the mono debugger. This changes it to talk about .NET Core, Desktop, and Mono.
=> Update C# Debugger information

docs/extensionAPI/extension-points.md
The word "activationEvent" is wrongly highlighted.
As it is just standard text and to align with the other usages of the same word within this document, I think the highlighting should be removed.
=> Remove highlighting of standard text

docs/languages/json.md
=> End json string with quote

docs/extensionAPI/vscode-api-commands.md
There was a super small typo probably from copying and pasting
=> Fixed vscode-api-commands.md typo

docs/editor/codebasics.md
I had to play with `-n` and `-r` to make sure which was which, this just adds a minimal note to the docs to make that explicit up front.
=> Clarify that `-n` is default open behavior at CLI.

docs/editor/tasks.md
The word "mandatory" was misspelled in the **Editor** -> **Tasks** -> **Defining a Problem Matcher** documentation.
=> Correct misspelling of mandatory in Tasks doc

docs/supporting/faq.md
@gregvanl are there other references in docs? I was suprised this was the only one (using global search for "uservoice" and "User Voice")
The connect widget is actually pointing to a forward link so its already updated. We do need to change the icon. Tracking that issue [here](https://github.com/Microsoft/vscode-website/issues/467).
=> Removed User Voice references and links. 

package.json, scripts/gulpfile.common.js
Fixes https://github.com/Microsoft/vscode-website/issues/464
@waderyan 
Two things to note:
1. To use this, we needed to upgrade our **markdown-it**, so it could support a `getAttr` method used by the new dependency I added.  Note that I set the required version to `"markdown-it": "^7.0.1"` (latest release).
2. Note that the dev dependencies for **markdown-it-external-links** says that it requires version `^6.0.4` of markdown-it as a devDependency [(see here)](https://david-dm.org/rotorz/markdown-it-external-links?type=dev).  Does this mean I can't use the latest markdown-it as I mentioned earlier?  Everything seems to work fine.
We should check that nothing renders in an unexpected way in the docs on PPE before we roll this out.
=> Markdown external links now open in new tab

docs/customization/keybindings.md
Key was added in https://github.com/Microsoft/vscode/commit/207a8e33145c09aaeaa99e44ee7599a4112cfbd4
=> Document key binding for `Reset Zoom`

docs/editor/integrated-terminal.md
Fixes #556
---
Note this is for `vnext`. @gregvanl feel free to merge and make your own improvements. I wasn't sure if an example was needed, it might get messy as the default set is quite big and may change across versions.
=> Add terminal.integrated.commandsToSkipShell docs

docs/editor/integrated-terminal.md
Altered the Copy & Paste commands for Linux % Windows to Ctrl+C and Ctrl+V as this appears to be the default at least as of release 1.4.
I also sent this as feedback on the article, but if I am mistaken feel free to ignore the Pull Request. Thank you.
=> updated integrated-terminal.md \\ Copy and Paste

docs/supporting/faq.md
The MP is working on an improvement to the install experience. They will need to link to something in our docs to find the VS code version.
=> Added FAQ to find version.

scripts/templates/blog-template.html, scripts/templates/portaldocs-template.html, scripts/templates/releasenotes-template.html
Regarding 
https://github.com/Microsoft/vscode-website/issues/408
Since we can only fit a 140 characters, descriptions are sometimes too long (except for the Updates pages which tend to be short).  Also, updates pages' descriptions seem to be more powerful than their sister titles.
=> Blog/docs tweet titles; Updates tweet descriptions

docs/languages/markdown.md
I believe that the VS Code markdown editor now targets CommonMark markdown using the Markdown-it library, instead of GFM using the marked library. This fixes the question and answer about GFM.
=> Fix GFM Question Since We're Using CommonMark

docs/languages/csharp.md
Add a link to my "Get started with VS Code using c# and .NET Core" tutorial on channel 9 under the "Installing C# Support" section.
=> Add link to Getting Started Tutorial

docs/extensions/example-language-server.md
```shell
WARNING -- WILL NOT HIGHLIGHT CODE BLOCK (```)
at /vscode-docs/docs/extensions/example-language-server.md
DUE TO ERROR :::Unknown language: "plaintext"
```
=> Remove non-existent language id (fix highlight.js error)

.gitignore, docs/introvideos/overview.md
There is a broken image on the intro videos overview page. This will fix it. 
[Problem Page](https://code.visualstudio.com/docs/introvideos/overview)
After Fix
Cause is that @pjmeyer and I deleted a video yesterday that wasn't being used. I failed to realize that the image of that old video was still being used.
=> Fix broken image on intro videos overview

docs/extensionAPI/extension-manifest.md
Example name does not match the pattern of "^[^A-Z]+$".
=> extension-manifest Spell example does not use lower case name

docs/customization/keybindings.md
Not all commands are listed in keybindings.md. This has led to at least one [feature request](https://github.com/Microsoft/vscode/issues/14266) for a command that already exists.
This change points users to the `Default Keyboard Shortcuts` file for more commands.
=> Add note about unbound commands in keybindings.md.

docs/introvideos/codeediting.md, docs/introvideos/configure.md, docs/introvideos/intellisense.md, docs/introvideos/overview.md
The order of the videos in the first post was not the same as the TOC. Also, the *next* links were not following the correct order.
=> Fix "next" links in intro videos

docs/supporting/requirements.md
Update [requirements page](https://code.visualstudio.com/docs/supporting/requirements) to be in sync with [Windows setup page](https://code.visualstudio.com/docs/setup/windows), which was recently updated to require .NET 4.5.2 (see #670).
=> Update requirements to .NET 4.5.2

blogs/2016/02/01/introducing_insiders_build.md, blogs/2016/05/23/evolution-of-insiders.md
Not mandatory, but I thought I'd go back and add this to all the previous Insiders-related posts.
=> Retroactively add Insiders social image to posts

release-notes/v1_8.md
Adds section explaining upgrade to Typescript 2.1 in VSCode 1.8
=> Add section on ts 2.1 to 1.8 release notes

docs/setup/linux.md
It's being removed in Chromium so it's probably not worth the effort to fix and validate it
=> Chromium SUID sandbox error can be ignored

docs/languages/javascript.md
@types is the prefered approach for managing d.ts. typings files. This updates the documentation use `npm install @types` instead of the `typings` tool
@waderyan can you take a quick look at the changes and let me know if you have any input or suggestions.
=> Update typings management section for JS to use @types instead of Typings

docs/languages/javascript.md
With VSCode 1.7.2+, we now use automatic typings acquisition to manage typings for JavaScript projects. This updates the documentation to explain what this is and how to enable it for a library.
=> Documenting Automatic Typings Acquisition for JavaScript

docs/languages/markdown.md
We use markdown-it instead of marked for the markdown extension, so it make sense to tell people to use the same tool for their markdown generation tasks.
=> Use markdown it for Markdown examples instead of marked

docs/runtimes/nodejs.md
- removed the setup steps for the typings file
- removed the description of the jsconfig.json file, since it is not needed for this walk through.
=> Runtime>Node: updated to 1.8 (removed the references to typings)

docs/editor/debugging.md
Please temporarily forget everything you know about sourcemaps, read this, and tell me if it could be helpful.
It might be too much information. On one hand, detailed info on how this process works may help some users help themselves. On the other hand, I don't want to scare users away by making this seem more complicated than it is. Most of the time, debugging with source maps just works. The rest of the time, it's usually one of the first 3 bullet points. 
The important ideas in the paragraphs before the bulleted list are
* We have to get the .js first before we can map .js <-> .ts
* The paths in the source map file have to be correct
If this should be a detailed explanation of everything that happens, it could be expanded. If it should be more of a basic troubleshooting list, it could …
=> Fix #713 - node sourcemap troubleshooting

docs/extensions/language-support.md, docs/languages/identifiers.md, docs/languages/overview.md
For #702
A complete list of all language identifiers as used by users (file associations) and developers.
The idea is that language extensions can add their identifiers there as well.
=> language identifiers reference

docs/editor/integrated-terminal.md
=> Clear terminal is now bound to ctrlcmd+k

docs/editor/integrated-terminal.md
=> Fix Linux copy/paste keybindings

docs/languages/markdown.md
The markdown example should not use two different kinds of headers.
=> Fixed inconsistency in markdown

docs/editor/whyvscode.md
#702 
- communicate value prop better
- added "pizazz" (e.g. "an editor that gets out of your way", "delightfully frictionless", "lightning fast", "make it your own", "built with love"... I was on a roll 😉)
- rewrote text to be more concise
- added headers and whitespace to make it more easily scannable
- updated content to reflect more recent state of affairs
- highlight customizability and extensibility more, as well as other key features that tend to be popular
There are enough changes it's probably easiest to read it directly from the branch:
https://github.com/mousetraps/vscode-docs/blob/125b0dedf71793f327058f8894d980be18d7ff34/docs/editor/whyvscode.md
=> refreshed "Why VS Code?" page

docs/editor/integrated-terminal.md
The menu no longer says "Toggle Integrated Terminal". It's just "Integrated Terminal". Looking at v1.8.1
=> Menu option just View -> Integrated Terminal

docs/editor/editingevolved.md
From https://github.com/Microsoft/vscode/pull/19699
The TypeDefinition api is not in 1.9, but should be in 1.10
=> Add Go to Implementation and Go to Type Definition Sections

docs/customization/keybindings.md
Related: https://github.com/Microsoft/vscode/issues/9988
=> Added `textCompareEditorVisible` when-clause context

docs/editor/codebasics.md, docs/editor/debugging.md
* Zen mode mention new settigns
* Debug: surface no launch.json debugging, automatic environment picking, add configuration from dropdown
I tried to find other places where we mention that debugging requires a folder but could not find that (since this is no longer needed).
fyi @weinand
=> debug: update docs from 1.9 release notes

docs/customization/keybindings.md
Run without debugging was added some time ago: https://github.com/Microsoft/vscode/issues/2780
but it's not on the keybindings page and also not in the online pdf/docx
I would edit the docx but since it's compressed/binary and thus won't turn up in the diff well, I'll leave that to a member.
=> Add Run command to keyboard shortcuts

docs/editor/intellisense.md
Parameter hints is an intellisense feature, so it should be present. (+ It was hard to find the way to disable property info popup without knowledge of the exact keywords)
=> Add parameterHints prop

release-notes/v1_10.md, release-notes/v1_5.md, release-notes/v1_6.md, release-notes/v1_7.md, release-notes/v1_8.md, release-notes/v1_9.md, scripts/gulpfile.common.js
Changes from using an inline script to scroll to the top of the page to using a href.
=> Use href="#" instead of Script to Scroll to Top of Release Notes

docs/languages/cpp.md
I struggled to find this information. I found it by chance in the autocompletion of the json file. I dont think it is documented anywhere.
The example could be shorter, but i guess its better to have a real example.
=> Describe the sourceFileMap section of launch.json

release-notes/v1_10.md
Used window title variable in defaults is ${activeEditorShort} - not ${activeEditorName}.
=> Fix reference to wrong window title variable

docs/extensionAPI/vscode-api-commands.md
Splits the Html preview docs out to its own section of the API complex commands documentation. Also adds notes on html preview security as part of https://github.com/Microsoft/vscode/issues/22103
=> Add secutity tips for the html preview

release-notes/v1_11.md
Noticed this when testing out each theme to see how the Workbench theming works.
=> Typo in Quiet Light theme name for release notes v1.11

release-notes/v1_11.md
@gregvanl I have added a note documenting a workaround in case keyboard dispatching does not work with scan codes.
=> Document workaround for keyboard dispatching

release-notes/v1_11.md
To comply with the rest of the document, highlight the boolean constant
'false' as code.
=> Highlight boolean constant as code

docs/extensions/example-language-server.md
I was not a very dutiful reader and somewhat skimmed the initial commands which lead me to pointing one instance of VS Code at the entire cloned repository.
Later when I read,
> Go to the VS Code instance containing the server code (see above) and press [...]
I was lost because I did not remember reading anything about opening dedicated instances.  A quick text search for _instance_ did not find anything earlier in the document, so I had to go back and re-read.
This adds a brief explanatory sentence that might be caught by a reader or at least provides something to search for when you encounter the text "see above".
=> Explain we have opened two VS Code instances (lang svr example)

release-notes/v1_12.md
Adding April iteration top localization contributors in Transifex for vscode projects.
=> Recognition of top localization contributors in release notes

docs/languages/javascript.md
Adds an example of how a user can use global variables with `@ts-check`
=> Add section on globals and ts-check

docs/setup/linux.md
Added a line between initial two OpenSuse commands for install.    If system requests password for initial command, and the user had pasted both lines.  It advises incorrect password.   Even after putting the correct password, the second command is not executed. (repo is not added).    This change just tries to clarify that a little bit...
=> Clarification for OpenSuse

release-notes/css/inproduct_releasenotes.css
**Bug**
Ugly blue outline on scroll to top button in release notes:
**Fix**
Disable this outline
=> Disable blue outline on scroll to top button

docs/extensions/example-word-count.md
It looks unnecessary to call twice in the same function.
Besides, the second call has a comment.
=> Removed an extra call to updateWordCount

docs/languages/csharp.md
Omnisharp and VS Code support CSX files (C# scripts) for a few months now. Updated the docs accordingly.
=> updated with CSX info

docs/extensions/yocode.md
The documentation for how to fix Yeoman in Windows 10 didn't work for me. I had to run command prompt with admin privileges before the arrow keys would work. I've gone ahead and updated the documentation in this pull request.
It seems as though this is actually being caused by an NPM bug:
https://github.com/nodejs/node/issues/13557
=> Windows 10 Yeoman Fix

docs/editor/command-line.md
url to open a file to line and column uses ':', not '?'.
=> fixed url to open a file to line and column

docs/extensions/testing-extensions.md
Also clarify what the defaults are.
See Microsoft/vscode-extension-vscode#70. This change needs to be in tandem with that PR.
=> Update doc for code extensions path env var

docs/languages/go.md
This was added by https://github.com/Microsoft/vscode-go/issues/581
`This feature is now available in the latest update (0.6.54) to the Go extension`
related issue https://github.com/Microsoft/vscode-docs/issues/1082
=> adding missing go.testOnSave option

docs/supporting/faq.md
VS Code which has own EULA and is no open source software as opposed to Code OSS software which use open source MIT license. See Microsoft/vscode#17996.
=> Update OSS link to the right license for VS Code

docs/setup/mac.md
Adding `code` to my PATH didn't work using the Command Palette. Adding instructions to manually add this.
=> Add manual instructions for adding VS Code to PATH

docs/editor/codebasics.md
From my July changes
- Add note on `./` syntax
- Mention limitations of ripgrep regex search
- Mention the buttons for ignore files and settings
- "ignore files" includes just `.gitignore` and `.ignore` files where the latter is in the .gitignore format, but is just a non-git-specific name that `ripgrep` and the silver searcher support. It's not worth calling it out in the docs.
- Added new subtitle so the fwlink can link directly to the 'advanced options' section
cc @kieferrm
=> Improvements to search docs

docs/editor/versioncontrol.md
When I read this I wasn't sure what a "launch command" meant. Assuming it's a shell command that starts VS Code, I added text to specifying why waiting for VS Code would be useful when using Git.
=> Clarify what is waiting when --wait is used.

docs/editor/debugging.md, docs/getstarted/settings.md, docs/nodejs/nodejs-debugging.md
This ensures that there are vertical margins between the images and their surrounding text.
For example, the following markdown:
```markdown
foo
bar
```
is rendered as the following HTML:
```html
<p>foo</p>
<p>bar</p>
```
while
```markdown
foo
bar
```
is rendered as:
```html
<p>foo</p>
<p>
</p>
<p>bar</p>
```
We still use `<img>` tags at some other places because we need finer control over the images to overcome the limitations of Markdown so we embed inline attributes (such as `style="..."`, `width="..."`, or `<center><img src="..." /></center`) in those `<img>` tags.
=> Wrap <img> tags in paragraphs

docs/languages/php.md
1. Added note to install full version of PHP if using XAMPP.
2. Divided settings.json additions into Windows and Linux.
I know that we cannot predict every configuration, so I'm only using the default values. If anyone thinks I should add a note about this, let me know.
=> Add Linux information to Linting section

tutorials/nodejs-deployment/create-website.md, tutorials/nodejs-deployment/deploy-website.md, tutorials/nodejs-deployment/express.md, tutorials/nodejs-deployment/extensions.md, tutorials/nodejs-deployment/getting-started.md, tutorials/nodejs-deployment/publishing-changes.md, tutorials/nodejs-deployment/tailing-logs.md
This adds the ability for users to report issues with our node deployment tutorials.  It requires that [PR 659](https://github.com/Microsoft/vscode-website/pull/659) is first integrated and deployed for the VScode-website repo.
See screnshots below for FF/IE/Edge/Chrome to see what this looks like:
=> Add feedback to our node deployment tutorials

docs/languages/csharp.md
It seems unnecessary to mention that Unity developers use VS Code over MonoDevelop.
Unity developers can use VS for Mac already (optional) and you also recommend using it further in this document:
> If you want the best possible experience for those projects and development on Windows in general, we recommend you use [Visual Studio Community](https://www.visualstudio.com/products/visual-studio-community-vs).
=> [Language/C#] Remove unnecessary MonoDevelop hit

docs/extensions/themes-snippets-colorizers.md
Looks like it's renamed according to this commit https://github.com/Microsoft/vscode-generator-code/commit/a88ba5be8581055123d35b5f7108643b94df0828
=> Fix outdated doc

docs/extensions/themes-snippets-colorizers.md
The extraneous comma would cause using the example to fail in a JSON theme definition.
=> remove extraneous comma from example

docs/languages/css.md
The file names in the tasks do not match the example
=> Fix file names in both tasks templates

docs/extensions/themes-snippets-colorizers.md
Looks like it must be `more than that` instead of `more than than`
=> Small typo fix for 'docs/extensions/themes-snippets-colorizers.md'

docs/extensionAPI/extension-points.md
A small change to add some basic information on how to use the `off-side` code folding and folding markers introduced in `1.17` in the `language-configuration.json`.
=> Added documentation for "folding" section in language configuration

docs/extensions/themes-snippets-colorizers.md, docs/getstarted/themes.md, release-notes/v0_8_0.md, release-notes/v0_9_0.md
The domain of color sublime was recently changed (https://github.com/Colorsublime/Colorsublime-Themes/issues/364) in favor of a github.io (https://colorsublime.github.io) alternative.
And since they went fully static, the download links also changed to just point to the raw files on the repo.
=> Update color sublime url

docs/setup/linux.md
✍ This fixes typo in line 99: **are are** to **are**
=> Fix repeated word typo

docs/editor/accessibility.md
NVDA 2017.3 has shipped with a change that no longer makes necessary the usage of a NVDA plugin for a good experience with VS Code.
=> Update NVDA recommendation

release-notes/v1_18.md
After looking into how `kbstyle` gets applied and other uses of it, I could only guess that the spaces were messing up the way the keybinding was rendered when viewing the release notes from within VS Code. 
On Windows this shows `Ctrl Unknown`
On Mac this shows `unassigned`
If this isn't the proper fix, please close.
=> Fix for keybinding improperly rendering in VS Code view of Release notes

docs/languages/python.md
Python extension is now under Microsoft namespace, changing link to avoid 404 Not Found
=> Changing link to Python extension

docs/editor/userdefinedsnippets.md
Single escape character is not accepted, whereas double works fine
=> Fix example using a variable in a snippet

docs/java/java-debugging.md
This PR fixes the URL for "Java Extension Pack" link which had a typo in the URL (**hhttps** instead of https). This results in having a broken link on the following page: https://code.visualstudio.com/docs/java/java-debugging (search for "Java Extension Pack" on that page). It doesn't repro when the markdown file is viewed on GitHub.
=> Fixing the broken hyperlink for "Java Extension Pack"

docs/python/debugging.md
Closes microsoft/vscode-python#299
=> Specify ptvsd 3.0.0 or later is required for remote debugging in Python

release-notes/v1_19.md
Add support for macOS's NSFindPboard, which is a global shared find buffer. This allows one to put text into the find buffer from other native apps like Chrome, TextEdit, Safari, Sublime, etc. and then switch to other Cocoa apps and use cmd-g to find next matching text. 
Pull request for this change is https://github.com/Microsoft/vscode/pull/35956
=> Add support for macOS NSFindPboard as an action

docs/editor/tasks.md
I recently needed to run some tasks using a specific Python virtualenv
and hadn't known that this was possible before searching through the
issue tracker and finding a maintainer's comment:
https://github.com/Microsoft/vscode/issues/23597#issuecomment-290329622
=> Tasks: document use of config settings

docs/python/linting.md
Change flake8 to mypy in appropriate section.
=> Fix typo in Python linting docs

docs/editor/integrated-terminal.md
The cmder terminal always change back to the current user directory, so record the working directory and change back to the working directory after cmder init.
=> improve the cmder terminal

docs/extensionAPI/vscode-api.md
These are some of the things I wish I had known before using the `TextDocument` event listeners.
cc @jrieken re: Microsoft/vscode#40653
=> Add note to differentiate btw TextDoc & TextEditor

docs/extensions/example-hello-world.md
The path of the `extention.ts` file in the generated code is different from the document.
=> Change the path of extension.ts

docs/languages/java.md
I assume third-party modules was the intended phrase vs thirty-party modules
=> Fixed small typo

docs/other/unity.md
Mention OS requirements to install .NET Core and Mono
Installing .NET Core ensures that `dotnet` CLI is installed.
Installing Mono avoids "Some projects have trouble loading. Please review the output for more details".
=> Add missing OSX prerequisite steps

docs/getstarted/tips-and-tricks.md
Erroneous page title 'Visual Studio Tips and Tricks' is confusing to users finding this page via a search engine. Corrected to 'Visual Studio Code Tips and Tricks'.
=> Corrected page title from VS to VS Code

docs/setup/network.md
Added `raw.githubusercontent.com` to the section "Common hostnames" of network.md, since access to that host is needed so you can see the screenshots and pictures in the extensions pages at both VS Marketplace website and at the VS Code "Extensions" view.
Also added `vsmarketplacebadge.apphb.com` so the Marketplace Status Badges can be seen inside the VS Code "Extensions" view.
=> Added two hostnames to network.md

release-notes/v1_20.md
@gregvanl This should still go into a _recovery_ docs build. Thanks!
=> Improve git commit input validation documentation

docs/other/dotnet.md
As of .NET Core 2, a restore now happens automatically so there is no need to explain how to do this.
=> Update C# documentation to remove 'dotnet restore' instructions

docs/extensions/publish-extension.md
In current Usage section https://code.visualstudio.com/docs/extensions/publish-extension#_usage
it is too much about publishing, and it skipped 2 essential steps before publishing
=> more clearly hint to use login, package before publish

tutorials/app-service-extension/deploy-app.md
This adds a hint on locating the most common error that we've seen to
date and suggest contacting us with more detail if they aren't able to
get the error fixed.
=> Add a hint for dealing with failed deployments.

docs/supporting/live-share-faq.md
We had previously updated the FAQ to mention VS Code Insiders as a pre-req for using Live Share. However, we did some work to no longer require this, and so, this PR simply updates the tooling question, in order to represent the support for both the Stable and Insiders build of VS Code.
=> [Live Share] Updating FAQ to mention support for the Stable build

docs/editor/codebasics.md
Dragging while holding the modifiers is not sufficient. The cursor first needs to be placed in one corner of the desired box selection without holding the modifiers.
=> Clarify column selection

docs/nodejs/reactjs-tutorial.md
Was: it's dependencies. Changed it to its dependencies.
=> Fix typo in reactjs-tutorial.md

docs/languages/typescript.md
This precision could avoid confusion for new VS Code or TypeScript users between the options that has to be changed in the User Settings of VS Code and the one that has to be changed in the tsconfig.json file.
=> Precise the file to update for changing options

docs/getstarted/keybindings.md
As named in vscode: https://github.com/Microsoft/vscode/blob/728f71d1bf7f7f99ce58fee8206ac1848268892d/src/vs/base/common/keyCodes.ts#L356
=> Fix typo nupad_separator -> numpad_separator

docs/supporting/live-share-faq.md
Now that VS 2017 15.6 RTW is released, this PR simply updates the FAQ to call out the support for Live Share in the latest VS and VS Code stable bits.
=> [Live Share] Updating FAQ to call out VS 15.6 RTW support

docs/python/debugging.md
Fixes #1451 
NOTE: This change needs to be done after the next version of the Python extension is released.
That's slated for sometime around the first week of March.
=> Update flask debug docs to remote reference to python issue

docs/nodejs/nodejs-debugging.md
The current doc shows `7.4` as the version where Electron started supporting the new debugger, but it was actually `1.7.4`. See https://electronjs.org/releases#1.7.4
=> Fix Electron version numbers in Node.js debugging guide

docs/languages/markdown.md
- Adds a new section about extending the markdown preview using extensions
- Updates the 'using your own css' section. The referenced screenshot no longer seems to exist and the documentation was a bit out of date
=> Rework section on customizing the markdown preview

docs/java/java-tutorial.md
The forked repository (https://github.com/microsoft/gs-spring-boot) used in the Java tutorial does not work well on current Spring Boot.
The upstream one (https://github.com/spring-guides/gs-spring-boot) worked well in my environment.
=> Change the git repository to upstream repository

docs/getstarted/locales.md
Issue in loading logic of VS Code fixed. Now support 'tr'. No longer support 'trk'
=> Change Turkish Language ID to 'tr'

docs/languages/javascript.md
Simply following the guide from the beginning, this command is not available at the moment that it's suggested, which will be confusing and likely result in wasted time trying to figure out why to people setting up their IDE.
=> Add details on checking TS version

docs/python/debugging.md
The previous word was "directly", but the meaning is "directory".
=> Corrected the typo in 'cwd'

tutorials/functions-extension/getting-started.md
The Azure Functions core tools no longer require the .NET core SDK to be
installed. This includes the instructions for macOS and Windows and
links out for Linux because there are a few extra setps depending on
the distro.
=> Update instructions for installing Functions CLI.

docs/python/linting.md
Also drop a markup mistake and de-emphasize `pep8` (it's an old name for pycodestyle which is part of flake8).
=> Add links to linter table

docs/editor/integrated-terminal.md
terminal.integrated.shellArgs.* only specifically referred to
Linux and macOS, when it in fact also exists for Windows
=> Clarify that shellArgs can also be used on Windows

docs/editor/tasks.md
* change `Node Saas` to `Node Sass`
* Add missing `$` to `$node-sass`
=> Node-sass related typo fix in tasks docs

release-notes/v1_22.md
@gregvanl Forgot to include the tree horizontal scrolling item in the release notes:
https://github.com/Microsoft/vscode/issues/15539
=> Release notes: tree horizontal scrolling

docs/editor/tasks.md
The handcrafted tsc problemMatcher example does not match errors with **location**s that consists of **2 numbers**.
Example:  `src/subfolder/Example.ts(52,42): error TS2300: Duplicate identifier 'DuplicatedIdentifier'.`
=> Tasks example problemMatcher regexp fix

docs/editor/codebasics.md
The search for folder and file names is case sensitive by default. I have added a question to capture this.
=> Capture the case sensitive nature of search

docs/getstarted/theme-color-reference.md
Add `editorIndentGuide.activeBackground` reference to the colors which became available `April 2018 (version 1.23)`
**DEMO**: Theme [Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple)
=> 📦 ADD: editorIndentGuide.activeBackground

docs/python/debugging.md
See https://github.com/Microsoft/vscode-python/issues/1320#issuecomment-379162146
=> New default of "console" for Python launch options is "integratedTerminal"

blogs/2017/11/15/live-share.md
Now that Live Share is in public preview, we want to add a note to the original announcement blog post that people can readily download it and use it.
=> Updating Live Share annoucement post that it is now in Public Preview.

release-notes/v1_23.md
The change was reverted, see Microsoft/vscode#49162
=> Remove terminal clear changes from 1.23 notes

docs/extensions/example-word-count.md
Make use of consistent strict inequality (`!==`) symbol.
=> Fix typo in extensions word-count example

CONTRIBUTING.md
This PR improves the contribution guide by:
1. Using the right lingo for terms like `language identifier` and `code blocks`. 
2. Also adds a link to read more about syntax highlighting of code blocks i.e. https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
Peace! ✌️
=> 👌 IMPROVE: Documentation Lingo

docs/python/linting.md
The default values ​​of python.linting.lintOnSave do not match in the following two documents.
docs/python/settings-reference.md#linting-settings
docs/python/linting.md
=> Python linting lintOnSave 

docs/azure/docker.md
Updated the link to point to the right file in the Docker Docs.
The current link doesn't point to the right file anymore.
=> Update link to "Create a Docker group"

docs/python/linting.md
- Fix user config file path for Windows
- Remove sentence stating that only the first file is considered (I tried using two files simultaneously on my local install, and flake8 picked up configuration from both)
- Add `.flake8` file to allowable project config files (fixes https://github.com/Microsoft/vscode-python/issues/1884)
=> Fix flake8 config file docs

docs/python/linting.md
Adds a section detailing pydocstyle to the Python Linting documentation, to mirror what's in place for Pylint, mypy, etc
=> Add a section for pydocstyle to Python linting

docs/editor/integrated-terminal.md
The comment in the vscode.bat snippet causes the batch file to not work. This can cause confusion for beginners who may think it is okay to leave it in there, and may not understand what they are doing wrong. My update takes the comment out of the batch file.
=> Update docs on cmder

docs/editor/extension-gallery.md
I've been a user of the recommendation system in VS Code for a while and I didn't know of the auto-completion feature until it was pointed out to me by a member of the vscode team in this comment https://github.com/Microsoft/vscode/pull/50419#issuecomment-399203239 of this pull request https://github.com/Microsoft/vscode/pull/50419, since it is not present in the documentation.
Naturally, the phrasing and positioning could be different.
=> Auto-completion feature inside `extensions.json`

docs/python/python-tutorial.md
Correct version is referenced in https://code.visualstudio.com/docs/python/editing#_run-selectionline-in-terminal-repl
=> Fix the hotkey to run selected code

docs/python/editing.md
Updated to ⇧⏎ in this commit: https://github.com/Microsoft/vscode-python/commit/5eb48c276c9bffda5ab3b0f8335681b37187cacf
=> Update run in python terminal keyboard shortcut to shift+enter

docs/python/tutorial-flask.md
In the Go to Definition and Peed Definition Commands the directions referenced view.py which has not been created yet during the tutorial, updated to app.py instead.
The naming of __init.py__ is incorrect, changed to __init__.py
=> Updated tutorial-flask, minor changes for programs

release-notes/v1_25.md
Corrected markdown anchor link for sub-word navigation section
=> fix sub-word link in v1_25

docs/editor/userdefinedsnippets.md
In the "Creating your own snippets" tutorial, the section for Variable transform shows a example. Each part that is required for making a transform is pointed, but i think that part 3 - which is pointed as "no options" should point to the forward slash and not $1 which belongs to part 2 of the transform syntax.
=> Variable transform example - change part 3 pointer

docs/languages/csharp.md
Adding instructions for folks who first miss the prompt to add build and debug assets in an FAQ section. These instructions are also being added to the [dotnet docs](https://github.com/dotnet/docs/pull/6456) due to folks still occasionally missing the prompt.
@gregvanl
=> Add missing assets FAQ

docs/extensions/example-language-server.md
Hello,
English is not my native language and I had some trouble understanding this part.
* If the start and end positions are the same, VS Code will **_squiggle_** the word at that position.
* If you want to **_squiggle_** until the end of the line, then set the character of the end position to Number.MAX_VALUE.
I know it might seems unnecessary now that I understand. But I think putting some emphasis on the fact that VS Code is just underlying the word and not really _"doing"_ anything with it can make the documentation more easily understandable.
Let me know what you think.
Thanks a lot for reading,
=> Language change for example-language-server.md

docs/extensionAPI/extension-manifest.md, docs/extensionAPI/extension-points.md, docs/extensionAPI/language-support.md, docs/extensions/themes-snippets-colorizers.md, docs/languages/identifiers.md, release-notes/May_2016.md
- The recommended icon size should be 256x256. We'll always want icons to be sharp on every screen, so I added this note in parenthesis.
- I added the documentation for `contributes.grammars.embeddedLanguages`. This field is very useful because VS Code seems to use it to inherit language _features_, not just syntax highlighting.
- It took me a long time to figure out that the grammar file doesn't have to be a Plist file. generator-code does a good job of making that clear, but I didn't use it at first because I didn't know how to answer all its questions. I added the `.json` extension to all `.tmLanguage` files in code examples and explained that using JSON is more convenient to use.
=> Add stuff I didn't know about authoring (language) extensions

docs/editor/userdefinedsnippets.md
Created a small table that could be expanded to give a handful of common transformation examples. I am suggesting this based on difficulty I had in understanding how to interpret the Grammar section and not realizing certain things may need "double escaped".
=> Added snippet transform examples

docs/getstarted/introvideos.md, docs/introvideos/basics.md, docs/introvideos/debugging.md
Fixes #1706 
Changes:
- removes first intro video
- replaces basics with "getting started"
- updates debugging video.
=> Update intro video for getting started and debugging

docs/python/unit-testing.md
Change the Nose configuration example to enable Nose as opposed to pyTest
=> Fix typo in Python unit test config example

docs/setup/linux.md
Installed ```apt-transport-https``` before ```apt-get update``` as it's a dependency for external repositories accessed via https.
=> Add apt-transport-https

docs/java/java-container.md
Docker is not a Linux toolkit and VS Code is not a Linux editor, so I don't see a reason to single out Linux there.
=> Update Docker definition in java-container

docs/extensionAPI/api-debugging.md
This commit updates the DAP readme to add a link to the official webpage for the Debug Adapter Protocol.
=> (maint) Update Debug Adapter Protocol link

docs/extensions/example-language-server.md
With the current wording, it's not obvious to see if `package.json` file refers to the one in root directory, or client directory.
=> explicitly show which package.json file is referred to

docs/editor/extension-gallery.md, release-notes/v1_26.md
The setting's name is `extensions.autoCheckUpdates` ([vscode source](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensions.contribution.ts#L211)).
=> Fix typos in extensions.autoCheckUpdates setting name

docs/extensions/example-language-server.md
there was a missing left square bracket in a link
=> fixed broken markdown link formatting

docs/getstarted/introvideos.md
All the other videos are done using the number of whole minutes of the video - i.e. rounding down to the next minute. (3:54 -> 3 minutes)
Alternatively the durations could be to the nearest minute, but it would involve changing more of them (3:54 -> 4 minutes). Either way, the duration for "Debugging" is way out as it is now.
=> Update introvideos.md with correct video durations

docs/python/python-tutorial.md
Added the ${workspaceFolder} variable to provide python with the full path to the "hello.py" script - without which this code will not work.
=> Update launch.json path in python-tutorial.md

docs/python/python-tutorial.md
In the original text it refers to the debug "continue" command as the "run" command but those are different commands.  Once you start debugging, F5 is assigned to "continue" so I fixed the description  to change "run" to "continue" in that section and to remove the reference to pressing the green arrow (which generates an error message to the user saying that a debug session is already underway).
=> Fix description of the debugging process

docs/python/python-tutorial.md
Included:
- Change of "you" to "your"
- Use of code font for `matplotlib` and `numpy` (they are Matplotlib and NumPy when written)
- Mention of "Debian" as the Linux flavor that uses the `apt` package manager
- Switching snippets that invoke `pip` to instead use `python -m pip`
- Recommended `get-pip.py` instead of `apt install python3-pip` on Debian. This is for two reasons: so that the downloaded `pip` is the latest version and so that `pip` is not owned by `root`
- Updated latest Python 3 from 3.6.5 to 3.7.0
- Rephrased troubleshooting section about `.vscode/launch.json`
- Used PyPI instead of PyPi
- Broke up a run-on sentence about installing `matplotlib` from a Python Terminal in the Command Palette
=> Grammar, formatting and command changes to Python tutorial.

docs/getstarted/theme-color-reference.md
The new editor is not `Preview` anymore so replaced the instructions with `UI` instead.
=> 🐛 FIX: UI Editor Name

docs/extensions/testing-extensions.md
I added a section to include how to disable other extensions in the testing instance of VS Code while developing your own extension.
=> Updating Testing extensions page

docs/extensionAPI/language-support.md
GoRCodeLensProvider => GoCodeLensProvider
Below the fixed line there is `GoCodeLensProvider` call, not the `GoRCodeLensProvider` call
=> Fixed typo

docs/extensionAPI/vscode-api-commands.md
Adds a note to the `previewHtml` command that it is now deprecated. Delete the supporting material around this command, most of which is now covered by the webview documentation
=> Mark the preview html command as deprecated

docs/languages/typescript.md
Fix only example that doesn't put a space before the closing curly brace.
=> Consistent spacing in typescript.md

docs/extensions/example-language-server.md
link does not work in https://code.visualstudio.com/docs/extensions/example-language-server
=> example-language-server: link url

docs/setup/linux.md
I'm using Nodejs since 2012 and I prefer to install Node Version Manager vs pure Nodejs version installation. 
It's much easier for support and adding a new version.
=> I've added a paragraph related with Node Version Manager.

docs/extensionAPI/vscode-api-commands.md
Fixes a typo in docs/extensionAPI/vscode-api-commands.md where the word `return` is misspelled.
=> typo(return): vscode-api-commands.md

docs/python/editing.md
VSCode docs are wonderful for being link-rich, so I added some links to the different python formatting styles available in the official python extension
=> Added links to python formatters

docs/python/tutorial-django.md, docs/python/tutorial-flask.md
I think Django is pretty consistent about using the single word "superuser" and the use of the two words "super user" in the section title was the only use I found which didn't match.
The sub-list in the Flask page wasn't being formatted as a list (including [in the online VS Code docs](https://code.visualstudio.com/docs/python/tutorial-flask#_refactor-the-project-to-support-further-development)) so it was hard to read.
=> Trivial fixes in Python topic

docs/languages/php.md
- [hyphenation rule regarding adjectives](https://www.grammarbook.com/punctuation/hyphens.asp)
- [dropdown or drop-down](https://www.merriam-webster.com/dictionary/drop-down)
=> Fixed typos in PHP documentation

docs/nodejs/angular-tutorial.md, docs/nodejs/extensions.md, docs/nodejs/reactjs-tutorial.md
The [vscode-ios-web-debug project has been deprecated](https://github.com/Microsoft/vscode-ios-web-debug#deprecation-update) and extension removed from the Marketplace.
This PR removes references to this old extension and fixes up some surrounding wording.
Thanks for all your work on VSCode! 🙌✨
=> Remove broken link to iOS debugger extension

docs/python/environments.md
I found a broken internal jump link, so I fixed it.
=> Fix link to "manually specify an interpreter"

docs/editor/userdefinedsnippets.md
Added another case where snippet syntax does not follow the TextMate snippet syntax, that `\u` is not supported (resolves #1882)
=> doc: added Textmate snippet syntax exception for `\u` (#1882)

docs/getstarted/theme-color-reference.md
This PR adds missing colors in the theme color reference from the latest v1.28 release.
- `editor.snippetTabstopHighlightBackground`: Highlight background color of a snippet tabstop.
- `editor.snippetTabstopHighlightBorder`: Highlight border color of a snippet tabstop.
- `editor.snippetFinalTabstopHighlightBackground`: Highlight background color of the final tabstop of a snippet.
- `editor.snippetFinalTabstopHighlightBorder`: Highlight border color of the final tabstop of a snippet.
- `activityBar.inactiveForeground`: Activity bar item foreground color when it is inactive.
Peace! ✌️
=>  📖 DOC: add missing colors from v1.28

docs/python/tutorial-flask.md
This is a small change to add a link to the extension page on flask webiste, this way users than are new to Flask can get a rapid overview of available extensions.
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file;
(b) I understand and agree that this project and the contribution
are public and that a record of the contribution (including all
personal information I submit with it, including my sign-off) is
maintained indefinitely and may be redistributed consistent with
this project or the open source license(s) involved.
Signed-off-by: William Moreno Reyes williamjmorenor@gmail.com
=> Include a link a to the relevant extensions page in Flask ´s docs

docs/editor/portable.md
Provide further info that Portable Mode can help in corporate environments or if you want to change the extension installation folder. 
Make it clear that this mode prevents auto updates.
=> Update information on Portable Mode for Windows

docs/python/linting.md
Adds a few sections to the Python Linting docs on [Prospector](https://prospector.readthedocs.io/en/master/index.html).
=> Add documentation for the Prospector Python linting tool

docs/editor/portable.md, docs/setup/linux.md
As suggested: Adding a Link to the AUR package installation wiki site instead of detailed instlalation instructions.
=> Setup: add Arch Linux installation information

docs/editor/integrated-terminal.md
Menu option is "Terminal" instead of "Integrated Terminal" at this moment (version 1.28)
=> Updated integrated terminal tip

docs/python/editing.md
A missing (but essential) word and two periods.
=> Fix typos in python/editing.md

docs/languages/powershell.md
`ps1xml` files are PowerShell's way to extend the type system and define output formatting. It's possible to get awesome autocompletion, validation etc for them, but it's not obvious how to. This PR adds documentation for that. Since the schema of these files is quite complex, this makes a night and day difference in editing experience.
=> Add instructions for getting IntelliSense on PowerShell ps1xml files

docs/languages/csharp.md, docs/languages/css.md, docs/languages/html.md, docs/languages/javascript.md, docs/languages/json.md, docs/languages/markdown.md, docs/languages/overview.md, docs/languages/php.md, docs/languages/typescript.md
Greetings, 
I've removed multiple spaces from the language files, also fixed a [typo](https://github.com/Microsoft/vscode-docs/commit/1947da826fd81db5f80a2d7125467d470a4a1d5e#diff-96f708142354de732fffafacadd12b75R292).
=> Remove Multiple Spaces in Languages Docs

docs/setup/mac.md
The OS X El Capitan Public Beta was released in 2015, so I believe the "Common Questions" section with this item can be removed – more than happy to close this PR if you believe it should stay in however 😄
=> Remove outdated information about OS X El Capitan

docs/editor/userdefinedsnippets.md
The `"editor.tabCompletion"` setting offers 3 modes: `"on"`, `"off"` and `"onlySnippets"`. 
Using `"editor.tabCompletion": true` returns: 
```
Incorrect type. Expected "string".
Value is not accepted. Valid values: "on", "off", "onlySnippets".
```
=> Updated enable editor.tabCompletion setting

docs/python/python-tutorial.md, docs/python/tutorial-django.md
In general, it seems to be in the convention in the VS Code docs to use commas after introductory prepositional phrases.  These sentences were missing them.
=> Missing commas after introductory prepositional phrases

blogs/2018/08/07/debug-adapter-protocol-website.md
Changed web site to website, which seems to be the most common spelling form of the word (https://mashable.com/2010/04/16/ap-stylebook-website/#6UApZ3.hgiqc). Google even shows a "did you mean" if you search for "web site" : P
=> Update website spelling in Debug Adapter blog post

docs/setup/mac.md, docs/setup/windows.md
Setup for Mac and Windows has the following verbage for updates:
> VS Code ships monthly [releases](/updates) and supports auto-update when a new release is available. If you're prompted by VS Code, accept the newest update and it will be installed (you won't need to do anything else to get the latest bits). If you'd rather control VS Code updates manually, see [How do I opt out of auto-updates](/docs/supporting/faq.md#how-do-i-opt-out-of-vs-code-autoupdates).
Setup overview has the following verbage:
>VS Code releases a new version [each month](/updates) with new features and important bug fixes. Most platforms support auto updating and you will be prompted to install the new release when it becomes available. You can also manually check for updates by running **Help** > **Check for …
=> Docs: Syntax of updates in mac and windows to match setup overview 

docs/languages/markdown.md
I fixed a typo in an image path in "markdown.md" ("Outline View" section), which was preventing the image from being displayed.
=> Image Path Fix in "markdown.md"

docs/languages/cpp.md
It seems to be red squiggles under the include statements if a `#include` file or one of its dependencies cannot be found.
=> fix a mistake

docs/java/java-spring-boot.md
Fix link to correct one: https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-cosmosdb-spring-boot-sample instead of https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-documentdb-spring-boot-sample
=> Bad link to example Cosmos DB project

docs/java/java-tutorial.md
There is one “out” too many in 
> _“If you'd like […], check**out out** the tutorial […]“_
.
=> Fix “checkout out” typo/redundancy in java-tutorial.md

docs/extensionAPI/api-debugging.md, docs/extensions/example-debuggers.md, docs/getstarted/settings.md, docs/languages/css.md, docs/languages/javascript.md, docs/nodejs/nodejs-debugging.md, docs/nodejs/nodejs-tutorial.md, docs/setup/additional-components.md, docs/setup/linux.md, docs/setup/setup-overview.md, tutorials/nodejs-deployment/express.md
Per the npm team, npm should always be lowercase. I updated all
references in docs and tutorials, I left the blogs and release notes
alone.
See this blog post for more references on using npm vs NPM or Npm:
https://css-tricks.com/start-sentence-npm/
=> Standardize on casing of npm

docs/python/unit-testing.md
Closes #2068 
I decided to completely remove the paragraphs detailing the individual test frameworks, since these are explained more in-depth in the [linked section](https://code.visualstudio.com/docs/python/unit-testing#_test-framework-configurations) anyways.
=> Update Python test discovery docs

docs/editor/extension-gallery.md, docs/editor/integrated-terminal.md, docs/editor/portable.md, docs/editor/refactoring.md
This PR fixes a few typos in the editor section of the docs.
=> Fix a few typos in the editor docs

docs/python/tutorial-django.md
Under the section **Create A Django app**. We `import render` which is unnecessary. And under section **Use a template to render a page** we ask the user to add `import render` which is incorrect with the code state in section **Use a template to render a page** if we don't remove the `import render` in section **Create A Django app**. 
I hope it makes sense.
=> Remove unused import

docs/python/linting.md, docs/python/tutorial-deploy-app-service-on-linux.md
It matches the precedent set up in the rest of the file and should save most readers a few clicks.
=> Added Links to Python Docs

docs/python/environments.md
Add a note mentioning that conda environments cannot be auto-activated if the shell is PowerShell (see https://github.com/Microsoft/vscode-python/issues/2898)
=> Add powershell/conda note on environments docs

docs/getstarted/tips-and-tricks.md
Fixed typos in Customization and Editing hacks sections
=> Fixed typo errors in tips and tricks

docs/customization/keyboard-shortcuts.md
Issue #1760 asks about what this command does, so I looked into it and documented it in the keyboard shortcuts md file. Seems appropriate since I installed a fresh copy of VSCode, and there was a default keybinding for this command.
Comments welcome.
=> Document workbench.action.quickInputBack

docs/python/tutorial-flask.md
Different strftime formats are shown, but because the month in the example is May, then two  (%b and %B) of the examples shows the same output. If a month with a longer name such as October is used, then the different format strings has different outputs.
=> Update flask strftime examples

docs/getstarted/tips-and-tricks.md
Similar to #2130. Sorry, I didn't realize it was already documented -- I've been using this feature since it was implemented. Feel free to close if you think it's too inconsequential, I'm not sure it's worth it.
@gregvanl
=> Add a mention about vertical selection using keyboard

docs/extensionAPI/vscode-api.md, docs/getstarted/settings.md, docs/introvideos/debugging.md, docs/languages/markdown.md, docs/nodejs/debugging-recipes.md, docs/nodejs/nodejs-debugging.md
According to the Node.js trademark policy, Node.js should be capatalized as such. I updated everything except release notes.
"You may only use Node.js wordmarks in their full form and properly capitalized (e.g. “Node.js”)."
Page 3: https://nodejs.org/static/documents/trademark-policy.pdf
Related to 38d94c9.
=> Standardize casing of Node.js

docs/languages/typescript.md
I got up to this point in step 2 in the docs, and had to go to step 3 to see what the shortcut was. Just added the shortcut in step 2.
=> adds keyboard shortcut for action.tasks.build

docs/getstarted/theme-color-reference.md
In the new VSCode release v1.9 there are two new colors which are not yet present in the theme reference. This PR adds them.
=> 📦 NEW: Debug Stack Frame Highlight Colors

release-notes/v1_28.md
> Note that this feature requires that the setting `javascript.validate.enable` is set to true.
=> explain the setting required for convert to async

docs/extensionAPI/extension-points.md
This broke the link on code.visualstudio.com.
=> Fix capitalization of taskDefinitions link

docs/setup/linux.md
The more recent versions of apt support installing deb packages directly without the dpkg -i && apt-get install -f trick. This should work on Ubuntu 14.04 and later and on the current Debian stable.
=> linux.md: update apt deb install instructions

docs/setup/linux.md
The following error is produced using the `apt-get update` command in the instructions:
```bash
E: Repository 'http://dl.google.com/linux/chrome/deb stable Release' changed its 'Origin' value from 'Google, Inc.' to 'Google LLC'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```
APT will provide the user a prompt to accept the change, but only if using `apt update`, _not_ with `apt-get update`.
This change adds instructions to the user for if the error appears. It doesn't change the existing command from `apt-get update` to `apt update` due to being unsure if it could be a breaking change for older Debian-based distros.
=> Provide workaround for Origin change error in APT

docs/extensions/testing-extensions.md
Made a few recommended updates to the samples Azure Pipelines YAML example in the "[Testing your extension](https://code.visualstudio.com/docs/extensions/testing-extensions#_continuous-integration)" docs, including using our recommended file name: `.azure-pipelines.yml`.
Here is this YAML building a simple VS Code extension created with "yo code":
https://dev.azure.com/willsmythe/azure-pipelines-playground/_build/results?buildId=198
=> Update Azure Pipelines YAML example in "Test your extension" docs

docs/getstarted/userinterface.md
Looks like this is old behavior: Cmd + Click => open in new panel.
For now All + Click is used instead.
Cmd + Click allows to select several files in the file explore
=> Cmd -> Alt

docs/editor/integrated-terminal.md
`terminal.integrated.shell.*` and `terminal.integrated.shellArgs.*` can only be set at user scope.
=> Specify `shell` and `shellArgs` settings allowed scopes.

docs/getstarted/keybindings.md
I've removed the documentation for the unsupported `resourceIsFile` keybinding context.
Support was removed in [VS Code version 1.26](https://code.visualstudio.com/updates/v1_26#_notable-changes) (via [#48725](https://github.com/Microsoft/vscode/issues/48275)).
=> undocument `resourceIsFile` keybinding context (it was removed in v1.26)

api/references/vscode-api.md
This word should be from the above registerReferenceProvider copied.
=> Modify an incorrect word

api/language-extensions/language-configuration-guide.md
In this document "increaseIndentPattern" and "decreaseIndentPattern" were reversed.
Also, this document did not include the case of ")" when "decreaseIndentPattern".
=> Fix Indentation Rules

api/language-extensions/syntax-highlight-guide.md
The link to Matt Neuberg’s blog only works if all characters are lowercased.
=> Fix link in syntax highlight guide

api/language-extensions/syntax-highlight-guide.md
There is a typo that should show `source.abc` which is used as the example throughout this documentation. This PR fixes those instances where `souce.abc` was found to avoid any confusion.
=> fix typo for grammar scopes example

api/language-extensions/syntax-highlight-guide.md
Ruby uses Onigma, a fork of Oniguruma, for regular expressions since version 2.0. So it’s no longer accurate to say TextMate uses _Ruby_ regular expressions.
VS Code uses Oniguruma to [implement](https://github.com/Microsoft/vscode-textmate/blob/bd860d3d87b37343cc61239e5e90d813c1b3595d/package.json#L30) grammars.
=> Syntax highlighting uses Oniguruma regular expressions

docs/other/unity.md
As the original guide does not implement this specific case of allowing visual code to hook into code completion from unity assets i added a short descriptive guide that i just completed and can confirm is working.
I did this on a system that was formatted and reinstalled yesterday without any prior installs. so a clean system does in fact require this to properly hook into code completion.
=> Add a short guide on code completion for Unity in VS code

docs/editor/userdefinedsnippets.md
snippet variables that insert line or block comments, honoring the current language. Use BLOCK_COMMENT_START and BLOCK_COMMENT_END for block comments and LINE_COMMENT otherwise.
v : 1.30.1
=> update line or block comments, honoring the current language v:1.30.1

api/references/contribution-points.md
contribution-points.md, fix broken link to when clause description
=> contribution-points.md, fix broken link

docs/editor/integrated-terminal.md
* remove outdated `vscode.bat` method  
(not required since Cmder v1.3.5)
* added a link to the official Cmder wiki
=> Update Cmder integration

docs/languages/css.md
Fixed a typo error in the line "You can test that your gulp installation was successful by typing `gulp -v`."
=> Fixed typo "by instead of but"

docs/editor/editingevolved.md
I'd argue this is more commonly used than the other features yet here only exists as a minor subpoint. Why not put it at the top?
=> Move cmd+p to top of docs

api/references/theme-color.md
This PR adds new settings for list/tree widget filter typed text as of [v1.31](https://code.visualstudio.com/updates/v1_31#_new-tree-widget).
E.g. 🦄 [Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple) theme custom colors demo.
=> 📦 NEW: List Filter Widget Colors

docs/getstarted/keybindings.md
Example used wrong context key name.
=> [docs/get-started/keybindings] fixed typo

docs/languages/javascript.md
I noticed a missing "as" in "...and for other platforms such `node`, serverless, or IoT."
=> Add missing "as" to "such as" in Docs/languages/javascript

docs/setup/linux.md
pivoting to only recommend the custom setting when accessibility mode is enabled to avoid a tight coupling of settings
=> update wording with new behavior

docs/getstarted/tips-and-tricks.md
=> Fix tips-and-tricks files.exclude indentation

docs/other/dotnet.md
Updating to the main .NET download page. The current link lands folks in a tutorial to build a hello world app with .NET Core CLI. We've heard from customers (via the Feedback button on the .NET site) that this is confusing.
The target page will automatically detect OS and show the correct downloads.
=> Update .NET Core download link

docs/python/editing.md
The path to Google AppEngine python27 runtime libraries was simply wrong, causing VSCode not to autocomplete these libraries.
Unfortunately, the path to each library that is used, must be specified.
=> Fix python autocomplete paths for Google AppEngine

CONTRIBUTING.md
While most people wouldn't confuse the two, there is technically a difference so I figure it's best to have the docs be as technically accurate as possible.
=> Correct "dashes" to "hyphens" under Bookmarks

api/working-with-extensions/bundling-extension.md
Hi, I corrected the documentation for the `.vscodeignore` file. I fixed a small typo 😉
=> Fix wrong file name (.vscodeignore)

docs/nodejs/reactjs-tutorial.md
Reloading vscode after installing the chrome debugger isn't needed anymore
=> Remove reload after extension install description

api/references/theme-color.md
The `breadcrumb.background` line was in the theme color reference docs twice, so this removes one of the entries.
=> Remove duplicate breadcrumb.background in theme color reference

docs/editor/tasks.md
dbaeumer commented on Sep 18, 2018
If you list more than one task in the dependsOn property they are executed in parallel.
=> Parallel execution of dependsOn tasks.

api/references/theme-color.md
We will be introducing a new color theme token, `statusBarItem.prominentForeground` and this is to update the docs to reflect this new color.
**Note:** this should only be merged _AFTER_ 1.33 is released since this will only be available in 1.34
FYI @aeschli
=> Add "statusBarItem.prominentForeground" to theme color docs

docs/editor/integrated-terminal.md
The documentation for removing old installs of `npm` on OSX in the integrated terminal docs work great but you may also need to delete the old `npx` binary and symlink.
=> Add documentation for removing OSX npx files

docs/editor/accessibility.md
Contains a paragraph in the screen reader section that points to the NVDA add-on I created. It is related to fixes added in the 1.33 insider edition.
The add-on enhances the following use cases:
* Reading the item completed from the intelisense code completion without reading back the entire line of code,
* Fixes losing focus when coding in the editor and using the escape key to leave the intelisense suggestion popup,
* Provides a settings.json file that can be useful when working with a screen reader.
The add-on with a redme file can be found here: https://github.com/pawelurbanski/nvda-for-vs-code
@jrieken - this pull request for the documentation makes our fixes complete, and makes working with VS Code much better.
=> Information about the NVDA screen reader add-on

docs/cpp/config-wsl.md
Without the settings added, VSCode will choose whatever the default shell is, in many cases PowerShell (see #2553 ). This fixes that issue, and makes the shell for the workgroup *Bash* instead of *PowerShell*.
=> Fixed WSL Guide Shell Settings

docs/python/python-tutorial.md
Link to /docs/python/debugging#_args was incorrectly formatted.
=> Fix link in Python tutorial

docs/python/images/django-tutorial/code-snippet-inserted.png
=> Correct base template path generated by snippet.

docs/python/linting.md
The section on **pydocstyle** mistakenly says "pycodestyle" in one place.
=> Fix typo: change "pycodestyle" to "pydocstyle"

docs/python/editing.md
Loading VSC from an activated Python Environment doesn't result in Python Extension using that environment.
=> Remove ref to loading VSC from activated env

docs/editor/userdefinedsnippets.md
Add the variable WORKSPACE_NAME to [User Defined Snippets documentation](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables). This variable was added in the [1.33 update (March 2019)](https://code.visualstudio.com/updates/v1_33#_snippet-variable-workspacename).
=> Added variable WORKSPACE_NAME to userdefinedsnippets.md

docs/remote/ssh.md
Microsoft/vscode-remote-release#126
Is this the best way to describe it, or x64, or Intel-based, etc?
=> Clarify x86_64 Linux for SSH

docs/remote/containers.md, docs/remote/troubleshooting.md, docs/remote/wsl.md
https://github.com/Microsoft/vscode-remote-release/issues/155
https://github.com/Microsoft/vscode-remote-release/issues/116
https://github.com/Microsoft/vscode-remote-release/issues/95
https://github.com/Microsoft/vscode-remote-release/issues/119
=> Edits based on customer feedback

README.md
without double trailing spaces, markdown merges the lines which limit readability of the 3.1 and 3.2 clauses.
=> fix 3.1 and 3.2 clauses

docs/remote/containers.md
I also made a change in the examples here: https://github.com/microsoft/vscode-dev-containers/pull/36
=> Added security documentation for when you're extending docker-compose

api/advanced-topics/remote-extensions.md, docs/remote/troubleshooting.md
Developer guidance due to https://github.com/microsoft/vscode-remote-release/issues/188
=> Update developer guide to recommend not using base Electron or VS Code modules w/o a fallback

docs/editor/versioncontrol.md
Hey,
Current url returns:
```
Error
Failed to load PDF document.
```
There is a simple url update.
=> Replace outdated git cheat sheet url

api/extension-capabilities/overview.md
`a HTML element` should be `an HTML element`.
=> Grammar fix

docs/python/jupyter-support.md
Changed IPython to IPython Notebook. I realise that it's a minor typo in terms of changes, but it's an important distinction to make as IPython is an on-going project on its own.
=> Distinguish Ipython and Ipython Notebook

tutorials/functions-extension/getting-started.md
The tag for version 2 has been removed so this installation command is
failing for users coming to the tutorial.
=> Update the install command for functions tools.

.gitattributes, docs/remote/containers-advanced.md, docs/remote/containers.md, docs/remote/faq.md, docs/remote/ssh.md, docs/remote/troubleshooting.md, docs/remote/wsl.md
This PR:
1. Adds an "Advanced configuration" section in the main containers article that now includes:
- Docker-in-Docker/Kubernetes (existed before)
- Connecting to multiple containers at once (new)
- Using SSH to connect to a remote Docker host (new)
2. Adds tips and tricks topics on:
- Setting up a SSHFS mount. (Referenced in "Using SSH to connect to a remote Docker host")
- Using rsync to move content to/from a remote host.  (Referenced in "Using SSH to connect to a remote Docker host")
- Two more SSH tips given commonly raised issues.
- Other cleanup
I could see the "Advanced configuration" section becoming a separate article or breaking up troubleshooting into separate articles per-extension that then includes advanced configuration.  However, I held off on making those changes.
=> Containers advanced topics and misc cleanup

release-notes/v1_34.md
=> terminal all → terminate all

docs/remote/containers-advanced.md
After I saw the article on connecting to a remote docker host in the actual site, I realized that some of the options in the first section looked like steps instead.  
This is mainly a formatting PR to fix that, but some of the narrative changes slightly to make it work.
=> Make options for remote Docker connectivity look less like steps

docs/languages/cpp.md
The link for `Windows Debugging with GDB` points to the same header that the link is in. This is not helpful for users who are trying to figure out how to setup GDB on Windows. Redirecting to /docs/cpp/config-mingw.md instead.
=> Update link in cpp.md

docs/getstarted/keybindings.md
The navigation key code, `F1`, to "Show All Commands" is documented in the PDFs for [Windows](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) and [macOS](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf).
This PR adds it to the HTML docs.
=> Add F1 as cross-platform navigation binding

api/working-with-extensions/continuous-integration.md, api/working-with-extensions/images/testing-extension/debug.mp4, api/working-with-extensions/images/testing-extension/launch-tests.png, api/working-with-extensions/images/testing-extension/pipelines-logo.png, api/working-with-extensions/images/testing-extension/pipelines.png, api/working-with-extensions/images/testing-extension/test-output.png, api/working-with-extensions/testing-extension.md, release-notes/v1_35.md
See context at https://github.com/microsoft/vscode/issues/71048.
@joaomoreno Please take a look at the release notes, testing/CI docs and see if it makes sense for you. I think it looks simpler.
=> vscode-test related updates

api/language-extensions/syntax-highlight-guide.md
add the missing scope of keyword.letter
=> fixing document about syntax sample

docs/languages/typescript.md
First paragraph of "Unused variables and unreachable code" subheading.
=> Add missing word in typescript.md

docs/editor/debugging.md
Or should be used in place of And, as we are informing about any language that get transpiled in to Java Script. And is used when we are restricting the options to selected few, here we are giving options of any language.
=> Corrected Line 19

docs/languages/markdown.md
[Suggestion]
Since the question how to keep trailing whitespace in markdown files (to create simple line breaks) pops up at various different corners, it might be helpful to provide a configuration example in the documentation.
=> Add configuration example to keep trailing whitespace

docs/editor/userdefinedsnippets.md
High-level summary of changes:
- Fix #2855 "Missing documentation for the 'snippet prefix arrays' feature"
- Fix #2450 "Not mentioned project level snippets"
- Standardize document title and first couple headers for clarity's sake
- Split--and then lightly extend--the subsection "Creating your own snippets" to improve SoC/SRP per section.
- Separate, reflow, and add detail to the cursory snippets files documentation with a new section that better addresses the language-vs-global and user-vs-project -scoping of snippets files.
- Add a new section "Snippet schema" that explicitly and declaratively provides the structure of a snippets file and snippet definition. (this was not something that existed before, outside of implicit and only-cursorily-documented VS Code intellisense)
=> Update and clarify snippet files part of the snippet user guide

docs/remote/containers.md
While testing, I realized the instructions for this did not work on Windows due to Docker limitations.  I instead went for a less elegant, but consistently working approach instead.
Ultimately, we need a feature to streamline what I describe.
=> Revise instructions on copying SSH keys into the container

docs/introvideos/extend.md
Change "Next Steps" to "Next Video" for parity with other intro pages.
=> All the other intro video pages say "Next Video" but this one says "Next

docs/editor/emmet.md
In line 103, we are referring to CSS properties where the preference has been enabled, hence those should be used instead of these, as we are referring to CSS properties having preference.
=> Line 103 update

docs/editor/emmet.md
Cannot use does when referring to plural snippets, either use snippet or use do not.
=> Correct helping verb for Line 378

docs/python/python-tutorial.md
The Windows installer for 3.7.4 offers an option to add Python to PATH in its UI. Also changed the latest version number to 3.7.4.
=> Update python-tutorial.md wrt PATH on Windows

docs/python/tutorial-flask.md
Modify the hello_there function in views.py to have the name parameter default to None as seen in app.py.  This restores the message returrned when navigating to /hello
=> Modify hello_there in views.py same as app.py

api/references/extension-manifest.md
The Extension Manifest Editor extension has been broken for a while (see https://github.com/microsoft/extension-manifest-editor/issues/20).
=> Remove link to broken extension

docs/editor/intellisense.md
It would be better to re-arrange line  26 in following manner:
If you continue typing characters, the list of members is filtered to only include members containing the typed characters. 
One other option that can be used goes like this:
If you continue typing characters, the list of members is filtered to include only the members containing the typed characters.
=> Line 26 re-arrangement

api/advanced-topics/remote-extensions.md, docs/remote/containers-advanced.md, docs/remote/containers.md, docs/remote/images/containers/install-all-extn-containers.png, docs/remote/images/ssh/install-all-extn-ssh.png, docs/remote/images/wsl/install-all-extn-wsl.png, docs/remote/linux.md, docs/remote/ssh.md, docs/remote/wsl.md
This PR has the following doc changes:
- Adds information on the "Install Local Extensions" command
- Corrects / refines information on Alpine and ARMV7l support.
- Makes a correction to the extension guide.
- Makes some small corrections to the multi-container section of advanced containers.
This differs from the previous PR simply in that Alpine/ARMv7 support is still in VS Code Insiders
=> [Corrected] Updates for 1.37

docs/cpp/enable-logging-cpp.md
Add logging info for the debugger.
Content from https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/FAQs.md#how-to-enable-logging
=> Add logging info for the debugger

docs/editor/tasks.md
Make has been replaced with Makes, as the reference is being made of a json file.
=> Line 57 changes

docs/setup/linux.md
Before this change the key has been trusted for all possible repositories.
Moving it to /usr/share/keyrings/, the conventional location, prevents that.
The 'signed-by' links location with its particular, authoritative key(s).
To prevent any name clashings, it's a good practice to not use an
organizations name here (except the key or keyring is really meant to cover
the entire org, like GNU's) and go with with a descriptive one,
or one obvious to where it will be used.
=> Limit the validity of the signing key to packages.microsoft.com

docs/cpp/launch-json-reference.md
fix "args" example in launch-json doc
=> fix "args" example in launch-json doc

docs/remote/containers-advanced.md
Adapt to feedback/fix typo mentioned in https://github.com/microsoft/vscode-docs/pull/2988#discussion_r315418340, tweak commands so they do not wrap in the actual docs site.
Make sure the "extend" option for Docker Compose is visible in all sections given other GH commands in issues indicating this was not obvious in the section.
=> Corrections, streamlined and formatted commands

docs/remote/containers-advanced.md, docs/remote/troubleshooting.md
Updates to avoid https://github.com/microsoft/vscode-remote-release/issues/1172 for SSH and https://github.com/microsoft/vscode-remote-release/issues/1233 for containers.
=> Updates to avoid GH 1233 and 1172

docs/setup/linux.md
- prefer `sudo dnf check-update` over `dnf check-update`, no need to create cache as user since `root` is installing
- couldn't actually find docs on this, but in my experience if I do `dnf check-update` I have to re-download the same updated lists as `root`.  Since all other commands here are as `sudo` it seems to be OK to encourage this, even if it doesn't actually make a difference.
- `dnf` / `yum` command to update lists is `check-update`, not `update`
=> minor rpm-based command corrections

release-notes/v1_38.md
As an experiment, I'd like to add a short list of 1.38 highlights to the remote section of the core VS Code release notes.  Its presence here seems to drive more uptake than their presence in the release notes.
=> Add remote highlights to 1.38 release notes

api/index.md
There are 17k questions right now. But there will be more in the future.
State something generic like `thousands`.
=> docs: Remove inaccurate number

api/advanced-topics/remote-extensions.md, api/references/contribution-points.md, docs/languages/dotnet.md, docs/nodejs/working-with-javascript.md, docs/python/tutorial-azure-functions.md, docs/python/tutorial-create-containers.md, docs/python/tutorial-django.md, release-notes/July_2016.md, release-notes/June_2016.md, release-notes/v1_17.md
- `json`: It must begin and ends with paren. Otherwise it's invalid JSON and syntax highlighting would fail.
- `console`: It should be `cmd` instead.
- `output`: There's no such language.
=> Fix syntax highlighting issues coming from docs

docs/editor/codebasics.md
In Python spaces between "#" and "region" / "endregion" are allowed
https://github.com/microsoft/vscode/pull/46885/files
=> Add markers "# region" and "# endregion" for Python

release-notes/v1_39.md
Related: https://github.com/microsoft/vscode/pull/79735
I believe we will (and should) keep using full-width kana. Just updating CSS will not make katakana half-width. ["Half-width kana"](https://en.wikipedia.org/wiki/Half-width_kana#Encoding) normally refers to special katakana characters that are assigned [different Unicode code points](https://en.wikipedia.org/wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block)). Fonts like Meiryo UI have **full**-width katakana that are narrower than average.
=> Remove 'half-width kana' from 1.39 release note

docs/python/linting.md
If you do `pylint pylint --generate-rcfile >.pylintrc` in PowerShell,
then this file gets written in UTF-16. This in turn is not accepted by
`pylint`, which will throw the following error upon *any* execution:
"""
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position
0: invalid start byte
"""
See also https://stackoverflow.com/q/52418511/603003.
Also when executing "linting" in VSCode, VSCode just does nothing. After fixing the encoding, linting works from within VSCode and from shell via `pylint`.
=> docs: don't use PS stdout redirection doing UTF-16

docs/python/environments.md
docs.pipenv.org is dead, point to pipenv.readthedocs.io instead.
=> Update outdated pipenv links.

docs/python/settings-reference.md
Fixed a typo and updated the capitalization of "Python interpreter" (in line with the rest of the topic).
=> Fix typo and capitalization

docs/languages/tsql.md
Either one or peek definition or Go To definition can be used, hence OR should be used in place of AND
=> line 53 modified to use 'OR'

docs/editor/codebasics.md
Reformatted the for creating reigon markers into a Table for better visiablility of it.
Looking at it as a List I found it very hard to read and understand.
With it formatted into a table it makes it clear markers of which are the Starting regions and ending regions.
Additionally I have removed the HTML from it due to not having any, although it uses the same region markers as Markdown.
=> Reformatted region section to a Table

docs/java/java-azurefunctions.md
In the example of running Func after deploying to Azure the code snippet says to call api/hello, but the code that the maven artefact creates creates httptrigger-java
Either the instructions need updating, as per this PR, or, the instructions need to change to tell the reader to change the Function name before deploying.
=> Updating hello - httptrigger-java

docs/remote/troubleshooting.md
The following error occurs when running the provided commands in PowerShell:
Adding braces around the variable name as suggested by PowerShell fixes this.
Running on Windows 10 1903 (OS Build 18362.418)
=> PowerShell chokes on $REMOTEHOST

docs/getstarted/keybindings.md
For some reason, isFileSystemResource was duplicated twice in a row.
=> Remove extra isFileSystemResource

api/extension-guides/virtual-documents.md
The virtual documents guide talks about event emitters and introduces an example which is supposed to use them but actually doesn't. 
The text has been updated to reflect what the code really does, and the mention of the event emitter feature is now accompanied by a link to a relevant example.
Fixes #3183
=> Fix incoherence in Virtual Documents guide

release-notes/v1_39.md
Not sure if there’s any point in changing old release notes, but I mostly just wanted to bring this patch to someone’s attention since there’s a chance this section will get copied forward to the October release notes when TypeScript 3.7 stable is bundled with VS Code. /cc @mjbvz thanks!
=> Fix TypeScript formatter option name

docs/languages/powershell.md
Using the following command reads better than "with the following command".
=> Change to Line 27

docs/remote/containers-advanced.md
This is a quick edit to show users how to persist bash history between dev container sessions.
=> Add note on how to persist bash history

api/references/contribution-points.md
Link to details: https://github.com/Microsoft/vscode-SCMBuilders/wiki/SCM-API-Adoption-Guide#menus
=> docs: Update menu identifier docs for scm context

api/get-started/extension-anatomy.md
I know this is a trivial change but I just noticed it in passing. Please feel free to ignore if incorrect.
=> Make APIs plural.

api/advanced-topics/remote-extensions.md, docs/remote/faq.md, docs/remote/images/ssh/ssh-command-input.png, docs/remote/images/ssh/ssh-explorer-add-new.png, docs/remote/images/ssh/ssh-explorer-connect.png, docs/remote/images/ssh/ssh-explorer-forward-port.png, docs/remote/images/ssh/ssh-explorer-open-folder.png, docs/remote/images/ssh/ssh-host-input.png, docs/remote/images/ssh/ssh-open-folder.png, docs/remote/images/ssh/ssh-statusbar.png, docs/remote/ssh.md
This PR addresses two things:
1. As a part of https://github.com/microsoft/vscode-remote-release/issues/1776, I noticed the comment `(By the way, I think the "requires SSH key based authentication" part is outdated.)` and realized that this entire doc hadn't been updated since we got the Remote Explorer updated (since SSH had an explorer to begin with and didn't seem necessary). We also drove strongly to key-based auth given limitations and  I've seen some comments about how hard even the basics are. So, I ended up revising the content to break the getting started into two:
* A simple, really basic "connect" path.
* More meat around the SSH config file and the explorer for advanced setup.
2. Clarifies the array form of extensionKind per …
=> SSH Updates, Clarification on extensionKind

api/working-with-extensions/testing-extension.md
I have updated the example for [custom setup with vscode-test]( https://code.visualstudio.com/api/working-with-extensions/testing-extension#custom-setup-with-vscodetest) 
1. I have changed `resolveCliPathFromExecutablePath` because `resolveCliPathFromExecutablePath` has been renamed to `resolveCliPathFromVSCodeExecutablePath`. 
2. I have also changed the imports from commonjs to esm because all the other example use esm.
3. I have put an async main function around the code so that one can just copy and paste the example without getting an error. However I do think that the other variant is more readable and I can change it back if you want :)
=> docs: update custom setup with vscode-test

api/references/contribution-points.md
I was thinking that command's icon can be only string, therefor can't support light/dark mode.
I was happy to find out (by other resources) that it does possible.
A short example was save me some time 😀
=> docs: Add "icon" property to the "command" example

docs/remote/containers-advanced.md
I tested it from documentation and it was failing with:
```sh
docker-compose -f /XYZ/.devcontainer/docker-compose.yml config --services
ERROR: The Compose file '/XYZ/.devcontainer/docker-compose.yml' is invalid because:
Unsupported config option for services.remote_dev: 'env-file'
```
In docker-compose doc https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option, it's `env_file` and not `env-file`
=> `env-file` doesn't work in docker-compose

docs/remote/troubleshooting.md
The apt-get command for Debian/Ubuntu doesn't have sudo, which is required. I updated the doc to include this, as well as add in that the command can be run for both Debian and Ubuntu.
=> Corrected apt-get command

docs/cpp/cpp-ide.md
The default clang-format configuration given in the docs includes `BreakBeforeBraces: AllMan`, which is cased incorrectly and causes clang-format 6.0 to fail when used in an actual `.clang-format` file. The correct case is `Allman` with a lowercase m.
=> Fix letter casing for default clang-format config

docs/remote/containers-advanced.md
No install without apt update possible. Image ubuntu:bionic 
Added
```bash
&& apt-get update \
```
into the "adding non-root user" example.
=> Update advanced remote missing apt update

docs/remote/containers-advanced.md
Doc update for https://github.com/microsoft/vscode-remote-release/issues/2019
Currently the ssh:// protocol in Remote - Containers requires that your SSH key be in the SSH agent, which is mentioned for Git support but not in the advanced section.
=> Clarify requirements around using the SSH agent with the ssh:// protocol

docs/setup/network.md
Troubleshooting update install issues and found the URL being called was docsmsft.gallery.vsassets.io
=> fix: Update gallerycdn -> gallery

api/working-with-extensions/publishing-extension.md
Or at least I think there should be a hyphen. 😉
=> Add a missing hyphen

api/references/theme-color.md
The text under the "Side Bar" section ("The Side Bar contains views like the Explorer and Search") was mistakenly duplicated beside the documentation for `sideBar.dropBackground`
=> Remove accidental duplicated string

api/get-started/extension-anatomy.md
Looks like it is no longer required to get intellisense.
Moreover, as specified the postinstall does not work, as there is no vscode dependency.
I am not completely sure this is the right thing to do, but I think it is?
=> Remove mentions of postinstall

docs/remote/wsl.md, remote-tutorials/wsl/run-in-wsl.md
There have been quite a few emails that required customers to restart
their terminal to get the shell command to be available. This includes
that guidance in the note.
=> Update the note about issues launching VS Code.

docs/remote/containers-advanced.md
This link navigates to the id: https://code.visualstudio.com/docs/remote/containers-advanced#_adding-a-nonroot-user-to-your-dev-container
This link does not: https://code.visualstudio.com/docs/remote/containers-advanced#_adding-a-non-root-user-to-your-dev-container
=> Fix non-root link

docs/remote/containers-advanced.md
The Dockerfile snippet in the section "Changed Avoiding extension reinstalls on container rebuild" was creating the ".vscode" directory as root and giving to the local user the rights only on the subdirectory "extensions".
When vscode is then run in the container it tries to create the some directories (e.g. ".vscode/bin"), but it fails because the local user has no rights on the ".vscode" directory
=> Fixes in section "Avoiding extension reinstalls on container rebuild"

docs/python/jupyter-support-py.md
Jupyter was previously known as IPython Notebook, not IPython. (IPython is the kernel that underlies both old and new notebooks.) See, for example, https://ipython.org/notebook.html
=> Correct jupyter-support-py.md reference to IPython

docs/cpp/config-msvc.md
The current tutorial documentation [here](https://code.visualstudio.com/docs/cpp/config-msvc#_add-a-source-code-file) will produce a new file `Untitled-1`. The user must then realise that to name it as required, they must save the file. Alas, the default save location in the popup box is the .vscode subdirectory, and the code will not compile with the configuration outlined in the previous tutorial sections.
=> Added clarification regarding the location of a new cpp file.

api/working-with-extensions/continuous-integration.md
I published a Github Action to enable XVFB. I'm successfully using it here: https://github.com/GabrielBB/vscode-lombok/blob/master/.github/workflows/nodejs.yml
I also opened a [PR](https://github.com/microsoft/vscode-test/pull/54/commits/c51eedf2e66084d1e83dd63589c24a4761f5528f) to the official [vscode-test](https://github.com/microsoft/vscode-test) repo to include a running sample workflow
=> Add Github Actions to CI documentation

api/references/commands.md
There also might be other places where "all" and plurality is called for (i.e. other commands that return arrays), but without knowing whether that means multiple providers are called or a single provider with multiple values is returned I didn't want to be presumptuous and get it wrong.
=> Add some plurals to command reference

docs/remote/linux.md, docs/remote/ssh.md
Experimental Windows SSH host support currently requires that "Use Local Server" be set in `settings.json`. That's currently not in the docs or README, so adding it.
Old PR was to master instead of vnext.
=> Add required setting for windows SSH hosts

docs/languages/powershell.md
The Pester documentation has been migrated from Github wiki to https://pester.dev/
=> Update pester links to match site migration

api/advanced-topics/remote-extensions.md
The previous code for getNodeModule works fine in a development environment, but will fail loading the Node module in production. The function should be changed as indicated. That code is coming from the vscode-azureaccount repo.
=> Use a more solid getNodeModule for keytar

docs/containers/reference.md
Adds documentation for the Docker command customization features. The content is adapted from https://github.com/microsoft/vscode-docker/issues/1596#issue-558411927.
@karolz-ms, @philliphoff, @BigMorty for FYI.
This takes care of https://github.com/microsoft/vscode-docker/issues/1653.
=> Docker command customization documentation

docs/containers/reference.md
The key change here is that `includeDefaults` is not a property of the VS Code Docker **extension**--it is a property of the `labels` object that is part of the `dockerBuild` task.
@ghogen please review--thank you!
=> Clarify how to turn image auto-labeling off

docs/getstarted/userinterface.md
In VS Code 1.42.1 the default setting for window.restoreWindows is 'all' and not like mentioned 'one'
=> Correct window.restoreWindows default setting

docs/getstarted/images/tips-and-tricks/mdiff-switch-to-inline.png, docs/getstarted/images/tips-and-tricks/mgutter_icons.gif, docs/getstarted/images/tips-and-tricks/msee-changes.gif, docs/getstarted/images/tips-and-tricks/mstage-unstage.gif, docs/getstarted/images/tips-and-tricks/mswitch-branch.gif, docs/getstarted/images/tips-and-tricks/mswitch-to-inline.gif, docs/getstarted/images/tips-and-tricks/mundo-last-commit.gif, docs/getstarted/tips-and-tricks.md
This is needed because a lot of the icons in the images were still using old icons.
Also improve the instructions for using VS Code as a git merge and diff tool.
=> Update Tips and Tricks page with new screenshots/GIFs.

docs/supporting/faq.md
This issue was reported twenty versions ago, and got fixed in Electron 6 (we are at 7). I don't think it is any relevant today.
=> Remove "Blurriness on macOS Mojave" FAQ entry.

docs/containers/reference.md
The intention here is to address feedback we got about Docker ext task reference topic; the reader was looking for information about common task properties supported by Docker ext tasks (all are supported).
=> Add a reference to custom task docs

docs/remote/containers.md
In `docker-compose.yml`, `version` and `services` nodes must be on the same level.
=> Fix incorrect indentation in an example

docs/remote/containers-advanced.md
The "Avoiding extension reinstalls on container rebuild" section provides directions on how to create volume mounts to hold the remote VS Code server and extensions. In one of the steps, the volume mount target for VS Code Insiders is shown without the home prefix. Anyone using VS Code Insiders who blindly copies this configuration will end up mounting the volume to the wrong path.
This PR updates the volume mount to include the home directory in the target path.
=> Update volume target path

docs/languages/javascript.md
This note about IntelliSense not implementing ES7 seems to be a outdated. Newer features like `String.prototype.trimStart` and `trimEnd` from ES2019 already work.
Note: My assumption here is that older features must be complete if later ones are. Please decline this PR if actually some ES7 features are not yet present even though ES2019 is already supported.
=> Remove outdated note about IntelliSense for ES7

docs/remote/containers-advanced.md, docs/remote/containers.md, docs/remote/images/containers/checkout-pr-status.png, docs/remote/images/containers/dev-container-progress.png, docs/remote/images/containers/k8s-attach.png, docs/remote/images/containers/select-a-sample.png, docs/remote/images/containers/vscode-remote-try-node.png, docs/remote/images/ssh/ssh-select-platform.png, docs/remote/ssh.md, docs/remote/troubleshooting.md, docs/remote/wsl.md, release-notes/v1_44.md, remote-release-notes/v1_44.md
This PR adds:
1. Some refactoring around quick starts given improvements to open repository in container. Specifically, it uses the "Remote-Containers: Try a sample..." command as a starting point, covers how to use an existing folder next, then covers open repository mentioning its perf benifits.
2. Attach support for Kubernetes
3. Notes on experimental WSL2 support
4. A tip on the COMPOSE_PROJECT_NAME environment variable
5. Some related tweaks to release notes like mentioning the Python pre-built images
=> Updates to remote section for 1.44 release

docs/containers/debug-python.md, docs/containers/quickstart-python.md
Per @ghogen's request, 
I've updated the Python Quickstart to be more clear about using the requirements file, very minor edit to debug-python
=> Updated Python-Quickstart and Debug Python

api/language-extensions/syntax-highlight-guide.md, blogs/2017/02/08/syntax-highlighting-optimizations.md
Command title was changes in v1.42 however docs still had old name.
This PR updates name in docs to match name in VS Code.
There is third mention of old name, however it is in v1.9 release notes and I don't think it make sense to rename it there.
https://github.com/microsoft/vscode-docs/blob/master/release-notes/v1_9.md#new-tools-for-inspecting-textmate-scopes
=> Rename Inspect TM Scopes

docs/remote/containers.md
Path of custom dockerfile needs to be relative to the location of the primary docker compose file.
=> Fix doc bug mentioned in https://github.com/microsoft/vscode-dev-containers/issues/280

docs/containers/choosing-dev-environment.md
1. Add Python as supported target for Docker debugging
2. Add a sentence that points to Docker installation documentation. 
We recently received a complaint from a user that tried to install Docker extension on Windows Family edition; this succeeds, but Docker is not supported on that Windows SKU and so it cannot be used for Docker development. This is an attempt to clarify the requirements
=> Docker development environment topic updates

api/extension-guides/color-theme.md
Using the `.color-theme.json` suffix does not enable hover support and code completions.  The files generated by 'yo code' use a `-color-theme.json` suffix, which works.  Example `dark-color-theme.json`.
=> Typo / Incorrect suffix

api/extension-capabilities/theming.md, api/extension-guides/color-theme.md, api/language-extensions/images/semantic-highlighting/no-semantic-highlighting.png, api/language-extensions/images/semantic-highlighting/with-semantic-highlighting.png, api/language-extensions/images/syntax-highlighting/scope-inspector.png, api/language-extensions/images/syntax-highlighting/scopes.png, api/language-extensions/semantic-highlight-guide.md, api/language-extensions/syntax-highlight-guide.md, docs/getstarted/themes.md
Doc on semantic highlighting
- show the relationship to syntax tokenization
- semantic token provider API overview (@alexdima FYI)
- semantic classification
- theming
I first planed to leave theming to https://code.visualstudio.com/api/extension-guides/color-theme but found that page to be more to be about on how to create theme, without much detail on the syntax on how to do token styling.
Therefore I added a theming section to the syntax highlighting document where I think it fits well.
I realized that we still lack detailed information on TextMate theming (TextMate rule selectors...)
=> semantic tokenization doc

docs/java/java-tomcat-jetty.md
Link under the Jetty section is for VSCode TomCat
Fix capitalization of Red hat -> Red Hat
=> Fix Jetty for Java link

docs/java/images/java-tomcat-jetty/open-liberty.mp4, docs/java/java-tomcat-jetty.md
Hi 👋, we over at IBM/Open Liberty would like to add a section for Open Liberty and the Open Liberty Tools vscode extension in the `Working with application servers in Visual Studio Code` section of the java docs.
We wrote up a draft here for you to review and also included a small video similar to Tomcat and Jetty.
cc @yeekangc @ericglau
=> Add Open Liberty to 'Working with application servers in Visual Studio Code'

docs/setup/linux.md
VS Code no longer ships 32-bit binaries for Linux, so these instructions were a bit out-of-date.
=> Remove mentions of 32-bit from the Linux setup instructions

docs/cpp/customize-default-settings-cpp.md
Fixed the 'forcedInclude' property name on the "C++ / Customizing default settings" page.
Also removed the trailing comma from the configuration example.
=> Fix property name in config example

api/language-extensions/syntax-highlight-guide.md
The links point to 'semantic-highlighting-guide' (which does not exist), but they should point to 'semantic-highlight-guide'. This commit fixes two instances of this broken link.
=> Fix two semantic highlighting guide links

docs/containers/ssh.md
Docker context is a more convenient way to point VS Code and Docker CLI to a remote Docker engine.
Resolves https://github.com/microsoft/vscode-docker/issues/1797
=> Use Docker context for remote machines

docs/other/unity.md
Since 2019.2 it is required to install the vscode package. This should be added to projects by default, but having this information here seems valuable.
=> Adding note about Visual Studio Code package

docs/typescript/typescript-tutorial.md
The new file created by the `tsc helloworld.ts` command is `helloworld.js` rather than `HelloWorld.js`.
=> correct example file name

docs/containers/ssh.md
There are a few inconsistencies between Docker CLI and VSCode Docker extension that affect Docker endpoint access via SSH tunneling scenario. This is an attempt to help users steer clear and connect successfully on first try. 
@ghogen please review--thx!
=> Improve Docker access via SSH topic

api/extension-guides/custom-editors.md
`supportsMultipleEditorsPerDocument` should be set to true if the extension supports multiple editor instances for the same document, not `false` as the documentation stated.
=> supportsMultipleEditorsPerDocument should be true

docs/cpp/config-msvc.md
"You can use the C++ Toolset from Visual Studio Build Tools along with Visual Studio Code to compile, build, and verify any C++ codebases as long as you also have a valid Visual Studio license (either Community, Pro or Enterprise) that you are actively using to develop these C++ codebases."
=> Added CELA-approved note about MSVC license

docs/remote/containers.md
"Setting up a folder to run in a container" link has an extra `-` which is breaking the link in the docs website. See: https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference
=> Fix broken setup container link

docs/remote/containers-advanced.md
After spending part of a day troubleshooting why one of my devs was having the actual folder containing `.devcontainer` mounted, while everyone else was having the repository root folder mounted within their dev containers, we discovered that is because the "current workspace" changes to the repository root only if git is present on the user's `PATH` environment variable.  This is apparently the default value for the `workspaceMount` setting.  To be clear, however, the `${localWorkspaceFolder}` variable value does not change.
My dev (on a Windows host) was using git embedded in his terminal of choice, meaning vscode was unaware of the presence of a git.exe or the surrounding repo.
I think this is appropriate behavior (and we rely on it), but it needs to be documented properly so folks …
=> Clarify how "current workspace" is set

docs/editor/portable.md
I was installing for Linux in portable mode, took me a few extra moments to notice there was no actual .zip download for Linux.
Added detail to indicate Linux download is a .tar.gz file.
=> Update portable.md to include helpful details.

api/working-with-extensions/continuous-integration.md, api/working-with-extensions/publishing-extension.md
As part of https://github.com/microsoft/vscode-vsce/pull/447, supplying a PAT is now possible via an environmental variable.
This change updates the relevant documentation to reflect the ability to use convention over configuration and/or explicit coding to inject a PAT in order to publish an extension.
=> Updated automated publishing steps

docs/editor/settings-sync.md
This was changed in latest insiders and should be updated to reflect to avoid confusion.
=> Show Remote Data is now Show Synced Data

api/working-with-extensions/continuous-integration.md
The Node.js 8.x is EOL.
And [GabrielBB/xvfb-action](https://github.com/marketplace/actions/gabrielbb-xvfb-action) has newer version.
Thank you :)
=> Update Node.js and GabrielBB/xvfb-action versions

docs/languages/python.md, docs/python/linting.md, docs/python/settings-reference.md
Update documentation to match https://github.com/microsoft/vscode-python/pull/6570
=> Python linter pep8 was renamed to pycodestyle

api/language-extensions/language-server-extension-guide.md
Update to the document so the package.json file contents mentioned reflect the structure of the sample provided at https://github.com/microsoft/vscode-extension-samples/blob/master/lsp-sample/client/package.json.
=> Fix for language-server-extension-guide.md

docs/remote/containers-advanced.md, docs/remote/containers.md, docs/remote/faq.md
This is a companion PR to https://github.com/microsoft/vscode-dev-containers/pull/354
In a recent conversation with @jkeech, he correctly pointed out that technically our "Docker-in-Docker" definition is not true "Docker in Docker" as the docker daemon is not running inside the container. There are also base images like `docker` that actually do full DinD.
To avoid confusion, we renamed these to "Docker from Docker". This PR includes the related docs tweaks.  
Note that the old aka.ms have also been update, so people will still be routed to the right place even with the current docs.
=> Docker-in-docker to docker-from-docker

api/extension-guides/custom-editors.md
A small update fixing a typo in Custom Editor API section of custom-editors.md file.
=> Fixing typo in Custom Editor documentation

docs/azure/deployment.md
Added the "Deploy to Azure" extension and other updates to the page.
The paragraph above the table had to be changed because the "Deploy to Azure" extension does not live within the JavaScript Dev Center.
=> Updated Azure deployment docs

blogs/2020/06/09/go-extension.md
"golang" is the publisher ID and our display name should be "Go Team at Google".
I intended to update the screenshot of the extension that includes the publisher
name but it looks like that should be uploaded in a different location.
=> go-extension: use "Go Team at Google" instead of "Golang"

api/language-extensions/overview.md
Corrected grammatical error in overview.md. From 'is' to 'has' in line 12.
=> Corrected grammatical error in overview.md

release-notes/v1_46.md
Currently link navigates to eslint.org that has only few mentions of TS.
Looking at the sentence context [Migrate from TSLint to ESLint](https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration) in VS Code docs looks more appropriate.
@mjbvz could you confirm that this was your intention or provide better link please.
=> Update link to TS ESLint in 1.46 release notes

docs/containers/quickstart-aspnet-core.md
We got some doc feedback that might indicate people have trouble going through the tutorial because of random container port assignment.
Also includes minor change reflecting UI exposed by latest Docker extension release
=> Additional guidance for container port assignment

docs/containers/debug-python.md
After the 1.3 update, the Docker Extension will now use DebugPy in Python containers. I'm updating the docs to reflect this
=> Debugpy Revision

docs/remote/images/ssh/ssh-tunnel-different-local-port.png, docs/remote/ssh.md
Adding documentation for specifying a different local port when setting up port forwarding with a remote SSH server. 
I found the original commit and PR at: 
- https://github.com/microsoft/vscode/commit/b72188e25779fe5c165591e0f653cc04cbb349c9
- https://github.com/microsoft/vscode/issues/89031
=> Add documentation for specifying a different local port when setting up port forward

api/toc.json
Adjust title from "Commands" -> "Built-in Commands" in table of contents 
Fixes #3803
=> Update TOC to Built-in Commands

docs/remote/containers.md
`apt-get install` will fail (without a meaningful error message) in a Docker `RUN` command if it seeks `[Y|n]` input from the command line. We need to tell it not to ask.
=> -y flag to apt-get install

docs/setup/linux.md
On Debian-based systems, it is [recommended](https://www.debian.org/doc/packaging-manuals/fhs/fhs-3.0.html#ftn.idm236087550400) to not install local files outside of `/usr/local/` or `/etc/`, so we should not be manually installing files `/usr/share/`. Instead, we can use the existing `/etc/apt/trusted.gpg.d/` directory for apt archive keys.
=> Change apt key install directory

docs/remote/codespaces.md, docs/remote/containers.md, docs/remote/images/containers/repo-container-folder-setting.png, docs/remote/images/ssh/ssh-listen-on-socket.png, docs/remote/ssh.md, docs/remote/troubleshooting.md, docs/remote/wsl.md
Adds: 
- Setup information on the SSH unix socket option
- Info on using attach config tied to a container name rather than image
- Setup info on using the local remote-containers folder
- Misc edits and corrections
=> Remote updates for 1.47

docs/python/testing.md
The previous form, "To prevent this behavior, include `--no-cov` in `pytestArgs` when debugging tests.", left ambiguous _how_ to modify a setting "when debugging tests".
Let's take advantage of the earlier-explained launch.json config. I haven't found any way to directly change Visual Studio Code settings there, but we can set the environment variable `PYTEST_ADDOPTS`, which will have much the same effect. With this snippet, test-running just "does the right thing": coverage on Run Tests, and debugging on Debug Tests.
As to _how_ to provide the snippet, I defaulted to just adding a subordinate clause, for minimal disruption to the existing text. I'm not entirely happy with how verbose it makes the paragraph. If we think it's a common enough case, it might be better to pull this out of an …
=> clarify how to disable pytest-cov when debugging

docs/containers/choosing-dev-environment.md
We learned from Docker that installing Docker Desktop on virtual machines is not a supported configuration (although, technically, not a violation of the license agreement). As a result @BigMorty and I agreed with Docker product management that our documentation should recommend using Linux VMs and Docker Engine product if a VM is used for Docker development.
=> Docker Desktop not supported on VMs

docs/cpp/cpp-debug.md
This PR adds the additional info to attach to a process in Linux with
GDB.
This information comes from
https://askubuntu.com/questions/41629/after-upgrade-gdb-wont-attach-to-process
@pieandcakes
=> [cpp] Include extra info for Linux to Attach

api/working-with-extensions/continuous-integration.md
The current instructions for publishing using Azure Pipelines will cause the publishing step to fail, with an error like:
```
TF400813: Resource not available for anonymous access. Client authentication required.
```
Since `VSCE_PAT` is set as a secret variable, it cannot be immediately referenced and used as an environment variable (according to the [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables)). One has to explicitly map the secret variable using the `env` block.
I've updated the YAML snippet to set the mapping for the `VSCE_PAT` environment variable.
=> Update Pipeline publishing steps to explicitly map secret variable

docs/containers/quickstart-node.md
Made a small tweak so a developer could easily find the location of the inspectMode property when making an edit to tasks.json
=> added clarity to location of the inspectMode property

docs/remote/containers.md
I am not %100 sure of this, but the example of adding the ssh-agent to my profile file didn't work as expected. And after I googled around, I found an almost identical example at https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent
The only difference was that it enters the condition if `$SSH_AUTH_SOCK` is empty, while the one here checks it is *not* empty (as far as I can tell, at least). Making this change got it to work for me.
=> Fixed Using SSH keys example on Linux

api/extension-guides/command.md
CC @gregvanl went to use my own documentation today & then notice the typo in the code, note the **`** that is not needed in the string
Fixes typo introduced from my PR #3865
=> Fix up my code typo from my PR #3865

api/advanced-topics/remote-extensions.md, blogs/2020/07/01/containers-wsl.md, docs/remote/attach-container.md, docs/remote/containers-advanced.md, docs/remote/containers-tutorial.md, docs/remote/containers.md, docs/remote/create-dev-container.md, docs/remote/devcontainerjson-reference.md, docs/remote/faq.md, docs/remote/images/containers/containers-attach.png, docs/remote/images/containers/k8s-attach.png, docs/remote/images/containers/select-a-sample.png, docs/remote/troubleshooting.md
Containers.md content pulled out into:
Attach to a Running Container - docs/remote/attach-container.md - in TOC
Create a Development Container - docs/remote/create-dev-container.md - in TOC
devcontainer.json reference - docs/remote/devcontainerjson-reference.md - not in TOC
I also streamlined the Containers.md Getting Started content to make it less scary. Let me know if you think we need to keep in some of the caveats about Linux and Docker or if most users won't hit these.
I couldn't help myself but I took out some of the `-ing` in H2 headers. If you think many people have created heading bookmarks, I can revert those updates.
=> Refactor containers.md into several topics

api/language-extensions/semantic-highlight-guide.md
When I tried to implement semantic highlighting for my own extension, I read this guide. It doesn't explain how to actually construct a `SemanticTokens` response, it only has the comment:
```ts
// analyze the document and return semantic tokens
```
Instead I read the documentation for [`provideDocumentSemanticTokens`](https://code.visualstudio.com/api/references/vscode-api#provideDocumentSemanticTokens) which walks you through how to transform your data to a low-level Uint32Array.
But I could have avoided this all by using the built-in `SemanticTokensBuilder`! Add a simple example using `SemanticTokensBuilder` that will actually highlight the text in the document.
=> semantic highlighting: add semanticTokensBuilder example

blogs/2020/07/01/containers-wsl.md
The list items 'Opening existing source code in a container' and 'Working with a GitHub repository' both refer to the same place in the documentation where it is described how to open an existing folder in a container.
However, there is a dedicated section about how to open a Git repository or GitHub PR which is probably more appropriate for the last list item.
=> Fix wrong link

docs/editor/extension-gallery.md
since eslint is the successor to tslint, it might be best to just remove this from the docs to keep things current with the times
=> remove mention to (deprecated) tslint extension

api/extension-guides/notebook.md
Stumbled on a broken link, FTFY.
=> Update vscode-notebook-renderer-starter link in Notebook API

release-notes/v1_48.md
Hello,
I'm an intern on the Azure Cache team and we recently released a new VS Code extension ([link](https://marketplace.visualstudio.com/items?itemName=ms-azurecache.vscode-azurecache)) that lets users interact and view data in their Azure Caches.
We're hoping to have the extension featured in the next VS Code release notes, similar to how it's done [here](https://code.visualstudio.com/updates/v1_46#_azure-extensions).
=> Include new Azure Cache extension in 1.48 release notes

docs/nodejs/nodejs-debugging.md
`port` in debug configurations should be number and not string, otherwise 'Incorrect type. Expected "number".' error is shown.
=> Fix port to be number

docs/languages/dotnet.md
The `-lang` parameter to create `F#` console applications must be quoted.
References:
https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode
=> Fix dotnet cli command typo

docs/languages/javascript.md, docs/languages/typescript.md
Fixes https://github.com/microsoft/vscode/issues/104219
=> Add codeActionsOnSave to docs

docs/containers/quickstart-python.md
I wanted to make sure it was clear that the gunicorn entry point is not used in the python django or python flask launch configurations.
=> Added information about Gunicorn

api/extension-guides/product-icon-theme.md
There was a confusing double use of the word extension.
=>  Remove typo from Product Icon Theme preview warning

api/working-with-extensions/publishing-extension.md
The PR https://github.com/microsoft/vscode-vsce/pull/474 added a new `--githubBranch` flag to override the GitHub branch for relative links in the `README`.
=> Mention new VSCE --githubBranch flag

docs/containers/debug-common.md
In VSCode, creating a new launch config within launch.json with the template name Docker: .NET Core Attach (Preview) will create a config listed in the .NET Core section. I believe the quote saying "previous (Preview)" is deprecated is ambiguous, since the documentation doesn't say that the current version of the config available as a launch config template is still labeled as a preview. This let me to believe that the config I had added within my launch.json was the deprecated implementation.
I propose this simple change to clear up my original confusion.
See comment: https://github.com/microsoft/vscode-docker/issues/2248#issuecomment-680043505
=> Remove confusion about .NET Core Docker Config Deprication

api/extension-guides/notebook.md
notebookProvider.ts was moved into a folder and breaking the link.
=> Fixed dead link

docs/getstarted/telemetry.md, docs/supporting/faq.md
With Electron 9 that is going out with `1.49` we have changed the preferred way of disabling crash reporter.
=> docs: update disabling crash reporter section

docs/languages/cpp.md
Please merge after September 14th, 11 am
remove "preview" from c/c++ extension
=> remove "preview" from c/c++ extension 1

api/extension-guides/notebook.md
Since I've updated the notebook debugging samples to the latest APIs, I noticed that they are referred in the notebook API doc. I took the liberty to clarify how notebook debugging can be implemented and how this is shown in the samples.
=> clarify notebook's debugger section

docs/other/unity.md
The documentation presumed that the users folder is on C: and used a {username} pseudo-wildcard. Using %localappdata% ensures that the path goes to the user's local appdata folder and allows them to copy paste the path from the docs.
=> Change default VS Code path to use %localappdata%

docs/editor/intellisense.md
By default, `tabCompetition` is off.
https://code.visualstudio.com/docs/getstarted/settings#_default-settings
Although I still use `Tab` to confirm suggestions, even though it's disabled. 🤔
=> IntelliSense minor update

docs/other/unity.md
https://code.visualstudio.com/docs/other/unity#_unity-version-20192-or-above
=> Remove broken image from unity docs and fix link

docs/containers/debug-node.md, docs/python/tutorial-create-containers.md
This PR cleans up the docs a bit to use the Dockerfile `ENV key=value` syntax.
I haven't changed the screenshots, I think it's good enough to have the copy-pastable code examples updated.
See also https://github.com/microsoft/vscode-docker/pull/2344
=> Use Dockerfile ENV key=value

docs/editor/accessibility.md
it is outdated. and NVDA has its own appModule
=> stop advertising NVDA add-on for VS Code

docs/setup/linux.md
Although https://github.com/microsoft/vscode/issues/3541 shows `code` as an `editor` alternative, it doesn't show as a valid option when installed as an Snap package. This commit add instructions on how to manually install `code` as an editor alternative.
=> Add instructions to install vscode as alternative

api/working-with-extensions/continuous-integration.md
This fixes https://github.com/microsoft/vscode-docs/issues/4060
Previously if someone used this script directly any failing npm tests would not fail the Actions build due to a bug in version 1.2 of GabrielBB/xvfb-action. Xvfb is included in the GitHub Actions Linux images now so we can instead use Xvfb directly. [`xvfb-run`](https://manpages.ubuntu.com/manpages/trusty/man1/xvfb-run.1.html) is a wrapper for the Xvfb command which simplifies the task of running commands within a virtual X server environment.
I've also tested that this method correctly fails the Actions build if any tests fail as shown in this PR on my own extension https://github.com/golf1052/code-sync/pull/47
=> For GitHub Actions use xvfb directly

docs/getstarted/tips-and-tricks.md
Currently there is no key binding shown for **Find All References** because it refers to an invalid (probably old) command ID.  
By replacing it with the current ID the key binding should be shown again.
=> Show key binding for 'Find All References'

docs/editor/images/userdefinedsnippets/builtin-javascript-snippets.png, docs/editor/userdefinedsnippets.md
There is no reference to the built-in snippets available in the [Snippets in Visual Studio Code](https://code.visualstudio.com/docs/editor/userdefinedsnippets) User Guide. 
This topic was raised in issue #3642 .
In the PR, I have added a section about the built-in snippets.
=> Documentation lacks information on builtin Snippets

docs/supporting/troubleshoot-terminal-launch.md
This was not clearly documented on stackoverflow or other sources and took too long to sort.
More and more developers are moving to the WSL for day-to-day development so seems pertinent to have this included here.
=> Added relevant WSL terminal launch code 1 issue.

api/references/commands.md
Seems the returned object is of type LocationLink (based on a debug inspection of the values)
=> Doc: Fix vscode.executeDefinitionProvider return type

docs/python/editing.md
- Move the warning pop up about `black` not supporting "Format Select" inside the troubleshooting table.
- Add setting for formatting the whole file at save (instead of only "modifications") since that also triggers the warning.
=> Improve black warning troubleshooting

api/extension-guides/tree-view.md
I believe #3831 was closed incorrectly, as it was referring to this docs example, not the auto-generated API reference.
I think the example code is overly wordy with repeating the type three times when once will suffice, but since that's how it already was I'm leaving that and simply updating it so that the provided example actually compiles.
=> Fix TreeDataProvider.onDidChangeTreeData example

docs/python/tutorial-django.md
=> typo fix in tutorial-django.md

api/extension-guides/webview.md, api/references/theme-color.md
After sharing the theme completions extension in the VS Code Development Slack, several people suggested adding a pointer to it in the docs.
=> suggest extension to provide intellisense for webview theme variables

docs/editor/command-line.md
Portable mode (presence of  `/data/` folder in VSC installation directory) effectively prevents `--user-data-dir` and `--extensions-dir` switches from working.
Been told it is OK and will not be changed: https://github.com/microsoft/vscode/issues/63657
This info could potentially save a lot of WTH moments and confused fuddling to folks looking at this docs and not getting it working in their "Portable installs" when for example trying to launch a "vanilla" profile without touching their `/data/` directory.
(This edit is crude, probably would be better as a note below table, but I couldn't figure it out how to formulate and mark it.)
=> Mark 2 command switches ineffective in Portable

docs/editor/integrated-terminal.md
Running Git Bash like the change in the pull request causes `$USERPROFILE/.bash_profile` to also be loaded, potentially loading important environment variables, aliases or other configuration.
=> Run $USERPROFILE/.bash_profile in Git Bash

api/working-with-extensions/testing-extension.md
Since [Mocha 8.0.0](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#800--2020-06-10) `useColors` was removed, and now we should set the `color` as `true` on on `new Mocha`
=> Update mocha code on "testing-extension"

api/extension-guides/notebook.md
Fix the identifier for the notebook provider according to example extensions: [Jupyter example](https://github.com/microsoft/notebook-extension-samples/blob/master/notebook-provider/package.json) and [GitHub issues example](https://github.com/microsoft/vscode-github-issue-notebooks/blob/master/package.json)
@JacksonKearl would you be able to verify if I made a right correction?
=> Fix identifier for notebook provider in package.json and fix typo

docs/python/data-science-tutorial.md
In newer versions, the following can not be found: "Python: Create New Blank Jupyter Notebook" and "Jupyter: Create New Blank Jupyter Notebook" is available instead.
=> Changed  Python: to Jupyter: for new notebooks

api/references/theme-color.md
I don't think people are using vscode or creating a color theme that supports 3 years old outdated colors.
=> Remove outdated colors

api/references/contribution-points.md
Adds a note in the contribution points section that `views` can either be tree views or webview views
=> Add note on webview views to contribution points

docs/azure/kubernetes.md, docs/containers/bridge-to-kubernetes.md
No code or content changes. Part of an effort to remove unnecessary versioning link syntax.
See user story [1797650](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1797650) for more information.
=> 1797650: Remove '?view=azure-cli-latest' link syntax

docs/containers/bridge-to-kubernetes.md
The "Disconnect After Debugging" setting's description was a little bit different in the current version. I confirmed with Bridge to Kubernetes v1.0.120201118.
=> Fix Disconnect After Debugging setting description

release-notes/v1_52.md
This adds a blurb at the top (is that the right place?) with a link to the GH Universe session. The video should be live by the time we publish tomorrow. Once the video is on YouTube, I will update the link to point to our YT channel (where I'll syndicate the video) instead.
=> GH Universe video in release notes

api/working-with-extensions/publishing-extension.md, docs/editor/extension-gallery.md
Very minor chore, but the inconsistency bothered me.
- Changed all instances of "MarketPlace" to "Marketplace" which is the official spelling as found everywhere else it is referenced, as well as in the Marketplace itself.
=> Fix "Marketplace" capitalization

docs/containers/reference.md
~~Please do not merge this yet, we plan to release tentatively December 16.~~
Pertaining to https://github.com/microsoft/vscode-docker/issues/2445. @karolz-ms @philliphoff @ghogen @gregvanl FYI. This adds a section for the new `docker-compose` task and the new `${serviceList}` token for the Compose Up customizable command, along with a few minor corrections.
=> Add info about compose task and service subsets

docs/remote/containers-advanced.md
The link to see more details in **Use Clone Repository in Container Volume** section is pointing to **Open an existing folder in a container**.
I believe it should point to **Open a Git repository or GitHub PR in an isolated container volume** since we are talking about how to "Clone Repository" and not "Open an existing folder...".
=> Update clone repository link

api/extension-guides/custom-editors.md, api/extension-guides/tree-view.md, api/references/vscode-api.md, docs/cpp/natvis.md, docs/python/settings-reference.md
Some 'the the's are found in the document. This PR provides corrections of them.
I hope these are not intentional.
Thanks!
=> Remove duplicate 'the's

docs/containers/reference.md
The example configuration for a docker-compose task does not align with the reference outlined below it. I fixed this by adding the `dockerCompose` property to the example.
I ran in to this issue myself during configuring of a project that used docker-compose. The errors of the VSCode linter pointed me in the right direction, declaring that "up" was not an allowed property; Even though I just copied the example from the docs.
=> Fix example configuration for docker-compose task

docs/azure/kubernetes.md
Azure Dev Spaces was deprecated; the newer technology to point to is Bridge to Kubernetes.
The references to Java and Azure Dev Spaces were outdated. If equivalents for Bridge to Kubernetes are available, we could add links to that.
=> Azure Dev Spaces --> Bridge to Kubernetes

docs/containers/debug-python.md, docs/containers/docker-compose.md, docs/containers/quickstart-python.md
Removed Gunicorn specific debug directions. We now have a compose debug file that allows our users to volume map the debugger into a container. 
Updated Docker Compose Python directions with clearer information. 
Note: Will likely be out for the rest of the year starting Dec 14th, so feel free to make any edits or you can wait until I am able to make the necessary changes.
=> Gunicorn edit

docs/languages/json.md
Currently the json language service escapes markdown in description tooltips unless it is specified as `markdownDescription` instead of `description`.
|With `description`|With `markdownDescription`|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/102041749-38159e00-3d9e-11eb-9112-92938e776115.png)|![image](https://user-images.githubusercontent.com/1770056/102041768-45328d00-3d9e-11eb-8113-5320cf17e31a.png)|
Since this is a VSCode specific extension of JSON Schema, I figured it could use a spot in the documentation.
I did notice the other VSCode specific schema extension, `defaultSnippets`, [does have documentation](https://code.visualstudio.com/docs/languages/json#_define-snippets-in-json-schemas).
I would have had no idea how to do this if I hadn't gone digging into …
=> Add documentation about `markdownDescription` JSON schema extension

docs/remote/containers-advanced.md
The correct location, for the devcontainer.env file is the complete path ".devcontainer/devcontainer.env" and not as  described, relative to the devcontainer.json file.
=> Error in devcontainer.env file location

docs/getstarted/keybindings.md
Was not rendering the line for 'Or' correctly on GitHub due to GitHub's handling of pipe characters
=> Fix conditional operators table

docs/java/extensions.md, docs/java/java-tomcat-jetty.md, docs/languages/java.md
The "MicroProfile Extension Pack" has been renamed to "Extension Pack for MicroProfile". Update all references to use the new name.
Signed-off-by: Kathryn Kodama <kathryn.s.kodama@gmail.com>
=> Rename to Extension Pack for MicroProfile

docs/supporting/images/troubleshoot-terminal-launch/search-for-modified-settings.png, docs/supporting/images/troubleshoot-terminal-launch/search-for-settings.png, docs/supporting/images/troubleshoot-terminal-launch/settings-json-file.png, docs/supporting/troubleshoot-terminal-launch.md
Call out that troubleshooting steps work on all platforms.
Move Step 1 about Windows to be a Note.
Add more direction about checking settings and @modified filter tip.
Fixes #4240
=> Mention all platforms and add help for settings
