- runtimes/ASPnet5.md
- runtimes/office.md
With the ASP.NET 5 Beta 7 release, the folder parameter is no longer permitted in the dnx command. See [here](https://github.com/aspnet/Announcements/issues/52) for more info. I have updated the sample dnx command accordingly.
> Updated inaccuracies in documentation

- runtimes/ASPnet5.md
See template: https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/hosting.ini
> Updated default port based on yo template

- docs/extensions/example-hello-world.md
- docs/extensions/example-word-count.md
Two, fairly minor, grammar tweaks that bugged me as I read the documentation.
> Misc grammar cleanup

- docs/languages/csharp.md
There was  word missing and it didn't seem clear what the purpose of the sentence was, so i removed it all together.
> Get rid of sentence that was unclear.

- docs/languages/markdown.md
It would be better to ask "What flavors of Markdown do you support?", but I don't know the answer to that.
--Beman Dawes, Boost.org
> Add GitHub Flavored Markdown FAQ

- docs/editor/editingevolved.md
> Grammar tweak

- docs/tools/vscecli.md
> You can also load extensions locally and share them ~~view~~ via email [...]
> a small typo in vsce.md

- docs/extensions/install-extension.md
When I read this I wasn't sure what qualified as the generated output. I added a sentence describing an additional way to package a side loaded app that should help developers if they are confused.
> Added additional side loading instructions

- docs/languages/csharp.md
Added quickfix shortcut to c# language docs
> added quickfix shortcut to c# language docs

- docs/editor/setup.md
By setting the local environment variable VSCODE_CWD, just as in the above bash function, the code function supports opening multiple files/directories.
> Update `Fish Shell Tip` to support multiple paths

- release-notes/latest.md
> Fix typo in release notes

- blog/2016/02/23/introducing-chrome-debugger-for-vs-code.md
- GIF is down to 6.5MB. Still big, but that's the best I can get it down too.
- Re-added the "Introducing" to the title, as the post otherwise felt like an FAQ and not an intro post
> Optimized GIF for Chrome Debugger post + title update

- blog/2016/02/23/introducing-chrome-debugger-for-vs-code.md
-  Tweak wording of Chrome Debugger post to include Microsoft Edge
-  Update twitter account in chrome debugger post
> Tweak wording of Chrome Debugger post to include Microsoft Edge

- docs/runtimes/nodejs.md
Without the links, I wondered where that great documentation was. I tried man, didn't work... :-)
> Add links to documentation

- release-notes/latest.md
> Spell correction

- docs/supporting/requirements.md
> Add title tag to /supporting/requirements

- docs/extensionAPI/extension-manifest.md
see https://github.com/Microsoft/vscode/commit/3dfbf9058c7c07c347d61c528f241ee3c12b04fa
> isAMD has been removed

- docs/customization/keybindings.md
Added a bit on how to see the key bindings for another OS than the one you are using.
> Added note on seeing key for other OS

- docs/languages/markdown.md
This is the first time I use VS Code. And I found myself kind of lost at the beginning trying to figure out how is the support of Markdown in the editor, because the current instructions assume certain familiarity with the tool and also omit the fact that the file must be saved before visualizing it for the first time. Just giving a little more context at the beginning would be great.
> A better introduction of Markdown support.

- release-notes/latest.md
@pflannery I changed the settings keys to make them flatter after thinking about the integrated terminal settings
@gregvanl you may want to rephrase the OS X part?
> Clean up launch your preferred shell section

- release-notes/latest.md
I guess that should be "now" and not "not".
> FIXED: typo

- docs/languages/json.md
Settings spelled Settindgs in topic
> Typo in the instructions

- scripts/templates/portaldocs-template.html
- scripts/templates/releasenotes-template.html
Related to https://github.com/Microsoft/vscode-website/pull/392
> Making OpenGraph metadata page-specific

- docs/languages/cpp.md
Documented code formatting (clang-format), fuzzy auto-complete, windows (cygwin/mingw) debugging, macOS console app debugging.
> Doc new features for CPP extenision May update

- CONTRIBUTING.md
FWIW, here's how I've tried to explain it, targetting GitHub Flavored Markdown in issues / comments: https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify#formatting
> Improve code formatting in CONTRIBUTING

- docs/extensions/example-word-count.md
> Fixed trivial typo

- docs/editor/integrated-terminal.md
> Integrated terminal documentation improvements

- docs/editor/codebasics.md
> obvious typo

- docs/supporting/faq.md
Could be either :
"Want an early peek at" or  "Want to get an early peek at"
> Correction

- docs/languages/cpp.md
Added a getting started section and cleaned up some out of date debugger limitations
> Updates to C++ docs

- docs/introvideos/overview.md
Must be merged in tandem with its brother PR on the vscode-website repo.
> Updated intro videos page.

- blogs/2016/08/15/introvideos.md
- docs/introvideos/basics.md
@gregvanl it'd be great to get this out soon.
> Switched out to higher volume video.

- docs/languages/typescript.md
> Changes per Chris's suggestions

- scripts/gulpfile.releasenotes.js
Associate website PR - https://github.com/Microsoft/vscode-website/pull/477
> Modified gulpfile to copy raw markdown files

- docs/languages/overview.md
The list as it was implied a short lost of languages so this change is designed to correct that and make the page easier to maintain.
> Change description for languages

- docs/languages/csharp.md
Added "Video" to name of link for the Getting started Tutorial on channel 9.
Added Unity link to the first paragraph that mentions Unity game development.
> Update Video Link and Unity Link

- docs/introvideos/overview.md
Original title in video list was "Basics and Setup." Changed to "Setup and Basics" to keep consistency amongst sidebar ToC and page title of page (https://code.visualstudio.com/docs/introvideos/basics).
> Update overview.md - "Setup and Basics"

- docs/runtimes/dotnet.md
Added steps 3-5 to "Getting Started"
Linked my video tutorial from channel 9 at end for additional help.
> Added Steps to Getting Started

- docs/introvideos/overview.md
Must go along with PR for https://github.com/Microsoft/vscode-website/issues/304
> Correct heading hierarchy for intro videos

- docs/extensions/example-word-count.md
Removed an extra space in the code example indentation.
> Fixed indentation

- docs/introvideos/basics.md
- docs/introvideos/codeediting.md
- docs/introvideos/configure.md
- docs/introvideos/debugging.md
- docs/introvideos/intellisense.md
- docs/introvideos/overview.md
- docs/introvideos/quicktour.md
- docs/introvideos/versioncontrol.md
- docs/languages/javascript.md
> Upload new intro video.

- docs/extensionAPI/extension-manifest.md
The Marketplace has introduce a new category called formatters for extensions that add formatting.
> Added new marketplace categories

- docs/editor/integrated-terminal.md
feel free to delete my PR and fix via other edits.
> typo in Windows ps config

- docs/customization/keybindings.md
> Minor typo fixed

- docs/languages/markdown.md
I removed the future tense in a number of places. Using future text can, for some non-native English speakers, be a lot harder to understands. I also tighthed up on some of the sentences and corrected a typo. Just trying to make the text easier to read.
> Some minor gramatical changes

- docs/customization/keybindings.md
- docs/editor/codebasics.md
- docs/introvideos/basics.md
- docs/setup/setup-overview.md
Please take a look. No rush getting these out.
> Increase keymap visibility

- blogs/2016/11/15/formatters-best-practices.md
Ready for your eyes @gregvanl. 
We should talk timing of publishing date. We've got 1.7.2 and connect next week. We may want to do this end of next week or even start of the week after. 
Ping @jrieken - do you have any strong feelings on when this should go out? 
We could publish today... but I know there are some loose ties with the release hold.
> Formatter extension blog post

- docs/setup/linux.md
> Explain how to set VS Code as default app on Linux

- docs/editor/codebasics.md
#702
This section be expanded upon when Microsoft/vscode#15467 is resolved
> Hot exit documentation

- docs/editor/integrated-terminal.md
> Terminal font size no longer defaults to editor.fontSize

- docs/runtimes/dotnet.md
- Added tip explaining msbuild with link for more info
- Added link to additional video tutorials for mac and linux
- Added link to a [Debug doc walk through on .NET Core docs](https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/with-visual-studio-code)
- Added link to .NET Core docs
Debug walkthrough link is relevant to #530
> Update .NET Core Getting Started

- docs/editor/codebasics.md
@joaomoreno - Not sure if this is totally needed, but it seemed like it could be helpful.
Adds documentation to open a project and to open a file at a specific line and column number
> Update codebasics.md documentation for opening code with URLs

- docs/editor/codebasics.md
> Fixed spelling mistake

- docs/editor/debugging.md
See https://github.com/Microsoft/vscode/issues/19461
> fix node debugging link

- docs/languages/javascript.md
Fixes the sentence from:
Your workspace contains more then
to
Your workspace contains more than
> Grammar fix

- docs/introvideos/basics.md
- docs/introvideos/overview.md
> Update setup and basics video

- docs/introvideos/overview.md
- docs/introvideos/quicktour.md
> New quick tour video

- docs/languages/go.md
The test commands.png needs to be updated, but any screenshots I take look huge. @gregvanl Can you help?
> Polishing of go docs

- docs/setup/mac.md
> Improve `code` docs for macOS

- docs/extensionAPI/extension-manifest.md
Mention yo code extension pack generator support.
> Updated for 1.9

- docs/editor/tasks_appendix.md
Based on [this commit](https://github.com/Microsoft/vscode/commit/8b5b1eb495362c7215e05775be628b807c3f6bf5)
> Add ShellConfiguration to task doc

- docs/editor/intellisense.md
> Fix small mistake

- docs/setup/linux.md
Mostly the same as yum one, only the file path is different and we have to add repository type.
> Add documentation for openSUSE/SLE

- docs/introvideos/codeediting.md
- docs/introvideos/configure.md
- docs/introvideos/debugging.md
- docs/introvideos/extend.md
- docs/introvideos/intellisense.md
- docs/introvideos/overview.md
- docs/introvideos/versioncontrol.md
Before merging, @gregvanl and @pjmeyer please review each video:
After merging:
> New Intro Videos

- docs/getstarted/keybindings.md
Fixes https://github.com/Microsoft/vscode/issues/23229
> Add note on using settings in when clause

- docs/editor/debugging.md
Simply/please should be avoided.
> remove please/simply

- docs/getstarted/keybindings.md
> Add Keybinding command arguments section

- docs/getstarted/keybindings.md
Update to grammar in the command clause and when clause sections.
> Update to grammar

- docs/editor/tasks.md
Minor change, but it had me concerned that I was doing something wrong when my experience didn't match the documentation.
> Small typo

- docs/extensionAPI/api-scm.md
function createResourceUri should return vscode.Uri instead of string
> function createResourceUri should return Uri

- release-notes/v1_12.md
CHT contributor Alan helped on last minutes translation gap fill up. Want to include in release notes if still have time.
> Adding CHT contributor who helped on last minute gap fill up.

- docs/supporting/faq.md
Typo can be found at the **Important Notice** at https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting
> Fixed typo from 'addional' to 'additional' in FAQ

- docs/languages/json.md
Related issue with an example and some discussion: https://github.com/Microsoft/vscode/issues/26407
> Added warning about non-standard `$schema` mapping

- docs/editor/integrated-terminal.md
minor edit -- changed Window 10 to Windows 10
> minor edit -- typofix /Window 10/Windows 10/ (#1)

- docs/extensions/example-word-count.md
> Use let instead of var for consistency

- docs/nodejs/reactjs-tutorial.md
@gregvanl I did an edit pass. 
**Overall:** Fantastic! Easy to follow. Great for beginners to get going and experienced users to skim through to learn to make the most out of VS Code. Good use of images and code blocks. 
This PR is a few fixes I'd suggest. 
One other comment is on the title. "React Tutorial in VS Code" didn't feel right. Is it the preposition "in"? It is what we do for the Node.js Tutorial so might not be worth changing. It seems like we want something like "Using React in VS Code Tutorial" but that is too long and doesn't flow well. Worth discussing.
> Edit pass on reactjs-tutorial

- release-notes/v1_13.md
Adding recognition to Transifex localization contributors of May iteration release to Release Notes.
> Adding recognition to Transifex localization contributors of May.

- docs/languages/csharp.md
Follow up to https://github.com/Microsoft/vscode-docs/pull/1020
> Removed unneeded "both"

- docs/getstarted/theme-color-reference.md
Small wording adjustment that I found slightly confusing on my first pass. 
This also takes care of a typo.
> Re-word overview ruler explanation

- docs/getstarted/settings.md
> Add missing comma

- docs/editor/command-line.md
in propose with https://github.com/Microsoft/vscode/issues/27768
> add info about how to use code-insider at cmd

- docs/editor/debugging.md
- docs/editor/tasks.md
For https://github.com/Microsoft/vscode/pull/28018
I added the debugging with transpilation section. See if you need to make some adjustements to the wordings.
> Add relativeFileNoExtension doc

- blogs/2016/06/27/common-language-protocol.md
Unreachable site for json-rpc - Changed back to http
> Json-rpc specification not available on https

- docs/extensionAPI/extension-points.md
Most of the text is copied from https://code.visualstudio.com/updates/v1_11#_tasks
I could not find any documentation on `problemPatterns`, so I am not sure what the usage is.
> Document contributes.problemMatchers

- release-notes/v1_14.md
Adding June update release localization contributors to release notes - v1_14.md.
> Adding June update release localization contributors to release notes

- docs/editor/integrated-terminal.md
See https://github.com/Microsoft/vscode/issues/12006
> Adds cmder specific details for integrated terminal

- docs/languages/markdown.md
"Workplace Settings" is not found from the submenu of File.
> "Workplace Settings" -> "Settings"

- docs/editor/integrated-terminal.md
Microsoft/vscode#8429
Microsoft/vscode#22971
> Change Linux & OS X to Shell arguments section

- release-notes/v1_15.md
Merging Localization contribution acknowledgement for July update release
> Merging Localization contribution acknowledgement for July update release

- docs/editor/debugging.md
- docs/getstarted/settings.md
- docs/nodejs/nodejs-debugging.md
This ensures that there are proper vertical spacing between the images and their surrounding text.
See #1115 for details.
> Wrap <img> tags in paragraphs

- docs/extensionAPI/vscode-api.md
- package.json
- scripts/api-doc/doc.js
- scripts/api-doc/doc.ts
- scripts/api-doc/model.js
- scripts/api-doc/model.ts
- scripts/api-doc/styles.css
- scripts/gulpfile.api.js
Since typedoc was outdated, I updated it.
I can not do complete debugging, but I confirmed that it worked on my clone site.
by typedoc 0.5.5
https://github.com/Microsoft/vscode-docs/blob/eb0f79a71ad79c463e898f30769167a572422af6/docs/extensionAPI/vscode-api.md
by typedoc 0.8.0
https://github.com/Microsoft/vscode-docs/blob/dea80ed88bc2801f3a7c158c0584f8b935fcda27/docs/extensionAPI/vscode-api.md
> Update to typedoc 0.8.0

- docs/extensionAPI/language-support.md
- docs/extensions/themes-snippets-colorizers.md
A few small nitpicks I found while creating an extension. Overall the docs have been incredibly useful so far, keep up the good work!
> Fix some typos and grammatical nitpicks

- docs/languages/typescript.md
From https://github.com/Microsoft/vscode/issues/32658#issuecomment-323219492
> Add note on pointing typescript.tsdk to a full TS install

- docs/nodejs/reactjs-tutorial.md
The previous order of the first sentence made it a little ambiguous - is React only for web applications developed by Facebook? No.
> Clarify wording about React's purpose and origin

- release-notes/v1_15.md
- release-notes/v1_16.md
Adding August update release localization contributors.
> Adding August update release localization contributors.

- release-notes/v1_16.md
Updated to the correct youtube link for the highlights video
> Correct youtube link

- release-notes/v1_16.md
> Adds a missing thank you

- release-notes/v1_17.md
Adding September update release localization contributors.
> Loc/v117: Adding September update release localization contributors.

- docs/languages/csharp.md
The existing link is outdated and a new video is available.
> Updated link to video tutorial

- docs/languages/html.md
> HTML5 is one word

- docs/editor/tasks-appendix.md
> Remove possible error in comment

- release-notes/v1_18.md
Recognition of localization contributor of October update release.
> Adding October update release localization contributors.

- docs/editor/multi-root-workspaces.md
Multi-root shipped in 1.18, removed note about Insiders only
> Multi-root is no longer Insiders-only

- docs/java/java-tutorial.md
> Update the Java tutorial

- docs/editor/integrated-terminal.md
after installing github, vs code suggests changing the default terminal to bash instead of powershell.
I clicked OK thinking it's easy to change in terminal window by some button but I didn't find how to change it even through reading this document
so propose file change is about how to customize default terminal
> A problem I faced and now found the solution

- docs/nodejs/reactjs-tutorial.md
> Fixed grammar on reactjs-tutorial.md

- release-notes/v1_19.md
Localization contributor recognition.
> Adding November udpate release localization contributors.

- docs/extensions/themes-snippets-colorizers.md
Provide the actual commands for running the Yeoman generator,
as is done in docs/extensions/example-hello-world.md
> themes-snippets-colorizers.md: yo code setup

- docs/setup/linux.md
@dcelasun what was the reason for the change?
> Fix link to AUR

- docs/editor/integrated-terminal.md
> Fix term Windows sysnative advice

- docs/editor/debugging.md
- docs/editor/tasks-v1.md
- docs/editor/tasks.md
Add doc for Microsoft/vscode#39483
> Add selectedText to variable substitution section

- docs/python/debugging.md
See issues [#514](https://github.com/Microsoft/vscode-python/issues/514) and [#133](https://github.com/Microsoft/vscode-python/issues/133)
> Only PTVSD version 3.0.0 is supported at present.

- docs/extensionAPI/extension-points.md
For https://github.com/Microsoft/vscode/issues/41113
Adds documentation on the new `typescriptServerPlugins` contribution planned for 1.20.
@gregvanl Please let me know if you feel there is a better place to document this
> Add section on typescriptServerPlugins contributions

- docs/other/unity.md
Update prerequisites to address OSX and Windows users, with O/S specific steps.
> Clarify prerequisites for Windows users

- docs/java/java-webapp.md
Just a small grammatical fix. 'We've built' could also work.
> Edit java-webapp.md: 'we've build' to 'we built'

- docs/languages/python.md
Fixed "thirty-party" to "third-party"
> Thirty-party fix

- docs/java/java-container.md
Noticed a minor typo (registory) when working through this otherwise excellent tutorial.
> minor typo (registory)

- docs/languages/csharp.md
> Add link to C# extension wiki for full .NET

- docs/supporting/live-share-faq.md
This PR simply updates the FAQ for Live Share.
// CC @pjmeyer
> [Live Share] Updating FAQ

- release-notes/v1_20.md
Adding January update release localization contributors.
> Adding January update release localization contributors.

- docs/supporting/live-share-faq.md
Since starting the private preview, we've had the question about tooling requirements come up frequently enough that it makes sense to address it in our FAQ.
> [Live Share] Adding FAQ question about tooling requirements

- tutorials/functions-extension/create-app.md
- tutorials/functions-extension/create-function.md
- tutorials/functions-extension/deploy-app.md
- tutorials/functions-extension/getting-started.md
- tutorials/functions-extension/run-app.md
Broke create app into three separate steps: create app, create function,
run app. Added some detail to the functions tools installation verification
and added a link to the docs describing the functions binding config.
> Break the Functions tutorial into discrete steps.

- tutorials/app-service-extension/getting-started.md
- tutorials/docker-extension/getting-started.md
- tutorials/functions-extension/getting-started.md
Updated each link to correctly indicate the source article.
> Update Azure referral link tracking.

- docs/editor/tasks.md
Only minor changes.
Learning about pull requests - I'm supposed to start somewhere!
> Fixed typos in tasks.md

- docs/languages/identifiers.md
language identifiers: add ABAP
used in https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abap
https://github.com/larshp/vscode-abap/blob/master/package.json
> language identifiers: add ABAP

- docs/extensions/example-debuggers.md
> Fix typo in example-debuggers.md

- docs/editor/debugging-recipes.md
- docs/nodejs/debugging-recipes.md
> Update debugging recipies

- docs/nodejs/nodejs-debugging.md
- release-notes/v1_21.md
Added by Microsoft/vscode-node-debug#171
> Document support for nvs

- docs/languages/html.md
built-in vs built-it. Thank you very much for providing such detailed documentation
> Fixed simple typo on line 147

- release-notes/v1_21.md
Adding February update release localization contributors.
> Adding February update release localization contributors.

- docs/getstarted/keybindings.md
Fixes Microsoft/vscode#43623
@alexandrudima please review
> Add FAQ about ctrl/cmd+k to clear terminal

- docs/python/environments.md
Please do not merge until the next release of the Python extension for VS Code goes live.
Closes Microsoft/vscode-python#965
> Mention support for pyenv, pipenv, and direnv in Python

- docs/getstarted/locales.md
Adding Bulgarian, Hungarian, Portuguese (Brazil),  Turkish which now suppoted through Language Pack extension in Marketplace.
Move Spanish higher in the list.
> Adding Language Pack languages to locale list

- release-notes/v1_18.md
- release-notes/v1_19.md
Hi,
I've renamed my account from maxibanki to mxschmitt, so it would be cool, when we could fix those dead URLs.
Best regards
Max
> renamed username from maxibanki to mxschmitt

- tutorials/app-service-extension/deploy-app.md
- tutorials/app-service-extension/getting-started.md
Added notes about the most common issues including users attempting to
deploy to exisitng Windows plans and users behind a proxy that are
unable to authenticate with the extension.
> Update the app service tutorial based on feedback.

- tutorials/nodejs-deployment/create-website.md
There have been a few people that got tripped up on this step because they are
using PowerShell. This includes the PS specific command with escaping.
> Add PS specific command to CLI create.

- docs/python/debugging.md
> Wording change

- docs/editor/extension-gallery.md
"Everything that can be HTTPS should be HTTPS"
> HTTPS links

- docs/python/debugging.md
> Update debugging.md to fix definition of python debug console

- docs/editor/userdefinedsnippets.md
I thought that your sentence was not very clear and hope that my sentence is better.
> Clearification on multiple tabstops

- tutorials/static-website/deploy-cli.md
- tutorials/static-website/getting-started.md
Removed steps to create storage resources using azure-cli because we already walk the user through it in the previous section using portal.
> Fixed repeated storage creation in cli

- docs/extensions/example-hello-world.md
> Fix bulleted list in example-hello-world.md

- docs/getstarted/themes.md
> Fix command

- docs/getstarted/theme-color-reference.md
Issue: https://github.com/Microsoft/vscode-docs/issues/1587
> Added missing workbench colors

- docs/languages/jsconfig.md
- Added a link to the tsconfig.json reference.
- Added the expected string syntax to "include" and "exclude".
A follow up to https://github.com/Microsoft/vscode-docs/pull/1595#issuecomment-386771168.
> Clarified some tsconfig.json relations

- tutorials/static-website/code-change.md
Fixed inconsistency with number of exclamation marks in the React code snippet.
The image shows one, and the code example had three.
> Removed two exclaimation marks to solve inconsistency in a React code snippet.

- docs/editor/versioncontrol.md
VSTS URL was incorrect previously
> Fix VSTS URL in versioncontrol.md

- docs/python/python-tutorial.md
The live site shows 1, 2, 1 instead of 1, 2, 3.
I also cleared two linting errors.
> Fixed numbering of Prerequisites.

- docs/getstarted/tips-and-tricks.md
On MacOS this opening from Code > Preferences > User Snippets
> Create custom snippets

- docs/editor/integrated-terminal.md
Part of Microsoft/vscode#46954
> Add documentation on rendererType setting

- docs/nodejs/angular-tutorial.md
Name of image file was not correct in link. image name has capital 'W'.
> Updated Welcome to app image link

- docs/editor/multi-root-workspaces.md
Make command reference bold to adhere to the [formatting guideline](https://github.com/Microsoft/vscode-docs/blob/master/CONTRIBUTING.md#text-formatting)
> Use proper formatting for command reference

- release-notes/v1_24.md
This PR fixes several typos and grammatical errors, instead of explaining the details, I'd let you check the changed instance and for details, the grammatical error commits have descriptions attached to them.
Peace! ✌️
>  📖 DOC: Fix Several Typos and Grammatical Errors

- release-notes/v1_24.md
> Typo in v1_24.md

- docs/languages/python.md
Corrects a closing brace on the pip3 command.
> Correct a closing brace in python docs

- blogs/2018/07/11/introducing-logpoints-and-auto-attach.md
Here are some fixes for typos and a few suggestions.
> Some small fixes and suggestions

- docs/extensions/example-language-server.md
"implemented in *ther* native programming languages" -> "implemented in *their* native programming languages"
> Update example-language-server.md to correct typo

- tutorials/static-website/create-storage.md
Added an additional step to storage creation to explicitly call out that
gpv2 is requried.
> Update storage creation to mention setting gpv2.

- tutorials/functions-extension/run-app.md
Used xplat shortcuts (Ctrl, Cmd) following docs pattern 
Thanks!
> Update open in browser shortcuts

- docs/editor/multi-root-workspaces.md
fixed a typo in the multi-root-workspaces.md file
> fix a typo

- docs/azure/docker.md
docker.languageservice.diagnostics -> docker.languageserver.diagnostics 
See here: 
https://github.com/Microsoft/vscode-docker#configuration-settings
> Docker.md: Update the setting to customize linting

- tutorials/static-website/getting-started.md
The configuration option is no longer required so this will remove it
from the tutorial. Also updated the version output information to be a
little more current.
> Remove configuration requirement for static sites.

- release-notes/v1_26.md
> Adding July update release localization contributors- fixed version

- docs/java/java-azurefunctions.md
Update document to use Azure Functions instead of serverless
> Update document to use Azure Functions

- docs/editor/userdefinedsnippets.md
Removing the comma as it's not needed in this case.
> Deleted trailing comma

- docs/editor/versioncontrol.md
Add PR section to Version Control topic.
See https://github.com/Microsoft/vscode-website/commit/c35b3f2e4dbeba76a84de683ed8ae72473d7c28f
> Add PR section to Version Control topic

- docs/extensionAPI/extension-points.md
Fix Microsoft/vscode#58353
@octref is this the right place for this?
> Add note about using "markdownDescription"

- docs/python/python-tutorial.md
- docs/python/tutorial-flask.md
Address https://github.com/Microsoft/vscode-docs/issues/1849
> Fix MacOS python command

- docs/python/python-tutorial.md
> Mention matplotlib limit on Windows Linux Subsystem

- docs/supporting/faq.md
- adding a section about recommendations
> add a recommendation FAQ

- docs/extensionAPI/extension-points.md
> Fix some typos

- docs/python/environments.md
> doc: added documentation on python extension

- docs/python/environments.md
Added documentation on Python Virtual Environments configuration (resolves #1878)
> doc: added documentation on python venv (#1878)

- docs/python/environments.md
Reverts Microsoft/vscode-docs#1905
> Revert "doc: added documentation on python venv (#1878)"

- docs/python/editing.md
- docs/python/python-tutorial.md
- docs/python/tutorial-django.md
- docs/python/unit-testing.md
Makes a few minor grammatical corrections to some of the Python docs, adds links to the DBMS homepages in the Django tutorial.
> Minor improvements/corrections to Python docs

- docs/languages/css.md
Update css.md According to  [Update 1.23.1](https://code.visualstudio.com/updates/v1_23#_css-region-folding) and  [Update 1.27.2](https://code.visualstudio.com/updates/v1_27#_path-completion-for-css-imports)
> fixes css.md

- docs/editor/tasks.md
- docs/getstarted/userinterface.md
- docs/languages/javascript.md
Fixed a few typos. Happy #hacktoberfest ;)
> Some documentation fixes

- docs/python/settings-reference.md
Added documentation in `settings-reference.md` on the new `python.condaPath` setting. 
This will resolve #1867
> doc: add conda setting

- tutorials/app-service-extension/deploy-app.md
you're prompted to updateD your... --> you're prompted to update your...
> a pair of typos

- release-notes/v1_28.md
Nothing critical, just a tiny fix :)
> Fix typo in September 2018 release notes

- README.md
Updated the README to include an additional comma, representing that each of the three listed operating systems are supported.
> Include oxford comma in list of OSes supported

- CONTRIBUTING.md
Hope I helped, and happy Hacktoberfest 2018!
> I've added links to the GitHub help page on how to fork and pull request!

- docs/getstarted/keybindings.md
> Added reference to Complex commands page to easy access related information.

- docs/python/tutorial-django.md
Tutorial updates for the sample code changes proposed in PR: https://github.com/Microsoft/python-sample-vscode-django-tutorial/pull/1
> Tutorial updates for sample code changes

- docs/python/debugging.md
> fixed typo

- docs/setup/mac.md
sync differences between  docs/setup/mac.md and  docs/setup/windows.md
> sync docs/setup/ across mac and windows 

- docs/getstarted/tips-and-tricks.md
Second attempt to my first contribution to open source and Visual Studio code documentation for issue #1423 opened by tsalinger. I tried to process the feedback that I got last time. I hope I processed the feedback in the right way.
> Multi cursor selection

- docs/getstarted/tips-and-tricks.md
This PR
- Fixes minor typo in the word `everyday`. It should be `every day`.
`Everyday` is an adjective that means **commonplace** or **happening every day**.
`Every Day` is an adverbial phrase that means **each day** or **daily**
> Add missing white space in tips-and-tricks.md

- CONTRIBUTING.md
Adds help for editing a commit message and squashing commits.
> CONTRIBUTING.md: Adds help for editing a commit message and squashing commits

- docs/extensionAPI/extension-manifest.md
> Changed extensionDependencies to extensionPack

- docs/python/tutorial-django.md
- docs/python/tutorial-flask.md
This is just a draft of what I'm thinking about to put at docs.
Fixes #1967 .
> [WIP] saying more about pip freeze

- docs/languages/javascript.md
Changed the sentence structure.
> Small syntax changes to /languages/javascript.md

- docs/extensions/themes-snippets-colorizers.md
> Fix themes-snippets-colorizers.md

- docs/other/unity.md
linking anyone looking for unity debugging back to the debugging doc so they can learn how that works
> Adding more about unity debugging

- docs/getstarted/theme-color-reference.md
- docs/languages/css.md
- docs/languages/markdown.md
- docs/languages/powershell.md
- docs/other/office.md
- docs/python/debugging.md
- docs/python/environments.md
- docs/python/linting.md
- docs/python/python-tutorial.md
- docs/setup/linux.md
* Add language to code block
* Fix missing link
* Remove trailing space
> Improve markdown formatting

- docs/python/tutorial-django.md
- docs/python/tutorial-flask.md
> Fix typo in Django Tutorial

- docs/editor/portable.md
I think "extensions" is correct here?
> Fix a typo.

- docs/extensions/example-language-server.md
Updated and corrected a comment with a typo for the connection.onCompletionResolve handler.
> Fixed typo in Adding additional Language Features section

- docs/extensions/webview.md
This addresses issue #2060 and adds a list to the Theme color reference.
> Added a link to the Theme Color Reference.

- docs/getstarted/settings.md
Modified setting are indicated with a blue line on left of it. Added this info.
Feedback appreciated. 
Thanks
> added blue line indicator info

- CONTRIBUTING.md
Fixed typos in key bindings section
> Fix typos in contributing document

- CONTRIBUTING.md
One of the style guides is to keep the language simple, writing is much more frequently used than authoring and developing and this version a good bit more fluent to read through.
> Streamline wording of Contributing - Authoring Tools

- docs/extensionAPI/extension-manifest.md
- docs/nodejs/extensions.md
Add how to uninstall extension with hook tutorial, whith description in this [issue](https://github.com/Microsoft/vscode-docs/issues/2049) using with model this [documentatio](https://code.visualstudio.com/updates/v1_21#_extension-uninstall-hook) update.
> Add how to uninstall extension with hook to nodejs tutorial

- docs/extensions/testing-extensions.md
Cleaned up the extension CI docs. Will contribute another PR for Azure Pipelines.
> Improve extension CI docs

- docs/nodejs/nodejs-debugging.md
Per https://github.com/Microsoft/vscode-docs/pull/2105#issuecomment-434088078
> Add FAQ for debugging ES modules with Node

- docs/python/tutorial-flask.md
Added link to Jinja on first mention, and changed Jinja links to point to the latest version automatically
> Fix Jinja links

- docs/python/python-tutorial.md
> Clarify `code .` setup for macOS users in python tutorial

- docs/setup/linux.md
This PR just adds/tweaks some punctuation and grammar where I feel the flow of sentences is improved by doing so, as well as adds formatting where I believe it may have been overlooked. Additionally, I updated the information on fixing Chinese character display on Ubuntu to make use of the new settings interface.
> Update and tidy Linux setup documentation a bit

- tutorials/nodejs-deployment/deploy-website.md
- tutorials/nodejs-deployment/getting-started.md
- tutorials/static-website/code-change.md
- Added a comma as it didn't sound quite right
- One tutorial had "LTS" as "Long Term Support" and another as "Long Term Stable"
- One page had both "redeploy" and "re-deploy"
- Changed exclamation mark to a colon.
> Minor grammar fixes and clarification

- docs/python/python-tutorial.md
- docs/python/tutorial-django.md
I found some more problems with some of the code snippet in  **python-tutorial.md** and **tutorial-django.md**.
> Add imports and remove unused import

- release-notes/v1_29.md
- references view is a preview (try to be more clear about it)
- change wording in summary
> Release notes tweaking

- docs/editor/versioncontrol.md
Visual Studio Team Services extension renamed in Azure Repos
> Azure Repos extension name

- docs/python/linting.md
per https://github.com/Microsoft/vscode-python/pull/2775
@DonJayamanne
> Add bandit to python linting docs

- docs/python/tutorial-deploy-containers.md
In Changes for Django apps was Flask
> Fix Framework name

- docs/getstarted/tips-and-tricks.md
- docs/getstarted/userinterface.md
- add mouse related shortcuts
- fix `kbstyle`
> Add corresponding shortcuts for mac

- docs/languages/overview.md
This is a common question:
https://stackoverflow.com/questions/35904221/change-vscode-default-language-for-new-files
https://stackoverflow.com/questions/48456682/how-to-set-default-file-type-for-new-files-in-vs-code
> Add files.defaultLanguage description to FAQ

- docs/python/unit-testing.md
> Correct py.test to pytest

- docs/python/tutorial-django.md
> Fix linter error on strftime

- tutorials/functions-extension/getting-started.md
Updated to use the new, serverless specific signup URL and campaign.
> Update the signup link for Functions.

- docs/getstarted/tips-and-tricks.md
Added more examples per:
https://github.com/Microsoft/vscode/issues/21489#issuecomment-353609526
I also think it should be added [here](https://code.visualstudio.com/docs/getstarted/settings) in the default settings page, but I'm not sure if it actually has a default value...
> Add more font size tips

- docs/python/debugging.md
This pull request contains proposed changes to the Python debugging document. Most of the changes fix (what I take to be) grammatical errors, but a few are stylistic / for clarity.
> Grammar and usage

- api/extension-capabilities/theming.md
fix https://github.com/Microsoft/vscode/issues/65683
> Fix a broken link

- docs/java/java-tutorial.md
Fixing a broken link to the "Java Unit Testing" page
> Updating java-tutorial.md

- api/language-extensions/syntax-highlight-guide.md
* Update npm install code
* Update incorrect npm project link
> Fix Syntax Highlighting Yaml Section

- docs/getstarted/tips-and-tricks.md
Add info about new default editor for settings (visual one) and guidance for switching to JSON settings, that are listed below in tips.
Reference: https://github.com/Microsoft/vscode-tips-and-tricks/pull/142
> Update "Tune your settings" part

- docs/python/tutorial-django.md
Updated an invalid file path: template/hello_there.html --> template/hello/hello_there.html
> Update file path in tutorial-djanjo.md

- docs/languages/overview.md
> ovreview.md

- docs/languages/css.md
Gulp v4.0 no longer supports synchronous tasks. The last code was probably written for v3, that did not work when i installed gulp v4.0. So I updated the code as per official guidelines [here](https://gulpjs.com/docs/en/getting-started/creating-tasks#compose-tasks)
> Updated gulp task creation code to v4.0

- docs/languages/python.md
- docs/python/debugging.md
- docs/python/editing.md
- docs/python/linting.md
- docs/python/python-tutorial.md
Reverts Microsoft/vscode-docs#2362
> Revert "Python debug API into vNext for staging review"

- docs/python/python-tutorial.md
> Clarify elevation and use venv if needed

- docs/editor/refactoring.md
Add some missing articles, reword a bit for clarity.
> Add missing articles, some clarifications

- docs/python/tutorial-flask.md
> Correct routing for /hello/ with no name

- docs/python/environments.md
> Add section on variable substitution

- tutorials/static-website/create-storage.md
> explained SPAs

- docs/editor/tasks.md
Add showReuseMessage to Output behavior section
> Add showReuseMessage to Output behavior section

- docs/python/unit-testing.md
Markdown was not being rendered properly in inc_dec.py code snippet. Code block markdown was being rendered on screen
> Format of inc_dec.py snippet in unit-testing.md

- release-notes/v1_32.md
See https://github.com/Microsoft/TypeScript/releases/tag/v3.3.3333.
> Fix typo 43 -> 3333

- docs/python/tutorial-django.md
- docs/python/tutorial-flask.md
> Remove inline HTML from code example

- blogs/2018/11/26/event-stream.md
Update list of blocked extensions per March 15th
> Update list of blocked extensions per March 15th

- api/extension-guides/task-provider.md
Saw a typo and ended up changing a few other things while reviewing the file :)
> Improve wording and fix some spelling in the task provider guide

- release-notes/v1_32.md
Fixing February localization contributors with correct data.
> Fixing February localization contributors with correct data.

- api/extension-guides/task-provider.md
- docs/editor/tasks.md
Based on feedback from https://github.com/Microsoft/vscode/issues/70876
> Add more tasks documentation to existing task documentation.

- docs/python/debugging.md
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse
> Added Windows 10 OpenSSH installation

- docs/python/linting.md
```
"python.lintingflake8Enabled": true,
```
vs
```
"python.linting.flake8Enabled": true,
```
> Update linting.md docs - missing .

- docs/cpp/config-wsl.md
@gregvanl I'd like to stage this internally only until PM has a chance to validate this fixes the problem.
> updates to WSL  to fix shell issue

- docs/cpp/config-wsl.md
@gregvanl if these look good we can  go ahead and publish.
> updates to linux install steps

- docs/cpp/config-wsl.md
@gregvanl This needs to go live at the same time as #2582. https://github.com/Microsoft/vscode-docs/pull/2582 Thanks!
> Updates for WSL tutorial Bash settings and Linux commands

- docs/java/java-azurefunctions.md
> Fix broken link for remote debugging in Java

- docs/cpp/config-wsl.md
fixed a Windows path in launch.json to use \\ separators.
> fixed windows path

- blogs/2018/12/04/Java.gif
- blogs/2018/12/04/rich-navigation.md
* Adds new gif for Java
* Links to LSIF implementations for TypeScript and Java
* Updates sign-up link
> Updates to the rich code nav blog post

- api/advanced-topics/remote-extensions.md
- docs/remote/containers.md
- docs/remote/faq.md
- docs/remote/remote-overview.md
- docs/remote/ssh.md
- docs/remote/troubleshooting.md
- docs/remote/wsl.md
This PR adds clarifications or troubleshooting tips for the following:
https://github.com/microsoft/vscode-remote-release/issues/195
https://github.com/microsoft/vscode-remote-release/issues/170
https://github.com/Microsoft/vscode-remote-release/issues/127
https://github.com/microsoft/vscode-remote-release/issues/211
ptrace options introduced in https://github.com/microsoft/vscode-docs/pull/2633
Makes the note about remote development extensions at the top of each article a clickable download link.
> Troubleshooting and clarifications

- docs/remote/troubleshooting.md
> Update troubleshooting.cmd - PATH

- api/advanced-topics/remote-extensions.md
- docs/remote/troubleshooting.md
>  Add tip on installing local VSIX, clarify launch.json settings

- docs/editor/tasks.md
Fixes https://github.com/Microsoft/vscode/issues/68705
> Make problem matcher loop documentation clearer.

- docs/setup/additional-components.md
Line 21 gives a brief about Node.js , Node.js is a platform and runtime does not sound apt to me, replaced it with Cross platform runtime. 
Please review.
> Update additional components.md

- CONTRIBUTING.md
* plus minor formatting proposal
> Fix syntax issue on paragraph 29

- docs/remote/containers.md
- docs/remote/faq.md
- docs/remote/linux.md
- docs/remote/ssh.md
This is an initial pass at being a bit more explicit about our Linux requirements and what is/is not known to work.  //cc: @kieferrm @roblourens - LMK if the info looks accurate or if you want to include / exclude something.
> Linux prerequistes

- docs/remote/containers-advanced.md
- docs/remote/containers.md
- docs/remote/faq.md
- docs/remote/ssh.md
- docs/remote/troubleshooting.md
- docs/remote/wsl.md
There were a few "frown" comments on the remote docs that I cleaned up. This also resolves feedback from https://github.com/microsoft/vscode-remote-release/issues/547
> Adapt to docs feedback

- docs/remote/containers-advanced.md
- docs/remote/troubleshooting.md
Fixes https://github.com/microsoft/vscode-remote-release/issues/586
>  Remove references to .vscode-remote

- docs/python/images/jupyter/jupyter-data-viewer.png
- docs/python/images/jupyter/jupyter-variable-explorer.png
- docs/python/jupyter-support.md
Added section about data viewer and variable explorer for Python
> Data viewer and variable explorer for Python

- docs/getstarted/tips-and-tricks.md
Rephrased line 269 to make better readability.
> Update tips and tricks.md

- docs/java/images/java-tutorial/detect-eng.png
- docs/java/java-debugging.md
- docs/java/java-project.md
- docs/java/java-testing.md
- docs/java/java-tutorial.md
- docs/languages/java.md
Addressing a couple customer feedback.
> Update Java Documents

- docs/python/images/functions/deployment-popup.png
- docs/python/tutorial-azure-functions.md
Reverts microsoft/vscode-docs#2771
> Revert "Add settings sync and log stream"

- api/working-with-extensions/publishing-extension.md
See, https://github.com/microsoft/vscode-vsce/pull/365
Also, https://github.com/microsoft/vscode-vsce/issues/364
> Update vsce-publish docs for -m flag

- docs/python/tutorial-django.md
- docs/python/unit-testing.md
For [#2787](https://github.com/microsoft/vscode-docs/issues/2787)
> [Python] Update args for running tests in parallel with pytest-xdist

- docs/python/environments.md
- docs/python/tutorial-django.md
- docs/python/unit-testing.md
@brettcannon can you review this please? 😊
> Add virtualenvwrapper support to docs

- docs/remote/wsl.md
Mentioning the new features listed in https://github.com/microsoft/vscode-docs/blob/vnext/remote-release-notes/v1_36.md#wsl
> update WSL doc

- docs/getstarted/keybindings.md
Correct typo in Line 15, it should be Key Bindings rather than Key Binding
> KeyBindings

- api/index.md
This PR aims to correct some of the grammar in the docs for the VS Code Extensions API.
> Improve some grammar.

- docs/editor/accessibility.md
Along with incremental knowledge of Zoom levels , we should also mention decrement values as well.
> Zoom Level

- docs/editor/codebasics.md
Introducing line break in line 13, will make readability better.
> Line Break

- docs/editor/debugging.md
All in line 33 does not make any sense, removed it for better understanding
> Removed All from Line 33

- docs/editor/debugging.md
Added "to" in Line 99 to make it accurate as per standards. 
The best way to explain <something> is to think of a <way>
> Preposition missing in Line 99

- api/advanced-topics/remote-extensions.md
- docs/remote/containers.md
- docs/remote/images/containers/container-settings.png
- docs/remote/images/containers/forward-port-containers.png
- docs/remote/images/containers/select-docker-compose.png
- docs/remote/images/containers/select-dockerfile.png
- docs/remote/images/ssh/forward-port-ssh.png
- docs/remote/images/ssh/ssh-settings.png
- docs/remote/images/ssh/ssh-user@box.png
- docs/remote/ssh.md
- docs/remote/troubleshooting.md
- docs/remote/wsl.md
This PR includes:
1. Some clarifications and corrections for the containers article and adds images to break up some of the "walls of text".
2. Some revisions to the tips and tricks article to fix some out-of-date advice.
3. Typo fixes
> Break up "walls of text" with images, typos, clarifications

- docs/remote/containers-advanced.md
- docs/remote/containers.md
- docs/remote/faq.md
- docs/remote/ssh.md
- docs/remote/troubleshooting.md
- docs/remote/wsl.md
The Docker extension's ID changed, so updating docs to reflect that.
> Update Docker extension ID

- docs/java/java-testing.md
> Add FAQ section

- docs/editor/debugging.md
Line 309 'in' should be used , multiple statements in a single line is correct.
> Correcting prepositions

- docs/languages/go.md
Update Go.FormatOnSave example to the current version with its current settings.
> Update Format on save information

- docs/editor/emmet.md
Line 217 had article misplacement, the same has been removed
> Line 217 had article misplacement

- docs/python/python-tutorial.md
Setting up the PowerShell execution policy to allow activation of a virtual environment and install packages
> .venv activation and PowerShell execution policy

- api/working-with-extensions/continuous-integration.md
The service is called Travis CI, not just Travis. That's more or less what this PR fixes.
> Minor fixes to CI page

- docs/cpp/colorization-cpp.md
Updated to match the latest doc here: https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/colorization.md
> Update scopes in colorization-cpp.md

- docs/editor/extension-gallery.md
Section of line 160 has been re-written to make it a better read and also corrected one typo.
> Re-writing line 160

- blogs/2017/03/07/extension-pack-roundup.md
1. Change `extensionDependencies` to `extensionPack`. 
2. Update Wade's Twitter to the Code twitter
> Update extension pack post

- api/working-with-extensions/continuous-integration.md
@gregvanl Just want to run by you to see it's fine.
> Update CI doc

- docs/editor/integrated-terminal.md
> Line 193 correction

- docs/python/tutorial-deploy-app-service-on-linux.md
Fixed a broken link to the Python container on GitHub
> Fixing a broken link

- api/references/theme-color.md
Documented the new color from version [1.37 New theme color for active input options](https://code.visualstudio.com/updates/v1_37#_new-theme-color-for-active-input-options)
Peace! ✌️
> 📦 NEW: Background color of activated input fields

- docs/editor/multi-root-workspaces.md
Re-written line 87 to use better terms for business understanding and standard
> Re-Written line 87

- docs/editor/tasks.md
Correcting the typo in line 183
> Typo in Line 183

- docs/editor/tasks.md
For example was duplicated in line 220, the same has been removed
> Removing duplicate text in line 220

- docs/editor/tasks.md
Task's run behaviors should be there.
> Line 360 change

- docs/editor/tasks.md
Typo in line 362 was corrected
> Typo in line 362

- docs/editor/tasks.md
Correcting line 515 to make it more apt for readers
> Changes to line 515

- docs/editor/tasks.md
> Typo in line 540

- docs/editor/tasks.md
Helping verb was missing in line 563
> Line 563 update

- docs/editor/tasks.md
Verb form was correct in line 585
> Line 585 update

- docs/setup/network.md
While the usage of "know" here is not technically incorrect, it is unusual. The more idiomatic usage is "learn".
> know -> learn

- docs/editor/userdefinedsnippets.md
> Add CURRENT_SECONDS_UNIX to snippets documentation

- docs/azure/remote-debugging.md
Per https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1556054, updating UI interaction terminology in conceptual content linked from Javascript dev center.
(update file 1 of 4)
> Update UI interaction terms

- docs/typescript/typescript-tutorial.md
not "squillies" but "squiggles"
> simple word change

- tutorials/static-website/create-storage.md
- clarified that the storage account will take a moment to be created.
- renamed Index.html to index.html
- added Angular and Vue to the note
> clarifying some of the storage steps

- docs/remote/containers.md
- docs/remote/troubleshooting.md
We've had a couple of people hit problems in GH, twitter, and other places that could be tightened up in docs a bit.
//cc: @bowdenk7 - FYI. I didn't edit the tutorial, but updated the existing sections as discussed.
> Tighten up some comments, add tips and tricks

- docs/python/testing.md
To address https://github.com/microsoft/vscode-docs/issues/3041
> Add info for request type 'test' for debugging tests

- docs/typescript/typescript-compiling.md
Add in a tsconfig.json file does not make correct sense. 
If we are adding a new file it should Add a tsconfig.json file, or if we are adding to already existing file it should be Add in tsconfig.json file.
> Changes to Line 43

- docs/typescript/typescript-compiling.md
Your compile starts should be replaced with Your compilation starts
> Typo in line 117

- docs/typescript/typescript-compiling.md
> Verb correction

- tutorials/images/static-website/deployment-complete.png
Updated the toast to match what's current in the extension.
Closes #3002
> Update static website deployment complete toast.

- docs/python/editing.md
> Remove automatic indentation docs for Python

- docs/typescript/typescript-tutorial.md
identified typo in line 102, same has been fixed.
> Typo correction

- docs/typescript/typescript-tutorial.md
Line 120 was missing a preposition, same has been corrected
> Preposition missing

- docs/getstarted/keybindings.md
> Add || and && to keybindings

- docs/python/images/flask-tutorial/debug-continue-arrow.png
- docs/python/images/flask-tutorial/debug-local-variables.png
- docs/python/images/flask-tutorial/debug-program-paused.png
- docs/python/images/flask-tutorial/debug-select-configuration.png
- docs/python/images/flask-tutorial/debug-status-bar.png
- docs/python/images/flask-tutorial/debug-toolbar.png
- docs/python/images/flask-tutorial/new-file-icon.png
- docs/python/images/shared/debug-panel-initial-view.png
- docs/python/tutorial-flask.md
Debugging steps and related images updated
> Updated debugging section of Flask tutorial.

- docs/java/java-azurefunctions.md
We need to point to the Azul java jdks, aligned with https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-maven
> Update the Java jdks

- api/working-with-extensions/continuous-integration.md
> docs: add "Automated publishing" section to "Continuous Integration"

- api/language-extensions/syntax-highlight-guide.md
> Fix value of embedded languages in api doc.

- docs/cpp/launch-json-reference.md
Adding LoadSymbolInfo and RequireExactSource
@pieandcakes 
Note: Please wait on completing this PR till next week. For vscode-cpptools 1.26.0-insiders
> New cpp debugger configurations

- docs/languages/json.md
> Line 18 Typo correction

- docs/python/editing.md
> Fix capitalization

- api/extension-guides/webview.md
First of all - thank you for such fun and detailed guide about Webviews. It really helped me to clarify some questions I had.
This PR has 2 small corrections
1. Fixed setting ID that was a bit off.
1. In my opinion 'global scope' is term that is often used in plain JS and clearly communicates variables scope where malicious scripts can access saved reference. However I have no hard filing about this terminology and will drop that commit if needed.
> Webview guide fixes

- docs/remote/containers.md
I think it's easy to miss as it is now and there will be an idea that it will work since it's Windows and it's Microsoft.
> Made it clearer this is just for Linux containers

- docs/languages/java.md
> Fix typo in java lang intro.  Be very explict about how to open getting started from the Command Palette

- docs/remote/troubleshooting.md
I went over the WSL troubleshooting page and added new sections for troubleshooting issues with env variables and server prerequisites.
@gregvanl If you could have a quick look and, if ok, merge, that would be great.
Maybe we can also tackle the problem that we no have spread out WSL troubleshooting in https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips and https://code.visualstudio.com/docs/remote/wsl.
I personally think it would be best to have it all in https://code.visualstudio.com/docs/remote/wsl.
> wsl troubleshooting update

- docs/editor/tasks-appendix.md
Fixes #3182 using documentation from microsoft/vscode#83803
> Document problem matcher file location "autodetect" configuration 

- docs/other/office.md
Multiple article usage in line 12 does not make for good reading, i suggest we remove one of the occurrences.
> Line 12 modification

- api/advanced-topics/remote-extensions.md
- docs/remote/containers-advanced.md
- docs/remote/containers.md
- docs/remote/images/containers/containers-explorer-python.png
- docs/remote/images/containers/containers-explorer-remove.png
- docs/remote/images/containers/open-folder-python.png
- docs/remote/images/containers/select-dev-container-def-all.png
- docs/remote/images/containers/select-dev-container-def-python.png
- docs/remote/troubleshooting.md
This PR:
1. Adds a new containers quick start on using a container for multiple folders (per Nov plan)
2. Makes a tweak to the extensionKind docs https://github.com/microsoft/vscode-remote-release/issues/1787
3. Adds some images to break up text in a few areas
4. Drops some unneeded references to the Docker extension
5. Minor cleanup, corrections
> Add multi-folder quick start, images to break up text, update extension guide, cleanup

- docs/remote/containers.md
- docs/remote/faq.md
- docs/remote/ssh.md
- docs/remote/troubleshooting.md
- docs/remote/wsl.md
Partial resolution to https://github.com/microsoft/vscode-remote-release/issues/1826
> Update docs now that the Docker extension is a workspace extension by default

- docs/cpp/config-clang-mac.md
- docs/cpp/config-msvc.md
Fix numbering of last step of "Build the program".
> Fix numbering under "Build the program" section.

- docs/languages/python.md
include helping verb in line 24 to make readability better.
> Line 24 modified

- docs/remote/containers-advanced.md
One of the options reads better than one of options.
> Article inclusion in line 16

- docs/remote/containers-advanced.md
Line 99 has been rewritten to overcome the typo error
> Re-written line 99

- docs/remote/containers-advanced.md
Typo correction has been made in line 145
> Line 145 modified

- docs/remote/containers-advanced.md
farther is used for physical distances, for steps further is recommended
> further should be used in line 232

- docs/editor/intellisense.md
I search for this option every time I switch to a new pc so it would be great to have it directly in the doc
> Add 'acceptSuggestionOnCommitCharacter' option

- docs/java/extensions.md
- Remove LeetCode
- Add Remote extensions
> Update Recommended extensions section

- docs/python/editing.md
- docs/python/environments.md
- docs/python/images/editing/packageAbbreviations.gif
- docs/python/images/editing/quickFix.gif
- docs/python/images/jupyter/native-line-number.png
- docs/python/jupyter-support-py.md
- docs/python/jupyter-support.md
- docs/python/settings-reference.md
- Added info about using quick fix for Python imports
- Noted support for Altair and line numbering in Jupyter notebooks (incl. the interactive menu)
- Added info on predefined variables and a few setting for language server
- Clarified methods for setting PYTHONPATH
> Assorted updates for Python issues

- docs/java/java-testing.md
+@hexiaokai 
P.S. the wording `projects that manually manage their dependencies` might be needed to update once we have the public name for the `invisible project`
> Update the Getting Started part for JUnit and TestNG

- docs/getstarted/introvideos.md
This pr focuses on fixing the issue [#3268](https://github.com/microsoft/vscode-docs/issues/3268).
> Improved readability for introvideos.md

- docs/azure/docker.md
Line 44 is re-written to make better readability. Please merge
> Re-written line 44

- docs/cpp/launch-json-reference.md
To get started debugging, does not sound appropriate, hence suggesting change. Please merge.
> Line 14 modification

- docs/remote/ssh.md
Source is [this comment on an old issue](https://github.com/microsoft/vscode-remote-release/issues/190#issuecomment-506411258)
> Describes how to connect to a remote host directly

- docs/remote/containers-advanced.md
This outlines how to mount directories from the `devcontainer` into docker containers started.
> Mounting host dirs with docker in devcontainer

- api/language-extensions/language-configuration-guide.md
> #3315 fix minor typos

- docs/python/tutorial-create-containers.md
Small typo change for better readability
> Fixed minor typo

- docs/java/images/java-debugging/data-breakpoint.png
- docs/java/images/java-debugging/run-debug-button.PNG
- docs/java/images/java-editing/call-hierarchy.png
- docs/java/images/java-project/java.build.status.mp4
- docs/java/images/java-testing/test-status.png
- docs/java/java-debugging.md
- docs/java/java-editing.md
- docs/java/java-project.md
- docs/java/java-testing.md
Accumulated updates from January 2020.
> Java Documents Update 

- docs/cpp/launch-json-reference.md
> Add clarifying statements for `program` and `externalConsole`

- docs/languages/dotnet.md
> Added F# guides to vscode dotnet page

- docs/languages/images/typescript/refactor-convert-import.gif
- docs/languages/images/typescript/refactor-extract-constant.gif
- docs/languages/images/typescript/refactor-extract-function.gif
- docs/languages/images/typescript/refactor-extract-interface.gif
- docs/languages/images/typescript/refactor-generate-get-set.gif
- docs/languages/images/typescript/refactor-move-file.gif
- docs/languages/typescript.md
Add documentation on specific typescript refactorings
> Add refactoring section for TS

- docs/remote/containers.md
- docs/remote/images/common/restore-forwarded-ports.png
- docs/remote/images/containers/dotfiles.png
- docs/remote/ssh.md
Adapt to @chrmarti feedback for PR #3376
> Adapt to feedback in PR #3376

- docs/python/environments.md
Added execution policy hint for windows powershell users. This is proposed at https://github.com/microsoft/vscode-python/issues/2559
> Execution policy hint

- blogs/2020/02/14/chart.png
- blogs/2020/02/14/hero.png
- blogs/2020/02/14/optimizing-ci.md
This is a shared blog post between @ethanis and I, we want to get it out in February.
@gregvanl @fiveisprime Could you give it a quick review and help us get the blog post out there? Thanks!
@gregvanl How can we get a `MetaSocialImage` for this? Maybe from @misolori?
> Blog post: Optimizing CI build times

- docs/editor/emmet.md
feel seemed confusing, so I replaced with experience. if that is not the intent, please edit this PR.
thanks
> rephrase awkward sentence

- docs/python/jupyter-support-py.md
- docs/python/jupyter-support.md
Addresses https://github.com/microsoft/vscode-python/issues/10317
> Corrected variable explorer section

- docs/containers/debug-common.md
Minor edits, forgot to add python and rearrange orderings on common debug page
> added python into debugging list, changed orderings to node, python, .net

- docs/editor/emmet.md
- docs/getstarted/settings.md
- docs/nodejs/nodejs-tutorial.md
- docs/setup/additional-components.md
https://github.com/pugjs/pug/issues/2184
> Renaming jade -> pug

- docs/containers/quickstart-aspnet-core.md
- docs/containers/quickstart-node.md
- docs/containers/quickstart-python.md
And made next steps section consistent across each language
> Added debugging link to python quickstart

- docs/languages/dotnet.md
- docs/other/unity.md
I found the sentences a bit misleading since the SDK includes the runtime
> Improve language around .NET Core SDK

- docs/cpp/config-clang-mac.md
- docs/cpp/images/clang-mac/clang-task-in-terminal.png
- docs/cpp/images/clang-mac/helloworld-in-terminal.png
- docs/cpp/images/msvc/file-explorer.png
- docs/cpp/images/msvc/new-file-button.png
This pass does some graphics cleanup.
> Update title, resize two graphics, remove menu bar from two graphics

- api/extension-guides/images/tree-view/view.png
- api/extension-guides/tree-view.md
> More tree view guide improvements

- docs/editor/variables-reference.md
discussion of actual behavior and documentation inaccuracies https://github.com/microsoft/vscode/issues/89758
> variable replacement explanation correction

- release-notes/v1_43.md
fixing hover text from [https://github.com/microsoft/vscode/issues/92785](url)
> Added title to scroll button to change hover text

- docs/containers/debug-node.md
- docs/containers/quickstart-node.md
Related to https://github.com/microsoft/vscode-docs/issues/3497
> Fixes for Node.js quickstart and debug 

- docs/python/jupyter-support-py.md
#%% does not work, the "Run Cell, etc. commands" only shows for # %%
> change #%% to # %%

- api/language-extensions/embedded-languages.md
- api/language-extensions/images/embedded-languages/embedded-lsp-sample.gif
Related https://github.com/microsoft/vscode-extension-samples/pull/264
> Embedded LSP doc

- docs/languages/javascript.md
Removed "your code" dublication in ""Auto imports" section.
> Fixing phrase duplication

- docs/cpp/config-msvc.md
> remove extra "or"

- docs/python/data-science-tutorial.md
Updated link  "https://scikit-learn.org/stable/modules/naive_bayes.html".  Was "n" instead of "h" in ".html"
> Fixed url typo in docs data-science-tutorial.md

- docs/java/java-tutorial.md
Edited java-tutorial.md with a few headings, rewording, and grammar corrections.
> 95yc439311c edited java-tutorial.md

- docs/java/extensions.md
- docs/java/java-tomcat-jetty.md
- docs/languages/java.md
"Microprofile" should be "MicroProfile".
> Typo fix for MicroProfile

- docs/java/java-tomcat-jetty.md
> Fix capitalization of WildFly

- docs/containers/app-service.md
- docs/containers/images/quickstarts/select-registry.png
- docs/containers/images/registries/azure-registry-context-menu.png
- docs/containers/overview.md
- docs/containers/quickstart-container-registries.md
- docs/containers/tutorial-django-push-to-registry.md
@ucheNkadiCode @BigMorty @karolz-ms FYI
@gregvanl @ghogen for review
**NOTE**: Please don't submit these changes just yet, we anticipate version 1.1.0 of the Docker extension releasing in a few weeks.
> Doc updates for new v1.1.0 image push experience

- api/extension-guides/command.md
> fix typescript error on api.command

- docs/remote/containers.md
```cmd
> docker version
Client: Docker Engine - Community
Version:           19.03.8
API version:       1.40
Go version:        go1.12.17
Git commit:        afacb8b
Built:             Wed Mar 11 01:23:10 2020   
OS/Arch:           windows/amd64
Experimental:      false
Server: Docker Engine - Community
Engine:
Version:          19.03.8
API version:      1.40 (minimum version 1.12)
Go version:       go1.12.17
Git commit:       afacb8b
Built:            Wed Mar 11 01:29:16 2020
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          v1.2.13
GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
runc:
Version:          1.0.0-rc10
GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
docker-init:
Version:          0.18.0
GitCommit:        fec3683
```
> Docker 19.03.8 Windows GUI

- docs/python/tutorial-django.md
The new Python extension doesn't need the reload anymore. Makes the workflow a lot smoother.
> Update tutorial for new VS Code Python extension

- docs/containers/ssh.md
(tip was added based on testing done by @bigmorty )
Also I have moved all platform-agnostic tips in front of platform-specific tips.
> One more tip for Docker SSH connectivity

- docs/containers/choosing-dev-environment.md
WSL2 is now supported by stable versions of Windows and Docker (yay!)
> Refresh Windows development env recommendation for Docker

- docs/containers/reference.md
Adding Python to Reference Document (customizing Docker Build and Run tasks)
> New customize python

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
> Refine vscode-docs dev container to be a bit faster to startup

- docs/cpp/c-cpp-properties-schema-reference.md
- docs/cpp/colorization-cpp.md
- docs/cpp/configure-intellisense-crosscompilation.md
- docs/cpp/cpp-ide.md
- docs/cpp/enable-logging-cpp.md
- docs/cpp/faq-cpp.md
- docs/cpp/images/intellisense/compiler-path.png
- docs/cpp/images/intellisense/include-path.png
- docs/cpp/images/intellisense/intellisense-mode.png
- docs/cpp/launch-json-reference.md
- docs/cpp/natvis.md
- docs/cpp/pipe-transport.md
> draft for new cross-compilation settings topic

- api/extension-guides/custom-editors.md
> Fix typo in custom-editors

- docs/setup/mac.md
The incorrect Command palette command was being used
> Fixed the command palette command

- docs/python/environments.md
There is a grammar mistake at the conda environment definition:"....is a virtual environment**s** that's..."
> Fix grammar mistake

- docs/containers/docker-compose.md
- docs/containers/images/compose/docker-compose-netcore-debugger-prompt.png
Updated the compose document to show how user can compose up with multiple compose files.
> Docker Compose with multiple Compose files

- blogs/2020/05/14/vscode-build-2020.md
Updated the Build 2020 post with the links to sessions. Please push this live at noon (PST) on Tuesday 5/19.
Thank you!
> Updated Build 2020 blog post

- docs/containers/quickstart-aspnet-core.md
- docs/containers/quickstart-node.md
- docs/containers/quickstart-python.md
For clarity, I added a direct link to the Customize TOC
> Added link to Customize page in next steps

- docs/editor/tasks.md
Slightly improve ProblemMatcher documentation
> Suggestion for #98908

- docs/java/java-refactoring.md
Added package renaming support
> Java refactoring: add package renaming support

- blogs/2020/06/09/go-extension.md
Adding link at the bottom to the blog by the Go team (let me know if this is the best way to proceed)
Also, @asw101 has some more feedback coming in shortly
> More updates

- docs/containers/debug-python.md
- docs/containers/python-user-rights.md
- docs/containers/reference.md
We're adding to our documentation to inform users of how to enable hot reloading in their containerized application. 
**Please** wait for a sign off from @haniamr
> Added Hot Reload directions for Django and Flask

- docs/python/environments.md
- docs/python/settings-reference.md
Fixes a number of GH issues (https://github.com/microsoft/vscode-docs/issues/3674, https://github.com/microsoft/vscode-docs/issues/3741, https://github.com/microsoft/vscode-docs/issues/3656, https://github.com/microsoft/vscode-docs/issues/3562, https://github.com/microsoft/vscode-docs/issues/3481, https://github.com/microsoft/vscode-docs/issues/3789)
> Addresses a number of GitHub issues

- docs/containers/debug-common.md
This revision aims to make it clear what is required of a developer to use a launch configuration to debug their application.
> Revised Common debug page

- docs/editor/emmet.md
**Changed**: ...`stylus` files. As well as 
**To**: ...`stylus` files, as well as
> Fix grammar error

- api/get-started/extension-anatomy.md
- api/get-started/your-first-extension.md
**Changes:** 
- Provide a bit more context about Contribution Points in https://code.visualstudio.com/api/get-started/your-first-extension
- Provide a bit more context about `deactivate` in https://code.visualstudio.com/api/get-started/extension-anatomy
Fixes #3800
> Add context to contributes and deactivate

- README.md
vs code now support mobile development with flutter and react-native
> specifed new use cases

- api/extension-guides/command.md
This will replace PR #3852 - cc @gregvanl
> Update command.md -  Custom When Clause Context for Extension Developers

- docs/containers/images/quickstarts/python-edit-dockerfile.png
- docs/containers/images/quickstarts/python-view-logs.png
- docs/containers/quickstart-python.md
I added two files and threw in the two scenarios we previously discussed
- Added Dockerfile Editing (env variables)
- Used the Docker View to view logs
> Improved feature awareness of Python Docs

- docs/setup/mac.md
Add VS Code to PATH in .zshrc (Catalina default shell)
> Add VS Code to PATH in .zshrc (Catalina default shell)

- docs/languages/powershell.md
Wondering if it should be PSScriptAnalyzer rather than Pester.
> Proposing update to the Doc

- docs/containers/overview.md
> Added link to intellisense doc

- docs/other/unity.md
> Fixed typo on unity.md

- docs/editor/emmet.md
Explain what Emmet is, link to emmet.io, and clean up sentence structure
> emmet.md: Link to & explain what is Emmet

- docs/editor/integrated-terminal.md
Update this question: "Can I use Cmder's shell with the terminal on Windows?"
See issue #3930 for complete description.
> Update Integrated Terminal FAQ 

- README.md
There was a typo in the docs. I removed the extra space
> removed an extra space in readme

- docs/remote/ssh.md
Make it clearer that Remote specifically overrides User settings and that Workspace overrides both.
> Update ssh.md with more clarity on settings overrides

- api/language-extensions/language-server-extension-guide.md
All changes are updates to show latest version of the code, you can see it in the vscode-extension-samples repo:
https://github.com/microsoft/vscode-extension-samples/blob/83261e3f32421da84513c5a76e8b6a08fff3c332/lsp-sample/client/package.json#L12
https://github.com/microsoft/vscode-extension-samples/blob/83261e3f32421da84513c5a76e8b6a08fff3c332/lsp-sample/server/package.json#L14
https://github.com/microsoft/vscode-extension-samples/blob/master/lsp-sample/server/src/server.ts
https://github.com/microsoft/vscode-extension-samples/blob/83261e3f32421da84513c5a76e8b6a08fff3c332/lsp-sample/.vscode/launch.json#L25
https://github.com/microsoft/vscode-extension-samples/blob/83261e3f32421da84513c5a76e8b6a08fff3c332/lsp-sample/client/src/test/completion.test.ts#L10 …
> Update language server extension guide to latest version of the code

- docs/python/editing.md
- docs/python/environments.md
- docs/python/testing.md
- Fixes https://github.com/microsoft/vscode-docs/issues/3810
- Fixes https://github.com/microsoft/vscode-docs/issues/3856
- Fixes https://github.com/microsoft/vscode-docs/issues/3928
> Addressing GH issues 

- docs/python/jupyter-support.md
Inspired by my issue https://github.com/microsoft/vscode-python/issues/13580
> more easy to change mode，and add `z` to undo

- docs/python/jupyter-support.md
, or if you've deleted a cell accidentally you can recover it.
> undo a cell deleted 

- blogs/2020/07/27/5-commands-list.png
- blogs/2020/07/27/5-commands.png
- blogs/2020/07/27/6-clone-repo-command.png
- blogs/2020/07/27/6-open-repo-command.png
- blogs/2020/07/27/containers-edu.md
As per recommendation in https://github.com/microsoft/vscode-docs/pull/3970#issuecomment-684001761
> Update edu blog post to use "Clone Repository in Container Volume"

- release-notes/v1_49.md
We didn't mention it originally, but we can add it now.
See also https://github.com/microsoft/vscode/pull/105685#issuecomment-690563552
> Add section about new numeric fontWeight

- api/extension-guides/overview.md
Just fixed a tiny grammar mistake.
> Fix a grammar mistake.

- docs/getstarted/tips-and-tricks.md
> Fix grammar for tips-and-tricks.md

- docs/containers/reference.md
I messed up the merging and mistakenly added some things in #3902 that aren't released yet.
> Correct mistaken merge

- docs/containers/choosing-dev-environment.md
(change inspired by documentation feedback from confused reader)
> Clarify remote machine container dev instructions

- api/get-started/your-first-extension.md
The following videos also should be updated.
+ `/api/get-started/your-first-extension/launch.mp4`
+ `/api/get-started/your-first-extension/reload.mp4`
> Update mismatch instruction

- docs/editor/debugging.md
It would probably help plenty of people if this attribute was documented here. See for example this SO-thread:
https://stackoverflow.com/questions/29971572/how-do-i-add-environment-variables-to-launch-json-in-vscode
> Add description of envFile

- release-notes/v1_50.md
I've added a sentence on how Remote Extensions can be used on devices such as Raspberry Pi and Chromebook as a proposal. LMK what you think!
CC @bamurtaugh
> Small update for ARM announcement

- docs/python/python-tutorial.md
New comers don't need to know this, and experts can help themselves.
> Removed note about Python2

- docs/containers/reference.md
(Got the PRs right this time)
In the upcoming Docker extension 1.7.0 release we're adding these two parameters. Release date is tentatively October 19, so please hold on until then.
@karolz-ms @gregvanl @ghogen FYI.
> Update container reference for new 1.7.0 features

- docs/remote/containers-advanced.md
> Fully name devcontainer.env

- docs/python/coding-pack-python.md
- docs/python/images/jupyter/native-code-cells-11.png
- docs/python/images/jupyter/native-code-cells-11a.png
- docs/python/jupyter-support-py.md
- docs/python/jupyter-support.md
- docs/python/linting.md
Addresses https://github.com/microsoft/vscode-docs/issues/3869
> GH issues updates

- docs/python/jupyter-support-py.md
fixed kbstyle spelling error and added in two missing closing parenthesis ")"
> corrected table

- docs/containers/reference.md
Tiny PR to fix broken page link
**From**: [#_node-object-properties-docker<b><code>-</code></b>build-task](https://code.visualstudio.com/docs/containers/reference#_node-object-properties-docker-build-task)
**To**: &nbsp;&nbsp;&nbsp;&nbsp;[#_node-object-properties-dockerbuild-task](https://code.visualstudio.com/docs/containers/reference#_node-object-properties-dockerbuild-task)
> fix broken page link

- docs/cpp/cmake-linux.md
> Fix typo in cmake-linux.md

- api/extension-guides/webview.md
Make sure the basic webview page also mentions custom editors and webview views
> Add note on how webviews can be used in various VS Code apis

- api/get-started/your-first-extension.md
`$ yo code` now asks to bundle the source code with webpack.
Update the documentation to include the new step
`? Bundle the source code with webpack? No`
> Include webpack step in your-first-extention.md

- docs/supporting/faq.md
proposed changes to `Resolving Shell Environment is Slow (Error, Warning)` FAQ entry.
> suggest changes to Resolving Shell Env FAQ

- api/extension-capabilities/common-capabilities.md
It feels so awkward to read "write/read" instead of "read/write" that I had to change it.
> Changed write/read to read/write

- api/extension-guides/webview.md
> Standardize function parameter in Webview.md

- docs/setup/linux.md
Makes it a bit easier to spot the problem with file watcher.
> Add a hint to the watcher problem.

- api/language-extensions/semantic-highlight-guide.md
This PR removes duplicate row of `interface` from the table.
> Remove duplicated row

- learn/educators/codetour.md
- learn/educators/images/codetour/codetour-example-lesson.gif
- learn/educators/images/codetour/codetour-extension-marketplace.png
- learn/educators/images/codetour/codetour-space-jam.gif
- learn/educators/images/codetour/space-jam-lessons-home.png
- learn/educators/learn-modules.md
- learn/educators/webinars.md
> Add CodeTour under Educators in the Learn section

- docs/python/python-tutorial.md
Add the Python 3.9 link in the windows store
> Update python-tutorial.md with Windows 3.9 link

- learn/educators/images/notebooks/jupyter_market_place.png
- learn/educators/images/notebooks/notebook_assignment.gif
- learn/educators/images/notebooks/notebook_interactive_output.gif
- learn/educators/images/notebooks/notebook_lesson_visual_md.gif
- learn/educators/images/notebooks/notebook_runtime_lecture.gif
- learn/educators/notebooks.md
- learn/educators/webinars.md
> Notebooks for classrooms under Educators in /learn

- api/references/contribution-points.md
See https://github.com/microsoft/vscode/commit/0cd3c4c9946f56ddecd580817c3e1c07fe7f0ba4
cc @isidorn
> menu item's 'alt' command also triggered by Shift key on Windows and Linux

- docs/remote/containers-tutorial.md
Step helps the tutorial user to insure that the Docker Context is supported for the **Remote-Containers: Try a Sample...** command
> ??
> If I have targeted the wrong branch for this change proposal, please advise and I will correct it.
> ??
This is in reference to [#4386](https://github.com/microsoft/vscode-remote-release/issues/4386)
> Update to add a precautionary step

- docs/editor/integrated-terminal.md
> It now defaults to PowerShell even on Win7

- docs/setup/linux.md
Good morning!
This PR proposes a couple of small grammar edits to the Linux markdown file contained within /setup.
- Added a hyphen to a compound modifier.
- Added a comma to the right of a conjunctive adverb to increase emphasis.
- Update "multi version" to "multiple versions" for clarity.
- Update infinitive by adding an article to increase clarity.
> Update Linux (markdown)

- learn/educators/images/nodejs/learn-build-node-app.png
- learn/educators/images/nodejs/node-js-extension-pack.png
- learn/educators/nodejs.md
- learn/educators/notebooks.md
- learn/educators/python.md
- learn/educators/webinars.md
> Web Development educator story and topic

- api/extension-guides/scm-provider.md
- api/references/contribution-points.md
This PR fixes #4384 and makes a few related improvements.
> fix #4384 add missing SCM menu contribution, and clarify SCM doc

- docs/remote/containers-advanced.md
This PR updates the section on using docker inside a dev container to include the new docker-in-docker model.
> Add docker-in-docker to docs

- api/advanced-topics/extension-host.md
Good afternoon!
This PR:
- Updates first instance of product name to align with naming guidelines [found here](https://github.com/microsoft/vscode-docs/blob/main/CONTRIBUTING.md#product-name).
Why:
- Increase concistency within VS Code documentation.
> Update extension-host (Markdown)

- docs/python/debugging.md
Added pythonArgs property to address https://github.com/microsoft/vscode-docs/issues/4248 and https://github.com/microsoft/vscode-docs/issues/4161.
> added pythonArgs property

- docs/typescript/typescript-tutorial.md
Good Afternoon!
This PR:
- Updates some article usage.
- Makes small grammar updates.
Why:
- Increase tutorial clarity.
> Update typescript-tutorial (Markdown)

- docs/typescript/typescript-compiling.md
Good Afternoon!
This PR:
- Makes a small grammar edit.
Why:
- Increase clarity within sentence.
> Update typescript-compiling (Markdown)

- docs/typescript/typescript-debugging.md
Good Afternoon!
This PR:
- Adds some hyphens to compound phrases.
Why:
- Increase document conciseness.
> Update typescript-debugging (Markdown)

- api/extension-guides/debugger-extension.md
- api/references/theme-color.md
- api/references/vscode-api.md
- blogs/2016/03/11/ExtensionsRoundup.md
- docs/getstarted/settings.md
- docs/remote/containers.md
- docs/remote/ssh-tutorial.md
- docs/remote/ssh.md
- docs/remote/wsl.md
- release-notes/July_2016.md
- release-notes/v1_24.md
- release-notes/v1_30.md
- release-notes/v1_54.md
- release-notes/v1_6.md
- release-notes/v1_8.md
Good Evening!
This PR:
- Updates mutiple instances of "drop down" to "dropdown".
Why:
- To follow the Microsoft Writing Style Guide.
> Update Instances of drop down

- api/language-extensions/language-configuration-guide.md
> Add documentation for `onEnterRules` in language configuration.

- docs/languages/python.md
Addresses https://github.com/microsoft/vscode-docs/issues/4469
> Removed code snippet section

- docs/cpp/introvideos-cpp.md
@gregvanl I created the Intro Videos doc for C++ that we talked about a few weeks ago. This is not ready to merge yet, I need to fix a few things. I'd appreciate your help whenever you get the chance.
Things to fix:
1. What should I put for ContentId?
2. I put "Order: 1" because we want this to be first in the the C++ TOC. Is there another document I need to edit to add this to the TOC? And then should I increment the Orders of all the other C++ docs in the TOC by 1?
3. The iframes aren't rendering, do you know what I'm doing wrong?
> created doc for cpp intro videos

- docs/languages/css.md
Pointing to the most up-to-date Sass extension.
> Link Correction for Indentation Based Sass Syntax

- docs/remote/containers.md
You can learn more about the [Remote - WSL extension in is documentation] -> in **its** documentation
> Fixed small typo

- docs/setup/raspberry-pi.md
Adding a section on system requirements (hardware) for RPi
> Adding system requirements for RPi

- docs/containers/bridge-to-kubernetes.md
This is dependent on the VS docs pr:
https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/8060
> add link for managed identity configuration

- api/get-started/your-first-extension.md
It's easier navigate to Extension Manifest from here by link
> Add URN for Extension Manifest

- docs/java/java-tutorial.md
There was a grammatical error on the first line, on the first sentence under the header titled: "Installing a Java Development Kit (JDK)"
> Sentence modified

- docs/java/java-faq.md
"Are there any other feature" --> "Are there any other features"
> Fix typo in Java FAQ

- docs/python/debugging.md
- docs/python/tutorial-django.md
Addresses GH issue https://github.com/microsoft/vscode-docs/issues/4252 and https://github.com/microsoft/vscode-docs/issues/3997
> Updates for GH issues

- docs/python/coding-pack-python.md
Made some basic grammatical and clarity corrections. Also correct typos.
> Grammatical and clarity corrections

- docs/python/tutorial-django.md
> Add missing f-string prefix

- docs/python/editing.md
Fixed a few spelling mistakes.
> Small spelling fixes

- docs/editor/workspace-trust.md
Pending PR if security.workspace.trust.emptyWindow defaults changed to true.
> Update empty window section

- docs/editor/workspace-trust.md
I forgot to merge this into main before the release, but this gives me the opportunity to leave this up as a PR.
> Adjust workspace trust doc

- blogs/2021/06/10/remote-repositories.md
Based on https://github.com/microsoft/vscode/issues/125939#issuecomment-859461920, adding information about `extensions.supportVirtualWorkspaces`.
> Add supportVirtualWorkspaces info

- docs/cpp/launch-json-reference.md
Adding new `launch.json` schema. 
See https://github.com/microsoft/vscode-cpptools/pull/7680
> Add SymbolOptions to Launch.json docs

- docs/python/debugging.md
- docs/python/tutorial-flask.md
Addresses https://github.com/microsoft/vscode-docs/issues/4185, https://github.com/microsoft/vscode-docs/issues/4017, and https://github.com/microsoft/vscode-docs/issues/3251
> Small updates to debugging and Flask tutorial

- docs/python/environments.md
Addresses https://github.com/microsoft/vscode-docs/issues/4232
> Added PYTHONPATH example

- docs/other/office.md
Made a few edits to the Office Add-in topic.
> Fixing grammar in Office Add-ins

- api/references/icons-in-labels.md
See https://github.com/microsoft/vscode/issues/124703
> Explain how to escape icon syntax

- learn/develop-cloud/ssh-lab-machines.md
- learn/get-started/basics.md
- learn/get-started/extensions.md
- learn/get-started/personalize.md
Tweaked titles/descriptions of some learn pages based on the most popular search queries for them on Google.
> Tweaked learn page titles

- release-notes/images/1_58/live-preview-summary-1.gif
- release-notes/images/1_58/live-preview-summary-2.gif
- release-notes/v1_58.md
Since this is the first time that Live Preview will be in the release notes, it would be great for somebody to double-check how I wrote this.
> Adding Live Preview to 1.58 Notes

- docs/python/environments.md
Extension supports Pipenv and poetry
> Mention the other supported package managers

- docs/containers/troubleshooting.md
Small edits for troubleshooting page. Prior to a rewrite of the troubleshooting page with Python
> Tips and Tricks doc update

- docs/python/editing.md
This PR fixes broken links from the python documentation
> Fix broken url related to python isort

- docs/containers/debug-python.md
Update to the debug-python file for containers to include a docker-build task and provide a complete image of one Flask example config.
> Added docker-build and full examples

- docs/languages/overview.md
See also: https://docs.microsoft.com/en-us/style-guide/punctuation/commas
> Oxford comma

- api/working-with-extensions/publishing-extension.md
- Changed `This topics covers` to `This topic covers`
> Fix a minor typo

- docs/editor/github.md
- docs/editor/images/github/continue-working-on.png
- docs/editor/images/github/continue-working.png
- docs/editor/images/github/github-remote-explorer.png
- docs/editor/images/github/github-repositories-extension.png
- docs/editor/images/github/open-github-repository-dropdown.png
- docs/editor/images/github/open-remote-repository-dropdown.png
- docs/editor/images/github/remote-explorer.png
- docs/editor/images/github/remote-repositories-extension.png
- Updated content in Working with GitHub section
- Outstanding question: should we also update the blog post https://code.visualstudio.com/blogs/2021/06/10/remote-repositories? Or is that considered more of a point-in-time?
> Update repositories extension

- api/advanced-topics/remote-extensions.md
[Rendered](https://github.com/akosyakov/vscode-docs/blob/akosyakov/document-using-setkeysforsync-4699/api/advanced-topics/remote-extensions.md#sync-user-global-state-between-machines)
> fix #4699: how to sync user global state across machines

- docs/containers/ssh.md
Fixes https://github.com/microsoft/vscode-docker/issues/3142. This can be merged at any time.
@karolz-ms FYI
> Update SSH agent scripts to be PowerShell

- docs/languages/java.md
As I read through this page, I noticed a few passages that could be improved. These edits are meant to improve readability, consistency and correctness. Some of these changes may be matters of style, so I'm happy to integrate any editorial feedback.
> Various updates to the Java language overview

- release-notes/images/1_60/python-run-and-debug-buttons.gif
- release-notes/images/1_60/python-test-explorer.png
- release-notes/v1_60.md
Add updates from the Python extension to the VS Code release notes
> Add Python updates to release notes

- docs/editor/github.md
> Fix a small typo

- api/references/contribution-points.md
Not to be confused with natural/display languages.
> Clarify kind of languages for contributes.language

- docs/remote/ssh.md
It may be beneficial to mention the space requirement directly on the extension doc.
Would love to hear your thoughts on placement, wording, etc.
> Update host requirement

- docs/datascience/overview.md
- docs/introvideos/configure.md
> Fixed typos

- docs/other/unity.md
Add a link to the unity manual's page about Visual Studio Code Editor package
> Add a link in "unity.md"

- docs/nodejs/working-with-javascript.md
subject/verb agreement
duplicate word
> minor typo corrections

- api/get-started/your-first-extension.md
Yo now lets asks you use code as default editor when prompted to.
> Small update on your-first-extension.md

- docs/editor/vscode-web.md
Include info on where extensions are persisted and how users can persist them through Settings Sync.
@gregvanl I know we discussed a new H2, but since we already have an Extensions H3, I thought this content might fit in the existing section. Happy to chat further and potentially move to a new section if we think it'd fit better elsewhere.
> Update web extension info

- docs/containers/debug-common.md
> updated definition for Python projectType

- docs/cpp/cmake-linux.md
Use aka.ms link instead of full path
> Update link to CMake Tools documentation

- docs/remote/troubleshooting.md
Fixes https://github.com/microsoft/vscode-remote-release/issues/5823
@chrmarti @gregvanl I thought the tips and tricks section made sense, but let me know if you have any other thoughts. Thank you!
> Add container persistence tip

- docs/languages/python.md
- docs/python/editing.md
- docs/python/linting.md
I believe I caught all the remaining ones, but if someone could please double check that would be great!
> Remove all remaining references for python.pythonPath setting

- api/working-with-extensions/publishing-extension.md
Update verified publisher docs to include self-service verification steps
> Chgill-update-verified-publisher-docs

- docs/languages/markdown.md
- insert commas separating dependent clauses
- delete extraneous article
> correct minor punctuation and grammar
