microsoft/vscode-docs

api/language-extensions/semantic-highlight-guide.md, docs/getstarted/themes.md
In the screenshot the variable is `languageModes` while the text has `languageMode`.
=> Fix a typo in semantic-highlight-guide.md

api/extension-capabilities/overview.md, api/extension-guides/overview.md, api/get-started/your-first-extension.md, api/index.md
This updates sections of the docs to link to our new extension guidelines. Feel free to tweak as needed.
=> Add links to extension guidelines

docs/remote/containers.md
In some cases, relative paths doesn't work correctly. (For example, if .zprofile is a symlink)
The solution is to use an absolute path.
=> fix .ssh/ path

docs/python/tutorial-flask.md
Shares some common fixes with #4285 
- Splitting the python3/python commands for Mac, linux and Windows isn't needed as VS Code will activate the venv anyway
- Update pip before doing anything
- Fix the pip docs link
- Update the process for setting up `launch.json` as the window won't look as its described (new screenshot in #4285 )
=> Updated flask tutorial to newer versions

docs/cpp/config-clang-mac.md
There is a huge issue with the input entry with the newer versions of Mac. I spent at least 2 hours trying to understand why this is happening. 
Until the issue is fixed, I think, this troubleshooting must be included in the main documentation as this is where new developers, especially students would land, when trying to run a simple hello world on their new Macs.
=> added troubleshooting for no input terminal

docs/languages/go.md, docs/languages/images/go/completion-signature-help.gif, docs/languages/images/go/go-extension.png, docs/languages/images/go/hover.png, docs/languages/images/go/signaturehelp.png
We are now using the gopls as the backend of the most language features.
https://blog.golang.org/gopls-vscode-go
This PR removes mention of old tools and replaces the two pngs with one gif to demonstrate all the intellisense features.
Also updates the extension image.
=> Update Go extension documentation to reflect the recent change

docs/setup/additional-components.md, docs/setup/network.md, docs/setup/raspberry-pi-os.md, docs/setup/windows.md
Fixes #4276 
* Added setup guide for Raspberry Pi OS now that code is in the official Raspberry Pi OS apt repositories.
* Renumbered the pages to position the Raspberry Pi OS page alphabetically inside the other OS setup pages, keeping consistent with the current ordering
=> Adding Raspberry Pi OS setup guide

docs/typescript/typescript-tutorial.md
…avoid confusion on rerun
According to https://www.typescriptlang.org/docs/handbook/tsconfig-json.html,  When input files are specified on the command line, tsconfig.json files are ignored.
See Issue: https://github.com/microsoft/vscode/issues/116171
=> update typescript-tutorial.md to avoid confusion on change build output

api/extension-guides/notebook.md
Add how cells share a single output renderer.
=> Add detail to Notebook API docs about output renderers

api/index.md
The sections listed in the section "How to build extensions" had a formatting issue, i.e. it had an extra asterisk in addition to the two that were required to boldify the section title - for example, "* ***Get Started** teaches fundamental concepts". 
This PR fixes the issue by removing that extra asterisk and make it as "* **Get Started** teaches fundamental concepts".
=> Update index page to fix an issue in section list

api/references/contribution-points.md, docs/editor/command-line.md, docs/editor/debugging.md
Occurrences of 'can not' in release notes for previous versions have not been changed.
=> Replace 'can not' with 'cannot' to conform with majority usage

api/working-with-extensions/continuous-integration.md
`macos-10.13` isn't available anymore and [should migrate](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software) to at least `macos-10.14`, but perhaps it's better to just move to the latest versions of all images, as done in the GitHub Actions example.
=> Update suggested images for AZP configuration

docs/nodejs/debugging-recipes.md, docs/nodejs/nodejs-debugging.md, release-notes/v1_13.md, release-notes/v1_16.md
We will be removing the TypeScript-Docker recipe in https://github.com/microsoft/vscode-recipes/pull/290
because it was created for remote scenarios before Remote - * extensions were made available.
This PR:
* update release note references to a specific commit with this doc
* remove any references of this doc to be deleted
* rework the nodejs-debugging doc to mention Remote Development
=> remove old recipe doc

release-notes/v1_54.md
Adding mentions of benefits (no emulation, better performance, longer battery life) and explain that the default builds are now Universal.
CC: @ornellaalt
=> Slightly expanded Apple Silicon release notes

docs/cpp/faq-cpp.md
Changed **C_Cpp: Reset IntelliSense Database**  to **C/Cpp: Reset IntelliSense Database** to reflect the actual command in VS Code
=> Fixed spelling mistake in Reset Intellisense Database

api/working-with-extensions/testing-extension.md
`extensionDevelopmentPath` had an extra `..` in it.
=> Fix typo in test script sample

docs/setup/raspberry-pi.md
Two changes:
- Added note about license acceptance (similarly to the Linux page)
- Renamed file to reset the URL and comments: once we're ready to go live, setup will be simplified and the issues that users have experienced ("cannot find package code") will not happen anymore
=> Updated RPi setup document

api/references/contribution-points.md
=> fix #4378 add 'scm/sourceControl' to 'contributes.menus' reference list

api/references/when-clause-contexts.md
On line 168, it was missing a closing double quotes `"` on the example.
=> Add missing closing quotes

docs/containers/python-configure-containers.md
Thanks once again to @TheYarin for giving us great feedback to improve the product! We have now changed our Python scaffolding to include the best practice of setting an explicit UID when creating a non-root user.
We changed our docs to Bash rather than powershell.
Lastly, we updated our instructions to help the user setfacls from their host with the knowledge that they already have an explicit UID declared
=> Explicit UID Instructions

docs/editor/userdefinedsnippets.md
Change to describe how to have content like ```$MyVar = 2``` from a snippet.
=> New common question - How to add a variable with $ prefix

api/working-with-extensions/testing-extension.md
`assert.equal` is [deprecated](https://nodejs.org/api/assert.html#assert_assert_strictequal_actual_expected_message) in favour of `assert.strictEqual`
=> Replace deprecated `assert.equal`

api/references/extension-manifest.md
Follow-up from:
- https://github.com/microsoft/vscode/pull/118589
- https://github.com/microsoft/vscode-docs/pull/43
Seems like this one instance was missed ;)
=> add missing Education as valid value

docs/editor/userdefinedsnippets.md
While looking through the code, I noticed there were some variables missing in the docs.
There doesn't seem to be any reason why these shouldn't have been documented in the first place:
* `/pascalcase`: [merged 2018-10-02](https://github.com/microsoft/vscode/pull/59758)
* `RANDOM` and `RANDOM_HEX`: [merged 2019-10-16](https://github.com/microsoft/vscode/pull/82529)
* `UUID`: [merged 2021-01-07](https://github.com/microsoft/vscode/pull/113826)
* `RELATIVE_FILEPATH`: [merged 2021-01-14](https://github.com/microsoft/vscode/pull/114208)
Added documentation for the undocumented variables and the undocumented format option.
=> Update snippet docs

docs/languages/go.md
Change from `"golang.go”` to `"golang.go"`
=> Fix: double quotation in docs/languages/go.md

docs/getstarted/telemetry.md
This updates the telemetry documentation to contain information regarding the `--telemetry` command that has existed since 2019 but been a bit hidden. This also includes @sbatten work around the telemetry APIs which allow extension authors to respect the telemetry setting without utilizing our npm module.
=> Update telemetry docs with the additional information

docs/remote/troubleshooting.md
One of my goals this iteration is to make some updates to help with troubleshooting and triaging issues in remote-release.
1) I've noticed that we often first ask users for their logs. We don't currently ask for logs in the issue reporter, and there's some complexity since we have 3 different extensions. I've added a section about reporting quality issues to the remote troubleshooting doc, which largely includes how to grab the correct logs.
2) In addition to logging info, I've also included a couple other pieces of info in this new section based on common questions we often ask users, i.e.:
- Can they SSH into their machine from an external terminal?
- Does their WSL issue lie on the WSL side or the Remote - WSL side?
3) I wanted to update the doc with any tips or settings that folks …
=> Update remote troubleshooting

release-notes/v1_55.md
I forgot to mention this in the release notes.
See also https://github.com/microsoft/vscode/issues/118270#issuecomment-813995203
=> Add release notes about `editor.autoClosingDelete`

docs/setup/linux.md
Without this, distributions may install their own version of `code`, which is likely outdated.
In ran into this issue in practive: https://www.reddit.com/r/pop_os/comments/mo1vv8/why_does_apt_downgrade_vscode/. The newly added instructions were the solution for me.
=> Describe to use PPA priority

docs/cpp/config-mingw.md
`compilerPath` should the full path to the compiler.
=> Change compilerPath example to full path

api/working-with-extensions/bundling-extension.md
Adds instructions for bundling extensions using esbuild. I put it above webpack since for most users it will be far simpler and easier to configure, but we can move it below webpack if we'd prefer to keep webpack as the recommended path instead.
=> add bundling docs for esbuild

api/language-extensions/programmatic-language-features.md, api/references/vscode-api.md, docs/python/linting.md, docs/remote/faq.md
Scope of changes is restricted to markdown docs only.
=> fix(docs): corrects common typos in project documentation

docs/python/editing.md
`python.autocomplete.addBrackets` doesn't exist.
=> fix python autoComplete configuration setting key

api/extension-guides/webview.md
Fixes a typo in a code snippet from "pragmatically" to "programmatically"
=> Fix typo in Webview API guide

release-notes/v1_56.md
It says single dollar signs but shows `$$`. Also fix a typo.
=> Fix minor mistake in v1.56 release notes about KaTeX

docs/getstarted/userinterface.md
This PR:
- Updates the instruction for hiding the Menu Bar on Windows and Linux to include using the `View > Toggle Menu Bar` command, as well as changing the setting to `toggle` to be able to use the <kbd>Alt</kbd> key to show again.
- Fixes [#4496](https://github.com/microsoft/vscode-docs/issues/4496)
Why:
- Documentation and functionality deviated slightly.
=> Update userinterface (Markdown)

api/extension-guides/tree-view.md
It looks indent is broken a little.
=> Fix indent of package.json example

docs/python/tutorial-django.md
It looks like a stray `f` was added to one of the code snippets so this removes that.
=> Remove stray character from Django tutorial

api/advanced-topics/images/proposed-api/install-from-vsix.gif, api/advanced-topics/using-proposed-api.md
Not sure about how to give the appropriate path for Mac or Windows depending on their machine.
=> Add documentation on how to share and run extensions using the Proposed API

api/working-with-extensions/continuous-integration.md
This updates the Continuous Integration documentation to include an example for GitLab CI.
This is based on the configuration here:
https://gitlab.com/Elypia/magick-image-reader/-/pipelines/302079622
---
This might not be ideal as installing packages in the pipeline isn't optimal, but it's a solution that works on the shared runners without creating ones own Docker image.
An alternative solution could be to make a Docker image just for testing Visual Studio Code Extensions, similarly to how there are containers for testing in Chromium. Like this, it could be based on a node:buster image that just installed the packages to allows us to run a headless instance of Visual Studio Code.
=> docs: add gitlab ci example

docs/cpp/launch-json-reference.md
`filterStdout` and `filterStderr` are existing (undocumented) options. `stopAtConnect` and `hardwareBreakpoints` are new options available in the Insiders release of the C++ extension.
FYI @aleun @robotdad
=> Add new C++ debugging options to launch.json

docs/containers/bridge-to-kubernetes.md, docs/containers/images/bridge-to-kubernetes-vs-code/debug-local-tunnel-context-menu.png, docs/containers/images/bridge-to-kubernetes-vs-code/debug-local-tunnel.png
Adds coverage of the alternate way of getting to Bridge to Kubernetes debugging - from the open-source Kubernetes extension, by choosing local tunnel debugging and then choosing the Bridge to Kubernetes extension as the provider.
=> local tunnel debugging in Bridge tutorial

docs/languages/go.md
To configure the lint tool one should be using `go.lintTool` setting.
=> Fix typo in "Build, test, and diagnose" section

docs/remote/containers.md, docs/remote/images/containers/dev-volumes.png, docs/remote/images/containers/docker-explore-dev-container.png
Updating the docs to reflect @egamma's latest updates to the Clone Repository in Container Volume flow.
- Update inspection command name to **Remote-Containers: Explore a Volume in a Development Container...**
- Add explanation and image for dev volumes section in Remote Explorer
- Update image for inspecting in Docker extension
I explored the other Remote - Containers docs (especially https://code.visualstudio.com/docs/remote/containers-advanced) to see if any content there needed to be updated, but the volume information there seems up-to-date (i.e. code-focused rather than impacted by the new command flow/UI). The [cloning quick start](https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume) also seemed pretty …
=> Update clone in volume information

docs/nodejs/debugging-recipes.md
In relation to https://github.com/microsoft/vscode-docs/issues/4561.
Linking to a recipe for debugging Node.js Lambda functions locally https://github.com/microsoft/vscode-recipes/pull/299.
=> Linking to recipe for debugging Lambda functions locally

docs/python/debugging.md
Fixed a few typos, added missing commas, removed redundancies, and improved conciseness.
=> Fix typos and grammar in Python/Debugging.md

docs/python/settings-reference.md
The default path is "pytest", not "py.test":
https://github.com/microsoft/vscode-python/blob/f6100335a5260967031a2a1ee3684f701e95a932/package.json#L1837
Originally introduced in https://github.com/microsoft/vscode-python/commit/5b3cd6ee51754621c7be776c50157214d22a55da as "pytest".
=> Fix default pytest path

docs/containers/quickstart-python.md
Updated the order of the prompts after selecting `Python: Django` as the app type when using `Docker: Add Docker Files to Workspace...`. For the Docker extension (v1.13.0), the correct order should have the prompt to select whether or not to include Docker Compose files as the last prompt, not the first.
=> Correct quickstart-python.md prompt order

api/working-with-extensions/continuous-integration.md
Follow up to https://github.com/microsoft/vscode-docs/pull/4547
This is a minor change to the packages installed in `.gitlab-ci.yml`.
I replaced `libgbm-dev` with `libgbm1`, as the dev version isn't required to run `xvfb-run -a npm run test`.
I noticed this change in another repositories, and it appears to be valid here too:
https://github.com/puppeteer/puppeteer/pull/5693
The overall impact of the change is minimal, however:
* 104 packages installed -> 103 packages installed
* 62.9 MB downloaded -> 62.8 MB downloaded
=> docs: update packages for gitlab ci script

docs/supporting/requirements.md
The macOS universal build is currently 180.2 MB and the disk footprint on my system is 458.2 MB.
=> update download/footprint sizes

api/extension-guides/command.md, api/references/when-clause-contexts.md
I tried to follow the directions on setting the context for when clauses, but it didn't work as documented.
The `setContext` value must match the expected read value.
It is correct in the release document. See: [vscode-docs/v1_49.md at main · microsoft/vscode-docs](https://github.com/microsoft/vscode-docs/blob/main/release-notes/v1_49.md#in-operator-for-when-clauses)
Two ways to document based upon preferred convention:
```ts
vscode.commands.executeCommand('setContext', 'ext.supportedFolders', [ 'test', 'foo', 'bar' ]);
```
```json
{
"when": "explorerResourceIsFolder && resourceFilename in ext.supportedFolders"
}
```
```ts
vscode.commands.executeCommand('setContext', 'ext:supportedFolders', [ 'test', 'foo', 'bar' ]);
```
```json
{
"when": "explorerResourceIsFolder && resourceFilename in …
```
=> fix: Make sure `setContext` docs match behavior

docs/remote/faq.md
After recent extension investigations, we thought perhaps there could be documentation improvements to clarify `extensionKind` to users, i.e. the concept itself, differences in extension kinds, when to define it.
Upon reviewing the docs even more closely, I feel as though they are quite well-defined already (but perhaps that's also because I'm rather close to the problem at this point).
One takeaway I thought could make the experience a bit easier to read/grasp would be linking users directly to the [troubleshooting section](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) as that took a bit of scrolling to find and may not be immediately obvious if we just link users to the top of the [Supporting Remote …
=> Add additional extensionKind info

docs/remote/containers.md
Fixes https://github.com/microsoft/vscode-remote-release/issues/3703
I updated the gpg section to include a WSL section following the steps in the linked issue. I also separated the platforms into bullets to make them a bit easier to read now that there is more detail. Please let me know if this is the accurate information and what you had in mind. Thanks!
=> Remote-Containers Doc: Mention WSL2 specifics in GPG section

docs/editor/integrated-terminal.md
Fish does not use `~/.fishrc` but `~/.config/fish/config.fish`.
=> Fix fish config file location

docs/remote/containers.md
Proofread pass noted d**ae**mon as canonical spelling for Docker daemons
https://code.visualstudio.com/docs/remote/containers
https://docs.docker.com/get-started/overview
`dockerd`
=> docs(containers.md): proofread typo `daemon` from `deamon`

api/extension-guides/custom-editors.md
It seems that there's misdescription in custom editors section of extension guide. But I'm not sure if it's really a misdescription or misunderstanding.
=> fix: custom-editors docs typo

docs/java/extensions.md
Removes "Java Linter" from the list of recommended extensions.
> This extension is now unpublished from Marketplace. You can choose to uninstall it.
> \- https://marketplace.visualstudio.com/items?itemName=faustinoaq.javac-linter
=> fix: remove unavailable extension

api/references/contribution-points.md
removed an extra backtick in the `contributes.taskDefinitions` body
=> fix invalid syntax in contribution-points.md

api/extension-guides/notebook.md
NotebookContentProvider no longer exists, and the link points to NotebookSerializer. 
Should remove the old name to avoid confusion.
=> Update reference name to NotebookSerializer

docs/cpp/config-mingw.md, docs/cpp/images/mingw/mingw-build-output.png, docs/cpp/images/mingw/mingw-debug-output.png, docs/cpp/images/mingw/mingw-dir-output.png, docs/languages/cpp.md, docs/languages/images/cpp/gpp-build-task-msys64.png
Still need to update screenshots that show terminal output after running the build task.
@sean-mcmanus, when I use the mingw-w64 that I installed with MSYS2, the default build task changes cwd to from "${workspaceFolder}" to "C:/msys64/mingw64/bin". This seems weird to me, but it works. When I changed it back to "${workspaceFolder}" the build failed. Do you know why we're doing this?
=> Update tutorial to use up-to-date version of mingw-w64 via MSYS2

docs/editor/integrated-terminal.md
Adds workaround for https://github.com/microsoft/vscode/issues/128914 to the documentation.
What is currently listed in the documentation doesn't align with the way keybindings should be handled in the shell as explained here: https://code.visualstudio.com/docs/editor/integrated-terminal#_keybindings-and-the-shell
=> Add working (proper) way to send ctrl+f to shell to find section

docs/editor/workspaces.md
The two markdown URLs are leading to two wrong locations which redirect to the 404 page. The two wrongly formed URLs are the following:
- `https://code.visualstudio.com/docs/editor/docs/editor/tasks.md`
- `https://code.visualstudio.com/docs/editor/docs/editor/debugging.md`
Adding the leading forward-slash should fix this.
=> Fix non-working URLs

docs/python/python-tutorial.md
- Link of `get-pip.py` has broken in [Linux section of python-tutorial](https://code.visualstudio.com/docs/python/python-tutorial#_linux)
- Change https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py to https://pip.pypa.io/en/stable/installation/#get-pip-py
=> Fix broken link

docs/nodejs/browser-debugging.md
Fixed some typos in the urls for links to more detailed guides in [Browser debugging in VS Code](https://code.visualstudio.com/docs/nodejs/browser-debugging)
=> Typos in Browser debugging in VS Code

docs/remote/devcontainer-cli.md, docs/remote/devcontainerjson-reference.md, docs/remote/faq.md, docs/remote/images/devcontainer-cli/install.png, docs/remote/images/devcontainer-cli/reopen-in-container.png, docs/remote/troubleshooting.md
Adds initial docs for the `devcontainer` CLI: 
- https://github.com/microsoft/vscode-remote-release/issues/5302, 
- https://github.com/microsoft/vscode-remote-release/issues/5349
I made an initial estimate of placement in the table of contents, but let me know if the order should be tweaked
=> Initial devcontainer CLI docs

docs/setup/linux.md
For RHEL, Fedora, and CentOS based distributions the command `dnf check-update` can be executed without sudo.
=> Remove uneeded sudo from `dnf check-update`

docs/remote/containers-advanced.md
@bamurtaugh @burkeholland @stuartleeks 
Added a reference to getting minikube up in a dev container as discussed.
I also added a tip on getting processes to start and keep running on container start.  I've been seeing quite a few questions on this lately from folks using Codespaces and noticed we didn't have a section on it.
=> Add minikube-in-docker reference, tips for getting processes to start when the container starts

api/working-with-extensions/bundling-extension.md
This is no longer needed past npm v5, and is not documented anywhere. It
may confuse people.
**Note**: I saw the "Do not touch" note at the top of the file and read the contribution guidelines. I'm not sure if editing this `md` is the correct way to contribute, so please let me know if an alternate workflow is preferred. Thanks.
=> Remove old -S flag from sample `npm run`.

docs/languages/jsconfig.md
The existing link to the TypeScript `compilerOptions` documentation links to the `tsc` CLI options, which does not actually contain documentation on `compilerOptions`.
Let's link to the `compilerOptions` section in the `tsconfig` reference instead.
=> `jsconfig.json`: Update link to `compilerOptions`

docs/setup/additional-components.md
Front npm: https://www.npmjs.com/package/generator-aspnet
This package has been deprecated
Author message:
Use dotnet new instead
=> Remove generator-aspnet from Additional tools

docs/java/java-project.md
Looks like this change might have been missed in #3846 (which did the same change for the `java-build.md` page).
=> Fix page title in java-project.md

docs/languages/css.md
- Fixes #4667 
- Add a missing module so `gulp` won't throw errors
=> Replace `node-sass` with `sass` in the task example

docs/containers/reference.md
Related to https://github.com/microsoft/vscode-docker/issues/2777.
Please hold off on merging until our 1.16.0 release, tentatively on 16 August 2021.
=> Add info about Compose profile features

docs/python/settings-reference.md
Per https://github.com/microsoft/pylance-release/issues/1678.
This is `autoImportCompletions` not `autoImportCompletion`.
=> Fix typo in Pylance autoImportCompletions setting

api/extension-guides/file-icon-theme.md, api/language-extensions/syntax-highlight-guide.md, api/references/vscode-api.md, docs/cpp/natvis.md, docs/editor/emmet.md, docs/getstarted/tips-and-tricks.md, docs/languages/html.md, docs/languages/overview.md, docs/supporting/faq.md
This pull request replaces instances of "id" and "Id" with "ID". One instance of "Id" was replaced with "identifier", in another instance "id" was used to match the Yeoman screenshot.
=> Make capitalization of language ID consistent

docs/java/java-tutorial.md
Related to #4753, this time focused on the [Java tutorial](https://code.visualstudio.com/docs/java/java-tutorial) page.
=> Small edits to the Java tutorial page

docs/cpp/config-msvc.md
Hi,
Recently I had to configure VS Code to use Microsoft C++ compiler in remote development scenarios and I have found the following way of automated initialisation of developer command prompt during execution of build task.
I am not sure that PR is the right way to share such an idea but I thought it would be better to see the changes in place, so it will be easier to discuss them or reject them right away.
=> Automated use of developer command prompt in tasks

docs/remote/ssh.md
[Remote Development using SSH](https://code.visualstudio.com/docs/remote/ssh) lists the keyboard shortcut for the Command Palette as F1 repeatedly. It uses a (presumably) older style of listing shortcuts on the site.
This PR changes it to use the proper `kb(COMMAND-ID)` format to automatically resolve and display the keybindings based on the user's client platform.
=> doc: fix kb shortcut remote development with SSH

docs/editor/debugging.md
A link for "Automatically open a URI when debugging a server program" is currently directed at the section above that, "Remote debugging".
=> Fix section link in Debugging

docs/cpp/cpp-ide.md
The link under [**Next Steps**](https://github.com/microsoft/vscode-docs/blob/main/docs/cpp/cpp-ide.md#next-steps) for *“Configure VS Code for **MSVC**”* was pointing to  the **MinGW/GCC tutorial** instead
=> cpp-ide.md: Fix misdirecting link for MSVC config

docs/languages/python.md, docs/python/debugging.md, docs/python/environments.md, docs/python/python-tutorial.md, docs/python/tutorial-django.md, docs/python/tutorial-flask.md
Updated references to the **Terminal: Create New Terminal** command (current documentation contains what is likely the former name of this command)
=> Update references to the Create New Terminal command

api/references/commands.md
With reference to [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostApiCommands.ts#L27) and [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostApiCommands.ts#L33), it might be possible a big typo for the original document.
So here is my quick fix.
=> update the return types

docs/nodejs/images/working-with-javascript/partial-mode-status-item.png, docs/nodejs/working-with-javascript.md
This adds notes on partial mode IntelliSense for JS/TS
Partial mode is used on GitHub.dev as well as when opening files on virtual file systems
=> Adding section on JS/TS partial IntelliSense mode

docs/cpp/config-mingw.md, docs/cpp/config-msvc.md
Recently, I wanted to get a small C demo going (https://github.com/rzhao271/named-pipe-sample).
I read through the documentation too quickly, assumed that I knew what I was doing, and ended up stuck for a while, especially on the `cl.exe` setup.
This PR adds docs to and expands the troubleshooting sections of https://code.visualstudio.com/docs/cpp/config-mingw and https://code.visualstudio.com/docs/cpp/config-msvc to emphasize some steps that a user could've forgotten to do (or assumed were unimportant).
Edit: Commit https://github.com/microsoft/vscode-docs/pull/4846/commits/50045832a2f30f72703bdadde8b0c9e4e4fc435a says it is unverified, but that is because I don't have code signing set up on Codespaces.
=> C++ docs: Add redundancy to avoid pitfalls

docs/python/tutorial-django.md, docs/python/tutorial-flask.md
These changes reflect GitHub issue #3684 request.
All mentions of `env` were changed to `.venv` throughout the tutorial, as well as a small edit (removed an extra numbered item on line 201). In addition to these changes, the commands to create and activate the virtual environment were also updated for Window, macOS, and Linux (see lines 48-57).
Attached are the new screenshots to replace **environment-in-status-bar.png** and **select-virtual-environment.png**
=> Normalizing .venv on Flask and Django Tutorials

docs/python/settings-reference.md
Removed Microsoft from the list of supported language servers, in addition to removing MPLS content [here](https://github.com/microsoft/vscode-docs/commit/a97c8de28220315ce64efbdaae02adb193bb5239).
=> Removed Microsoft from supported language servers

api/extension-guides/virtual-documents.md
Missing a leading slash, without which the path is wrong
=> fix: broken link to virtual-workspaces page

docs/remote/containers.md, docs/remote/devcontainer-cli.md
Including @fyyyyy's tip from https://github.com/microsoft/vscode-remote-release/issues/5779 in our section in pre-building.
=> Add tip from remote-release on non-manual build

docs/java/java-project.md
`java.project.referencedLibaries` should be `java.project.referencedLibraries`.
=> Fix typo in setting ID

api/references/activation-events.md
`*` activation should only be used if all other activation events don't cover your usecase and I wanna stress this as we have seen a lot of folks using `*` when `onStartupFinished` would have been perfectly fine for their usecase.
This change just swaps the two entries and pulls out some of the content in the `*` section into a `Note` for emphasis.
=> de-emphasize `*` activation.

api/extension-guides/web-extensions.md
Chrome allows any website to access random localhost ports on your computer. Is this a good idea? IMO not really, but it's the reality we're in - I use this to do the same thing when making plugins for the TS playground. This means if you want to quickly test an extension in vscode.dev you have to do less work.
=> Update web-extensions to simplify setup for chromium browsers

docs/containers/images/overview/compose-group.png, docs/containers/images/overview/hover-support.png, docs/containers/images/overview/select-subset.gif, docs/containers/images/overview/tab-completions.gif, docs/containers/overview.md
This PR updates the current state of the VS Code Docker overview page to include newer gifs and content about our latest features
=> update VS Code overview page

docs/remote/linux.md, docs/remote/ssh.md
Updated references to Raspberry Pi OS to reflect new name
=> Raspbian is now called Raspberry Pi OS

docs/languages/javascript.md
It's really just a minor typo in the doc I was reading here: https://code.visualstudio.com/Docs/languages/javascript#_formatting
=> Minor typo

docs/getstarted/settings.md
I noticed this while I was reviewing settings for a fresh install. Hope this is helpful!
=> remove extra wording around terminal mnemonics

docs/languages/images/java/beginner-tips.png, docs/languages/images/java/extensions.png, docs/languages/images/java/getting-started.png, docs/languages/images/java/package-viewer.gif, docs/languages/images/java/package-viewer.mp4, docs/languages/images/java/resolve-main.gif, docs/languages/images/java/resolve-main.mp4, docs/languages/java.md
=> Java: update docs and videos

docs/java/java-refactoring.md
Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>
The Java refactoring page is a pretty long web page, it's hard to discover what code actions are supported by a glance.
The new page adds a ToC at the beginning to list all code actions supported.
=> Update docs for Java refactoring page

docs/java/images/java-build/gradle-auto-completion.mp4, docs/java/images/java-build/gradle-daemons.mp4, docs/java/images/java-build/gradle-dependencies.png, docs/java/images/java-build/gradle-dependency-completion.mp4, docs/java/images/java-build/gradle-highlighting.png, docs/java/images/java-build/gradle-outline.png, docs/java/images/java-build/gradle-pinned-recent-tasks.mp4, docs/java/images/java-build/gradle-problems.png, docs/java/images/java-build/gradle-tasks.mp4, docs/java/java-build.md
This PR extends the Gradle part of `Build Tools` section with the description and demo from Gradle for Java extension. 
cc: @nickzhums 
Signed-off-by: Shi Chen chenshi@microsoft.com
=> Java: add gradle part

docs/java/java-project.md
Since we have enabled platform specific extensions, there is no need to let the user knows the concept of language server JDK now.
=> Remove the section for the language server JDK

docs/remote/containers.md, docs/remote/create-dev-container.md, docs/remote/devcontainer-cli.md, docs/remote/devcontainerjson-reference.md, docs/remote/ssh.md, remote/advancedcontainers/develop-remote-host.md
This PR:
1. Adds the missing hostRequirements property set to the devcontainer.json reference
2. Tries to address some formatting issues with the devcontainer.json reference
3. Adds more details about pre-building container images, strengthens recommendation
4. Adds some known issues and misc corrections on SSH + Containers support
=> Add missing properties to devcontainer.json ref, flesh out features and image pre-builds, misc corrections

docs/editor/userdefinedsnippets.md
It is not clear to some users what `language identifiers` are when setting up `Language snippet scope`. I added a hyperlink so that users can learn more about it.
=> added language identifier hyperlink for better clarification

docs/python/settings-reference.md
Add missing python extension settings for the bandit linter.
=> Add python settings for bandit

api/references/theme-color.md, docs/getstarted/userinterface.md
I guess it's better to use non deprecated settings in docs. So here is the PR.
Ref:
> https://github.com/microsoft/vscode-docs/blob/main/release-notes/v1_61.md#indentation-guides-settings
>
> The `editor.renderIndentGuides` and `editor.highlightActiveIndentGuide` settings have been deprecated in favor of `editor.guides.indentation` and `editor.guides.highlightActiveIndentation`.
=> Fix editor.renderIndentGuides deprecation

docs/python/testing.md
We had a configuration for debugging tests named "Python: Current File" which was misleading. This PR fixes it to become "Python: Debug Tests"
=> Fix debug config name when debugging tests

api/language-extensions/programmatic-language-features.md
Update the provideCodeActions signature to match what's in https://code.visualstudio.com/api/references/vscode-api#CodeActionProvider%3CT%3E.
I had a fun time trying to figure out how to mark a code action as a quick fix until I realized that the docs were telling me to use a legacy return signature :).
=> Update provideCodeActions signature

blogs/2020/07/01/containers-wsl.md
The text "Enable WSL 2 by following the WSL 2 installation guide" links to https://docs.microsoft.com/en-us/windows/wsl/wsl2-install, which is broken. The new link should be https://docs.microsoft.com/windows/wsl/install.
=> Update install link

docs/languages/identifiers.md
The cuda language is supported in vscode, see https://github.com/microsoft/vscode/pull/119444
=> Add cuda language id

docs/editor/vscode-web.md
Based on recent discussions, I wanted to add a note on official browser support in VS Code for the Web and any potential limitations.
Added an initial note on which browsers are supported - it's my understanding there may be something to note for webviews in Firefox (@alexr00?), and @jrieken I think you've done notable testing in Safari. Would love to know if there's anything specific we should highlight for these or other browsers (cc @digitarald too).
=> Note on browser support

docs/python/debugging.md
In response to issue #5061 The following commit includes `jinja` as an option and `code` as an alternative to `module`. @karthiknadig @luabud Can you verify the accuracy please? ☺️
=> Adding jinja and code to configs

docs/nodejs/angular-tutorial.md
fix angular-tutorial by changing the title and description to "Angular TypeScript"  and changing as a "JavaScript Library" to a "Modern Web Development Platform"
=> fix: angular-tutorial

docs/editor/github.md
- Change `by clicking on the the Remote indicator` to `by clicking on the Remote indicator`
=> Fix typo in docs/editor/github.md

docs/containers/reference.md
For https://github.com/microsoft/vscode-docker/pull/3339 I was going to remove `envFiles` from the docs but I discovered it was never added in the first place. So, adding the new `envFile` option that will replace it.
~~**NOTE**: Please hold off on merging until our 1.19 release, tentatively 17 Jan 22.~~ Ready to merge!
=> Add `envFile` to compose task spec

docs/python/tutorial-django.md, docs/python/tutorial-flask.md
For https://github.com/microsoft/vscode-docs/issues/4691. 
I figured it was worth removing the note where it said users had to restart the debugger to apply the changes, and adding a step to trigger live reload of the web servers in the Flask and Django tutorials.
=> Include steps in tutorial to reflect support for live reloading of flask and django 

docs/python/testing.md
Addressing the doc-bug for PR #5109. @karthiknadig can you please confirm that having the Python extension and an open project are enough to get the beaker to render? ☺️
=> Edits in Configure Tests section

docs/remote/containers.md, docs/remote/devcontainer-cli.md
Link to the new https://github.com/microsoft/dev-container-spec repo from the dev container doc and dev container CLI doc.
=> Add new dev container repo link

api/references/when-clause-contexts.md
This tripped me up, "the value doesn't matter" is making a stronger claim than it should be.
https://github.com/microsoft/vscode/issues/140359
=> object used for `in` can't map to functions

api/references/contribution-points.md
This contribution point was added in https://github.com/microsoft/vscode/commit/f1a91d26611d80da90c295bb7262557e1b0e4265 by @connor4312 but didn't make the documentation.
=> Add`testing/item/gutter` menu contribution point

api/references/contribution-points.md
fix: changed typo in docs (see [here](https://github.com/microsoft/vscode/blob/5c85bdc1998f501306e305e48825747c6a12c8fa/src/vs/workbench/services/actions/common/menusExtensionPoint.ts#L84) )
=> Fixed typo in contributes.menus

remote/advancedcontainers/start-processes.md
There's an extra '`' in the CMD that causes the container to break when following instructions
=> Extra `'` typo in `CMD` causes container to break

api/references/theme-color.md
Adds a new theme token to /api/references/theme-color to account for the [new theme token](https://github.com/microsoft/vscode/pull/142665) added to VS Code.
=> Add theme color entry for `statusBarItem.focusBorder`

docs/getstarted/settings.md
The interactive settings editor will not write a default value to the workplace settings file. While there are good reasons for this, it is somewhat confusing, as many have noted on https://github.com/microsoft/vscode/issues/58038. This PR documents the current behavior and suggests the workaround of manually editing the workspace settings file.
=> settings: clarify editor can't write defaults

docs/python/linting.md
Removed _red_ and _green_ text from Pylint section. 
Fixes #5168
=> Minor Pylint edits

docs/remote/troubleshooting.md
I spent ages trying figure out why I couldn't run "git" commands in an Terminal on the remote machine.  Turns out that VSCode doesn't automatically forward the local SSH Agent to the remote even when "remote.SSH.enableAgentForwarding" is set - you need to tell SSH to do this explicitly.
=> Ssh-Agent works best with "ForwardAgent yes" in .ssh/config

docs/nodejs/angular-tutorial.md
Changed the link of react website to `https://reactjs.org` from `https://facebook.github.io/react` and changed the term `web framework` to `library for building ui`
=> Fixed angular-tutorial.md `React` section

docs/remote/create-dev-container.md
Very minor typo fix from `PostGreSQL` to `PostgreSQL` in dev container documentation
=> Documentation: fix capitalization of PostgreSQL

docs/containers/reference.md
This PR updates the documentation to include a new property that will be introduced to Docker compose task definitions via microsoft/vscode-docker#3440.
**This is not ready to be merged yet**. I will update this PR once it is known when the new property is released.
=> Add documentation for projectName on compose tasks

api/references/contribution-points.md
Semantic highlighting is already documented in the linked page but it was missing in the reference overview page, so this PR addresses that.
=> api: document missing semantic highlighting contribution points

.gitattributes, docs/remote/troubleshooting.md
The current commands fail to show any processes corresponding to the VS Code server. Grep for `vscode-server` instead.
Also add a separate command to clean up the most recent  `.$hash.{pid,log,token}` files.
For bonus points, mark Markdown files with the `diff=markdown` attribute in `.gitattributes`
=> remote: update 'Kill VS Code Server on Host' command

api/working-with-extensions/continuous-integration.md
**Context**: The use of the `after_script` for deployment may not be the best usecase for deployment. Since [2012](https://blog.travis-ci.com/after_script_behavior_changes), the `after_script` will **always** run regardless if the result of the test result.  Using the `after_script` will lead to attempts at publishing a new version of an extension in every build. 
The condition `env(TRAVIS_TAG) =~ ^v` has no effect so on each build it will still try to publish a new version.
I think a better solution is to use the `deploy` script which is design for deploy artifacts to a repository, such as the Azure Marketplace.
=> Updated docs to use deploy stage instead of after_script

docs/nodejs/nodejs-debugging.md
A small mistake, but "replaced list a list" is (I think) not what we are going for here.
Replaced "list a list" with "with a list" in `docs/nodejs/nodejs-debugging`.
=> Replace "replaced list a list" with "replaced with a list".

docs/containers/reference.md
We made some changes in https://github.com/microsoft/vscode-docker/issues/2977 / https://github.com/microsoft/vscode-docker/pull/3478 to the defaults for command customization, and added a new token `${composeCommand}` supported on the compose commands.
/cc @ucheNkadiCode
NOTE: Please hold off on merging until our 1.22 release, tentatively 18 Apr 22.
=> Update documentation to reflect new `docker.composeCommand` setting

docs/python/environments.md
I renamed the Python resource links from _Getting started_ to _More Python resources_ and included it in a note at the top of the page. I also moved the _Next steps_ section up.
=> small edits to environments resources

api/references/icons-in-labels.md, docs/java/images/java-project/java.build.status.mp4, docs/java/images/java-project/switch-to-standard.gif, docs/java/images/java-tutorial/JavaHelloWorld.Standalone.mp4, docs/java/java-project.md, docs/java/java-tutorial.md
Since vscode-java has [adopted](https://github.com/redhat-developer/vscode-java/pull/2363) the language status item, we'd better update our tutorial here.
cc: @nickzhums 
Signed-off-by: CsCherrYY <chenshi@microsoft.com>
=> Java: Update description and demos for language status item

api/extension-guides/telemetry.md, api/toc.json, docs/getstarted/telemetry.md
This PR adds a new Telemetry page to the extension guides.
This is a first cut @lramos15 please add what you had in mind directly in the PR. Thanks!
@gregvanl can you give this a quick review and add the page header as all the other pages seem to have that and I am not sure how to generate it. Thanks!
=> extension telemetry page

docs/editor/extension-marketplace.md, docs/editor/images/extension-marketplace/extension-contributions.png, docs/editor/images/extension-marketplace/extension-identifier.png, docs/editor/images/extension-marketplace/extensions-python.png
PR raised with Git LFS enabled. #5312
This PR updates the statement for finding the extension identifier on the extension details page. Moreover, the associated screenshots are also updated with the latest release.
This PR solves the issue https://github.com/microsoft/vscode-docs/issues/5306
=> Small edits to recent updates

docs/introvideos/basics.md
Fix 2 typos in key bindings in 'Video outline': 1) for '**View** > **Problems**'; 2) for '**Run** > **Start Debugging**'.
=> Update '/docs/introvideos/basics.md' - fix 2 typos

docs/containers/choosing-dev-environment.md, docs/containers/debug-common.md, docs/containers/debug-netcore.md, docs/containers/docker-compose.md, docs/containers/overview.md, docs/containers/quickstart-aspnet-core.md, docs/containers/reference.md
.NET 5 and later drop the "Core" and just use the brand ".NET"
ASP.NET Core still uses the "Core" name 
Product UI still uses .NET Core in places, so those refs are not updated
@ucheNkadiCode @gregvanl
=> Rebrand .NET Core > .NET

docs/python/debugging.md
... the settings configuration section. This PR closes issue #5344
=> remove mention of 'code' as alt to 'module'

blogs/2022/05/18/dev-container-cli.md
Update the blog post to be more explicit that the spec is still a WIP and has not yet been published (help address https://github.com/devcontainers/spec/issues/32).
cc @joshspicer @edgonmsft @jkeech
=> Update dev container blog post

docs/editor/codebasics.md, docs/editor/images/codebasics/search-editor-button.png, docs/editor/images/codebasics/search-editor-overview.png, docs/editor/images/codebasics/search-editor-triggers.gif
Fixes issue #3947 Added documentation for the search editor feature. Please let me know how this looks, and if there is anything else I should add. I am looking forward to making my first contribution. 
You can view how the md file looks <a href="https://github.com/joey2031/vscode-docs/blob/3947-searchEditorDoc/docs/editor/codebasics.md#search-editor">here</a>
List of sources (VS code blog posts)
- [January 2020 (v1.42)](https://code.visualstudio.com/updates/v1_42#_search-editor)
- [February 2020 (v1.43)](https://code.visualstudio.com/updates/v1_43#_search-editors)
- [May 2020 (v1.46)](https://code.visualstudio.com/updates/v1_46#_search-editor)
- [June 2020 (v1.47)](https://code.visualstudio.com/updates/v1_47#_new-search-editor-command-arguments)
- [July 2020 …
=> 3947 Added Search Editor Documentation

docs/getstarted/tips-and-tricks.md
Fix three links. The value of one of the parameters, 'sortBy', has been changed in the links.
Instead of the 'Downloads' value, it should be 'Installs', because there is no 'Downloads' value in the VS Code extension Marketplace:
=> Update tips-and-tricks.md - fix links

docs/getstarted/tips-and-tricks.md
Fixed a typo in the description JSON schema in section 'Add JSON validation'.
=> Update tips-and-tricks.md - fix typo

docs/getstarted/tips-and-tricks.md
The section title says about the folder, so keybinding should be `kb(workbench.action.closeFolder)`, not `kb(workbench.action.closeActiveEditor)`.
=> Update tips-and-tricks.md - fix keybinding

docs/java/java-debugging.md
When adding custom folders to a Java project's classpath, via the `classPaths` field, it was un-clear on how to append the automatically resolved classPath to the list.
i.e. specifying the following resulted in a simple class-path of `-cp /usr/local/data/git/some-folder/`, instead of all my maven dependencies plus the folder:
```json
{
"type": "java",
"name": "some-service",
"request": "launch",
"mainClass": "com.sample.SomeService",
"projectName": "some-service",
"classPaths": [
"/usr/local/data/git/some-folder/"
]
}
```
Had to dig around a bit to find an enum defined as `ClasspathVariable` under [microsoft/vscode-java-debug/src/constants.ts](https://github.com/microsoft/vscode-java-debug/blob/main/src/constants.ts) and saw that it was used …
=> Added classPaths options to java debugging

docs/editor/accessibility.md
Fixes #5367
It's fine to update a bit later/on recovery release, it's not critical to have this in immediately for 1.68.0.
=> Document hover lock feature

release-notes/v1_68.md
This was part of the 1.68 release, but I missed adding it to the release notes.
=> Add task globs to release

api/working-with-extensions/publishing-extension.md
The existing documentation is ambiguous about what happens in this scenario:
- User has pre-release version 0.1.0 installed.
- Release version 0.2.0 is published. User automatically updates to this version.
- Pre-release version 0.3.0 is published. Is the user now stuck on the release version, or are they still eligible for pre-releases because they had a pre-release installed before?
I tried creating a dummy extension on the marketplace and published a few versions to test the functionality, and the user appears to still be eligible for newer pre-releases. What I've written is correct based on that testing, but I'd love to get some expert validation of this behavior.
@aleun FYI
=> Clarify pre-release to release update semantics

docs/other/unity.md
With the recent removal of Mono & MSBuild Tools by default in the C# extension, `useModernNet` must be set to `false` for intellisense to work.
More info [here](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp#:~:text=Planned%20removal%20of%20the%20included%20Mono%20%26%20MSBuild%20Tools).
=> Intellisense requires additional configuration

docs/languages/go.md
Updates https://github.com/golang/vscode-go/issues/2094
=> go.md: update contents and replace go extension's doc links with wiki links

api/extension-capabilities/common-capabilities.md
The negation of `isHigher` is easy to miss.
=> Make code example easier to understand

api/working-with-extensions/continuous-integration.md
I discovered the hard way (== actually reading the documentation and using the code suggested in there) that the git ref used by GitHub for releases is `refs/tags/<RELEASE_NAME>`, not `refs/tags/releases/<RELEASE_NAME>`.
=> Fix git ref to use for release-triggered actions

docs/setup/linux.md
We moved to https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/vscode.nix in this [Nixpkgs pull request](https://github.com/NixOS/nixpkgs/pull/60423/commits/5c85979f78d4dee02cd0cb8be42f0953e7d71a18), let's update the Nixpkgs link to reflect the change.
Thanks for reviewing this!
=> setup/linux.md: fix broken Nixpkgs link

api/working-with-extensions/continuous-integration.md
Upgrades the GitHub actions in the continuous integration documentation as they were out of date, as part of this, upgrades node to the latest LTS
=> Upgrade GitHub actions dependencies

docs/python/editing.md
The previous command installed `pep8` package.
Maybe previously it was the same as `autopep8`, but now its a separate package, and the command to install `autopep8` has changed.
=> docs: a proper command to install autopep8

release-notes/v1_68.md
See https://github.com/microsoft/vscode-docs/issues/5452
=> Fixed the release notes extension link

docs/supporting/faq.md
Example reference from https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported removed. 
Fixes #5380
=> docs: remove example reference from faq section

docs/remote/vscode-server.md
There is no need to call environment variables in PowerShell using ${HOME}.
$HOME is enough.
=> Fix environment variables in PowerShell code

docs/python/settings-reference.md
In the next release, we are adding two types of inlay hints: for variable types and for return types. These two hints are behind feature flags: "python.analysis.inlayHints.functionReturnTypes" and "python.analysis.inlayHints.variableTypes". This PR adds these settings to the docs.
=> Add settings for inlay hints with Pylance

api/advanced-topics/remote-extensions.md, api/extension-guides/debugger-extension.md, api/get-started/your-first-extension.md, api/language-extensions/language-server-extension-guide.md, api/references/icons-in-labels.md, docs/containers/debug-netcore.md, docs/cpp/config-clang-mac.md, docs/cpp/config-linux.md, docs/cpp/config-mingw.md, docs/cpp/config-msvc.md, docs/cpp/config-wsl.md, docs/editor/accessibility.md, docs/editor/debugging.md, docs/editor/images/debugging/run.png, docs/introvideos/debugging.md, docs/java/java-tutorial.md, docs/languages/julia.md, docs/nodejs/angular-tutorial.md, docs/nodejs/browser-debugging.md, docs/nodejs/images/nodejs/debugicon.png, docs/nodejs/images/nodejs/hello-world-debugging.png, docs/nodejs/nodejs-debugging.md, docs/nodejs/nodejs-tutorial.md, docs/nodejs/reactjs-tutorial.md, docs/python/debugging.md, docs/python/tutorial-django.md, docs/python/tutorial-flask.md, docs/typescript/typescript-debugging.md, docs/typescript/typescript-tutorial.md
View is now called "Run and Debug"
"create a launch.json file" link instead of Gear icon if no launch.json is detected
Couple of stale screenshot update
Edge: launch -> Web App (Edge), Chrome: launch -> Web App (Chrome)
pwa-msedge -> msedge, pws-chrome -> chrome
=> Various debugger UI updates

docs/remote/create-dev-container.md
This change helps avoid users who update the dockerfile following docs example from running into container creation failures. Without the `-y` flag it hangs at the interactive prompt and the container fails to create.
=> Add the -y flag in apt-get example in dockerfile

docs/remote/containers.md, docs/remote/devcontainer-cli.md, docs/remote/devcontainerjson-reference.md, docs/remote/images/devcontainer-cli/dev-container-stages.png, docs/remote/images/devcontainer-cli/install.png, docs/remote/images/devcontainer-cli/reopen-in-container.png
Update docs/remote/devcontainer-cli topic for new devcontainer CLI.
Much of the content came from the announcement blog post.
=> Update devcontainer-cli topic for new CLI

docs/editor/settings-sync.md
Error description: "The name org.freedesktop.secrets was not provided by any .service files"
Reference with explanation: https://tips.initpals.com/kde-tips/fix-for-error-the-name-org-freedesktop-secrets-was-not-provided-by-any-service-files-in-kde/
=> Added docs for another sync error on Linux

docs/getstarted/keybindings.md
In VSCode 1.69.2, the menu item for retrieving popular keymap extensions is **File > Preferences > Migrate Keyboard Shortcuts from...**, not **File > Preferences > Keymaps**.
=> Update "Keymaps" menu item to current text label

docs/editor/command-line.md
In line with the https://code.visualstudio.com/updates/v1_70#_command-line-option-merge this documentation needed to include the new `---merge`
=> Three-way-merge-to-cli-options

docs/languages/r.md
The lintr hyperlinks were dead. They now point to the new lintr documentation.
=> update {lintr} hyperlinks

docs/terminal/shell-integration.md
Part of microsoft/vscode#143769, this is new coming in 1.71
=> Add a git bash section to shell integration

remote/advancedcontainers/persist-bash-history.md
Hi!
I just copy/pasted the recipe to persist bash history in my Dockerfile, and [`hadolint`](https://github.com/hadolint/hadolint) (which is a linter for Dockerfile) raised a warning (SC2086).
In this specific case, double-quotes does not matter much, but at least it will avoid the warning to be raised by default for people copy/pasting this documented recipe and using Hadolint. :+1:
=> Use double quote to prevent globbing and word splitting

docs/typescript/typescript-compiling.md
Throughout the article it is written that `tsc` transpiles TypeScript source code to JavaScript. That's why I find it important to also state that in the beginning of the article.
=> Use transpiling over compiling

docs/python/testing.md
The `pyproject.toml` file is becoming more widely used in projects and requires a slightly different approach and syntax, with quotation marks and a specific header section.
This PR includes a minimum viable example for that use case that will be picked up by VS Code and cause the tests to run in parallel when triggered by the editor.
=> Extend description of running tests in parallel to include pyproject.toml example

docs/languages/dotnet.md
Updated the .NET getting started instructions to include the [.NET coding pack](https://code.visualstudio.com/learn/educators/installers) and the [.NET extension pack](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-pack).
=> Update .NET getting started instructions

release-notes/v1_71.md
'GitHub Codespaces' refers to the product as a whole, while 'a GitHub codespace' refers to a single instance
=> Consistently capitalize 'Codespaces' in 1.71 release notes

api/language-extensions/language-server-extension-guide.md
Since the description above this code is this:
> Below is a server implementation that uses the provided simple text document manager that synchronizes text documents by always sending the file's full content from VS Code to the server
I think that this line was misleading here. Or perhaps this description is not accurate
=> Fixed the description above the text sync example

docs/terminal/advanced.md, docs/terminal/basics.md, docs/terminal/images/advanced/envvarcollection-warning.png, docs/terminal/profiles.md
=> Terminal advanced usage page

docs/remote/create-dev-container.md
The `dockerfile` property in `devcontainer.json` is wrongly cased as `dockerFile`.
=> Fix typo: From dockerFile to dockerfile

docs/cpp/config-mingw.md
Updating the "Using GCC with MinGW" instructions page.  
Accounts for the removal of steps on MSYS2's Getting Started page, which is a dependency that these instructions rely on.
Without this change users following these instructions would be unable to compile C++ when using the default launcher specified by these instructions.  As these instructions acknowledge this is not meant to teach anything about GDB, MinGW, etc. so we can't expect the people using this page to correct this small gap on their own when following the instructions.  
Not sure if VS Code depends on all of these packages.  Might be able to get by on some minimal subset of packages but just including all of them simplifies the instructions.  One issue this resolves is that VS Code expects gdb.exe to be in the bin folder …
=> Update mingw toolset instructions

docs/editor/accessibility.md
The accessibility section of the VSCode editor documentation has a list of recommended themes for [color vision accessibility](https://code.visualstudio.com/docs/editor/accessibility#_recommended-themes-for-color-vision-accessibility)
This PR adds [Pitaya Smoothie](https://marketplace.visualstudio.com/items?itemName=trallard.pitaya-smoothie) as another theme for colourblindness support and meeting WCAG criteria for contrast.
=> DOC - Add VSCode theme to  accessibility docs

docs/containers/choosing-dev-environment.md, docs/containers/quickstart-node.md, docs/cpp/cmake-linux.md, docs/cpp/config-clang-mac.md, docs/cpp/config-linux.md, docs/cpp/config-mingw.md, docs/cpp/config-msvc.md, docs/editor/userdefinedsnippets.md, docs/languages/csharp.md, docs/languages/dotnet.md, docs/languages/rust.md, docs/other/unity.md, docs/python/environments.md, docs/python/linting.md, docs/python/python-tutorial.md, docs/python/testing.md, docs/remote/create-dev-container.md, docs/remote/ssh.md, docs/remote/troubleshooting.md, release-notes/v1_17.md, release-notes/v1_60.md, release-notes/v1_69.md, release-notes/v1_70.md, remote-release-notes/v1_70.md, remote/advancedcontainers/configure-separate-containers.md, remote/advancedcontainers/connect-multiple-containers.md, remote/advancedcontainers/environment-variables.md
I kept seeing warnings related to invalid language names while building the website, and so I took a look at what language names were being used and changed them to fit ones listed in [linguist/languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).
For plain text, one can just use three backticks without specifying a language.
=> Fix language names

api/working-with-extensions/continuous-integration.md, blogs/2017/01/15/connect-nina-e2e.md, blogs/2020/02/18/optimizing-ci.md, docs/containers/debug-netcore.md, docs/containers/debug-node.md, docs/containers/debug-python.md, docs/containers/docker-compose.md, docs/containers/quickstart-aspnet-core.md, docs/containers/quickstart-python.md, docs/containers/troubleshooting.md, docs/editor/settings-sync.md, docs/python/python-tutorial.md, docs/remote/containers.md, docs/remote/create-dev-container.md, docs/remote/linux.md, docs/remote/ssh.md, docs/remote/troubleshooting.md, docs/remote/wsl.md, docs/sourcecontrol/overview.md, docs/terminal/shell-integration.md, release-notes/v1_70.md, remote/advancedcontainers/add-nonroot-user.md, remote/advancedcontainers/avoid-extension-reinstalls.md, remote/advancedcontainers/docker-options.md, remote/advancedcontainers/persist-bash-history.md, remote/advancedcontainers/reduce-docker-warnings.md, remote/advancedcontainers/start-processes.md
We use shiki as the highlighter, so the actual reference list is at [shiki/languages.md](https://github.com/shikijs/shiki/blob/main/docs/languages.md).
One thing to note is that the ssh-config name currently isn't recognized locally, but I'm hoping that updating shiki would help.
=> Round two of fixing language names

api/working-with-extensions/publishing-extension.md
The extension manifest shows `engines.vscode` https://code.visualstudio.com/api/get-started/extension-anatomy#extension-manifest. `vscode.engine` does not exist.
=> Should reference engines.vscode not vscode.engine

docs/getstarted/images/themes/built-in-themes.png, docs/getstarted/themes.md
On macOS, there isn't **Show Built-in Extensions** button. I need to search for `@builtin` to show them. So I added a separate instruction for the OS.
I can't verify whether the button is still there on Windows and Linux versions (no environment sorry).
=> Fix instructions to show builtin extensions

docs/python/environments.md
Just reverts https://github.com/microsoft/vscode-docs/commit/b420f4ff18a4e58a81d116ebc641c37b89375441
The Survey invite is no longer needed by the UX researcher
=> Revert change to present UX survey

docs/azure/deployment.md, docs/nodejs/images/azure/azure-tools.png, docs/nodejs/nodejs-deployment.md
@spboyer and I noticed that the Node.js deployment should be renamed to be in line with the names from #5660. We also think the current Azure deployment really should be the Node.js deployment page. So I moved that table to the Node.js page-- I think the TOC link still reroutes to the Azure page so that change still needs to be made.
Finally, tables were reformatted to match #5705 and #5714
=> Add Node.js Deployment page and reconfigure Azure Deployment

build/sitemap.xml
https://github.com/microsoft/vscode-docs/pull/5725 added content back to Deploy Node.js Apps topic at https://code.visualstudio.com/docs/nodejs/nodejs-deployment.
This PR adds it to the sitemap so search crawlers will see it
=> Add rehydrated Node.js deploy topic to sitemap

blogs/2022/09/15/dev-container-features.md, docs/devcontainers/containers.md, docs/devcontainers/devcontainer-cli.md, release-notes/v1_73.md, remote-release-notes/v1_73.md
This PR removes the preview tag from Features, pushes a bit more strongly towards the containers.dev site instead of repositories, and drives to the Features template.
We should make a few additional tweaks once we have a starter repo for Templates, but that's not done yet.
=> Misc clarifications and tweaks for dev container content

README.md, docs/azure/extensions.md
The "Node Pack for Azure" actually points to the Azure Tools extension pack, now mentioned above in the article after a recent PR.
=> Remove node pack

docs/editor/codebasics.md
This issue was raised in #26393 and fixed  in #135805. 
It got a shout out in the [October 2021 release notes](https://code.visualstudio.com/updates/v1_62#_thank-you:%7E:text=InsertCursorAbove/Below), but was never documented anywhere on the site.
Since it's not configured via a setting, has even less discoverability that someone would know to add this specific command to the keybind args.
Also asked about on Stack Overflow [How to avoid multi cursor on wrapped lines in VS Code?](https://stackoverflow.com/q/53283020/1366033)
=> Add info on logical lines

docs/python/tutorial-flask.md
I noticed the imports were out of order, so I ran [shed](https://github.com/Zac-HD/shed) on the sample code. It fixed the imports and also added the standard 2 lines between definitions at the global layer.
I think it's nice when sample code follows Pythonic conventions so that people don't get warnings from linters running in their editor when they try to use a sample.
Perhaps the ordering is intentional, however, given you later describe how to sort imports? That's on views.py file though, so that learning goal could still be achieved. Up to you!
=> Make flask sample code style more Pythonic

docs/remote/vscode-server.md
Server docs still contain paragraph with the link to the old sign up form to the private preview, this is no longer needed.
=> Remove outdated info about the VSCode server private preview

api/advanced-topics/remote-extensions.md, docs/devcontainers/containers.md, docs/devcontainers/create-dev-container.md, docs/remote/linux.md, remote/advancedcontainers/configure-separate-containers.md, remote/advancedcontainers/questions-feedback.md, remote/advancedcontainers/use-docker-kubernetes.md
- Remove mentions of vscode-dev-containers, point users to devcontainers/templates, devcontainers/features, and self-hosting
- Update terminology: "definition" -> "Template"
- Use latest syntax for referencing Features
- Remove mentions of Features being in preview
Fixes https://github.com/microsoft/vscode-docs/issues/5736
=> Update to latest dev container repos and terms

docs/containers/ssh.md
In my instance of VSCode, the command category is called "Docker Context**s**", plural.
=> Typo Docker Contexts: Use

docs/remote/troubleshooting.md
according [doc](https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH#authorized_keys), the file name should be `authorized_keys` 🤣
=> fix(docs): authorized_key -> authorized_keys

remote/advancedcontainers/develop-remote-host.md
Followup PR from https://github.com/microsoft/vscode-docs/pull/5488#issuecomment-1329792728
@gregvanl @ghogen
I forgot to mention, but the Remote - Containers extension has already been updated to support this new setting, so both extensions should work nicely right now.
=> Update other reference to `docker.host`

docs/datascience/jupyter-notebooks.md
You can see the command here without the `Jupyter:` category prefix:
But if you type in the command as it appears in the docs, the command palette will return empty:
=> update jupyter command

blogs/2022/12/07/remote-even-better.md, docs/editor/command-line.md, docs/remote/tunnels.md, docs/remote/vscode-server.md
Commented this in an initial draft, but I didn't read carefully and it
seems to have survived. Port forwarding is different than tunnels (and
has no inherent security, where our tunnels do.)
=> remove mentions of port forwarding from tunnels

build/sitemap.xml, release-notes/v1_75.md
Also take out the download links from the Insiders snapshot since 1.75 isn't available yet but people still seem to find the page
=> add new topic to sitemap, update milestone query

release-notes/v1_75.md
For the Insiders 1.75 release notes placeholder, add the December plan and update to the renamed January issue query.
=> Add Dec plan, update Jan query

api/references/commands.md
This patch improve built-in commands description, including:
- Update description for call hierarchy since https://github.com/microsoft/vscode/issues/167717 fixed
- Add new API description for `type hierarchy`
- Update other APIs according to [API file](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostApiCommands.ts)
fix #5826
=> Update built-in commands

docs/remote/tunnels.md
Fixes a minor typo, and also adds a note to clarify that if the tunnel is enabled from the VS Code UI on the remote it will only remain available while VS Code is running there.
=> Clarify that closing remote VS Code closes tunnel; fix typo too

docs/remote/troubleshooting.md, docs/remote/wsl.md
The correct error name is `EACCES`, unintuitively.
=> Fix typo, EACCESS -> EACCES

docs/setup/windows.md
@deepak1556 I suggest to make an FAQ entry for running as admin on AppLocker that we can link to from the error message in the command line. Could you see if there are more details to fill in?
//cc @gregvanl
=> add applocker note when running as admin

docs/cpp/c-cpp-properties-schema-reference.md
This PR enhances the documentation about the `configurationProvider` option specified inside `c-cpp-properties.json` by introducing the requirement for an extension to become a `configurationProvider` candidate.
Not sure how to name https://github.com/microsoft/vscode-cpptools-api properly, so I just call it vscode-cpptools-api.
Fixes #5816
=> c-cpp-properties-schema-reference.md: configurationProvider: mention vscode-cpptools-api

docs/python/settings-reference.md
There is a duplicate `"reportPropertyTypeMismatch"` in Value. `"reportFunctionMemberAccess"` was not in the documentation, but seems to fit there.
=> Fix missing reportFunctionMemberAccess

api/references/when-clause-contexts.md
Fixes https://github.com/microsoft/vscode/issues/166647
Also call out the difference between view containers (viewlets) and views for the when clause conditionals.
=> Add when clause view IDs

api/references/extension-manifest.md
vsmarketplacebadge.apphb.com is currently not supported and is replaced with vsmarketplacebadges.dev . More details in microsoft/vscode-vsce#799 . Updating the document due to this change.
=> Update Approved Badges

blogs/2022/11/28/vscode-sandbox.md
cherry-picked from vscode-docs vnext
=> sandbox - remove statement about electron not supporting node.js

api/references/contribution-points.md
`gitMagic.blame.heatMap.enabled`  will be rendered as `Heat Map`, not `Heatmap`.
=> Fix spacing

api/extension-capabilities/common-capabilities.md
Link `/api/references/vscode-api#vscode.window.showOpenDialog` on current page points to a non-existent anchor `#vscode.window.showOpenDialog` on page `/api/references/vscode-api`.  Correcting it to point to an existing anchor: `#window.showOpenDialog`.
Also fixing link text `vscode.window.showOpenDialog` to be similar to other names on the page like `window.showInformationMessage`, `window.createOutputChannel`, etc.
Although it might be better to return all texts to the prefix `vscode.` for clarity.
=> Fix broken anchor and correcting link text to match other link texts

docs/languages/images/python/python-debugging-placeholder.png, docs/languages/images/python/python-linting-placeholder.png, docs/languages/python.md
A recent change to the website caused two Python .mp4 videos to no longer play.
Applying the same HTML as used with other videos (Java docs for example) fixes the issue
=> Fix Python mp4 videos

docs/cpp/faq-cpp.md
Considering that the Intellisense question & browse path/include path question are the most clicked, adding those to the top of the list in our FAQ.
=> Reordering link list based

docs/languages/rust.md
- The old command: `rust-analyzer.checkOnSave.command` is no longer a valid command with the current version of the rust-analyzer vscode extension.
- To achieve the desired result without a invalid type error the command used must be: `rust-analyzer.check.command`
=> Update Rust Linting Check on Save Command

docs/python/testing.md
Make updates that I think will help clarify these docs to users. In response to a docs reading meeting the python team had to review docs.
=> python testing doc update

docs/python/python-tutorial.md
Providing updates to the Python tutorial page.
=> Updates to Python Tutorial v2

api/advanced-topics/remote-extensions.md, api/extension-capabilities/common-capabilities.md, docs/remote/troubleshooting.md
As the `globalStoragePath` and `storagePath` properties are deprecated, I've updated it to use the new `globalStorageUri` and `storageUri` properties.
=> Updating the deprecated storagePath to storageUri

docs/editor/intellisense.md, docs/languages/cpp.md, docs/languages/csharp.md, docs/languages/java.md, docs/languages/javascript.md, docs/languages/json.md, docs/languages/overview.md, docs/languages/python.md, docs/python/editing.md
This helps avoid a line break in the pages right navigation list and also recommended writing practice to avoid gerunds in headers
=> Avoid gerund and shorten header

blogs/2016/12/12/roundup-customize.md, docs/languages/images/python/feature_showcase.mp4, docs/languages/images/python/python-snippets.mp4, docs/languages/python.md, docs/nodejs/images/nodejs-debugging/restartFrame.gif, docs/nodejs/nodejs-debugging.md
Just remove a video from an old 2016 blog post (100 page views since November).
The python videos were already in Git LFS (?) so update the links (tested building the site locally).
Also remove a couple unused .mp4's
=> Prefer keeping all videos in Git LFS

release-notes/v1_76.md
This adds a 1.76 release notes placeholder for the Insiders build but not shown in the website TOC (Order: is empty).
=> 1.76 release notes placeholder for Insiders

docs/setup/windows.md
Remove link to upstream bug since it is not relevant to end users, we already have link VSCode issue that users can follow for updates.
/cc @bpasero
=> chore: rm chromium bug info from applocker section

api/extension-guides/tree-view.md
Describing the `id` field as `the name of the new view container` is imprecise. Instead, it should be `the id of the new view container`.
=> Improve description of the `contributes.viewContainers` id property

docs/supporting/faq.md
Recommend telemetryLevel since it takes precedence over `enable-crash-reporter` in the runtime configuration.
=> Update disable crash reporting section

docs/python/images/testing/pytest-annotation-code-action.png, docs/python/images/testing/pytest-fixture-autocomplete.png, docs/python/images/testing/pytest-inferred-parametrized-argument.png, docs/python/settings-reference.md, docs/python/testing.md
This feature is now on the latest Pylance stable version: https://devblogs.microsoft.com/python/python-in-visual-studio-code-february-2023-release/#preview-improved-intellisense-support-for-pytest-with-pylance
=> Add pytest fixtures support with Pylance

api/language-extensions/snippet-guide.md, docs/editor/userdefinedsnippets.md
=> Update command name

docs/editor/command-line.md, docs/editor/images/profiles/create-profile-via-manage.png, docs/editor/images/profiles/create-profile.png, docs/editor/profiles.md, remote/advancedcontainers/start-processes.md
Outline for User Guide Profiles topic
=> Profiles topic

docs/python/editing.md, docs/python/environments.md, learn/develop-cloud/overview.md
Fixes https://github.com/microsoft/vscode-docs/issues/5954
I think the only explicit mention was in the Black formatter section but cleaned up a couple Python versioning examples as well.
=> Remove mentions of Python 2

.pipelines/templates/jobs/build.yml
CI broke at https://dev.azure.com/monacotools/Monaco/_build/results?buildId=203868&view=results due to an indentation issue.
=> Fix indent fail to unbreak CI

docs/languages/rust.md
This was removed in favour of the `onUnlessPressed` and `offUnlessPressed` options in Code.
=> Remove mention to outdated command in the inlay hints section of the Rust tutorial

release-notes/v1_76.md
Remote indicator is a LEFT end of Status Bar, not the right end.
=> Describe remote indicator position correctly

docs/devcontainers/images/tutorial/dev-containers-commands-simple.png, docs/remote/images/ssh-tutorial/remote-commands-simple.png, docs/remote/images/wsl-tutorial/wsl-commands.png
Based on endgame feedback I made a change to the remote indicator to only show the `Install Additional Remote Extensions` command if there are additional recommended remote extensions to be installed. 
In our docs screenshots we always show all 6 extensions' commands, so I'm updating them again to reflect the latest (one less item in the remote indicator).
=> Update remote indicator images

blogs/2021/06/10/remote-repositories.md
@bhavyaus pointed out it may be confusing if users find our blog post before our doc, so let's link to the doc from the blog.
=> Add doc note to GitHub Repos blog

docs/containers/app-service.md, docs/containers/overview.md, docs/containers/quickstart-aspnet-core.md, docs/containers/quickstart-container-registries.md, docs/containers/quickstart-python.md
/cc @ghogen @gregvanl. Adding some docs for the new [Deploy to ACA feature](https://github.com/microsoft/vscode-docker/issues/3535) in the Docker extension. Whereas the "Deploy to App Service" feature does _not_ require the AppSvc extension, the "Deploy to ACA" feature _does_ require the ACA extension. If it is not present, you'll be prompted to install it, and taken to the extension install page automatically if you accept. I tried my best to phrase the prose talking about that to make the distinction clear.
Please hold off on merging until our 1.24.0 release, tentatively planned for 22 Feb.
=> Add info about deployment to ACA from Docker

api/language-extensions/programmatic-language-features.md
the example code of [`Format Source Code in an Editor`](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#format-source-code-in-an-editor) doesn't match current version.
```Typescript
provideDocumentFormattingEdits(document: TextDocument, options: FormattingOptions, token: CancellationToken): ProviderResult<TextEdit[]>;
```
for now
=> Update formatting example

docs/languages/rust.md
While following the tutorial on macOS, I installed the first listed extension and had to look up why the debugger wasn’t working (giving the "MIDebuggerPath" error). A small addition like that could probably help other noobs in compiled languages like me :)
=> Add clarification for debugger extension per OS

docs/python/editing.md, docs/python/settings-reference.md
For https://github.com/microsoft/vscode-python/issues/20267
=> Update Python settings references

docs/devcontainers/containers.md
Fixes https://github.com/microsoft/vscode-docs/issues/6094.
@chrmarti @hediet thanks for sharing this feedback, it makes a lot of sense to me too. 
I agree just listing 3 quick starts may be confusing or overwhelming, i.e. which do I pick? Do I need to complete them all in order? I added a `## Picking your quick start` section at the top to provide further context. I also numbered each quick start as that feels a bit easier to parse (I can quickly see there are 3 quick starts, rather than not knowing if there are 1, 5, 10, or more).
I removed the [Working with Containers](https://code.visualstudio.com/docs/devcontainers/containers#_working-with-containers) header as it felt confusing to have this so early and feels like it may direct users to leave the page. I moved its couple of …
=> Update dev container doc based on feedback

docs/sourcecontrol/images/overview/merge-conflict.png, docs/sourcecontrol/images/overview/merge-editor-overview.png, docs/sourcecontrol/overview.md
Fixes https://github.com/microsoft/vscode-docs/issues/5618
=> Adds merge editor docs

api/references/activation-events.md
This shipped a bit ago which is why the PR is in to main instead of vnext.
cc @joyceerhl
=> Add call out for `onLanguage` wildcard

docs/languages/images/python/native-jupyter.png, docs/languages/python.md, docs/python/tutorial-flask.md
For https://github.com/microsoft/vscode-python/issues/20267
This PR:
- Updates Install Python section under the Python language topic (cc @cwebster-99)
- Updates the Jupyter section under the Python language topic (cc @minsa110) 
- Updates the Flask tutorial to try to clarify how to set FLASK_APP in PowerShell, giving a lot of folks seem to be having issues ehre https://github.com/microsoft/vscode-docs/issues/1881)
=> Update Python language section + Flask tutorial 

docs/languages/images/ruby/ruby_lsp_breakpoint.png, docs/languages/images/ruby/ruby_lsp_debugging_session.png, docs/languages/images/ruby/ruby_lsp_extension.png, docs/languages/images/ruby/ruby_lsp_extensions_view.png, docs/languages/images/ruby/ruby_lsp_inlay_hints.png, docs/languages/images/ruby/ruby_lsp_linting.png, docs/languages/images/ruby/ruby_lsp_quickfix.png, docs/languages/images/ruby/ruby_lsp_refactor.png, docs/languages/images/ruby/ruby_lsp_semantic_highlighting.png, docs/languages/images/ruby/ruby_lsp_status_center.png, docs/languages/images/ruby/ruby_lsp_symbols.png, docs/languages/ruby.md
Add a guide for the Ruby language in VS Code. The entry explains how to set up and use the Ruby LSP and is very similar to the Rust docs.
cc @isidorn
=> Add languages guide for Ruby

docs/languages/images/python/no-interpreter-selected-statusbar.png, docs/languages/images/python/selected-interpreter-status-bar.png, docs/languages/python.md, docs/python/environments.md, docs/python/images/environments/no-interpreter-selected-statusbar.png
Closes https://github.com/microsoft/vscode-docs/issues/6141
=> Update environments section under Python language

docs/languages/images/python/run-python-file-in-terminal-button.png, docs/languages/python.md
Closes https://github.com/microsoft/vscode-docs/issues/6138
=> Update Run code section under Python language

docs/languages/python.md, docs/python/editing.md
For https://github.com/microsoft/vscode-python/issues/20267 (follow up to https://github.com/microsoft/vscode-docs/pull/6142)
Because running code doesn't have much to do with editing, and we already have a "run code" section in our Python language docs page, I figured it'd be worth move the section there. This PR also tweaks the wording on a few bits of the editing docs.
=> Move run selection from editing docs to Python language docs

docs/containers/reference.md
This PR addresses this issue (https://github.com/microsoft/vscode-docker/issues/3801) by adding a sentence which clarifies that command customization is an alternative to tasks. In other words, they are not directly related.
=> Added Sentence to Clarify Separation between Tasks & Command Customization

release-notes/v1_78.md
Also remove the download links since 1.78 Stable isn't available yet
=> April plan to Insiders release notes placeholder

docs/editor/emmet.md
Fixes #6234
Using both 2 and 4 spaces for paragraph indentation causes incorrect indentation rendering on code.visualstudio.com
=> Use 2 space indentation through out emmet.md

release-notes/v1_78.md, release-notes/v1_79.md
Also add download links to 1.78 release notes, which was dropped accidentally
=> Add 1.79 release notes placeholder for Insiders

api/references/commands.md
Issue - https://github.com/microsoft/vscode-docs/issues/6258
Solution - Added the command for vscode.executeFoldingRangeProvider to the api/references/command.md web page
`vscode.executeFoldingRangeProvider` - Execute folding range provider.
* _uri_ - Uri of a text document
* _(returns)_ - A Promise that resolves to an array of FoldingRange instances.
=> Added the command for vscode.executeFoldingRangeProvider

docs/editor/tasks-appendix.md
Fix microsoft/vscode#182168
This PR applies the following updates on the `ProblemMatcher` interface definition:
- Adds `source` property.
- Updates `fileLocation` property (adds `search` method)
=> 🔨 Update `ProblemMatcher` interface definition

api/references/theme-color.md
This PR addresses a minor typo in the description for `listFilterWidget.shadow`. You can find the specific location of the typo [here](https://github.com/microsoft/vscode-docs/blob/e5602c94a51f0c705684f62e70ba4b792cbf4a19/api/references/theme-color.md?plain=1#LL183C4-L183C27). I discovered this _"issue"_ while working on a new theme from scratch and wanted to ensure the documentation is flawless. Thank you for reviewing!
EDIT: May I also mention that... I wish I could submit a PR for `microsoft/vscode-website` itself. The sidebar on the right-side (nav element, with the id `docs-subnavbar`), in a desktop view, isn't scrollable. I'm not on the payroll... but surely there's a front-end engineer somewhere, sitting around, willing to do a quick fix. 😉
=> Correcting a Minor Typo in theme-color.md

.vscode/settings.json
- Added `markdown.copyFiles.destination` so VS Code creates files dropped into release notes in expected path (requires VS Code 1.79)
- Turned on `organizeLinkDefinitions` on save. This removes unused link definitions and sorts the remaining definitions
=> Enable a few more markdown language features for repo

docs/nodejs/angular-tutorial.md
"it's" is short for "it is", which is not right. "its" is correct here because that's the possessive word.
=> Remove apostrophe from "it's" for possessive use

docs/datascience/jupyter-notebooks.md
While watching VS Code Day 2023 on Youtube, I heard about the option to use notebooks in VSCode. Exciting! 
Thanks for the great presentation, @minsa110 🚀 ✨ 
I went to the docs to learn more (as I could not remember) and found some inconsistencies. I hope you like my changes.
Focus: 
- click vs click on (this is what I started with, as usual, just two places :)
- capitalization (Jupyter Notebook(s) vs notebook(s))
- active vs passive voice
- shortcut code formatting using the kbstyle tag
- usage of the term "keyboard shortcut" / "the xyz key"
=> Fix style inconsistencies in Jupyter Notebooks docs

docs/python/images/jupyter/jupyter-running-remotely.png
Fixes #5806
Opted to just mask the URI since so much of the section talks about remote Jupyter servers on other computers.
=> mask the remote Jupyter server URI

docs/getstarted/locales.md
Available from @microsoft in Marketplace at https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-hu, but seems to be missing from https://code.visualstudio.com/docs/getstarted/locales#_available-locales.
=> Adds Hungarian to Available locales

docs/terminal/shell-integration.md
=> Update OSC 633 E docs to include nonce

docs/terminal/advanced.md
This should be merged _after_ 1.79 is released.
Fixes #https://github.com/microsoft/vscode-docs/issues/6361
=> Add section on terminal images

docs/editor/artificial-intelligence.md
Based on the latest https://code.visualstudio.com/updates/v1_79#_use-copilot-chat-in-stable-vs-code.
=> Remove mentions of VS Code Insiders for Copilot

docs/editor/artificial-intelligence.md
Mention GitHub Copilot in the page title to improve SEO to direct to this article rather than the blog post
=> Add mention of Copilot for SEO

release-notes/css/inproduct_releasenotes.css, remote-release-notes/css/inproduct_releasenotes.css
Ref https://github.com/microsoft/vscode/pull/185801
This removes the overrides on font styles to ensure our markdown looks the same in different areas of the product. It also improves readability by setting a max width on the content and centering it, similar to gh.com.
cc @mjbvz
=> Polish in-product release notes markdown styles

blogs/2023/03/30/vscode-copilot.md, docs/editor/artificial-intelligence.md, docs/editor/images/artificial-intelligence/copilot-ext-pre-release.png
Update based on https://github.com/orgs/community/discussions/59964, as Copilot Nightly has been replaced by the pre-release version of the main GitHub Copilot extension.
@gregvanl @isidorn @sandy081 let me know if you have any feedback on the updates here, especially on the image and link I added. I'm debating linking to https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions to help users understand pre-release extensions, but since the article is extension publishing focused, I linked to the release notes on pre-release extensions to start.
=> Update Copilot docs with pre-release info

blogs/2023/03/30/vscode-copilot.md, docs/setup/windows.md, release-notes/v1_77.md, release-notes/v1_78.md, release-notes/v1_79.md
Update release notes for latest GitHub Copilot extension installation (works in VS Code stable, use pre-release version instead of deprecated GitHub Copilot Nightly extension)
Add link to AI Tools in VS Code article from Chris' hugely popular blog post
Revert H2 change in https://github.com/microsoft/vscode-docs/pull/6452 to avoid breaking any external bookmarks.
=> Follow up edits

docs/editor/settings-sync.md
This was the correct value all along but it was a typo.
=> kde -> kwallet

docs/editor/settings-sync.md
Just `kwallet` is some really old implementation. We want `kwallet5` here which is known to work.
Fixes https://github.com/microsoft/vscode/issues/187436
=> fix kwallet name

docs/datascience/notebooks-web.md, docs/editor/editingevolved.md, docs/python/testing.md, docs/terminal/advanced.md
Hey :wave:,
This PR will fix :
1 typo in `docs/datascience/notebooks-web.md`
1 typo in `docs/editor/editingevolved.md`
1 typo in `docs/python/testing.md`
1 typo in `docs/terminal/advanced.md`
Best!
=> docs: fix typos

docs/editor/settings-sync.md
Related to https://github.com/microsoft/vscode/pull/187402, this makes the necessary docs change.
This can be merged before that PR is merged, it informs users about the compatibility issue with KDE 6, which that PR will fix.
The neon-specific instructions will only apply after the PR is merged, but I thought it would make sense to already add them so users can take these steps in advance.
=> Add more information about KDE 6

docs/editor/artificial-intelligence.md, release-notes/v1_80.md
Also changed docs.github.com Copilot link to go to VS Code documentation tab
=> Add themes used in 1.80 release notes

docs/editor/settings-sync.md
Remove underscore in relative header link as this results in broken link on code.visualstudio.com
Switch to using H4 headers for the two configure sections so they render better on code.visualstudio.com and are linkable.
=> Change header to H4, fix header link

docs/languages/markdown.md
Currently this is only documented in release notes
Also documents that you can copy-paste to insert markdown images and links
=> Document the markdown.copyFiles.destination setting

docs/supporting/faq.md
In the FAQ document, the link for "enter issues and feature requests directly in our [GitHub repository]" doesn't link to issues. It links to the guide to Contributing to the project, `CONTRIBUTING.md`. This edit changes the link.
=> changed GitHub Repo link from CONTRIBUTING.md  to issues

docs/setup/linux.md
Checked locally that `code-insiders` is present in the repository.
As such, just adding it to the documentation so that the next to read it know it is there :smile: Like it is available for other methods to install.
=> Add to Yum/DNF the same comment about code-insiders than the other methods

docs/editor/accessibility.md, docs/languages/cpp.md
Also fix a kbstyle() formatting typo.
Follow up C++ language refresh PR https://github.com/microsoft/vscode-docs/pull/6534
Here's the tutorial button layout:
=> Tune the C++ tutorial buttons

docs/containers/debug-common.md, docs/containers/debug-netcore.md, docs/containers/images/debug/debugger-scaffolding.png
I made a new PR per @gregvanl's request to use Git LFS since I will be committing an image. 
It's identical to https://github.com/microsoft/vscode-docs/pull/6521 but uses LFS to keep the repo size small. 
TODO: address all comments
=> Add Documentation for .NET SDK Container Build (with Git LFS)

.pipelines/templates/jobs/build.yml
Requires the website lint step to be merged first.
=> Add lint step

api/references/contribution-points.md, api/ux-guidelines/walkthroughs.md
Adds info and links to the Visual Studio Code Color Mapper Figma plugin to:
- API reference for `walkthroughs`
- UX guidelines
=> Add links to walkthrough image color mapper plugin

docs/python/data-science.md, docs/python/debugging.md, docs/python/editing.md, docs/python/environments.md, docs/python/formatting.md, docs/python/jupyter-support-py.md, docs/python/linting.md, docs/python/python-on-azure.md, docs/python/python-web.md, docs/python/settings-reference.md, docs/python/testing.md, docs/python/tutorial-create-containers.md, docs/python/tutorial-django.md, docs/python/tutorial-flask.md
cc @rchiodo @cwebster-99 
This PR:
- Moves "Formatting" out of editing.md into its own page in the docs (just like Linting)
- Changes the order of other doc pages so formatting goes right after linting
-  Moves "Troubleshooting IntelliSense" to the end of the editing.md file
- Adds a new subsection with some Pylance diagnostics and how to fix them
=> Add section with Pylance diagnostics

docs/datascience/jupyter-kernel-management.md, docs/python/editing.md, docs/python/formatting.md
Shorten Python formatting topic H1 header to avoid a line break.
Bump DateApproved.
Remove locale from docs.github.com URLs
Avoid gerunds in H2 headers
=> Formatting for recent edits

docs/containers/quickstart-python.md
Updates two links on the python quick start guide currently 404ing:
* https://github.com/microsoft/python-sample-vscode-django-tutorial/tree/tutorial
* https://github.com/microsoft/python-sample-vscode-flask-tutorial/tree/tutorial
=> Update python quickstart links.

blogs/2022/07/07/vscode-server.md
We've found folks are still referencing https://code.visualstudio.com/blogs/2022/07/07/vscode-server for the latest on the server and tunneling. I propose we leave the guidance in-tact as we consider blogs a point-in-time reference, and we add a link to our latest blog and/or docs.
=> Add update note

docs/supporting/requirements.md
We primarily want to support what Apple supports. Note that this doesn't mean we won't ship fixes for older versions of macOS, just we may not necessarily and they are typically lower priority than the supported versions.
Related microsoft/vscode#184713
=> Clarify macOS support policy

api/extension-capabilities/overview.md
Plural is used in the title. Changed it to singular :)
=> fix typo in extension-capabilities overview

api/references/contribution-points.md
Available since February 2021 (see https://github.com/microsoft/vscode/issues/117259)
=> Document `editor/title/run` menu contribution point

docs/cpp/config-clang-mac.md, docs/cpp/config-linux.md, docs/cpp/config-mingw.md, docs/cpp/config-msvc.md, docs/cpp/config-wsl.md
Fixes #6596
Update debug steps to no longer include the removed images and slight rewording as done in https://github.com/microsoft/vscode-docs/pull/6491
Also reverting a change in 6491. While we prefer "select" over "click" when possible, the UI gesture for setting a break point is to "click on the editor margin", not "select"
=> Fix broken images, match MinGW debug steps

docs/editor/artificial-intelligence.md, docs/editor/images/artificial-intelligence/switch-to-pre-release.png
Pre-release is no longer required so moving that mention down to avoid interrupting the call to action flow.
=> Move mention of Copilot pre-release down to FAQ

api/extension-guides/webview.md
=> fix: update example code for webview local content loading to fix passing parameters of incorrect type

api/references/extension-manifest.md
the vscode-extension-telemetry package is outdated
=> fix: update outdated package link

docs/cpp/config-mingw.md, docs/languages/cpp.md
With UCRT being added in our extension (among other MSYS versions) as noted in our [changelog](https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2) we now need to update our docs to support UCRT as the default minGW installation version.
=> Adding UCRT support for MinGW

docs/terminal/advanced.md
Part of microsoft/vscode#39137
=> Document hideOnStartup setting

docs/cpp/config-mingw.md, docs/devcontainers/containers.md, docs/languages/cpp.md
Fixes the syntax names used for highlighting so that shiki can highlight the blocks properly.
=> Fix highlight lang names

docs/editor/profiles.md, docs/getstarted/images/themes/colorthemes.png, docs/getstarted/images/themes/preferred-color-themes.png, docs/getstarted/themes.md
Refresh image and use Solarized Dark as the example
Also remove obsolete references to Dark+ Experimental in Profiles example
=> Refresh color themes for Dark Modern

api/extension-guides/webview.md
I followed the docs -- https://code.visualstudio.com/api/extension-guides/webview#webviews-api-basics
And I got this error.
The extension entry point is incorrect.
=> fix incorrect extension entry point

api/extension-guides/virtual-documents.md
=> virtual-documents.md: fix typo

api/get-started/your-first-extension.md
Walking through a test plan I had to create an extension. I couldn't figure out why I wasn't able to run the extension, turns out `extension.ts` needs to be open.
=> extension: Better explain how to start debugging

api/references/contribution-points.md
The current link to json-schema.org leads to a 404 page.
I updated it to the overview page of json-schema.org.
=> update json schema link

.pipelines/onebranch.buddy.yml, .pipelines/onebranch.official.yml
The vscode-docs pipelines are failing on a new Initialize Container step.
This PR switches the images to MCR ones.
=> Onboard onto MCR

docs/supporting/faq.md
This updates the FAQ to help users that have a blank screen after update.
Having experienced similar issues with Chrome on this hardware, it seems deleting the GPU cache is the best way to solve it.
I've only added the Linux path here, because I don;t have a windows system and I wouldn't know where the GPUCache is stored,
=> faq: blank vscode delete GPUCache after update

docs/getstarted/settings.md
This would normally be done during end game week in vscode-docs vnext but catching up from vacation.
Adding new 1.83 settings
Shortening some descriptions to keep /docs/getstarted/settings.md from getting too long and unreadable.
Typos and a little formatting (ending periods to description sentences)
=> Update 1.83 settings

docs/remote/troubleshooting.md
The Quick start section has commands to set up key based authentication where most of the commands used a ed25519 key, but the ssh-keygen command uses rsa. Someone following the commands exactly will encounter a problem when trying to copy the id_ed25519 key when it does not exist (but id_rsa will).
=> Properly use ed25519 throughout SSH keys guide

docs/languages/markdown.md
This pull request corrects the typo "selcting" to "selecting" in the Markdown file. I kindly request the repository maintainers to review and merge it.
=> docs: fix typo in docs/languages/markdown.md

docs/editor/workspace-trust.md
This pull request corrects the typo "unknowningly" to "unknowingly" in the Markdown file. I kindly request the repository maintainers to review and merge it.
=> docs: fix typo in docs/editor/workspace-trust.md

docs/terminal/basics.md
This pull request corrects the typo "layed" to "laid" in the Markdown file. I kindly request the repository maintainers to review and merge it.
=> docs: fix typo in docs/terminal/basics.md

blogs/2023/03/30/vscode-copilot.md, build/sitemap.xml, docs/csharp/cs-dev-kit-faq.md, docs/editor/github-copilot.md, docs/editor/intellisense.md, docs/languages/cpp.md, docs/languages/csharp.md, docs/languages/java.md, docs/languages/javascript.md, docs/languages/overview.md, docs/languages/python.md, docs/python/editing.md, docs/sourcecontrol/github.md, release-notes/v1_75.md, release-notes/v1_77.md
The follow up will be to add a redirect from docs/editor/artificial-intelligence to /docs/editor/github-copilot to handle any existing URL bookmarks
=> Rename "AI Tools in VS Code" to "GitHub Copilot"

api/extension-guides/webview.md
Adds a missing "than" to the webview documentation.
=> docs: fix webview doc typo

docs/python/debugging.md
Resolves #6722.
Let me know if I need to make any changes.
=> Use generic name for program path example

api/extension-guides/scm-provider.md
The screenshot immediately after this change would benefit from an update. It shows an outdated view title; SOURCE CONTROL PROVIDERS is now SOURCE CONTROL REPOSITORIES (noted in the updated text) as well as old Activity Bar icons, no blue Commit button and capitalized CHANGES header. Nor does it even show an open `scm/sourceControl` context menu on one of the four repositories in that view.
=> Clarify where the `scm/sourceControl` menu appears

api/index.md, blogs/2022/10/04/vscode-community-discussions.md
Use direct link instead of deprecated aka.ms link
Fixes #6772
=> Update dev community slack channel

docs/editor/settings-sync.md
These don't work, and require a lot of work to work... so let's call it out.
=> Add callout that Sovereign Cloud accounts don't work

docs/editor/github-copilot.md, docs/editor/images/artificial-intelligence/chat-in-panel.png, docs/editor/images/artificial-intelligence/open-session-in-editor.png, docs/editor/images/artificial-intelligence/open-session-in-sidebar.png
There is an earlier example of moving the Chat view to the Secondary Side Bar earlier so show example moving to the Panel region
=> Add section on moving the Chat view

docs/cpp/config-mingw.md
Spelling (previously "toochain") now edited to "toolchain".
=> Fix grammatical error in line 69

docs/editor/codebasics.md
`editor.find.seedSearchStringFromSelection` now accepts `"always"`, `"selection"`, or `"never"`, not a boolean value.
=> Update a sample value of `seedSearchStringFromSelection` compatible to the latest version

docs/csharp/debugging.md, docs/csharp/images/debugging/exception-settings.gif
The C# debugger docs were missing information on how to configure exception settings. This also removes usage of `https://aka.ms/VSCode-CS-LaunchJson`, as this repo should be the source of truth about debugger docs.
=> C#: Add debugger exception settings section

docs/devcontainers/containers.md, docs/devcontainers/images/containers/dotfiles.png
I was trying to get my dotfiles to work inside a dev container by following the recommended `settings.json` configuration in the published docs, which suggest using tildes to expand the install command path:
```json
{
"dotfiles.repository": "dslatkin/dotfiles",
"dotfiles.targetPath": "~/tmp-dotfiles",
"dotfiles.installCommand": "~/tmp-dotfiles/install.sh"
}
```
I noticed that I wasn't able to get my dotfiles to install and discovered the following output in my container creation logs:
```
[4536 ms] Setting current directory to ~/tmp-dotfiles
Could not locate ~/tmp-dotfiles/install.sh...
```
The following change _did_ work to install my dotfiles, however:
```diff
{
"dotfiles.repository": "dslatkin/dotfiles",
"dotfiles.targetPath": "~/tmp-dotfiles",
-   "dotfiles.installCommand": …
```
=> Fix recommended dotfiles install command

docs/terminal/basics.md
Arose from https://github.com/microsoft/vscode/issues/198275
=> Clarify that terminal view maximize requires Center panel alignment

docs/editor/accessibility.md, release-notes/v1_77.md, release-notes/v1_78.md
workbench.action.terminal.navigateAccessibleBuffer is replaced by "Go to Symbol in Accessible View" editor.action.accessibleViewGoToSymbol
=> Update Accessible View command ID

docs/csharp/debugging.md
=> Update warning icon to match check mark and red X

docs/editor/command-line.md, docs/editor/portable.md
The documentation for command line options stated that 2 options `--user-data-dir <dir>` and `--extensions-dir <dir>` did not work in Portable Mode, though this was not entirely accurate as the features were neither deprecates nor nonfunctional but did have special conditions for usage (they need no data folder to be present).
Related to this, some documentation made it unclear that `Microsoft VS Code/bin/code` was the recommended executable from which to launch vscode for command line arguments to function.
[Relevant issue with more detail](https://github.com/microsoft/vscode/issues/181876)
=> Add clarification for portable command line options behaviour oddity

docs/setup/linux.md
- Properly fix https://github.com/microsoft/vscode/issues/142912
- gvfs-trash has been deprecated and it is redirected to gio trash
- See https://manpages.debian.org/bullseye/gvfs-common/gvfs-trash.1.en.html
=> Update description on trash implementation

docs/editor/codebasics.md
Hi I found an unnecessary whitespace here, no whitespace in start region `//#region` that end region should also be consistent.
=> remove an unnecessary whitespace

docs/editor/github-copilot.md
With #6685 the second sub-bullet point has been removed, I think we can now inline it on a single bullet point.
=> Merged bullet points on Copilot Chat requirements

docs/devcontainers/containers.md, docs/remote/tunnels.md, remote/advancedcontainers/develop-remote-host.md
Missed these when updating the documention recently.
=> Dev Containers supports all host OSes

docs/containers/images/registries/github.png, docs/containers/images/registries/gitlab.png, docs/containers/overview.md, docs/containers/quickstart-container-registries.md, docs/containers/quickstart-python.md, docs/java/java-webapp.md
A couple of things in this PR.
- Azure Account is being slowly deprecated and replaced with the built-in Microsoft authentication provider. I could use some help with the verbiage here. The Azure Resources extension is required to sign in to some tenants (e.g., those with extra MFA after the primary sign-in) and is recommended (though not strictly required) if a sovereign cloud is being used.
- GitLab container registry support has been removed from the Docker extension (see https://github.com/microsoft/vscode-docker/issues/4132)
- GitHub container registry support has been added to the Docker extension (see https://github.com/microsoft/vscode-docker/issues/869)
Closes https://github.com/microsoft/vscode-docker/issues/4147
=> Azure Account -> Azure Resources and GitLab support removal, GitHub addition

api/references/when-clause-contexts.md
`quickFixWidgetVisible` seems to have been superseded by `codeActionMenuVisible`. The former doesn't exist in the current code base, while the latter was introduced about a year ago.
References:
https://github.com/microsoft/vscode/issues/55111
https://github.com/microsoft/vscode/blob/f0d15e28789098cbb6390f793d27e71a85fa5537/src/vs/platform/actionWidget/browser/actionWidget.ts
=> Replace quickFixWidgetVisible with codeActionMenuVisible

docs/editor/images/accessibility/high-contrast.png
Fix #6883 following given recomendations.
(Continued from #6886)
vscode version: 1.84.2
=> Update high-contrast theme image

docs/editor/userdefinedsnippets.md
The current text reads like you can escape $ and } where not strictly necessary, but according to VS Code's behaviour and https://github.com/microsoft/vscode/issues/201059 this is not the case - you may only escape the characters that are required to be escaped, otherwise you'll see backslashes in the output.
LSP PR: https://github.com/microsoft/language-server-protocol/pull/1868
=> Clarify snippet escaping rules

docs/nodejs/vuejs-tutorial.md
After the recent update for Vite and Vue 3, a couple of updates were missed.
The localhost port is now 5173 and the command to run the local server is `npm run dev`
=> Follow up Vue.js tutorial for new port and flow

docs/terminal/shell-integration.md
Fixes a typo:
> ... `code` **in** on the `$PATH` ...
Additionally, revises paragraph for conciseness
=> Fix typo and streamline language in documentation

api/working-with-extensions/testing-extension.md
When I ran the example file in `Testing Extensions` docs, it failed with `ReferenceError: after is not defined`. The test file looks like written in [TDD interface](https://mochajs.org/#tdd) of mocha. I think we need to use `suiteTeardown` hook instead of `after` hook (which is only available in BDD interface).
=> Fix example code in testing-extension.md

api/get-started/your-first-extension.md
Nowadays it is usually bad advice to install package globally and also not needed to just invoke a command once. So, it is better to use `npx` to invoke Yeoman here.
=> Use npx to invoke Yeoman

docs/remote/linux.md
Fixes https://github.com/microsoft/vscode-remote-release/issues/9449
I haven't updated the section ` Updating glibc and libstdc++ on RHEL / CentOS 6` for RHEL 7 distros since I haven't tested the flow and found the required package names.
=> docs: update supported distros for remote

docs/remote/images/wsl/wsl-installed-remote-indicator.png, docs/remote/images/wsl/wsl-local-installed-extensions.png
This PR fixes #6972 by renewing two screenshots that show the extensions pane in WSL. One of the two screenshots showed an extension that's deprecated (Debugger for Chrome).
=> Update WSL installed extensions screenshots

.pipelines/onebranch.official.yml
There's a new stage that shows up in the CI builds and it's always broken because it can't find tsaoptions.json.
This PR attempts to fix the issue by passing in an absolute path.
=> chore: pass absolute path to asyncSdl

.pipelines/onebranch.official.yml
I have confirmed that using an absolute path did not fix the build issue.
=> chore: disable asyncSdl to fix build

.pipelines/onebranch.official.yml
This reverts commit a0f1c2d8adbb4034411252704657db28b7206e8a.
It turns out we're not allowed to use an older upstream template.
=> Revert "fix: upstream broke our build again (#7031)"

docs/csharp/cs-dev-kit-faq.md
The colon was missing from the path meaning when copy/pasted the snippet would not work
=> Fix manual .NET installation for Windows example

api/working-with-extensions/bundling-extension.md
This is to fix the discrepancy of the bundle scripts. In other sections, e.g. `Using webpack`, the doc mainly uses `dist/extension.js` as the bundle file path. However, the script for esbuild uses `out/main.js`, which may cause confusions. 
I also tried to create a new project using the latest generator. It seems that the `package.json` uses `"main": "./out/extension.js",` by default, instead of `dist/extension.js`. This may cause more issues due to discrepancies.
It would be great to use an unified bundle path in all docs.
=> Update the bundle file location for esbuild scripts

api/working-with-extensions/publishing-extension.md
I noticed when you can add a `SUPPORT.md` to your extension, it will show a `support` link under the resources.
I have added the documentation for this in the **Marketplace integration** section
=> Added the support.md file documentation

docs/languages/identifiers.md
This identifier is used by the [OCaml extension](https://github.com/ocamllabs/vscode-ocaml-platform).
=> identifiers: Add OCaml

docs/nodejs/nodejs-debugging.md
=> docs: fix typo in node.js debugging page

docs/editor/emmet.md
I think a backslash is missing on this page.
Before:
After:
=> fix: backslash to escape special char in markdown table

api/working-with-extensions/testing-extension.md
The `glob` library used in the testing example docs has been updated to use `promise` instead of `callback` starting from version `v9.0.0`. This PR will update the documentation for these changes.
https://github.com/isaacs/node-glob/blob/v9/changelog.md#90
Thanks :)
=> docs: update `glob` usage in testing extension

api/references/activation-events.md
onView is only emitted by custom views, per microsoft/vscode#176805. It is additionally confusing that the documentation gives a couple of examples that cannot be applied because they are built-in views.
=> Explain onView activation event is not emit by built in views

docs/editor/images/intellisense/intellicode-usage-examples-v2.gif, docs/python/images/editing/intellicodeCompletions.gif, docs/python/images/editing/intellicodeCompletionsIntellisenseDriven.gif
Marketplace and docs pages are broken at the moment due to image files lost in repository migration.
This PR restores three images relating to IntelliCode Completions for Python and API Usage Examples.
=> Fix broken docs by rehosting images lost in migration away from intellicode-docs-pr

docs/getstarted/userinterface.md
`explorer.openEditors.visible` no longer allows 0
It was changed in https://github.com/microsoft/vscode/pull/181633
=> Remove the advise on setting `explorer.openEditors.visible` to 0 as it is no longer possible

docs/cpp/configure-intellisense-crosscompilation.md, docs/cpp/configure-intellisense.md, docs/cpp/cpp-ide.md, docs/cpp/cpp-refactoring.md, docs/cpp/customize-default-settings-cpp.md, docs/cpp/images/cpp/call-hierarchy.gif, docs/cpp/images/cpp/filesearch.png, docs/cpp/images/cpp/nested-calls-call-hierarchy.png, docs/cpp/images/cpp/parsing.png, docs/cpp/images/cpp/workspacesearch.png, docs/cpp/images/intellisense/AddingIncludePathToConfig.gif, docs/cpp/images/refactoring/copy-declaration-definition.gif, docs/cpp/images/refactoring/create-declaration-and-definition-different-files.gif, docs/cpp/images/refactoring/create-declaration-and-definition-same-file.gif, docs/cpp/images/refactoring/extract-method.gif, docs/cpp/images/refactoring/quick-fix-add-missing-includes.gif, docs/cpp/launch-json-reference.md
Updating the editing page to include more features that we support, reformatting, and doing an overall freshness pass. Also adding a lot of features of the extension which are split with a new refactoring page. 
Features add: 
- Go to Declaration 
- Go to References 
- Go to Type Definition 
- Call Hierarchy 
- Extract Method 
- Code Action: Add missing includes 
- Create Declaration/Definition
=> Freshness Pass Cpp Editing Page

docs/devcontainers/create-dev-container.md
Fixed the broken link for "Docker from Docker Compose". 
The documentation incorrectly pointed the link to a [404 page](https://github.com/devcontainers/templates/tree/main/src/docker-from-docker-compose). The link is corrected to [Docker Outside of Docker Compose](https://github.com/devcontainers/templates/tree/main/src/docker-outside-of-docker-compose).
=> Fixed broken link in 'Create a Dev Container' documentation

api/get-started/your-first-extension.md
Added a clarification of which command should be ran to start debugging the extension instead of only mentioning the key shortcut.
Added a hint to guide the reader to check if the vscode engine version is compatible with their installed version of VS Code.
=> docs(api): Update your-first-extension.md

docs/remote/vscode-server.md
- clarify the endpoints are in the links, these are not the endpoints
- change to links, instead of text
=> docs:  endpoint clarification

docs/datascience/jupyter-notebooks.md
A few people have been asking about which  launch.json configuration notebook debugging picks up. [e.g.](https://github.com/microsoft/vscode-jupyter/discussions/13394).
Across debugging, enough people ask about justMyCode that it is mentioned now in a tooltip when you skip a frame.  But there's nothing in the notebook docs about how to set it, which is different from the standard launch.json.   I assume since [debugging tests](https://code.visualstudio.com/docs/python/testing#_debug-tests) included this tidbit, at least something minimal would be desirable here too.
=> DOC: Debug notebooks uses settings, not launch.json configurations.

docs/editor/userdefinedsnippets.md
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_transform-examples
The second `^` is not needed
***
```jsonc
"name": {
"prefix": "name",
// "body": "${TM_FILENAME/[^0-9^a-z]//gi}"
"body": "${TM_FILENAME/[^0-9a-z]//gi}"
}
```
=> Unnecessary '^'

docs/languages/identifiers.md
This identifier is used by the [Svelte extension](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode).
=> identifiers: Add Svelte

docs/setup/linux.md
Utilized the principle of least privilege by elevating only the necessary command, `tee`, to write the repository configuration. This approach minimizes the scope of elevated privileges.
=> Change command to create repositories

remote/advancedcontainers/sharing-git-credentials.md
I recently encountered a problem related to the ssh agent forwarding and wasn't able to solve it until I stumbled upon this issue https://github.com/microsoft/vscode-remote-release/issues/8666 and saw that the solution was already mentioned in https://code.visualstudio.com/docs/devcontainers/containers#_known-limitations 
I feel that this section is somewhat hidden as the first documentation related to ssh agent forwarding in Dev Containers is https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials, and there was no mention of any potential issues, so I added a link to the `known limitations` sections in the `sharing-git-credentials` page.
Please let me know if this is useful.
=> Added link to known limitations in SSH agent forwarding documentation

api/extension-guides/webview.md
Currently the link navigates to https://code.visualstudio.com/api/references/contribution-points.md#contribution-points which 404s. The link without the `.md` works as expected: https://code.visualstudio.com/api/references/contribution-points#contribution-points
Looking a bit deeper there is not a [Document fragment](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#document_fragments) matching the `#contribution-points` part of the link so I removed it.
=> Fix Contribution Points link in webview Context menus section

api/references/commands.md, docs/customization/keyboard-shortcuts.md, docs/getstarted/keybindings.md, docs/getstarted/tips-and-tricks.md
The `editor.toggleFold` command is not documented anywhere, this PR adds it alongside the editor.fold and editor.unfold
=> Add toggle fold

docs/python/editing.md, docs/python/images/editing/change-spelling-code-action.gif, docs/python/images/editing/implement-inherited-abstract-classes.gif, docs/python/images/editing/move-symbol.gif, docs/python/images/editing/move-symbol.png, docs/python/images/editing/quickFix.gif, docs/python/images/editing/quickFix.png, docs/python/images/editing/search-imports-code-action.gif, docs/python/settings-reference.md
In this PR:
- Adding latest Pylance's code actions for add missing imports & implement abstract classes
- Adding a note that add import code actions don't support user symbol aliases
- Adding new Pylance setting to disable/enable auto indent
=> Update Python Editing docs with more code actions 

docs/python/python-quick-start.md
We noticed a PyCon that a gif was missing from the quickstart, so this PR fixes it
=> Fix missing image on quickstart tutorial

docs/editor/extension-marketplace.md, docs/editor/profiles.md, docs/editor/settings-sync.md, docs/getstarted/settings.md
Related to https://github.com/microsoft/vscode-docs/pull/7319
=> Specify extensions don't sync for remote

api/references/commands.md
This being missing from the docs cost me an hour or two! I only found it when I searched for other code using the API and found that about half of callers passed this fourth option.
While it's called columnOrOptions, I've only been able to get it to work with a vscode.TextDocumentShowOptions.
=> Document the fourth param to vscode.diff

docs/remote/linux.md
And setting useLocalServer is no longer required.
=> Mention Windows 11 support for SSH

remote/advancedcontainers/sharing-git-credentials.md
As documented in [this issue](https://github.com/microsoft/vscode-remote-release/issues/9217), newer versions of GPG use use-keyboxd for storing GPG keys, which is incompatible with the current implementation of vscode for sharing GPG keys with your dev container.
This pull request add a note to the bottom of "Sharing Git credentials with your container" that mentions this problem and offers a (temporary) workaround.
=> Add note about problems in newer gpg versions for sharing credentials with devcontainer

api/get-started/extension-anatomy.md
docs: correct instance of incorrect singularization ('description' -> 'descriptions')
=> docs: correct instance of incorrect singularization

docs/editor/refactoring.md, release-notes/v1_20.md
There's no "CodeActionProvided" API
=> corrected two typos ('CodeActionProvided API' to 'CodeActionProvider API')

docs/languages/images/ruby/navigation-placeholder.png, docs/languages/images/ruby/navigation.mp4, docs/languages/images/ruby/ruby_lsp_code_lens.png, docs/languages/images/ruby/ruby_lsp_symbols.png, docs/languages/ruby.md
The Ruby LSP project has evolved significantly since we added the first iteration of the documentation. This PR updates the docs to reflect the current state of features.
The summary of the changes are:
1. Included a section on navigation and intellisense, which we've been putting a lot of effort into. I added a video to showcase all features at a glance. Please let me know if the size/format is okay. I based it on the videos I found for the JavaScript docs
2. Updated the format of the version manager configuration, which we changed
3. Removed the code snippets section. It honestly doesn't add much value and we're planning on moving all of that to the server eventually so that completion is more accurate
4. Updated the debugging section to mention that the Ruby LSP now has a built-in …
=> Update Ruby documentation to reflect current state

api/references/contribution-points.md
It looks like TextDocument does not have (or no longer has) a `getLanguageId()` method
=> `TextDocument.getLanguageId()` changed to `TextDocument.languageId`

release-notes/v1_90.md
Was a bit surprised by the raw un-clickable link.
I reworded it a little and added a hyperlink.
=> docs: release v1.90: change raw link to hyperlink with descriptive text

docs/editor/images/testing/run-debug-tests-editor-gutter.png, docs/editor/images/testing/run-debug-tests-test-explorer.png, docs/editor/images/testing/run-tests-with-coverage.png, docs/editor/images/testing/test-coverage-view.png, docs/editor/images/testing/test-explorer-view-filtering.png, docs/editor/images/testing/test-explorer-view-test-results.png, docs/editor/images/testing/test-explorer-view.png, docs/editor/images/testing/test-results-panel.png, docs/editor/images/testing/testing-hero.png, docs/editor/images/testing/view-coverage-in-editor.png, docs/editor/images/testing/view-coverage-in-explorer.png, docs/editor/testing.md
Fixes https://github.com/microsoft/vscode-docs/issues/7208
=> Add Testing user guide outline

docs/copilot/images/copilot-chat/copilot-view.png
Add missing image for the Copilot Chat view that is referenced from the Copilot extension README.
=> Add Chat view image for marketplace

remote/advancedcontainers/set-docker-compose-project-name.md
Pointing to the more general section on docker.com since we now also support the `name` property in the `docker-compose.yml`.
Mentioning our override to avoid name collisions at the end.
=> Update project name section

api/extension-guides/language-model.md
Keeping `copilot-` in there breaks the extension response and sets the model to `undefined`.
=> Fix model names

api/references/icons-in-labels.md
The "snake" icon was sorted into the middle of the "symbol-*" icons.
=> Fix icon ordering.

release-notes/v1_90.md
All of these links are 404s, I didn't check all of them, so others may be wrong too
- updated link to bundling extensions guide
- updated link to web extensions guide
- updated link to extension esbuild sample
=> Update some links in v1_90.md

remote/advancedcontainers/sharing-git-credentials.md
as ssh-add does not persist in linux, the ssh-add command must be executed every time and should therefore be added to the snippet (see [this stackoverflow](https://stackoverflow.com/a/74704066) answer which led me to finding this).
Furthermore I found it annoying that `eval "cat $HOME/.ssh/ssh-agent"` echoes the PID of the ssh-agent and therefore polutes your terminal, therefore I suggest muting it's output.
=> Update linux ssh-agent snippet to include "ssh-add"

remote-release-notes/v1_92.md
- https://github.com/microsoft/vscode-remote-release/issues/7558
- https://github.com/microsoft/vscode-remote-release/issues/7369
- https://github.com/microsoft/vscode-remote-release/issues/9677
- https://github.com/microsoft/vscode-remote-release/issues/3906
=> Remote ssh 1.92

docs/cpp/cmake-linux.md
The "Create a CMake project" link on the page "docs/cpp/CMake-linux" was broken due to the incorrect `.md` extension at the end of the link.
I removed the `.md` extension so that the link works correctly and takes the user to the correct page.
The broken link can be found here: [Create a CMake project](https://code.visualstudio.com/docs/cpp/CMake-linux#_create-a-cmake-project)
=> docs(cmake-linux): Fix broken link to cmake-quickstart

api/references/activation-events.md
Complete the list of activation events by adding missing entries and a brief description of each.
Closes #5745 by completing the list.
Closes #6600 by documenting `onDebugInitialConfigurations` and `onDebugDynamicConfigurations` with the difference between them.
=> Add missing activation events

docs/cpp/colorization-cpp.md
Although enhanced colorization is enabled by default for C/C++, the JSON as currently displayed in the docs raises an IntelliSense warning for an invalid value due to incorrect capitalization. This groundbreaking commit changes "E" to "e" and restores balance to the VS Code Docs.
(I fully admit this is not the most substantial PR, but, as it fixes an invalid code snippet, I hope the correction is at least marginally helpful :joy_cat:)
=> Case-sensitive JSON correction

remote/advancedcontainers/sharing-git-credentials.md
microsoft/vscode-remote-release#10184
=> Remove obsolete workaround for GPG keyboxd

docs/editor/tasks.md
Currently, the `source` property is only mentioned under [Modifying an existing problem matcher](https://code.visualstudio.com/docs/editor/tasks#_modifying-an-existing-problem-matcher), but with no details, and it applies to more than just existing matchers.
It would be great to add it as part of the example as demonstrated in this PR, though it's incomplete: This also requires updating the screenshot below.
---
Related feature request I just opened on the VSCode repo: [QoL improvement: Show task `label` as source of problem if `problemMatcher` doesn't specify a `source`](https://github.com/microsoft/vscode/issues/225072)
=> tasks.md: add `source` property to `problemMatcher`

docs/editor/tasks.md
Currently, the `severity` property is only mentioned under [Modifying an existing problem matcher](https://code.visualstudio.com/docs/editor/tasks#_modifying-an-existing-problem-matcher), but with no details, and it applies to more than just existing matchers. (cf. #7493)
=> tasks.md: mention `problemMatcher.severity`

api/references/when-clause-contexts.md
Add missing inline code markup for context names in api/references/when-clause-contexts.md, and normalize column names.
=> Typo, add missing inline code markup

docs/datascience/images/jupyter-kernel-management/select-enter-server-url.png
Updated the enter Jupyter server URL screenshot in https://code.visualstudio.com/docs/datascience/jupyter-kernel-management#_existing-jupyter-server to reflect the new UI. 
Resolves #6433.
=> Update enter jupyter server url screenshot

api/working-with-extensions/publishing-extension.md
It appears pre release tags are not ignored but rejected. See https://github.com/microsoft/vscode-vsce/issues/1052
=> Remove incorrect statement about pre release tags

docs/languages/ruby.md
We just shipped a revamp of our [documentation website](https://shopify.github.io/ruby-lsp/) for the Ruby LSP and some of the links changed.
This PR just updates the links to reflect the new state.
=> Update Ruby links to point to new documentation

docs/editor/settings-sync.md
Another Flatpak/KDE5 wallet workaround, it worked well for me.  I think this is the more correct way to do it.
=> Another Flatpak/KDE5 wallet workaround

docs/python/python-tutorial.md
I have added a new Managing dependencies section illustrating the creation of requirements.txt file and reusing it while setting up another virtual environment.
=> Added new Managing dependencies section, fixed one typo

api/references/theme-color.md
Remove 2 properties, that are written twice in the theme-color.md
=> docs: remove double entries in theme color references

docs/getstarted/userinterface.md
Use youtube-nocookie.com/embed instead of youtube.com/embed to prevent YouTube from adding cookies to our website that violate internal cookie policies.
CC @ntrogh
=> fix: use youtube-nocookie for embeds

docs/python/testing.md
Previously we did not mention coverage and django test support was only supported if users are opted into the python test adapter experiment (which is currently running on 100%). Added in a tip for both of these sections to include this important information for users for the time being until this behavior is fully adopted. 
This also fixes the path for the coverage gif
=> Adding notes to Django and coverage docs section

README.md
Remove the link to the publishing instructions on our private vscode-website repo.
Resolves https://github.com/microsoft/vscode-docs/issues/7660
=> Remove publishing instructions from README

docs/csharp/testing.md
=> Added documentation for new Code Coverage in C# Fixes #7635

api/language-extensions/overview.md
Inside "API" outline, "LANGUAGE EXTENSIONS" section, "Overview" article, there is a paragraph on the top.
I was puzzled with sentence "VS Code doesn't provide built-in language support", because we have multiple language extension inside "extensions" at the root of VS Code codebase.
If I'm right, this pr would like to fix it to make this sentence clear~
=> doesn't provide built-in language support in the core editor

docs/remote/faq.md, docs/remote/ssh.md
The setting `remote.SSH.allowLocalServerDownload` is now deprecated and has been replaced by `remote.SSH.localServerDownload`.
=> Update Remote-SSH docs for deprecated setting

docs/editor/debugging.md
the location of debug toolbar has a limit `top` value of property of CSS, actually. As shown below: 
Perhaps it could be more fit for us to describe more for currently technically implement.
In addition, `editor` may not be appropriate because debug toolbar would appear outside the `editor`, therefore `window` could be right~
=> location is restricted in a limited area for debug toolbar as `floating`

docs/copilot/prompt-crafting.md
Some hash links are broken because of the title in the target markdown file has been changed
I think `inline-suggestions` is renamed as `Code-completions-in-the-editor`
But I'm not sure what is the `chat-features`'s target since the content has been changed a lot
=> fix broken links

docs/copilot/faq.md, docs/copilot/images/faq/account-preferences-quick-pick.png, docs/copilot/images/faq/copilot-extensions.png, docs/copilot/images/faq/extension-account-preferences.png, docs/copilot/images/setup/command-center-open-chat.png, docs/copilot/images/setup/copilot-chat-menu-command-center.png, docs/copilot/images/setup/copilot-status-menu.png, docs/copilot/images/setup/vscode-chat-view.png, docs/copilot/images/setup/vscode-status-bar-copilot-active.png, docs/copilot/setup.md
- Update Setup to reference the Copilot menu next to the Command Center and Chat view in Secondary Side Bar
- Update FAQ to include setting account preferences for switching GH account for Copilot
=> Refresh Copilot Setup and FAQ

api/get-started/extension-anatomy.md
This PR addresses [Issue #7787](https://github.com/microsoft/vscode-docs/issues/7787).
The current documentation states that extensions need to explicitly declare `onCommand` activation events. However, starting from [February 1, 2023](https://github.com/microsoft/vscode-generator-code/commit/366fa08fdaab957e3f1d2e63287899d76eaf6e5d), `yo code` no longer generates these entries, and VS Code Extension Examples removed them on [December 8, 2022](https://github.com/microsoft/vscode-extension-samples/commit/f7c3737b6e116c12e896c71dfe8e59ff3e8b9f3d). This inconsistency between the documentation and the generated project templates caused confusion and led to extra time spent figuring out the change.
This update adds a note to the "Extension Anatomy" section to clarify that `onCommand` …
=> Update Extension Anatomy with activation events note

api/extension-guides/color-theme.md
Our `color-theme` documentation of `Extensions Guide` has a little problem that could be wrong, `color` typically means fore color, but the following code was about background color which could be the right thing, as show below:
=> background color could be right

api/extension-guides/file-icon-theme.md
When I went through the `File Icon Theme` article tonight, I found that there is a code sample about defining an default icon for `latex` language, it seems to be un-completion. Let me complete it by enclosing the curly braces!
=> complete the jsonc code sample

docs/languages/identifiers.md
`dart` is a known language identifier but it is not currently listed as such in `docs/languages/identifiers.md`
=> Add Dart to Known Language identifiers

docs/csharp/debugging.md, docs/csharp/images/debugging/editor-run-debug.png
This PR adds in a section about how to run/debug your project via the editor window.
=> Add CDK Documentation for Editor Run/Debug buttons

docs/sourcecontrol/overview.md
Among the four git configs ([web link](https://code.visualstudio.com/docs/sourcecontrol/overview#_vs-code-as-git-difftool-and-mergetool)), two used 4-space indent and the other two used 2-space indent.
This PR unifies them to 4-space indent.
=> Unify indent spaces in a git config snippet

remote/advancedcontainers/sharing-git-credentials.md
This PR does two things:
1. Simplifies the `ssh-add` command in the tutorial (`ssh-add $HOME/.ssh/<your ssh key>` -> `ssh-add`)
2. Adds a note for enabling agent forwarding
=> sharing-git-credentials: Simplify `ssh-add`; Add note for enabling agent forwarding

docs/remote/linux.md
Bionic doesn't have a mention that it's missing glibc 2.28.
=> add what libraries are missing for bionic

docs/editor/codebasics.md
I added a short explanation of how to customize the auto save feature for specific language types in accordance with [this issue](https://github.com/microsoft/vscode/issues/234769), since the feature is currently not mentioned in the documentation or in the Settings GUI.
=> Add an explanation for auto saving based on specific languages/file types

release-notes/v1_96.md
I think should link to the specific JS/TS section here instead of the paste preferences settings
=> Fix toc link for JS/TS paste

release-notes/v1_96.md
A pretty minor thing, but the "&" jumped out at me, especially as it was inconsistent with the "and" in "drag and drop"!
=> Replace "&" with "and" in 1.96 release notes

docs/remote/remote-overview.md, docs/remote/ssh.md, docs/remote/tunnels.md, docs/remote/wsl.md
Clarify that the VS Code server installation on the remote system is managed by the client extension,
and independent of regular VS Code installations on the remote server.
fixes microsoft/vscode-remote-release#10523
which has already been closed.
That issue concerned remote-ssh; I have tried to also update the descriptions for tunnels and WSL, though I'm less sure of the latter.  Someone familiar with codespaces and containers might want to make similar changes for them, if appropriate.
=> Server is isolated

docs/csharp/debugger-settings.md
The console documentation had two issues that this PR addresses:
1. The `csharp.debug.console` setting is only used for console projects, but this was not called out in the documentation
2. The 'availability' section got moved into the 'Inputting text into the target process when using internalConsole', when it should have stayed in the 'Console (terminal) window' section
=> Add clarification to `csharp.debug.console` documentation

api/language-extensions/programmatic-language-features.md
Looks like the linked header was updated but not the link.
=> Fix a broken link

docs/cpp/config-mingw.md
There was some outdated information in the C++ MinGW guide.  I am updating the section discussing additional configuration options.
=> Update compilerPath information

api/extension-guides/language-model.md
Hi, there are 2 issues with the current documentation: 
1. `o1-preview` is not available as a model family, it is called `o1`.
2. `gemini-1.5-pro` is not available. 
See the following screenshot which returns from:
```
await vscode.lm.selectChatModels({
vendor: "copilot",
});
```
=> Update language-model.md with correct supported lm families

docs/languages/go.md
Use the new public domain go.dev over golang.org.
=> languages/go.md: update Go website link

docs/nodejs/browser-debugging.md
Replaces a mention of the option "host" for external hosts with "address".
=> Browser Debugging: Replace invalid reference to "host" with "address"

docs/remote/troubleshooting.md
As of my git `2.47.1.windows.1` from November 2024, the new name does not end in `core`. Took some research, please confirm!
=> Fix git credential manager for WSL

build/sitemap.xml, docs/editor/extension-marketplace.md, docs/editor/extension-runtime-security.md
Fixes https://github.com/microsoft/vscode-docs/issues/7874
=> Add extension runtime security article

docs/editor/codebasics.md, release-notes/v1_96.md
Fixes https://github.com/microsoft/vscode-docs/issues/7966
=> Add clarification for overtype mode

api/extension-guides/web-extensions.md, api/working-with-extensions/bundling-extension.md
I see no good reason to not display esbuild's warnings. This led me to:
https://github.com/evanw/esbuild/issues/4023
Also, when enabling `ts-check` in the provided example, there's a missing check for location being `null`. I fixed that too.
=> Tweak logLevel in esbuild.js examples

docs/editor/variables-reference.md
New predefined variable `${columnNumber}` is added in v1.97, but not documented. This PR adds its doc and example.
https://code.visualstudio.com/updates/v1_97#_column-number-variable
Also, the missing example of `${fileDirnameBasename}` is added, and the order of examples of `${fileDirname}` and `${fileExtname}` is swapped to align with that in section ["Predefined variables examples"](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables).
=> Document new predefined variable `${columnNumber}`

docs/python/testing.md
edit the testing documentation to include information about the new setting autoTestDiscoverOnSavePattern introduced here: https://github.com/microsoft/vscode-python/pull/24728.
=> add autoTestDiscoverOnSavePattern to python testing

docs/remote/faq.md
In preparation for https://github.com/microsoft/vscode/pull/235232
=> docs: update remote faq for unsupported server mode

docs/cpp/config-mingw.md
The wrong language ID `MSYS2` makes the copy button floating in an unexpected position
The URL is https://code.visualstudio.com/docs/cpp/config-mingw
=> correct markdown code block language ID for proper rendering

release-notes/v1_98.md
Added a full stop at the end, and changed to what I assume the sentence was supposed to say.
=> Fix Refined Snippet API in 1.98 release notes

docs/reference/variables-reference.md
The page https://code.visualstudio.com/docs/reference/variables-reference had some weird markup where the "Related resources" section was inside an example code block.
It seems that it was introduced here:
https://github.com/microsoft/vscode-docs/commit/85af33f44a4175578a4d00e3332409d43ae53a8f#diff-92a970470290ad4c8434cfa4028e81c09e079d6f126aba6e61e6bf2706ca7555R306-R310
So, this PR closes the code block
=> variables-reference: Close json code block

remote/advancedcontainers/docker-options.md
With the release of Dev Containers v0.399, there is no need to update a devcontainers.json to make it work with Podman (c.f. https://github.com/microsoft/vscode-remote-release/issues/10706).
And commands like “Dev Containers: Try a Dev Container Sample” and “Dev Containers: Clone Repository in Container Volume…” that used to fail with Podman are now fixed (c.f. https://github.com/microsoft/vscode-remote-release/issues/10706)
Also, some Podman details were outdated:
- Podman isn't Linux-only but currently supports Windows and macOS too
- Podman allows `Docker-from-Docker` now (in both rootless and rootful mode)
- Podman supports both Docker-Compose and Podman-Compose (with a priority for Docker-Compose)
=> Update Podman documentation

api/extension-guides/custom-editors.md
I've found some typos and grammatical slip-ups in the Custom Editor extension guide. I've tried to interpolate some words and a verb that were missing.
=> custom-editors.md: Fix spelling and grammar

docs/debugtest/port-forwarding.md
The current documentation labels the port forwarding feature as "Local Port Forwarding," which suggests tunneling from a local machine to a remote service. However, the described behavior—exposing a local service (e.g., port 5555 on the user's machine) to the internet via a public URL—is reverse port forwarding. This PR updates the title and , aligning with standard networking definitions. The change clarifies that it exposes local services externally, not the other way around, and adjusts the remote machine question for consistency.
=> Correct port forwarding terminology to reverse port forwarding

docs/copilot/copilot-customization.md
Add the `setting(github.copilot.chat.pullRequestDescriptionGeneration.instructions)` to the settings section.
=> Add pull request instruction to settings list

blogs/2021/10/11/webview-ui-toolkit.md
Working on some website updates today and just realized there's an old blog post with a broken link pointing to my Twitter account (that I deleted like 3 years ago). Update the link to my Bluesky account.
=> Switch broken Twitter link for Bluesky link

release-notes/v1_99.md
Related to https://github.com/microsoft/vscode-internalbacklog/issues/5286
=> chore: add legacy server end of support to v1.99

api/references/contribution-points.md, api/references/images/contribution-points/configuration-2.png
The current example uses a very outdated screenshot: https://code.visualstudio.com/api/references/contribution-points#Configuration-example.
=> Refresh configuration example

api/ux-guidelines/overview.md
The image below Command Palette https://code.visualstudio.com/api/ux-guidelines/overview#command-palette doesn't link to the clicked image. It opens a dead page, this pr fixes this
=> fix broken image link

docs/copilot/chat/chat-agent-mode.md
This pull request includes several improvements to the documentation for using agent mode in Visual Studio Code. The changes primarily focus on improving clarity and readability by fixing grammatical issues and enhancing the flow of the text.
Improvements to documentation clarity and readability:
* Corrected grammatical errors and improved sentence structure for better readability in various sections of `docs/copilot/chat/chat-agent-mode.md` [[1]](diffhunk://#diff-ca9ce10a4df63f883fe96d6c52d731c7c01365cb8cb2d38008c1047f14f993d6L9-R16) [[2]](diffhunk://#diff-ca9ce10a4df63f883fe96d6c52d731c7c01365cb8cb2d38008c1047f14f993d6L30-R38) [[3]](diffhunk://#diff-ca9ce10a4df63f883fe96d6c52d731c7c01365cb8cb2d38008c1047f14f993d6L47-R47) [[4]](diffhunk://#diff-ca9ce10a4df63f883fe96d6c52d731c7c01365cb8cb2 …
=> Fix grammar and punctuation in chat agent mode documentation

docs/copilot/copilot-smart-actions.md
It was probably a copy paste error, as the sentence with "test" is just below in the section about tests
=> Fix doc mentions tests in the "Generate documentation" section

api/extension-guides/scm-provider.md
Invalid fragments in some links in `scm-provider` documentation that results far from target position of `contribution-points` documentation
=> more closer to target for the links

docs/copilot/chat/mcp-servers.md
This pull request includes a minor change to the `docs/copilot/chat/mcp-servers.md` file. The change updates a URL to correct the file extension from `.md` to `.mdx`.
=> Update mcp-servers.md fix MCP spec link

docs/terminal/appearance.md, docs/terminal/images/appearance/rescale-off.png, docs/terminal/images/appearance/rescale-on.png
Forgot to document this feature from 1.90 https://code.visualstudio.com/updates/v1_90#_rescaling-overlapping-glyph-in-the-terminal
See confusion in recent issue https://github.com/microsoft/vscode/issues/247211
=> Document rescaleOverlappingGlyphs

docs/copilot/ai-powered-suggestions.md, docs/copilot/images/inline-suggestions/gutter-menu-highlighted-updated.png
Correct the heading for AI model completions, update the screenshot for the gutter menu, and introduce a collapsed mode to reduce distractions from edit suggestions.
=> Add collapsed mode for edit suggestions

docs/copilot/copilot-customization.md
Updating documentation for prompt and instruction files:
- Instructions files
- `.instructions.md` files
- User and workspace instructions files
- Sync with Settings Sync
- Add `applyTo` metadata to automatically assign to specific files
- Commands for creating instructions files
- Prompt files
- User and workspace prompt files
- Metadata fields for mode, description, tools
- Template variables
- Run from editor with play button
- Run with /<prompt>
- Save prompt with /save
- Commands for creating and running prompt files
=> Update prompt and instructions files

docs/remote/faq.md
This PR fixes a syntax error in the remote FAQ documentation related to `cp` usage.
The original line was:
```bash
cp <path-to-config-file> > .config
```
This is invalid syntax and results in the following error:
```bash
cp: missing destination file operand
```
It has been corrected to:
```bash
cp <path-to-config-file> .config
```
This change aligns the example with standard cp command usage and prevents confusion during setup.
Thanks!
=> Fix incorrect cp command in remote toolchain example

docs/csharp/debugger-settings.md
The current C# debugger-settings.md is mostly a long list of options without a walkthrough. To better guide users on how to use launchSettings.json. This PR:
1. Adds a walkthrough so this is hopefully more understandable. 
2. Moves the 'Configuring launchSettings.json file' up to the top after the walkthrough
3. Clarifies the 'launchSettings.json support' section, since we didn't do a great job there explaining those options were for `coreclr`/`clr`
These changes are based on feedback in https://github.com/dotnet/vscode-csharp/issues/8184
=> Add 'walkthrough' to debugger settings

docs/setup/vscode-web.md
=> Fix spelling in VSCode Web docs

release-notes/v1_100.md
- clarify that the updated browser support info also applies to HTML attributes
- add a link to the MDN doc about Baseline for more info
=> Update Baseline feature description

docs/copilot/copilot-customization.md
* Fix typo (`intructions` -> `instructions`)
=> Fix typo in instructions

docs/csharp/debugger-settings.md
Fixing typo in path `Propeties` to `Properties`
=> Update debugger-settings.md to fix typo

docs/containers/quickstart-python.md
The 3.0 docs give a security warning. Use "stable" which redirects to latest version.
=> Update quickstart-python.md: use stable Django docs link

docs/csharp/images/navigate-edit/inlay-hints.png, docs/csharp/navigate-edit.md
Adds a section to navigation and editing to show the C# inlay hints capabilities and settings
Fixes #8397
=> Add Csharp Inlay hints docs

docs/copilot/ai-powered-suggestions.md, docs/copilot/reference/copilot-settings.md, docs/copilot/reference/copilot-vscode-features.md
Updated to "next edit suggestions."
=> Update NES docs

docs/cpp/config-msvc.md
Updating the note in the C++ docs listing out the details of when the Visual Studio Build Tools can be used to match the official [license](https://visualstudio.microsoft.com/license-terms/vs2022-ga-diagnosticbuildtools/).
=> Updating Note on VS license

api/extension-guides/tools.md
Fixes the spelling mistake of `inutSchema`-> `inputSchema` in `extension-guides/tools`
=> fix: Spelling mistake of `inputSchema`

docs/configure/settings.md
Replaces an "experimental settings" reference with "preview settings" in the description of the **Preview** state to match the focus of the section (since experimental settings are focused in the previous section).
=> fix: swap "experimental" settings reference to "preview"

docs/intelligentapps/bulkrun.md, docs/intelligentapps/images/bulkrun/bulkrun.png, docs/intelligentapps/images/bulkrun/dataset_operation.png, docs/intelligentapps/images/bulkrun/full_screen.png, docs/intelligentapps/images/bulkrun/generate_data.png, docs/intelligentapps/images/bulkrun/manage_columns.png, docs/intelligentapps/images/bulkrun/view_detail.png
- Update how to start a bulk run
- Add dataset operation section
- Add Evaluate bulk run results section
- Add Manage data columns section
=> Refresh AITK Bulk Run Page

release-notes/v1_101.md
I've only glanced at them, but the listed issues seem to be "normal" issues to me, not security issues.
=> Fix incorrect mention of security issues in 1.101.1 release notes

release-notes/v1_101.md
Regarding the 1.101 release notes, "Custom chat modes (Preview)" section, this PR proposes replacing the hanging "and" there with a dot (`.`). It seems that additional words are unnecessary, and this is borne out by a previous iteration of that section (https://github.com/microsoft/vscode-docs/blame/cd87b04560378c3e34678b16b6d35cbbd696ae06/release-notes/v1_101.md#L177) which has only 3 words for the affected line.
=> Replace hanging "and" with "."

docs/languages/images/swift/configure-lldb.png, docs/languages/swift.md
Updates for new 6.1 release of the toolchain and for lldb-dap being the debugger dependency now
=> Updates to the swift language docs

build/sitemap.xml, docs/copilot/chat/mcp-servers.md, docs/copilot/guides/images/mcp-developer-guide/manage-trusted-mcp.png, docs/copilot/guides/images/mcp-developer-guide/mcp-allow-sampling.png, docs/copilot/guides/images/mcp-developer-guide/mcp-configure-model-access.png, docs/copilot/guides/images/mcp-developer-guide/mcp-error-loading-tool.png, docs/copilot/guides/images/mcp-developer-guide/mcp-prompt-argument.png, docs/copilot/guides/images/mcp-developer-guide/mcp-resources-picker.png, docs/copilot/guides/images/mcp-developer-guide/mcp-server-config-lenses.png, docs/copilot/guides/images/mcp-developer-guide/mcp-server-error-output.png, docs/copilot/guides/images/mcp-developer-guide/mcp-tool-input-parameters.png, docs/copilot/guides/images/mcp-developer-guide/mcp-tools-picker.png, docs/copilot/guides/mcp-developer-guide.md, docs/toc.json
Implements https://github.com/microsoft/vscode-docs/issues/8461
=> MCP Developer Guide

release-notes/v1_102.md
This PR makes a bunch of small changes to the changelog for v1.102 where we talk about the enhanced integration with Copilot coding agent. It:
* Re-orders starting new sessions from Copilot coding agent to the top
* Drops `the` from `the Copilot coding agent`
* Tweaks a few bits of a grammar here and there
=> Tweak Copilot coding agent information in v1.102 release notes

docs/copilot/faq.md
Clarifies the instructions to remove Copilot. Particularly, adds a mention to the actual command ("Chat: Hide Copilot") that can be run in the command palette to disable copilot.
This change may help people that want to disable Copilot entirely because, despite the menu option is mentioned in a lot of issues, similar issues are being raised on a regular basis:
- https://github.com/microsoft/vscode/issues/257770
- https://github.com/microsoft/vscode/issues/257329
- https://github.com/microsoft/vscode/issues/257117
- https://github.com/microsoft/vscode/issues/256932
- https://github.com/microsoft/vscode/issues/255559
- https://github.com/microsoft/vscode/issues/253245
- https://github.com/microsoft/vscode/issues/251564
- https://github.com/microsoft/vscode/issues/251334
- …
=> Clarify instructions to remove Copilot (command palette)

api/extension-guides/ai/mcp.md, api/extension-guides/images/ai/mcp/mcp-auth-client-id.png, api/extension-guides/images/ai/mcp/mcp-auth-client-secret.png, api/extension-guides/images/ai/mcp/mcp-auth-dynamic-client-required.png
Supports [#252892](https://github.com/microsoft/vscode/issues/252892)
=> docs: add mcp fallback auth flow with client credentials

release-notes/v1_103.md
Update release notes to remove note about terminal auto-approval not available at workspace-level
Related issue: https://github.com/microsoft/vscode/issues/260536
=> Bring back auto-approval at workspace level

docs/azure/vscodeforweb.md, docs/configure/keybindings.md, docs/sourcecontrol/overview.md
This PR includes the following fixes: 
- Fix a broken link in `docs/azure/vscodeforweb.md`.
- Correct typos in `docs/configure/keybindings.md` and `docs/sourcecontrol/overview.md`.
=> docs: fix broken link and some minor typos 

api/extension-guides/ai/chat.md
Fixes https://github.com/microsoft/vscode-docs/issues/8915
=> [Chat API Guide]: update for latest ChatFollowup interface

docs/copilot/customization/language-models.md
Add a FAQ item to the [Language Models docs article](https://code.visualstudio.com/docs/copilot/customization/language-models) to explain how to use locally-hosted language models.
Implements https://github.com/microsoft/vscode-docs/issues/8869
=> Add FAQ item about local models
