- docs/python/editing.md
- docs/python/images/editing/hello-world.gif
First draft of the Editing Code page includes:
-Removing anchor links from the top of the page
-Removing the initial text at the top of the page
- Including an introduction to IntelliSense, along with a "Hello World" gif to complement PowerBI sentiment from end user
- Included Jupyter Notebooks link in the Next Steps section
> Editing code page updates

- docs/python/debugging.md
- docs/python/images/debugging/debug-configurations.png
- docs/python/images/debugging/debug-icon.png
Did a review into the comments from users, sentiments, and archive prior to doing a pass on this doc. Happy to see that this page appears to be one of the highest performing pages. Updated some of the screenshots, formatting and text.
> New updates, edits, and screenshots

- api/language-extensions/syntax-highlight-guide.md
Chage the contribution point from grammar to grammars in the Tokenizations part of yntax-highlight-guide
> Chage the contribution point from grammar to grammars

- docs/other/unity.md
Adding an alternate method to modify workspace settings for file exclusions.
> alternate file exclusions

- docs/java/images/java-testing/displayname.png
- docs/java/images/java-testing/generate-tests-from-main.mp4
- docs/java/images/java-testing/generate-tests-from-test.mp4
- docs/java/images/java-testing/goto-test.png
- docs/java/images/java-testing/parameterizedtest.png
- docs/java/images/java-testing/report.gif
- docs/java/images/java-testing/report.mp4
- docs/java/images/java-testing/report_navigate.png
- docs/java/images/java-testing/run_codelens.png
- docs/java/images/java-testing/run_explorer.png
- docs/java/images/java-testing/status_bar.png
- docs/java/images/java-testing/test-junit5.gif
- docs/java/images/java-testing/test-junit5.mp4
- docs/java/images/java-testing/test-status.png
- docs/java/images/java-testing/test_report.png
- docs/java/images/java-testing/testng.gif
- docs/java/images/java-testing/testng.mp4
- docs/java/java-testing.md
This PR does the following things
- Remove some out-of-date images and videos
- Add a new section for project setup
- Add a new section for test generation
- Add a new section for test navigation
- Some update in existing sections
> Update the java testing document

- docs/java/images/java-project/add-maven-dependency.png
- docs/java/images/java-project/configure-classpath.png
- docs/java/images/java-project/context-menu.png
- docs/java/images/java-project/create-project.gif
- docs/java/images/java-project/create-project.mp4
- docs/java/images/java-project/enablesemantic.png
- docs/java/images/java-project/hierarchical.gif
- docs/java/images/java-project/hierarchical.mp4
- docs/java/images/java-project/inline-button.png
- docs/java/images/java-project/lib.mp4
- docs/java/images/java-project/lightweight-icon.PNG
- docs/java/images/java-project/manage-dependencies.gif
- docs/java/images/java-project/manage-referenced-libraries.png
- docs/java/images/java-project/multiple-source.gif
- docs/java/images/java-project/multiple-source.mp4
- docs/java/images/java-project/overflow-button.png
- docs/java/images/java-project/package-viewer.gif
- docs/java/images/java-project/package-viewer.mp4
- docs/java/images/java-project/processing-icon.png
- docs/java/images/java-project/projectmanager-addmavendep.PNG
- docs/java/images/java-project/projectmanager-createproject.png
- docs/java/images/java-project/projectmanager-overview.png
- docs/java/images/java-project/standalone.gif
- docs/java/images/java-project/standalone.mp4
- docs/java/images/java-project/standard-icon.PNG
- docs/java/images/java-project/syntaxonly.png
- docs/java/java-project.md
For the JDK part, I will update it in another PR.
This PR also removes some out-of-date images and videos, which can fix #4948
> Update the java project document

- docs/java/images/java-build/maven-archetype-command.mp4
- docs/java/images/java-build/maven-archetype-folder.mp4
- docs/java/images/java-build/maven-archetype.gif
- docs/java/images/java-build/maven-archetype.mp4
- docs/java/images/java-build/maven-dependency-tree.mp4
- docs/java/images/java-build/maven-effective-pom.gif
- docs/java/images/java-build/maven-history.gif
- docs/java/images/java-build/maven-plugin-goal.gif
- docs/java/images/java-build/maven-pom-editing.gif
- docs/java/images/java-build/maven-run.gif
- docs/java/java-build.md
> Java: update videos for Maven extension

- docs/java/images/java-tutorial/JavaHelloWorld.Project.mp4
- docs/java/images/java-tutorial/JavaHelloWorld.Standalone.mp4
- docs/java/images/java-tutorial/create-file.gif
- docs/java/images/java-tutorial/create-file.mp4
- docs/java/images/java-tutorial/detect-eng.png
- docs/java/images/java-tutorial/edit-code.gif
- docs/java/images/java-tutorial/getting-started.png
- docs/java/images/java-tutorial/invalid-jdk.png
- docs/java/images/java-tutorial/jdk-config-wizard-overview.png
- docs/java/images/java-tutorial/jdk-configuration.png
- docs/java/images/java-tutorial/jdk.acquisition.guide.gif
- docs/java/images/java-tutorial/run-debug.gif
- docs/java/java-tutorial.md
> Java tutorial:update videos accordingly

- docs/java/images/java-project/configure-project-runtime.png
- docs/java/images/java-project/download-jdk.png
- docs/java/images/java-project/jdk-configuration.png
- docs/java/images/java-project/projectmanager-javahomeconf.png
- docs/java/java-project.md
- docs/java/java-tutorial.md
The PR updates the section about java project runtimes.
@nickzhums please review when you have time 😀
> Update the java project jdk part

- docs/java/images/java-spring-boot/edit-starters.mp4
- docs/java/images/java-spring-boot/spring-code-edit.gif
- docs/java/images/java-spring-boot/spring-code-edit.mp4
- docs/java/images/java-spring-boot/spring-dashboard.gif
- docs/java/images/java-spring-boot/spring-initializr-add-starters.mp4
- docs/java/images/java-spring-boot/spring-initializr-edit.gif
- docs/java/images/java-spring-boot/spring-initializr-edit.mp4
- docs/java/images/java-spring-boot/spring-initializr.gif
- docs/java/images/java-spring-boot/spring-initializr.mp4
- docs/java/images/java-spring-boot/spring-live-info.mp4
- docs/java/java-spring-boot.md
> Java: update spring part

- docs/languages/images/java/testng.gif
- docs/languages/images/java/testng.mp4
> Update the java testing video

- docs/editor/integrated-terminal.md
> i dislike bad english

- docs/python/settings-reference.md
> Fix spelling

- docs/python/settings-reference.md
For https://github.com/microsoft/vscode-docs/issues/5030
> Remove add closing bracket setting from Python settings page

- api/extension-guides/color-theme.md
Small grammatical update to the Visual Studio Code tech docs.
> Grammatically updated the tech docs

- docs/java/java-testing.md
- docs/java/java-tutorial.md
- docs/languages/java.md
> update docs as platform-specific runtime is embedded in Java extension

- blogs/2019/05/23/strict-null.md
Hello~ 👋 
I fixed a small typo.
I could challenge fixing strict null checking in my team project thanks for the post.
@mjbvz
> Fix typo - add double quotation marks

- api/extension-guides/web-extensions.md
re: https://github.com/microsoft/vscode/issues/138623 where CSP errors occurs with using localhost
> Reverts #4945 

- docs/datascience/data-science-tutorial.md
- docs/datascience/images/data-science-tutorial/create-notebook.png
Completed Acrolinx, date approved, updated content, and minor changes.
> Content refresh 

- docs/remote/devcontainer-cli.md
https://github.com/microsoft/vscode-remote-release/issues/5957#issuecomment-999355431
> Noting NPM install doesn't support `open`

- docs/remote/containers.md
- docs/remote/faq.md
- docs/remote/images/containers/feature-contributions.png
Fixes https://github.com/microsoft/vscode-remote-release/issues/6128
@chrmarti @Chuxel @gregvanl Open to feedback on wording and location in the doc!
> Point to Remote-Containers feature contributions

- docs/python/testing.md
Replace 'true/false' with pythonic True/False
> Make testing.md more pythonic

- docs/remote/devcontainerjson-reference.md
From discussion in https://github.com/microsoft/vscode-remote-release/issues/6143, which led to https://github.com/microsoft/vscode-remote-release/issues/6143#issuecomment-1013318036
> Update name property definition in devcontainer.json reference

- api/references/when-clause-contexts.md
> fix mangled example of Matches operator in when clause (#5113)

- docs/java/extensions.md
- docs/java/images/java-gui/create-javafx.png
- docs/java/images/java-gui/run-javafx.mp4
- docs/java/images/java-project/projectmanager-createproject.png
- docs/java/java-faq.md
- docs/java/java-gui.md
@nickzhums Please let me know if you want to add more content in the new section for Java GUI development.
> Initialize the new section for Java GUI developmment

- docs/setup/windows.md
> Captilize U in Users

- docs/remote/devcontainerjson-reference.md
Fixes https://github.com/microsoft/vscode-remote-release/issues/6264
> Add dev container script failure info

- docs/cpp/config-msvc.md
> Live in the present: Update build tools version

- docs/python/images/environments/enter-interpreter-path.png
- docs/python/images/environments/interpreters-list.png
> Updated Python Environment Docs with Updated Images

- docs/python/testing.md
Small typo fixes. This article on Python testing was super helpful!!
> fix small typos in testing.md

- docs/java/images/java-testing/enable-tests.mp4
- docs/java/java-testing.md
> Add section: Enable Java tests for unmanaged folders

- release-notes/v1_64.md
not sure if this is the best solution, but it is a bit better than having 404 links
> fix: 404 links

- docs/editor/vscode-web.md
Want to point to overall limitations in https://code.visualstudio.com/docs/editor/vscode-web#_limitations, rather than Azure Repos specific limitations in https://code.visualstudio.com/docs/editor/vscode-web#_current-limitations.
> Update limitations link

- release-notes/v1_64.md
The default switched to off
See microsoft/vscode#142341
> Update auto replies notes

- docs/java/images/java-gui/enable-awt.mp4
- docs/java/java-gui.md
> Add video for enabling AWT development

- docs/java/images/java-testing/editor-decoration.png
- docs/java/images/java-testing/goto-test.png
- docs/java/images/java-testing/gutter-icon.mp4
- docs/java/images/java-testing/test-explorer.mp4
- docs/java/images/java-testing/test-navigation.mp4
- docs/java/images/java-testing/test-result.mp4
- docs/java/images/java-testing/test_explorer.png
- docs/java/images/java-testing/test_report.png
- docs/java/java-testing.md
> Replace screenshots with videos in java-testing.md

- api/working-with-extensions/publishing-extension.md
Fixes #5182 by noting the additional requirement of HEAD request response
> Update domain eligibility requirements

- docs/editor/integrated-terminal.md
> Update guidance around unsplitting terminal tabs

- docs/containers/ssh.md
Updating based on https://github.com/microsoft/vscode-remote-release/issues/6295#issuecomment-1032649038.
@bwateratmsft I'd love to know if this update makes sense to you (or if other folks should review too). Thank you!
> Add Remote-SSH + Remote-Containers info

- docs/editor/vscode-web.md
Restructure some setup and config.
> Browser setup updates

- docs/remote/create-dev-container.md
https://github.com/microsoft/vscode-remote-release/issues/6013
The mentioned log messages will be in the next stable release.
> Repository Containers: Clarify lookup

- docs/java/java-tutorial.md
- docs/languages/java.md
I think Azul Zulu should also be part of the recommended OpenJDK distributions. Thank's to Bruno Borges for the link to this repository.
> Added Azul Zulu to recommended OpenJDK distributions

- docs/editor/integrated-terminal.md
> Explain zsh workaround in faq

- docs/remote/containers.md
- docs/remote/create-dev-container.md
Add info about the badge and link to docs. Happy to discuss any wording or location suggestions!
> Add info about container URLs

- remote/advancedcontainers/docker-options.md
Add info about Rancher Desktop to the Docker options doc.
> Add Rancher Desktop info

- docs/editor/integrated-terminal.md
Fixes #5262
This can go in for 1.66 but isn't urgent if it's too late for that.
> Add section on dealing with complex PROMPT_COMMANDs

- docs/python/tutorial-django.md
what else should change when switching to production environment, example: ALLOWED_HOSTS = ['*']
> doc information complement,

- docs/python/debugging.md
... for debugging.md. This PR addresses [issue #5268](https://github.com/microsoft/vscode-docs/issues/5268). @karthiknadig are you able to validate this info, please? ☺️
> updating the troubleshooting section and md.date

- docs/python/environments.md
- docs/python/images/environments/selected-interpreter-status-bar.png
Hi @luabud!
I've reformatted/updated this document to improve the flow. Can you please take a look to make sure this aligns with the changes that have been made recently? ☺️ Any and all feedback is welcome. 
This should also address the following issues: 
- https://github.com/microsoft/vscode-docs/issues/3951 
- https://github.com/microsoft/vscode-docs/issues/5247
Notes:
- "Limited support for 2.7" section has been removed to align with CPython support. 
- @karthiknadig makes a great point in issue #3951. Users can have varied experiences depending on how they set up their conda environment. I could either include a note, explaining how this could be a potential hindrance. Or a table showing setup choices in different terminal shells. What are your thoughts? 🤔
> Addressing doc bugs and enhancements in Environments.md

- docs/editor/integrated-terminal.md
use jsonc instead of json to fix json highlight
> fix json highlight

- docs/editor/accessibility.md
- docs/editor/images/accessibility/accessibility-color-wheels.png
- docs/editor/images/accessibility/accessibility-extension-marketplace.png
- docs/editor/images/accessibility/accessibility-extension-squiggles.png
- docs/editor/images/accessibility/accessibility-select-theme.png
- docs/editor/images/accessibility/accessibility-settings-json-file.png
... for color vision accessibility. The following addition contains an H2 and H3 to help users with color vision deficiencies.
> added customizing error, warning, and theme colors

- docs/getstarted/locales.md
https://github.com/microsoft/vscode-loc-deprecated
> remove deprecated languages

- release-notes/v1_67.md
Release notes for changes to the jupyter extension
> Add jupyter release notes

- docs/python/environments.md
- docs/python/images/environments/conda-environment-refresh.png
> update Python 3.9 references, image, and refresh feature

- docs/python/images/linting/enable-linting-dropdown.png
- docs/python/linting.md
This PR includes new screenshots, updated content, and an Acrolinx check.
> update content, ms.date, and run acrolinx

- docs/getstarted/images/settings/activity-bar-hidden.png
I retook the activity bar hidden image so that it's on Stable rather than on Insiders.
> Update activity bar image

- docs/python/images/shared/environment-in-status-bar.png
- docs/python/tutorial-django.md
- docs/python/tutorial-flask.md
... to show virtual environment status on the bottom, right side. Fixes #5247.
> updating flask/django docs with env UI changes

- docs/azure/aksextensions.md
- docs/azure/images/aksextensions/right-click-menu-workflow.png
- docs/azure/images/aksextensions/right-click-menu.png
This PR adds the new screenshot with the `show properties` menu item for `aks vscode extension`.
Thank you so much for review and taking time for this PR: cc: @gregvanl and @peterbom
> Add new command screenshot and update.

- build/events-data.json
Adding details for 6/9/2022 livestream updates.
> Updating events-data.json

- remote/advancedcontainers/environment-variables.md
https://github.com/microsoft/vscode-remote-release/issues/3150#issuecomment-644010315
> Clarified automatic variables loading from .env

- remote/advancedcontainers/environment-variables.md
https://github.com/microsoft/vscode-docs/pull/5369
> Clarify .env folder

- docs/setup/network.md
> add vscode.dev to list of hostnames

- docs/other/images/office/office-add-in-manifest.png
- docs/other/office.md
The current [Office Add-ins with Visual Studio Code](https://code.visualstudio.com/docs/other/office) article contains outdated information. Update information, including links and images.
> Update Office Add-ins with VS Code article

- docs/nodejs/nodejs-debugging.md
Replaced "Something" with "Sometimes".
Issue: #5421
>  Fix minor typo in 'Node.js debugging in VS Code'

- .husky/post-checkout
- .husky/post-commit
- .husky/post-merge
- .husky/pre-push
Just adds single quotes around file paths.
> Update .husky files

- release-notes/images/1_69/task-icon.png
- release-notes/v1_69.md
not sure which are worthy of an image
> add task updates

- docs/setup/enterprise.md
- docs/setup/network.md
- docs/setup/uninstall.md
- Added Group Policy content in new Enterprise doc
- Moved hostnames section from Network to Enterprise doc
> Add enterprise section

- release-notes/images/1_69/jupyter_chemiscope_widget.gif
- release-notes/images/1_69/jupyter_chemiscope_widget.png
- release-notes/images/1_69/jupyter_ihaskell_widgets.gif
- release-notes/v1_69.md
Added Jupyter Extension release notes
> Add entry in release notes for Jupyter extension

- release-notes/v1_69.md
- fixed mentions of quick pick
- added extra way to access debug console
> Debug Console Fixes 1.69

- docs/editor/vscode-web.md
- docs/remote/remote-overview.md
Add a mention of the VS Code Server to the vscode.dev user guide and remote overview.
cc @tanhakabir @connor4312
> Remote and vscode.dev server updates

- docs/editor/terminal-shell-integration.md
Allow me for a minor contribution.
> Fix format error

- release-notes/v1_69.md
Fixes https://github.com/microsoft/vscode-docs/issues/5465
> Fix spelling of inline completions setting name

- api/index.md
- This change just adds "time" to index of API docs and "docs" instead of "doc", which feels a bit nicer (to me, wonder how other people think "time" matters, I have never published extensions before).
`api/index.md`
> Text change

- docs/java/java-linting.md
- docs/nodejs/extensions.md
- docs/nodejs/images/extensions/sonarlint.gif
We've updated the SonarLint description for Java to mention the in-context guidance and to provide links to the supported inspections and quick fixes. Similar content has been added to the JavaScript inspections.
> SonarLint description updated for Java, added for Javascript

- docs/python/environments.md
This PR addresses and will close #5371 ;
> Clarify environment variable order of precedence

- docs/python/debugging.md
The PR addresses and will close #5330 ; Please let me know if this could use a bit more clarification or if there are any other areas you feel may need to be addressed. ☺️
> Clarify launch.json config

- release-notes/images/1_70/code-action-all.gif
- release-notes/v1_70.md
- Added Code Actions release notes
> added release notes on code actions widget!

- api/references/theme-color.md
Refs https://github.com/microsoft/vscode/issues/156110
> Add button separator color token

- release-notes/v1_70.md
Adding better use case for debug session picker description.
> Adding Extra Debug Session Info

- api/references/theme-color.md
> Adding the colors. Fixes #157069.

- remote-release-notes/v1_70.md
Be a bit more specific about timelines.
> Update remote notes

- docs/terminal/basics.md
- docs/terminal/profiles.md
- docs/terminal/shell-integration.md
Part of #4809
This was mostly just shuffling content around, I also reviewed and made some minor updates.
> Create new terminal profiles section

- docs/terminal/shell-integration.md
Part of microsoft/vscode#139400
> Add fish shell integration manual install

- docs/python/python-tutorial.md
... from **macOS** note. This PR closes #5528
> remove outdated information

- docs/languages/images/powershell/HSGavatar.png
- docs/languages/images/powershell/PowerShellExtension.png
- docs/languages/images/powershell/codeLensPesterDebug.gif
- docs/languages/images/powershell/extensionBrowser.png
- docs/languages/images/powershell/pwshChangeVersion.png
- docs/languages/images/powershell/pwshCodeSettings.png
- docs/languages/images/powershell/pwshSettings.png
- docs/languages/images/powershell/pwshVsixIcon.png
- docs/languages/images/powershell/vscodeSettingsGui.png
- docs/languages/images/powershell/vscodeSettingsMenu.png
- docs/languages/powershell.md
Fixes AB#4819 - Update PS Extension docs
- Reflowed paragraphs per PowerShell-Docs style guide
- Reorganized content
- Removed outdated references
- Updated main screenshot
> Update PS Extension docs

- release-notes/v1_71.md
@deepak1556 let me know what you think about the wording. Is "codecs container" the right term?
@gregvanl I put this under Workbench, and I seem to be the first one to write the release notes so just let me know if I changed the template properly
> Add codecs support to release notes

- api/references/contribution-points.md
- api/references/images/contribution-points/settings-ui-icon-theme.png
Fixes https://github.com/microsoft/vscode-docs/issues/5585
> Add enumItemLabels documentation

- docs/cpp/config-mingw.md
Update MSYS2 download link to the latest MSYS2 installer.
> Update MSYS2 installer link

- docs/python/editing.md
> correct yapf indent width

- release-notes/images/1_71/screenshot_paste.gif
- release-notes/v1_71.md
Add info on pasting into notebooks for the release notes. @Yoyokrazy looped in as the dev.
> Image paste into notebook info

- docs/terminal/appearance.md
- docs/terminal/basics.md
- docs/terminal/images/appearance/custom-glyphs.png
- docs/terminal/images/appearance/tabs.png
- docs/terminal/images/appearance/terminal_appearance.png
> Add terminal appearance section

- api/references/contribution-points.md
> Add contributes.terminal docs

- docs/editor/settings-sync.md
Fixes https://github.com/microsoft/vscode/issues/130893
> Add a windows trouble shooting step

- release-notes/v1_71.md
If I'm not mistaken, it should be the opposite (as in this PR). Right?
> Fix sentence about using Node.js APIs in web

- docs/remote/ssh.md
- learn/educators/learn-modules.md
- learn/educators/nodejs.md
- learn/educators/python.md
- learn/students/github-pack.md
- release-notes/v1_52.md
- release-notes/v1_67.md
**Global effort to fix build validation errors**
The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.
DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!
CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck
> [BULK] DocuTune - Fix build validation issues: docs-link-absolute

- docs/remote/troubleshooting.md
Same as in this guide https://www.telepresence.io/docs/latest/troubleshooting/#volume-mounts-are-not-working-on-macOS
> Fix macOs installation instruction for sshfs

- docs/remote/wsl-tutorial.md
I've ran into this issue a few times before, and every single time I forget why it doesn't work. Hopefully this will save me (and others) some time in the future :)
> Add command to run VS Code Insiders from WSL

- docs/azure/deployment.md
- docs/datascience/pytorch-support.md
- learn/educators/learn-modules.md
- learn/students/nasa-python.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck
> [BULK UPDATE] DocuTune - Rebranding

- docs/sourcecontrol/github.md
- docs/sourcecontrol/overview.md
- Added 3 videos for Git, including the intro video right on top.
- Moved SCM Provider content down in favor of Git-related content.
- Added mergetool config
> Git topic editing

- docs/editor/settings-sync.md
Following @TylerLeonhardt's suggestion to add this fix to the docs from [here](https://github.com/microsoft/vscode/issues/137850#issuecomment-1203693756)
> docs: arch keyring fix using dbus-launch

- docs/getstarted/settings.md
> fix extra parenthesis of `kb()` in getstarted/settings.md

- api/advanced-topics/python-extension-template.md
- api/toc.json
- build/sitemap.xml
- docs/python/editing.md
- docs/python/linting.md
I've tried to cover the main points of the template without going into too much detail.
@karthiknadig Let me know if you think we need more content on extension authoring best practices or if you've noticed specific questions from authors that need to be addressed here or in the main API docs.
> First draft of new Python extension template topic

- release-notes/images/1_72/notebook-cell-tags.gif
- release-notes/images/1_72/notebook-outline-html-headers.png
- release-notes/images/1_72/notebook-slideshow.gif
- release-notes/v1_72.md
Add Notebook/Jupyter updates for Sept release.
> add notebook updates

- docs/remote/images/ssh/add-new-port.png
- docs/remote/images/ssh/change-local-port.png
- docs/remote/images/ssh/forward-port-ssh.png
- docs/remote/images/ssh/ssh-explorer-forward-port.png
- docs/remote/images/ssh/ssh-tunnel-different-local-port.png
- docs/remote/ssh.md
Update based on latest views and commands.
Fixes https://github.com/microsoft/vscode-remote-release/issues/7227
> Update ports info

- blogs/2022/10/04/github-discussions.png
- blogs/2022/10/04/vscode-community-discussions.md
Blog post announcing the new VS Code Community Discussions for extension authors
> Add VS Code Community Discussions blog post

- docs/terminal/basics.md
- docs/terminal/images/basics/gitlens-link.png
- docs/terminal/images/basics/integrated-terminal.png
- docs/terminal/images/basics/link-extension.png
- docs/terminal/images/basics/link-file.png
- docs/terminal/images/basics/link-folder.png
- docs/terminal/images/basics/link-uri.png
- docs/terminal/images/basics/link-word.png
- docs/terminal/images/basics/select-profile-dropdown.png
- docs/terminal/images/basics/select-shell-dropdown.png
- docs/terminal/images/basics/tabs.png
- docs/terminal/images/basics/terminal-editor-grid.png
- docs/terminal/images/basics/terminal-editor.png
- docs/terminal/images/basics/terminal-find.png
- docs/terminal/images/basics/terminal_run_selected.png
- docs/terminal/images/basics/terminal_run_selected_result.png
Still a work in progress, but this will close out the last item in #4809 🎉 
Fixes #4809
> Terminal basics page refresh

- docs/setup/mac.md
changed M1 references to Apple Silicon now that there are new generations
> docs: update Apple Silicon reference

- docs/terminal/shell-integration.md
> Add vscode shell integration sequences to docs

- docs/terminal/basics.md
> add missing closing code block

- docs/java/java-gui.md
Add more descriptions according to the users' feedback.
> Add more information to the java-gui document

- docs/languages/javascript.md
- docs/typescript/typescript-editing.md
- docs/typescript/typescript-refactoring.md
I don't know exactly how your website build occurs but based on other /assets/ links present in the repository I believe this should fix the broken video links and point to the files that are actually there. May fix #5717.
> Adds relative link fix for several videos.

- api/advanced-topics/remote-extensions.md
Fixes https://github.com/microsoft/vscode-remote-release/issues/7182
> Update remote extension known issue

- docs/editor/accessibility.md
> update accessibility docs

- .github/workflows/pr-chat.yml
Add the YML file for the codereview chat action. Please hold off on merging until secrets are added.
> Add codereview chat action

- docs/sourcecontrol/overview.md
This is minor, but I wonder if view counts are off because of the allow list.
> Potential yt fix.

- api/working-with-extensions/publishing-extension.md
> Clarify extension unique name restriction issue #5584

- blogs/2022/07/07/vscode-server.md
- docs/remote/vscode-server.md
Update to the latest extension name.
> Update to Remote Tunnels

- docs/python/environments.md
- docs/python/images/environments/conda_environment_python_versions.png
- docs/python/images/environments/create_environment_dropdown.png
- docs/python/images/environments/create_environment_prompt_status.png
Adding steps and pictures to the Python environments documentation to include the Create Environment command.
> Updating Python docs to include the Create Environment command

- docs/remote/ssh-tutorial.md
Updated the message "Remote-SSH: Connect to Host" to the latest version of vscode "Connect to Host... Remote-SSH" in the list of Remote extension commands.
> Updated the message "Remote-SSH: Connect to Host" to the latest version of vscode "Connect to Host... Remote-SSH"

- docs/editor/codebasics.md
- docs/nodejs/angular-tutorial.md
- docs/other/unity.md
- docs/remote/images/ssh-tutorial/remote-commands.png
- docs/remote/ssh-tutorial.md
A few edit and formatting changes for recent community PRs.
Also moving a fairly advanced section on Logical Lines to the Common Questions section of Basic Editing
> Follow up edits for recent PRs

- docs/python/tutorial-flask.md
When I asked VS Code to auto-create a Flask launch.json configuration, it did not quite match what was in the tutorial. This PR updates it to match what was generated.
I believe the changes make sense, too, since:
1) FLASK_ENV is deprecated in favor of FLASK_DEBUG
2) justMyCode was a recently added feature to VS Code?
> Update launch.json per current Flask launch.json

- remote/advancedcontainers/add-nonroot-user.md
> Dev Containers also updates DockerCompose user ID

- blogs/2020/02/18/optimizing-ci.md
- docs/cpp/configure-intellisense-crosscompilation.md
- docs/remote/vscode-server.md
- docs/setup/mac.md
- docs/setup/uninstall.md
- docs/supporting/faq.md
ARM should be Arm per https://github.com/microsoft/vscode/issues/165297
Apple silicon brand name is lower case "silicon"
> Follow build architecture naming conventions

- docs/remote/ssh.md
> docs/remote/ssh.md: fix typo: "AArch322" to "AArch32"

- docs/java/java-tutorial.md
- docs/languages/java.md
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>
> Add IBM Semeru Runtimes to list of JDKs

- docs/languages/typescript.md
> Quick Fix for misspelling in  TypeScript.md file

- docs/getstarted/keybindings.md
It's mentioned here and it's very useful:
https://stackoverflow.com/a/43192243/2604492
Document it to help people find about it easier.
> Document overwriting a key binding with an empty command

- docs/datascience/data-science-tutorial.md
- docs/datascience/images/data-science-tutorial/create-notebook.png
- docs/datascience/jupyter-notebooks.md
The Jupyter notebook topics was reviewed by a community member so bumping the DateApproved.
The Data Science tutorial still needs a freshness pass
> Update New Jupyter Notebooks command and image

- docs/azure/aksextensions.md
- docs/azure/images/aksextensions/aks-periscope-webview.png
- docs/azure/images/aksextensions/right-click-menu-kubectl.png
New PR to add updated and new images to Git LFS to unblock https://github.com/microsoft/vscode-docs/pull/5817
> new PR on Git LFS for PR #5817

- release-notes/v1_74.md
Added a short intro about the newly defined `search` file location method for problem matches.
Issue: microsoft/vscode#160771
PR: microsoft/vscode#165156
> 🎤 Introduce `search` file location method

- docs/remote/tunnels.md
Fixed broken link to Remote - Tunnels extension in **Remote - Tunnels extension section**
> Fixed broken link to Remote - Tunnels extension

- docs/remote/vscode-server.md
Fix 3 broken links on https://code.visualstudio.com/docs/remote/vscode-server
> Fix some links that are broken when published

- docs/java/java-editing.md
- docs/languages/images/java/code-snippet.png
- docs/languages/java.md
- docs/remote/tunnels.md
Add missing image, small edits
Also fix typo in tunnels.md spotted in #5845
> follow up for Java updates

- docs/remote/tunnels.md
Fixes https://github.com/microsoft/vscode/issues/168370
> add security notes on dev tunnels

- docs/cpp/cpp-ide.md
- docs/sourcecontrol/github.md
Fixes #5850
Also updated Cloud Changes setting name
> Fix topic link

- docs/editor/vscode-web.md
Updating to "VS Code Desktop," as discussed.
> Update desktop phrasing

- docs/terminal/shell-integration.md
See https://github.com/microsoft/vscode/pull/168211
> Update fish shell integration support

- docs/editor/variables-reference.md
> Add fileDirnameBasename predefined variable

- docs/editor/variables-reference.md
> pickString option can also show a label

- api/references/contribution-points.md
> mention contributes.languages.filenamePatterns

- api/extension-guides/tree-view.md
- api/references/contribution-points.md
> Clarify where TreeView.message comes from

- docs/editor/variables-reference.md
> launch config object is passed to command variable

- docs/getstarted/keybindings.md
> mention the focus breadcrumbs keyboard shortcuts

- docs/editor/accessibility.md
> Call out shell integration in the terminal's a11y section

- docs/terminal/basics.md
Part of microsoft/vscode#170643
> Add new open detected link keybinding

- docs/terminal/appearance.md
Part of microsoft/vscode#170732
> Add background on why term mcr is on by default

- docs/python/environments.md
For https://github.com/microsoft/vscode-docs/issues/5738
> Clarify variable substitution is not supported in .env files

- docs/editor/vscode-web.md
Update based on ongoing discussion. I'll also share with others in case there are additional keyboard shortcuts we should also add.
> Update keyboard shortcuts

- api/ux-guidelines/views.md
- docs/datascience/notebooks-web.md
- docs/editor/userdefinedsnippets.md
- docs/getstarted/tips-and-tricks.md
- docs/python/debugging.md
- docs/python/environments.md
- docs/python/python-web.md
- docs/python/testing.md
Bump DateApproved for recent updates
**User Snippets** menu item is now **Configure User Snippets**
Fix a couple of typos
> Edits and formatting for recent updates

- docs/editor/portable.md
> address @meganrogge's feedback

- api/working-with-extensions/images/publishing-extension/remove-extension.png
- api/working-with-extensions/images/publishing-extension/remove-warning.png
- api/working-with-extensions/publishing-extension.md
This brings over the changes in https://github.com/microsoft/vscode-docs/pull/5978 with some edits and using Git LFS for the images
> Remove extension via Marketplace management page

- api/language-extensions/language-configuration-guide.md
I just realized my mistake about four years ago.(#2297)
> Fix Indentation Rule

- docs/terminal/shell-integration.md
The change failed verification, see microsoft/vscode#139400
> Revert fish shell integration changes

- docs/editor/artificial-intelligence.md
- docs/editor/images/artificial-intelligence/copilot-access-toast.png
- docs/editor/images/artificial-intelligence/copilot-access.png
- docs/editor/images/artificial-intelligence/copilot-auth-toast.png
- docs/editor/images/artificial-intelligence/copilot-auth.png
Address feedback from @digitarald today:
- Reduce size of notification images
- Combine sign in and sign up sections
> AI doc feedback

- docs/editor/tasks.md
> Updated command names

- api/working-with-extensions/testing-extension.md
> testing-extension: fix install extension use

- api/extension-guides/tree-view.md
This was missing from the documentation and I had to do a combination of [searching it up on StackOverflow](https://stackoverflow.com/a/70896443/5661593) and looking at how the [Git extension](https://github.com/microsoft/vscode/blob/1.74.3/extensions/git/package.json) did it.
> Explain how to order & group Tree View actions

- release-notes/v1_75.md
Copied from here and edited incorrectly:
https://github.com/microsoft/vscode-pull-request-github/pull/4409/files#diff-2017e39c19325198b4313b18a83f5fc6e8334b88f1b11265334febfd922acd19R175-R182
> Remove extra brackets in v1_75.md

- api/references/extension-manifest.md
> Remove stale badge prefixes

- docs/setup/windows.md
- docs/sourcecontrol/faq.md
- release-notes/v1_75.md
Some minor edits and bring over https://github.com/microsoft/vscode-docs/pull/6008 from vnext
> Small follow up PR

- api/advanced-topics/remote-extensions.md
- api/extension-guides/webview.md
Fixes https://github.com/microsoft/vscode/issues/173448
> Use joinUri in webview docs

- remote/advancedcontainers/start-processes.md
Arrr its pirate day! This PR removes the unneeded r.
> Remove extra r in overrideCommand

- docs/devcontainers/containers.md
- docs/devcontainers/devcontainer-cli.md
Fixes https://github.com/microsoft/vscode-docs/issues/6042.
> Add dev container artifact distribution info

- docs/remote/tunnels.md
Fixes https://github.com/microsoft/vscode-remote-release/issues/7670.
> Add curl install info to tunneling doc

- .pipelines/templates/jobs/build.yml
This PR changes the pipeline so that it attempts to install dist dependencies as part of the artifact
> Install dist dependencies as part of artifact

- build/sitemap.xml
- docs/sourcecontrol/intro-to-git.md
Here's a draft of the format/edit pass.
I'll wait until we can have a look on the staging server to finalize the PR but you can get started with a review now
> Intro to Git follow up

- docs/sourcecontrol/intro-to-git.md
Also add query to open Git doc on VS Code pivot.
GHPRI is plural "Pull Requests"
> Tune titles in Intro to Git

- docs/devcontainers/images/tutorial/dev-containers-commands-simple.png
- docs/devcontainers/images/tutorial/dev-containers-commands.png
- docs/devcontainers/tutorial.md
- docs/remote/images/ssh-tutorial/remote-commands-simple.png
- docs/remote/images/ssh-tutorial/remote-commands.png
- docs/remote/images/wsl-tutorial/remote-wsl-commands.png
- docs/remote/images/wsl-tutorial/wsl-commands.png
- docs/remote/ssh-tutorial.md
- docs/remote/wsl-tutorial.md
Fixes https://github.com/microsoft/vscode-docs/issues/6040
@joyceerhl I looked through all our remote docs, and these were the images I found to update. If there's other content you think we should change, please just let me know!
I'll update individual extensions' readmes in separate PRs to those extensions.
> Update remote indicator content

- docs/editor/profiles.md
Editing profiles by using the normal means of changing settings, modifying extensions etc might see obvious to some but still should be explained somewhere.
This PR is just a small section about this fact, and a note about editing the settings.json directly while switching profiles.
> Add small section about editing a profile.

- release-notes/images/1_76/experimental_notebook_search.mp4
- release-notes/images/1_76/multiple-quick-diff.png
- release-notes/images/1_76/notebook-renderer-performance-diagnostics.png
- release-notes/images/1_76/remote-indicator.mp4
- release-notes/images/1_76/web-git-lfs.mp4
- release-notes/v1_76.md
This should help us verify https://github.com/microsoft/vscode/issues/175366 mp4 rendering for the in-product release notes
> Snapshot for 1.76 Insiders

- docs/python/jupyter-support-py.md
- learn/collaboration/live-share.md
- learn/educators/nodejs.md
- learn/educators/python.md
- learn/overview.md
The LiveShare extension link was broken.
> Fix LiveShare broken link

- build/sitemap.xml
- docs/editor/accessibility.md
- docs/editor/command-line.md
- docs/editor/emmet.md
- docs/editor/images/profiles/create-profile-via-manage.png
- docs/editor/images/profiles/create-profile.png
- docs/editor/images/profiles/profile-gear-two-letters.png
- docs/editor/images/profiles/profile-show-contents.png
- docs/editor/images/profiles/settings-sync-profiles.png
- docs/editor/multi-root-workspaces.md
- docs/editor/profiles.md
- docs/editor/settings-sync.md
- docs/editor/userdefinedsnippets.md
- docs/editor/workspace-trust.md
> Profiles topic

- docs/python/python-tutorial.md
Found the upper one updated one but this one is not.
> Replace python with py for windows

- release-notes/v1_77.md
Publish a hidden (not in TOC) 1.77 release notes placeholder for 1.77 Insiders
> 1.77 snapshot for Insiders

- docs/cpp/c-cpp-properties-schema-reference.md
Addresses: https://github.com/microsoft/vscode-cpptools/issues/10235
> Update doc and description for configurationProvider setting

- docs/cpp/customize-default-settings-cpp.md
Addresses: https://github.com/microsoft/vscode-cpptools/issues/10235
> Update Settings Documentation for C++ Extension

- docs/editor/profiles.md
A tiny update to the grammar in the first paragraph of these docs
> Profiles docs grammar update

- docs/setup/uninstall.md
> Add "on the VS Code/Visual Studio Code website" to `setup/uninstall.md`

- build/sitemap.xml
- docs/datascience/images/overview/polyglot-nb-ext.png
Also update a Polyglot Notebooks extension image
> Add Polyglot topic to the sitemap

- api/extension-guides/overview.md
- api/extension-guides/tree-view.md
- api/language-extensions/snippet-guide.md
- api/ux-guidelines/notifications.md
The changes are described in commit messages and descriptions. 
Some help the readability of the documents, some adds more needed info (or the ones that needed update)
> Minor changes in API docs

- docs/languages/images/python/no-interpreter-selected-statusbar.png
- docs/languages/images/python/selected-interpreter-status-bar.png
- docs/languages/python.md
For https://github.com/microsoft/vscode-docs/issues/6141
> Use correct link to images in Python environment doc

- docs/getstarted/keybindings.md
The command will be available in the coming stable release (1.77)
> document `runCommands` 

- blogs/2023/03/30/vscode-copilot.md
- release-notes/v1_78.md
Also fix for keybinding in the Copilot blog post
> Add 1.78 placeholder for Insiders

- blogs/2023/03/30/vscode-copilot.md
Minor change to be more explicit about collaborating with GitHub on Chat View
> give credit where credit is due

- blogs/2023/03/30/vscode-copilot.md
making the suggestion more explicit
> monty python rocks

- docs/terminal/basics.md
- docs/terminal/images/basics/open-in-terminal-command.png
Add section on opening terminals from the Explorer
Mention runas to elevate to Admin
Couple of passive voice removals
Use spaces versus tabs in examples
> Terminal Basics additions based on doc feedback

- api/references/theme-color.md
Duplicated lines were 204 and 206
> API: remove duplicated `activityBar.activeBackground`

- blogs/2023/04/13/monaco-workbench.png
- blogs/2023/04/13/post.md
- blogs/2023/04/13/visual-studio-online.png
- blogs/2023/04/13/vscodeday-header.png
Hopefully I got the LFS stuff right...
> initial commit

- docs/datascience/images/overview/jupyter-notebook-preview.png
- docs/datascience/overview.md
https://github.com/microsoft/vscode-jupyter-internal/issues/402
- Blurb to encourage extension building
- Updated overview photo
> extension building

- docs/editor/profiles.md
Add Profile Templates in our profiles doc.
@gregvanl  @sandy081 let me know what you think.
Tomorrow I plan to fill in the gaps for the remaining 6 profile templates; if you like this structure.
The plan is to then link various language docs to these subsections. And @gregvanl will drive that work.
fyi @luabud @minsa110 @nickzhums
> add Profile Templates

- docs/remote/troubleshooting.md
> Fix linux bash syntax

- docs/datascience/jupyter-notebooks.md
- docs/datascience/overview.md
- docs/java/extensions.md
- docs/java/java-faq.md
- docs/languages/markdown.md
- docs/languages/python.md
- docs/nodejs/angular-tutorial.md
- docs/python/tutorial-django.md
- docs/python/tutorial-flask.md
Updates Pivotal to VMWare as VMWare now publishes the Java Spring Boot extensions.
Fix copy and paste mistake making profile template plural.
Fix a couple other references to old command name, now "Select Default Profile"
> follow up for recent PRs

- docs/python/jupyter-support-py.md
> correct Jupyter Debug Just My code setting location

- docs/setup/windows.md
> windows - update faq on unc paths

- release-notes/v1_78.md
This should be merged on the morning of the 1.78.2 release
> mention 1.78.2 release

- release-notes/v1_78.md
Updated "Microsoft Cloud for Sovereignty" link in 1.78 release notes.
This PR should close issue #6293
> Updated Microsoft Cloud for Sovereignty Link

- docs/terminal/shell-integration.md
This reverts commit 78707ef6e629d02371b81c91e1d4b0c9d80f91d4.
Fish auto injection should work this iteration https://github.com/microsoft/vscode/pull/183005
> Revert "Revert fish shell integration changes (#5985)"

- docs/devcontainers/containers.md
- docs/devcontainers/tips-and-tricks.md
- docs/devcontainers/tutorial.md
Fixes https://github.com/microsoft/vscode-docs/issues/6264.
> Further highlight Docker options info

- api/working-with-extensions/images/publishing-extension/create-token.png
- api/working-with-extensions/images/publishing-extension/menu-pat.png
- api/working-with-extensions/images/publishing-extension/new-token.png
- api/working-with-extensions/images/publishing-extension/token1.png
- api/working-with-extensions/images/publishing-extension/token2.png
- api/working-with-extensions/publishing-extension.md
- Updated screenshots to be more strict and accurate
- Improved steps description to be more logical and clear
> Refactor "Get a Personal Access Token" section in "Publishing Extensions" page

- docs/terminal/basics.md
The idea was to split the terminal basics into basics and interactions but I stumbled across some wording-related things I want to fix first.
- Intro update
- Terminal editors section update
- Group section update
- Link section update
> Terminal editors update

- docs/java/java-debugging.md
- docs/languages/java.md
Fixes #6303
Will follow up with the Java extension team for topics under /docs/java
> All alt text to Java language topic videos

- docs/editor/userdefinedsnippets.md
> Add new snippet variable CURRENT_TIMEZONE_OFFSET

- docs/editor/accessibility.md
> Mention Toggle Screen Accessibility Mode command

- learn/collaboration/live-share.md
> Note about deprecated LiveShare Extension Pack

- docs/editor/profiles.md
> Clarify unchecking an extension in Profiles view

- docs/nodejs/nodejs-debugging.md
Fixes https://github.com/microsoft/vscode-js-debug/issues/1709
> nodejs: add note about node_options

- docs/python/testing.md
> Give table first column unique names

- docs/csharp/build-tools.md
- docs/csharp/cs-dev-kit-faq.md
- docs/csharp/debugging.md
- docs/csharp/formatting-linting.md
- docs/csharp/get-started.md
- docs/csharp/intellicode.md
- docs/csharp/navigate-edit.md
- docs/csharp/package-management.md
- docs/csharp/project-management.md
- docs/csharp/refactoring.md
- docs/csharp/testing.md
- docs/languages/csharp.md
- docs/languages/dotnet.md
Release delayed
Also fix one doc link and removed trailing spaces (automatic via vscode-docs workspace setting)
> Take new content out of TOC

- build/sitemap.xml
- docs/csharp/build-tools.md
- docs/csharp/cs-dev-kit-faq.md
- docs/csharp/debugging.md
- docs/csharp/formatting-linting.md
- docs/csharp/get-started.md
- docs/csharp/intellicode.md
- docs/csharp/navigate-edit.md
- docs/csharp/package-management.md
- docs/csharp/project-management.md
- docs/csharp/refactoring.md
- docs/csharp/testing.md
- docs/languages/csharp.md
- docs/languages/dotnet.md
Reverts https://github.com/microsoft/vscode-docs/pull/6374
Also a couple of formatting changes as well as xUnit casing corrections
> Add new C# topics to TOC and sitemap

- blogs/2023/06/05/vscode-wasm-wasi.md
Clarify what isn't available yet in WASI
> Small blog post update

- docs/csharp/get-started.md
Some grammar improvements to the article based on Microsoft style guide (use of contractions, don't spell out SDK, etc.)
> Get started update

- release-notes/v1_79.md
Refs https://github.com/microsoft/vscode/issues/177676
> docs: add windows 8 and 8.1 support end section

- docs/remote/tunnels.md
- docs/remote/vscode-server.md
Add information on limits and how users may reach out to us.
cc @curib would love your feedback on this change too!
> Update information on tunneling

- docs/languages/php.md
Encountered an alternative location for php in MacOS.
> alternative location for php on MacOS

- docs/supporting/faq.md
Don't need to mention the minor version for the deprecation message
Fixes #6411
> Remove the 1.79 minor version

- docs/editor/settings-sync.md
This is the first iteration of the new docs for troubleshooting keychain issues.
It's less content than before because we're not sure if the same issues still apply... they likely don't which is why I didn't include them.
> New keyring docs

- docs/cpp/pipe-transport.md
- docs/devcontainers/containers.md
- docs/python/linting.md
Avoid raw links which don't render clickable on code.visualstudio.com
Bump linting.md DateApproved after rewrite
Switch to present tense
Fix a couple of header links
> Follow up edits to recent PRs

- docs/python/tutorial-django.md
To reflect recent tutorial review and update
> Update Django tutorial freshness date

- docs/devcontainers/containers.md
Suggested here: https://github.com/microsoft/vscode-remote-release/issues/8666#issuecomment-1627688334
> Add note on `ssh-add -l` working correctly and Git.

- docs/remote/tunnels.md
Update to a more general title as this section doesn't only discuss number of tunnels.
@connor4312 please let me know if you have ideas on other changes that'd make this section even clearer!
TODO: Update aka.ms link if/when we publish this section with a new title.
> Update tunnel section title

- docs/editor/settings-sync.md
> List out the options

- api/advanced-topics/python-extension-template.md
For https://github.com/microsoft/vscode-python/issues/20949
> Add a section mentioning npm module for Python API

- api/advanced-topics/python-extension-template.md
- api/references/commands.md
- blogs/2023/07/20/mangling-vscode.md
- typo in a command ID
- prefer sentence casing headers
> Update social handle

- docs/getstarted/settings.md
I believe this is the correct command
> typo in settings.md

- docs/csharp/signing-in.md
- docs/getstarted/settings.md
- docs/getstarted/tips-and-tricks.md
- docs/languages/powershell.md
- docs/supporting/troubleshoot-terminal-launch.md
- release-notes/v1_19.md
- release-notes/v1_27.md
- release-notes/v1_31.md
Follow up to https://github.com/microsoft/vscode-docs/pull/6457
Also small edits to C# Dev Kit troubleshooting update.
> Update command name "Open User Settings (JSON)"

- docs/editor/userdefinedsnippets.md
- release-notes/v1_78.md
> Fix CURRENT_TIMEZONE_OFFSET example format

- docs/editor/accessibility.md
- docs/getstarted/tips-and-tricks.md
- docs/sourcecontrol/overview.md
- release-notes/v1_44.md
Update command ID and "Accessible Diff Viewer" UI name
> Updates for Accessible Diff Viewer rename

- blogs/2019/05/23/strict-null.md
- blogs/2020/05/14/vscode-build-2020.md
- blogs/2022/08/16/markdown-language-server.md
- release-notes/v1_71.md
Just updating my personal social link as my twitter is 🪦
> Update personal social link

- api/extension-guides/images/webview/webview-split-button-menu.png
- api/extension-guides/webview.md
> webview: Explain how to show a context menu on left/primary-click

- docs/terminal/shell-integration.md
> Add enhanced a11y to terminal shell integration page

- docs/editor/command-line.md
> Document VSCODE_RESOLVING_ENVIRONMENT

- docs/remote/remote-overview.md
- docs/remote/tunnels.md
- docs/remote/vscode-server.md
Update based on the latest info and to provide overall greater clarity.
cc @curib
> Updates to tunneling docs

- docs/sourcecontrol/github.md
- docs/sourcecontrol/images/github/create-pull-request-view.png
Text and screenshot to reflect the new UI.
> Update GitHub PR section and screenshot

- docs/csharp/cs-dev-kit-faq.md
- docs/other/images/unity/unity-externaltools.png
- docs/other/images/unity/unity-overview.png
- docs/other/images/unity/unity-packagemanager.png
- docs/other/unity.md
Not sure what is going on with the images and Git LFS and why they don't show up in the GitHub preview.
Will double-check this on the staging server after this PR is merged and built
> Update Unity topic for new extension

- build/sitemap.xml
- docs/python/editing.md
- docs/python/formatting.md
- docs/remote/troubleshooting.md
Also adding new Python formatting topic to sitemap
> Small edits to recent PRs

- docs/datascience/jupyter-kernel-management.md
https://github.com/microsoft/vscode-jupyter-internal/issues/445
> add codespaces jupyter server content

- docs/editor/settings-sync.md
ref https://github.com/microsoft/vscode/issues/189672
> Include another KDE workaround

- api/working-with-extensions/images/publishing-extension/deprecated-extension.png
- api/working-with-extensions/images/publishing-extension/deprecated-migrate-button.png
- api/working-with-extensions/images/publishing-extension/deprecated-migrate.png
- api/working-with-extensions/images/publishing-extension/deprecated-with-alternative-extension.png
- api/working-with-extensions/images/publishing-extension/deprecated-with-alternative-setting.png
- api/working-with-extensions/images/publishing-extension/deprecated-with-no-alternatives.png
- api/working-with-extensions/images/publishing-extension/deprecated.png
- api/working-with-extensions/publishing-extension.md
This PR is the continuation of the previous two: #6260 and #6356 
Sections that were refactored:
* Deprecating extensions
* Packaging extensions
* Your extension folder
* Visual Studio Code compatibility
This includes:
* Making the content uniform across the sections
* Updating the screenshots to be uniform and consistent
* Removing old screenshots
> Refactor extension management sections to be more concise

- docs/cpp/cmake-linux.md
Per discussion with CMake extension PM
> Bump CMake version to 3.27

- api/extension-guides/webview.md
> fix: update example code for webview to fix broken typescript assignment error

- api/extension-guides/webview.md
> fix: unhandled undefined value passed to reveal method example

- docs/editor/artificial-intelligence.md
- docs/editor/images/artificial-intelligence/copilot-chat-extension.png
- docs/editor/images/artificial-intelligence/open-in-chat-view.png
- docs/editor/images/artificial-intelligence/quick-chat-dropdown.png
Direct users to Copilot Chat stable
Add short Common questions section
> Add mention of Quick Chat

- api/extension-guides/markdown-extension.md
- docs/editor/artificial-intelligence.md
Also fix nit that Mermaid should be capitalized (noticed in another PR)
> Fix incorrect command ID

- api/references/contribution-points.md
Closes https://github.com/microsoft/vscode-docs/issues/6618
> Clarify that deprecationMessage hides setting

- api/references/contribution-points.md
> Correct terminal profile provider example

- api/extension-guides/webview.md
> fix: update example code for webview resource accessing to fix passing parameters of incorrect type

- docs/remote/tunnels.md
Fixes https://github.com/microsoft/vscode-docs/issues/6626
> Document more tunneling / CLI options

- docs/remote/faq.md
> Update remote faq

- api/references/contribution-points.md
Available since April 2023 (see https://github.com/microsoft/vscode/issues/180730)
> Document `editor/lineNumber/context` menu contribution point and its context key

- api/references/contribution-points.md
- api/references/theme-color.md
- docs/getstarted/images/tips-and-tricks/getstarted_page.png
- docs/getstarted/images/tips-and-tricks/interactive_playground.png
- docs/getstarted/images/tips-and-tricks/welcome-page.png
- docs/getstarted/tips-and-tricks.md
- release-notes/v1_61.md
- release-notes/v1_70.md
This was helpfully called out in https://github.com/microsoft/vscode-docs/pull/6642
Going a little further and updating images and other references to the Welcome page
> Get Started is now Welcome

- docs/nodejs/browser-debugging.md
Closes https://github.com/microsoft/vscode/issues/192895
> add docs for source map loading

- docs/datascience/azure-machine-learning.md
- docs/editor/vscode-web.md
- docs/getstarted/themes.md
Also add line break to Custom URL table to adjust column widths more equitably
> Small edits and formatting

- release-notes/v1_82.md
`workpsace` -> `workspace` ... would love to know what a psace is though
> v1_82.md: fix typo

- api/references/contribution-points.md
Part of microsoft/vscode#79034
> Document new terminal menu contribution points

- docs/supporting/requirements.md
Refs https://github.com/microsoft/vscode/issues/193086
> chore: update minimum supported linux distro versions

- docs/csharp/cs-dev-kit-faq.md
- docs/csharp/images/faq/dotnet-runtime-path.png
- docs/csharp/images/faq/dotnet-sdk-path.png
- docs/csharp/images/faq/dotnet-sdk-timeout.png
This is a basic edit/formatting pass
I did convert the settings.json screenshots to code blocks
@mikadumont @webreidi let me know if you'd like anything else updated
> Edit pass on C# Dev Kit FAQ updates

- docs/editor/accessibility.md
Part of microsoft/vscode#30522
Part of microsoft/vscode#191775
---
This doesn't need to go in until 1.83 as the feature is currently experimental and could change.
> Document dim unfocused views feature

- docs/terminal/images/shell-integration/recent-command.png
- docs/terminal/shell-integration.md
> Document recent command pinning

- api/references/contribution-points.md
- api/references/images/contribution-points/menu_view_title.png
> Add example for contributing to a view's actions

- release-notes/v1_83.md
> Perl 5 -> Perl 6

- .pipelines/onebranch.buddy.yml
- .pipelines/onebranch.official.yml
I know what happened. The previous PR got merged, and the builds that were green were actually from uncommitted changes. Here are those changes.
> Actually onboard onto MCR

- docs/datascience/data-science-tutorial.md
> Data Sci tutorial: select only numeric cols in pandas corr()

- api/references/contribution-points.md
Format with identifier first and description next similar to other sections of Contribution Points document.
> format menu contribution points

- api/references/commands.md
Takes most (but not all) of the output from _generateCommandsDocumentation and applies it to api/references/commands.md
> Refresh complex commands reference

- docs/devcontainers/tips-and-tricks.md
This pull request corrects the typo "strage" to "strange" in the Markdown file. I kindly request the repository maintainers to review and merge it.
> docs: fix typo in docs/devcontainers/tips-and-tricks.md

- docs/languages/python.md
For more on the pitfall that these instructions guide away from, see: https://stackoverflow.com/q/61628896/145173
> Run Python file in new terminal after running line.

- docs/azure/deployment.md
kubernetes is also one of important steps in deployment added in the next steps after deployment 
please have a loook and merge the pr @gregvanl
> Added kubernetes in the list 

- api/extension-guides/images/scm-provider/sourcecontrol-menu.png
- api/extension-guides/scm-provider.md
follow up PR to address comments about stale image in https://github.com/microsoft/vscode-docs/pull/6754
Also a little formatting and fix a broken API reference link
> Update image with context menu

- docs/editor/vscode-web.md
Fixes https://github.com/microsoft/vscode/issues/195552 with the info @jrieken provided
> Add browser version info

- docs/python/tutorial-fastapi.md
> Fix screenshots and shorten last header

- docs/python/tutorial-fastapi.md
Open Folder not available on macOS.
Couple of typos
> Remove non-existent keybindings

- docs/editor/port-forwarding.md
- docs/remote/tunnels.md
Update our tunneling-related docs:
- Mention Microsoft dev tunnels specifically 
- cc @curib please let me know if we should use any other capitalization, terminology, docs links, etc!
- Cross-link to info on Dev Containers + Remote-Tunnels (cc @chrmarti)
> Update port forwarding and Remote-Tunnels docs

- release-notes/v1_84.md
Fixed a couple of things in the release notes, namely the awkward repeat of "to the" regarding the Activity Bar, and changed the order of the codicons list to match the image.
> Fix language and list in v1_84.md

- docs/editor/github-copilot.md
- docs/editor/images/artificial-intelligence/deactivate-copilot.png
- docs/editor/images/artificial-intelligence/disable-completions.png
- docs/editor/images/artificial-intelligence/show-copilot-status-menu.png
More updates coming in later PRs (agents, etc) but this updates the obsolete activate/deactivate instructions.
> Update disable completions section

- docs/editor/github-copilot.md
- docs/editor/images/artificial-intelligence/command-palette-ask-copilot.png
- docs/editor/images/artificial-intelligence/copilot-answer-hide-editor-overview.png
- docs/editor/images/artificial-intelligence/copy-code-block.png
- docs/editor/images/artificial-intelligence/generate-commit-message.png
- docs/editor/images/artificial-intelligence/more-actions-code-block.png
- docs/editor/images/artificial-intelligence/run-in-terminal.png
- docs/editor/images/artificial-intelligence/sparkle-icon.png
Chat view keyboard shortcuts
Chat code blocks actions
Mention other types of Copilot integration (sparkles, Ask Git Copilot in Command Palette)
> Add new features to Copilot topic

- build/sitemap.xml
- docs/cpp/configure-intellisense.md
Follow up PR for https://github.com/microsoft/vscode-docs/pull/6614
Also use Markdown `<details>` flyouts for sample sections
> Update links, edit/formatting pass for C++ IntelliSense

- api/references/theme-color.md
> Add window.activeBorder/inactiveBorder caveats

- api/advanced-topics/remote-extensions.md
- docs/containers/choosing-dev-environment.md
- docs/editor/images/artificial-intelligence/open-session-in-sidebar.png
- docs/editor/settings-sync.md
- release-notes/v1_72.md
- release-notes/v1_82.md
No need to shout in Notes
Crop a Copilot chat image to avoid a half-truth
> Small follow up edits

- docs/editor/github-copilot.md
- docs/editor/images/artificial-intelligence/terminal-command-explanation.png
- docs/editor/images/artificial-intelligence/terminal-quick-fix.png
Also correct the description of the GHPRI Create view sparkle
> Add example of terminal Copilot sparkle

- docs/editor/github-copilot.md
- docs/editor/images/artificial-intelligence/editor-copilot-menu.png
- docs/editor/images/artificial-intelligence/generate-docs-example.png
- docs/editor/images/artificial-intelligence/inline-chat-fix-example.png
- docs/editor/images/artificial-intelligence/inline-chat-slash-commands.png
List the inline chat slash commands
Mention editor Copilot menu group
Add Common Question for lost Chat view
> More Copilot doc updates

- docs/editor/custom-layout.md
Prompted by https://github.com/microsoft/vscode/issues/197873
> Clarify that Panel can only be maximized when center-aligned

- docs/editor/workspaces.md
> Minor copy edits

- docs/python/python-tutorial.md
Adding a call out to the VS Code for Education Introduction to Python course.
> Adding VS Code for Edu link to Python tutorial

- docs/csharp/cs-dev-kit-faq.md
- docs/csharp/debugging.md
- docs/csharp/images/debugging/hotreload-demo.gif
- docs/csharp/images/debugging/hotreload-statusbar.png
- docs/csharp/images/debugging/hotreload-toolbar.png
Add documentation and examples regarding the C# Dev Kit support for Hot Reload.
> C#: Add Hot Reload section for C# Dev Kit

- docs/typescript/typescript-tutorial.md
Modified the 404 not found page to work properly.
> Update typescript-tutorial 404 not found urls

- docs/csharp/cs-dev-kit-faq.md
- docs/csharp/debugging.md
Now that the documentation has been updated with Hot Reload information, I added some small corrections around grammar and consistency that I originally missed.
> C#: Minor updates to Hot Reload documentation

- docs/editor/command-line.md
- docs/editor/portable.md
Follow up PR for https://github.com/microsoft/vscode-docs/pull/6309
Use brief text for portable mode caveats in command-line.md
Move hyperlink in code block to a Note
> follow up for recent portable PR

- api/references/contribution-points.md
- docs/editor/custom-layout.md
- docs/editor/debugging.md
- docs/editor/images/custom-layout/activity-bar-top.png
- docs/editor/refactoring.md
- docs/getstarted/images/userinterface/activity-bar-context-menu.png
- docs/getstarted/images/userinterface/tabs-hero.png
- docs/getstarted/images/userinterface/wrapped-tabs.png
- docs/getstarted/userinterface.md
Add mention of:
editor tab scroll bar and sizing
wrapped editor tabs
Activity bar position (now includes top)
refresh some stale UI images
update editor.suggestions setting
fixes #6846 talking about green squiggles
> Update UI topics for new features

- api/ux-guidelines/sidebars.md
> Typos in api/ux-guidelines/sidebars #6857

- docs/editor/github-copilot.md
This pull request includes minor updates to the `docs/editor/github-copilot.md` file, such as correcting links, fixing grammar, and updating sentences.
* <a href="diffhunk://#diff-40bf2043a45cfc45111754ca825a9599619721464f2365855042acc6ae288344L380-R380">`docs/editor/github-copilot.md`</a>: Corrected links, fixed grammar, and updated sentences. <a href="diffhunk://#diff-40bf2043a45cfc45111754ca825a9599619721464f2365855042acc6ae288344L380-R380">[1]</a> <a href="diffhunk://#diff-40bf2043a45cfc45111754ca825a9599619721464f2365855042acc6ae288344L120-R120">[2]</a> <a href="diffhunk://#diff-40bf2043a45cfc45111754ca825a9599619721464f2365855042acc6ae288344L362-R362">[3]</a>
> [VS Code] Fix typos in Copilot article

- docs/languages/identifiers.md
[ref1](https://github.com/microsoft/vscode/blob/0e16324eff7e45a43223f9c11dafa1b3768d3174/extensions/julia/package.json#L17), [ref2](https://github.com/julia-vscode/julia-vscode/blob/6710d6c9b678a601aaa7ce8f2752ca4f72220701/package.json#L77)
> Add Julia to list of known language identifiers

- remote/advancedcontainers/connect-multiple-containers.md
- Updated the example source tree
- Updated the example `docker-compose.yml`
- Update each `devcontainer.json`
- Added section for use of `Dev Containers: Switch Container` command. 
- Updated Extend Docker Compose section to reflect new structure
> Updated connect to multiple containers command

- api/references/theme-color.md
added new themes via endgame script
> added new themes

- docs/editor/custom-layout.md
- docs/getstarted/images/userinterface/sticky-scroll.png
- docs/getstarted/userinterface.md
> Adding official documentation for sticky scroll

- docs/editor/vscode-web.md
Updating based on the latest changes. These are only in insiders for now, so let's wait to merge this PR until the next stable @gregvanl.
> Update vscode.dev URLs

- docs/editor/github-copilot.md
- release-notes/v1_86.md
Also fixing updated terminal Quick Fix flow
> Add 1.86 placeholder for Insiders

- build/sitemap.xml
Remove obsolete landing page and blog post experiment (just use code.visualstudio.com/blogs)
Remove extra '>'
Add missing intro video
> Tidy up sitemap

- docs/setup/enterprise.md
> Words reordering

- api/references/icons-in-labels.md
This PR includes updates to the `icons-in-labels.md` documentation.
> Added new icon references to documentation

- docs/terminal/shell-integration.md
Fixes https://github.com/microsoft/vscode-docs/issues/6918
> Clarify terminal command navigation shift modifier

- api/references/commands.md
for https://github.com/microsoft/vscode/issues/200453
> document arguments for findWithArgs

- docs/csharp/debugger-settings.md
Related: https://github.com/microsoft/vscode-dotnettools/issues/820
> Update checkForDevCert for C# Debugging Settings

- docs/cpp/config-mingw.md
- docs/cpp/introvideos-cpp.md
We have released two C++ youtube videos to supplement the docs, which are added to our docs in this PR.
> Add References to new C++ Youtube Videos

- docs/supporting/faq.md
- docs/supporting/requirements.md
Follow-up to https://github.com/microsoft/vscode/pull/192513
> docs: add client faq for older linux versions

- docs/remote/faq.md
Needed for https://github.com/microsoft/vscode/pull/202210
> docs: add remote faq for older linux versions

- docs/java/java-project.md
> Clarify Bazel Java plugins

- docs/remote/faq.md
- docs/supporting/faq.md
- docs/supporting/requirements.md
Backports https://github.com/microsoft/vscode-docs/pull/6954 and https://github.com/microsoft/vscode-docs/pull/6953
> docs: update faq for linux client and remote

- release-notes/v1_85.md
This pull request includes a single change to update the download version of Visual Studio Code for the November 2023 release from `1.85.1` to `1.85.2`.
* [`release-notes/v1_85.md`](diffhunk://#diff-517ae69b5fe0e32171419f22f7d114421d0ca986e23583ad8e58b99ac0aaa2a7L8-R15): Updated the download version of Visual Studio Code for the November 2023 release from `1.85.1` to `1.85.2`.
> Update release note for recovery release 1.85.2

- api/extension-guides/virtual-workspaces.md
Just a simple spelling correction :)
> Fix spelling error in docs

- api/extension-guides/command.md
https://code.visualstudio.com/api/extension-guides/command#using-a-custom-when-clause-context
> Numbers stay consistent

- api/references/theme-color.md
> Documenting the new colors in theme-color.md file

- docs/cpp/config-mingw.md
Updated the download link for MSYS2 installer to the most recent one.
> I updated  the download link for the MSYS2 installer, which is the most recent

- release-notes/v1_86.md
Pushed to vnext but it's already been merged into main
> Clarify terminal notes

- release-notes/v1_86.md
> Fix typo in release notes 1.86

- release-notes/v1_86.md
"while holder [key]" changed to "while holding [key]"
> Fix typo in release notes for v1.86

- docs/getstarted/settings.md
The original text is confusing.
> update `formatOnSave` in settings.md

- release-notes/v1_86.md
Updating the release notes for recovery release 1.86.2
> Updating release notes for 1.86.2

- release-notes/v1_86.md
> Updating the release notes for recovery release

- api/references/commands.md
Realized with https://github.com/microsoft/vscode-dev/issues/1038 that the walkthrough command is not documented.
> Update commands.md to add walkthrough command

- api/index.md
> Update Stack Overflow link.

- api/extension-guides/chat.md
- api/extension-guides/images/chat/chat.png
- api/extension-guides/images/chat/commands.png
- api/extension-guides/images/chat/diagram-lm.png
- api/extension-guides/images/chat/diagram.png
- api/extension-guides/images/chat/stream.png
- api/extension-guides/images/chat/variables.png
- api/extension-guides/language-model.md
- api/toc.json
- build/sitemap.xml
Cherry-picking commits from vnext to publish extension guides to production website.
> Add Chat & Language Model extension guides

- docs/remote/tunnels.md
The bandwidth limit was increased to 5GB and number of tunnels was increased to 10.
> Update tunnels doc

- api/extension-guides/chat.md
> Minor chat doc updates

- api/references/theme-color.md
added 2 theme colors via `scripts/test-documentation.sh`
> added theme colors via `test-documentation`

- docs/editor/images/accessibility/editor-dictate.png
- docs/editor/images/accessibility/hey-code.png
- docs/editor/images/accessibility/speech-extension.png
- docs/editor/images/accessibility/voice-chat.png
- docs/editor/voice.md
> Add a topic around voice support

- release-notes/v1_87.md
Fixed a few things in the release notes. Possibly too much for one PR - please let me know.
> Fix some language issues in v1_87.md

- docs/csharp/cs-dev-kit-faq.md
This PR adds information about why users are getting a password prompt on macOS and the commands to by pass it.
cc @gregg-miskelly
> Add macOS Debugging FAQ

- release-notes/images/1_87/pylance-add-imports.mp4
> Fix release note video encoding

- api/extension-guides/webview.md
I couldn't run the code sample in question because it has syntax errors.
> Fix incorrect code sample in api/extension-guides/webview.md

- blogs/2023/11/13/vscode-copilot-smarter.md
Use chat *participant* instead of *agent*.
> Update chat agent terminology in blog

- api/get-started/your-first-extension.md
> Extensions Getting started - Fix video links

- docs/editor/images/refactoring/refactor-preview-launch.gif
- docs/editor/images/refactoring/refactor-preview-partial.png
- docs/editor/images/refactoring/refactor-preview.png
- docs/editor/refactoring.md
> Add Refactor Preview to refactoring docs

- docs/terminal/shell-integration.md
> Document OSC 1337 ; CurrentDir and 633 E nonce

- docs/csharp/get-started.md
- docs/languages/dotnet.md
> Remove references to .NET Coding Pack

- docs/terminal/shell-integration.md
> Adopt kb for a couple of shell integration keybindings

- docs/setup/setup-overview.md
They went out of sync in 78d1fc5735f8270d7297e9e8f7f95f7e134b0eaa
> Make download size and disk footprint consistent with requirements.md

- docs/editor/debugging.md
- docs/editor/images/debugging/debug-menu.png
> Review debugging content

- docs/editor/images/workspaces/add-remove-folder-in-workspace.png
- docs/editor/workspaces.md
> Edit pass for workspaces article

- docs/terminal/profiles.md
> Add example of a newWithProfile keybinding

- api/references/contribution-points.md
> Document terminal menu groups

- docs/sourcecontrol/images/intro/git-clone-repository-url.png
- docs/sourcecontrol/images/intro/open-workspace-in-codespace.png
- docs/sourcecontrol/images/intro/publish-to-github.png
- docs/sourcecontrol/images/intro/scm-create-branch.png
- docs/sourcecontrol/images/intro/scm-create-pull-request.png
- docs/sourcecontrol/images/intro/scm-init-publish.png
- docs/sourcecontrol/images/intro/scm-menu.png
- docs/sourcecontrol/images/intro/scm-stage-changes.png
- docs/sourcecontrol/images/intro/scm-unstage-changes.png
- docs/sourcecontrol/images/intro/source-control-view.png
- docs/sourcecontrol/images/intro/timeline.png
- docs/sourcecontrol/images/intro/vscode-accounts-menu.png
- docs/sourcecontrol/intro-to-git.md
> Review Intro to Git article

- docs/editor/images/refactoring/refactoring-hero.png
- docs/editor/images/refactoring/ts-extract-local.gif
> Update refactoring screenshots

- api/references/theme-color.md
cherry-pick of some vnext changes into main
> docs: add newer colors

- docs/editor/custom-layout.md
- release-notes/v1_88.md
> Fix keybinding references

- docs/languages/images/Markdown/markdown-paste-link.png
- docs/languages/images/Markdown/math-formula-rendering.png
- docs/languages/markdown.md
> Markdown docs refresh

- docs/sourcecontrol/images/overview/scm-git-editor.gif
- docs/sourcecontrol/overview.md
> Add commit message editing in editor

- docs/csharp/debugging.md
Fixes a formatting problem on this page:
https://code.visualstudio.com/docs/csharp/debugging
> Fix formatting of symbol server options

- docs/copilot/getting-started-chat.md
- docs/copilot/getting-started.md
> Fix keybindings for Chat view

- docs/setup/additional-components.md
> Fix language for list of popular extensions

- release-notes/v1_89.md
> Fix docs links in release note

- release-notes/images/1_89/pylance-implement-abstract-classes.mp4
Fixes https://github.com/microsoft/vscode-docs/issues/7254
> Update video encoding

- docs/supporting/images/troubleshoot-terminal-launch/search-for-modified-settings.png
- docs/supporting/images/troubleshoot-terminal-launch/search-for-settings.png
- docs/supporting/images/troubleshoot-terminal-launch/settings-json-file.png
- docs/supporting/troubleshoot-terminal-launch.md
Fixes https://github.com/microsoft/vscode-docs/issues/7204
> Update terminal troubleshooting screenshots

- docs/csharp/cs-dev-kit-faq.md
- docs/csharp/get-started.md
- docs/csharp/images/get-started/InstallSDK.png
Updates to remove old information and add new stuff being released 5/7.
> Updating C# FAQ and Getting started

- docs/cpp/cpp-ide.md
I have removed the duplicate content and kept the bulleted content above. Feel free to let me know if further adjustments are needed.
fixed: #7279, #7278
> Remove Duplicate information in `docs/cpp/cpp-ide.md`

- docs/cpp/cpp-ide.md
Fixes https://github.com/microsoft/vscode-docs/issues/7280
> Remove reference to missing keybinding

- api/extension-guides/chat.md
> Update chat extension guide with naming conventions and restrictions

- docs/copilot/faq.md
add faq about blocked extensions to copilot docs
> add faq about blocked extensions

- docs/editor/extension-marketplace.md
- docs/editor/images/extension-marketplace/settings-sync-extensions.png
- docs/editor/images/settings-sync/sync-accounts.png
- docs/editor/images/settings-sync/sync-configure.png
- docs/editor/images/settings-sync/turn-on-sync.png
- docs/editor/profiles.md
- docs/editor/settings-sync.md
- docs/getstarted/images/settings/accounts-context-menu.png
- docs/getstarted/settings.md
Fixes https://github.com/microsoft/vscode-docs/issues/7221
> Settings Sync not supported for remote

- docs/editor/extension-marketplace.md
there's no @oudated filter, only @updates
> corrected a typo

- api/extension-guides/task-provider.md
Just improves the clarity and readability of the mentioned section.
> Task providers: Improve clarity in 'when clause' section

- docs/csharp/debugging.md
- docs/csharp/images/debugging/function-breakpoint.gif
This PR adds a section for Function Breakpoints in the debugging.md for csharp.
@gregg-miskelly
> Add Function Breakpoint Docs

- docs/editor/accessibility.md
- docs/editor/codebasics.md
- docs/editor/custom-layout.md
- docs/editor/editingevolved.md
- docs/editor/extension-marketplace.md
- docs/editor/images/extension-marketplace/extension-search-filters.png
- docs/editor/intellisense.md
- docs/editor/multi-root-workspaces.md
- docs/editor/port-forwarding.md
- docs/editor/voice.md
- docs/editor/workspace-trust.md
- docs/editor/workspaces.md
- docs/nodejs/working-with-javascript.md
Fixes https://github.com/microsoft/vscode-docs/issues/7353
Fixes https://github.com/microsoft/vscode-docs/issues/7337
Fixes https://github.com/microsoft/vscode-docs/issues/7336
Fixes https://github.com/microsoft/vscode-docs/issues/7340
> Various docs fixes

- docs/cpp/config-mingw.md
- docs/languages/cpp.md
- This PR improves the documentation regarding update PATH variable section.
- The PR fixes the issue #7344
> doc-enhancement/update PATH variable

- learn/educators/installers.md
Fixes https://github.com/microsoft/vscode-docs/issues/7370
> Remove .NET coding pack

- docs/cpp/config-linux.md
Without return statement there will be errors while running
> The main should return a int.

- api/extension-guides/chat.md
@ntrogh what do you think about this?
Just reading the docs and stumbling upon GitHub apps I found confusing. So I created a new short section, that might grow over time.
> GitHub app deservers a separate section

- docs/python/editing.md
- docs/python/images/editing/auto-import-suggestion.png
For https://github.com/microsoft/pylance-release/issues/5996
Adding a screenshot and clarifying a bit the wording on our docs to make it clearer how auto import suggestions work
> Clarify how auto imports work in Python

- api/working-with-extensions/publishing-extension.md
Update the domain validation section to better explain the validation that takes place for Visual Studio Marketplace domains to get the blue checkmark, the time it can take and notes around when validation can be revoked
> Update publishing-extension.md to better reflect VS Marketplace domain validation

- docs/devcontainers/create-dev-container.md
Fixes https://github.com/microsoft/vscode-docs/issues/7398
> Fix docker-compose file reference (#7398)

- docs/python/python-tutorial.md
Fixes https://github.com/microsoft/vscode/issues/218052
> Python tutorial: fix image link

- api/get-started/wrapping-up.md
- added documentation on contributing menu/issue reporter command
> update some extension reporting guidlines

- release-notes/images/1_91/accessible-view-hover.png
- release-notes/images/1_91/apply-in-editor.png
- release-notes/images/1_91/copilot-terminal-hint.png
- release-notes/images/1_91/debug-shadowed.png
- release-notes/images/1_91/extension-install-actions.png
- release-notes/images/1_91/incoming-outgoing-changes.png
- release-notes/images/1_91/inline-chat.png
- release-notes/images/1_91/notebook-find-in-selection.mp4
- release-notes/images/1_91/notebook-output-context-menu.mp4
- release-notes/images/1_91/profile-new-window-actions.png
- release-notes/images/1_91/profiles-editor-action.png
- release-notes/images/1_91/profiles-editor.png
- release-notes/images/1_91/pylance-restructuredtext.png
- release-notes/images/1_91/quick-toggle-readonly.png
- release-notes/images/1_91/release-highlights.png
- release-notes/images/1_91/terminal-powerline-scale.png
- release-notes/images/1_91/terminal-powerline.png
- release-notes/images/1_91/ts-new-escape-from-regexp-error.png
- release-notes/images/1_91/ts-regexp-invalid-group.png
- release-notes/images/1_91/underline-links.png
- release-notes/v1_91.md
Verify that release notes appear correctly in-product. Release notes don't show on website.
> Validate 1.91 release notes in insiders

- docs/editor/codebasics.md
- docs/getstarted/tips-and-tricks.md
- docs/sourcecontrol/overview.md
Fixes https://github.com/microsoft/vscode-docs/issues/7284
> Add compare files functionality

- release-notes/v1_91.md
This pull request updates the release notes to version 1.91.1 and includes a link to the addressed issues.
> Update to 1.91.1 Release

- api/references/activation-events.md
Got the description from here: 
https://github.com/microsoft/vscode/blob/5e25f3eecf5865a1780545455891cfc18e29e561/src/vs/workbench/services/extensions/common/extensionsRegistry.ts#L315
> document `onTaskType` activation event

- docs/editor/multi-root-workspaces.md
"an File Icon Theme" => "a File Icon Theme"
> minor grammar correction

- api/extension-guides/chat.md
> measuring success

- api/extension-guides/chat.md
> minor polish of Measuring Success docs

- release-notes/v1_92.md
> Fix a few release notes setting links

- build/sitemap.xml
- docs/getstarted/educators-and-students.md
- docs/getstarted/images/educators-and-students/codetour-example-lesson.gif
- docs/getstarted/images/educators-and-students/codetour-extension-marketplace.png
- docs/getstarted/images/educators-and-students/codetour-space-jam.gif
- docs/getstarted/images/educators-and-students/live-share-extension.png
- docs/getstarted/images/educators-and-students/liveshare-icon.png
- docs/getstarted/images/educators-and-students/liveshare-invitation.png
- docs/getstarted/images/educators-and-students/liveshare-join-session.png
- docs/getstarted/images/educators-and-students/liveshare-joined.png
Ref https://github.com/microsoft/vscode-internalbacklog/issues/5005
> Add Educators & Students page

- docs/devcontainers/faq.md
- docs/remote/faq.md
- remote/advancedcontainers/use-docker-kubernetes.md
Fixes https://github.com/microsoft/vscode-docs/issues/7449
> Update dev container Template and Feature links, naming

- docs/nodejs/images/vuejs/vue-extension.png
- docs/nodejs/vuejs-tutorial.md
Update the vue.js tutorial to use the vue.js official recommended extension
Fixes https://github.com/microsoft/vscode-docs/issues/7519
> fix: vue recommend extension

- api/extension-guides/language-model.md
Since it's just a static method:
```typescript
export class LanguageModelChatMessage {
static User(content: string, name?: string): LanguageModelChatMessage;
}
```
> Remove `new` from `vscode.LanguageModelChatMessage.User`

- api/language-extensions/embedded-languages.md
Removed language that insinuated pull diagnostics were planned.
> To Close Issue #7536: Update "Embedded Programming Languages"

- docs/java/java-faq.md
- docs/java/java-tutorial.md
- docs/languages/java.md
For reference, see:
- redhat-developer/vscode-java#3728
- eclipse-jdtls/eclipse.jdt.ls#3266
> Update supported Java versions

- docs/cpp/config-clang-mac.md
Fixes https://github.com/microsoft/vscode-docs/issues/7565
> Clarify adding a watch variable

- docs/getstarted/images/settings/activity-bar-hidden.png
- docs/getstarted/images/settings/color-customization-example.png
- docs/getstarted/images/settings/search-for-activity.png
- docs/getstarted/images/settings/settings-editor-user-tab.png
- docs/getstarted/images/settings/settings-editor-workspace-tab.png
- docs/getstarted/images/settings/settings-modified.png
- docs/getstarted/settings.md
Fixes https://github.com/microsoft/vscode-docs/issues/7480
> Update Settings article (refresh & application settings)

- docs/getstarted/educators-and-students.md
- docs/getstarted/images/tips-and-tricks/open-walkthrough.png
- docs/getstarted/tips-and-tricks.md
Resolves https://github.com/microsoft/vscode-docs/issues/7547
> Update walkthroughs info

- docs/getstarted/getting-started.md
- docs/getstarted/introvideos.md
- docs/getstarted/tips-and-tricks.md
Resolves https://github.com/microsoft/vscode-docs/issues/7359
> Publish VS Code tutorial

- docs/python/python-tutorial.md
> Fixed missing "!" in code

- docs/editor/images/workspace-trust/gear-manage-workspace-trust.png
- docs/editor/images/workspace-trust/restricted-mode-banner.png
- docs/editor/images/workspace-trust/restricted-mode-status-bar.png
- docs/editor/images/workspace-trust/trust-parent-folder.png
- docs/editor/images/workspace-trust/workspace-trust-buttons.png
- docs/editor/images/workspace-trust/workspace-trust-editor.png
- docs/editor/workspace-trust.md
Resolves https://github.com/microsoft/vscode-docs/issues/7545
> Refresh Workspace Trust content

- CONTRIBUTING.md
Resolves https://github.com/microsoft/vscode-docs/issues/7590
> Update repo structure description

- docs/devcontainers/attach-container.md
- docs/devcontainers/containers.md
- docs/remote/ssh.md
microsoft/vscode-remote-release#6054
> Update Attach to Kubernetes docs

- docs/languages/python.md
- docs/python/python-tutorial.md
Updating Run options to include Smart Send
> Updating Python Run options to reference Smart Send

- docs/csharp/get-started.md
Fixes https://github.com/microsoft/vscode-docs/issues/7634
> Fix command ID for Run without Debugging

- docs/editor/extension-marketplace.md
Resolves https://github.com/microsoft/vscode-docs/issues/7623
> Add guidance for signature verification errors

- api/extension-guides/chat.md
Resolves https://github.com/microsoft/vscode-docs/issues/7543
> Chat response output types

- api/references/contribution-points.md
- api/references/images/contribution-points/settings-ui-enum.png
- api/references/images/contribution-points/settings-ui-icon-theme.png
> Fix enum docs, fixes #7511

- api/references/contribution-points.md
> Clarify point 5 for #7511

- api/extension-guides/images/lm-api/code-tutor-annotations-gif.gif
- api/extension-guides/images/lm-api/code-tutor-hello-world.png
- api/extension-guides/images/lm-api/code-with-annotations.png
- api/extension-guides/images/lm-api/toggle-tutor-annotations-button.png
- api/extension-guides/images/lm-api/tutor-command-command-palette.png
- api/extension-guides/language-model-tutorial.md
> Add Language Model API Tutorial

- api/extension-guides/chat.md
- docs/copilot/copilot-chat.md
> docs: add note about local editor context

- docs/getstarted/images/userinterface/timeline-filter.png
- docs/getstarted/images/userinterface/timeline-view.png
- docs/getstarted/userinterface.md
Fixes https://github.com/microsoft/vscode-docs/issues/6677
> Document timeline view

- .pipelines/onebranch.buddy.yml
- .pipelines/onebranch.official.yml
- .pipelines/templates/jobs/build.yml
- .pipelines/templates/stages/build-buddy.yml
- .pipelines/templates/stages/build-official.yml
Match the templates we use elsewhere in VS Code.
> chore: migrate to 1ES pipeline templates

- api/extension-guides/chat.md
- docs/copilot/copilot-chat.md
References https://github.com/microsoft/vscode-docs/pull/7671
> Remove GH Apps from Chat extension guide

- docs/sourcecontrol/overview.md
Fixes https://github.com/microsoft/vscode-docs/issues/7697
> Fix broken link in SCM docs

- docs/editor/debugging.md
A fresh command title has came out for the command 'Start Without Debugging'
> Outdated command title

- api/extension-guides/chat.md
- api/extension-guides/language-model.md
> update docs to specify request.model usage, and not selectChatModel

- docs/editor/debugging.md
> fix: little typo

- api/language-extensions/semantic-highlight-guide.md
https://github.com/microsoft/vscode/blob/main/src/vs/platform/theme/common/tokenClassificationRegistry.ts
Please look at line 562
> The scope of the macro token map is incorrect

- release-notes/images/1_95/demo-alt-text.gif
- release-notes/images/1_95/demo.gif
- release-notes/v1_95.md
Fixes https://github.com/microsoft/vscode-docs/issues/7726
> Fix image links

- api/extension-capabilities/common-capabilities.md
ref https://github.com/microsoft/vscode/issues/213903
> Add Secret Storage call out to extension author docs

- release-notes/v1_95.md
[Previous PR](https://github.com/microsoft/vscode-docs/pull/7724 )
I accidentally deleted the previous forked repository, so I resubmitted the PR.
> fix: release notes v_1.95 link issue

- api/extension-guides/testing.md
- api/extension-guides/web-extensions.md
- docs/azure/mongodb.md
- docs/copilot/getting-started.md
- docs/csharp/debugging.md
- docs/csharp/package-management.md
- docs/getstarted/tips-and-tricks.md
- docs/java/java-project.md
- docs/supporting/oss-extensions.md
Christmas is early and you get a small present with spelling fixes to things i have found across the repo.
Enjoy !
> Spelling Fixes

- docs/editor/vscode-web.md
> Clarify "compute"

- api/references/contribution-points.md
ref https://github.com/microsoft/vscode/issues/233757
> Add authentication to contribution points

- docs/devcontainers/create-dev-container.md
> Remove reference to removed logo

- api/references/commands.md
Fixes https://github.com/microsoft/vscode-docs/issues/7790
> Update Commands reference

- .pipelines/onebranch.buddy.yml
Ref https://github.com/microsoft/vscode-website/issues/2006
Verification build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=306579&view=results
> chore: enable SBOM for unofficial builds

- docs/editor/tasks.md
Fixes https://github.com/microsoft/vscode-docs/issues/7810
> Add instanceLimit option

- remote/advancedcontainers/persist-bash-history.md
https://github.com/microsoft/vscode-remote-release/issues/9931
> Add note on automatic UID:GID update

- api/extension-guides/chat.md
This pr would like to correct a SyntaxError of example code snippet for contributing a chatParticipant in the `API/EXTENSION_GUIDES/chat` article!
> correct json code snippet of Implement participant detection.

- docs/python/debugging.md
Addresses feedback from https://github.com/microsoft/vscode-python/issues/23003
> Addressing feedback about pickArgs

- blogs/2024/11/15/introducing-github-copilot-for-azure.md
@ntrogh - would you please let me know if this is an appropriate change for the VS Code blog?
> Update with Reynald's video

- api/language-extensions/images/syntax-highlighting/yaml-grammar.png
Fixes https://github.com/microsoft/vscode-docs/issues/7844
> Syntax highlighter guide: update screenshot

- docs/csharp/package-management.md
Added information about a setting for c#  users to include prerelease packages in their NuGet searches.
> Add information about prerelease packages setting.

- docs/remote/troubleshooting.md
https://github.com/microsoft/vscode-remote-release/issues/6426
> Remote - SSH: Add details on modifying the $EDITOR variable

- docs/languages/cpp.md
Fixes https://github.com/microsoft/vscode-docs/issues/6978
> Update docs to remove confusion

- docs/editor/images/refactoring/code-actions-on-save.png
- docs/editor/refactoring.md
Fixes https://github.com/microsoft/vscode-docs/issues/5276
> Add Code Actions on save

- api/ux-guidelines/images/examples/javascript-update-imports-dialog.png
- api/ux-guidelines/images/examples/save-ai-generated-changes-dialog.png
- api/ux-guidelines/notifications.md
Fixes https://github.com/microsoft/vscode-docs/issues/4425
> Add guidelines for modal dialogs

- release-notes/v1_90.md
Fixes https://github.com/microsoft/vscode-docs/issues/7885
> Fix typo in past release note

- build/sitemap.xml
- docs/getstarted/introvideos.md
- docs/introvideos/codeediting.md
- docs/introvideos/configure.md
- docs/introvideos/customize.md
- docs/introvideos/productivity.md
Fixes https://github.com/microsoft/vscode-website/issues/2020
> Remove OnePlayer video player

- docs/containers/ssh.md
Fixes https://github.com/microsoft/vscode-docs/issues/7898
> Add note to install Docker extension

- api/references/commands.md
Fixes https://github.com/microsoft/vscode-docs/issues/7913
> Re-add vscode-open details

- docs/setup/windows.md
Ref: https://github.com/microsoft/vscode/issues/122951, https://github.com/microsoft/vscode/issues/233953
> Update run as admin instructions

- docs/terminal/appearance.md
See microsoft/vscode#233006, microsoft/vscode#237503
> Update ligatures documentation for stable ligatures

- docs/editor/images/testing/copilot-fix-test-failure.png
- docs/editor/images/testing/editor-failed-test-message.png
- docs/editor/images/testing/run-debug-tests-editor-gutter.png
- docs/editor/images/testing/test-explorer-view-test-results.png
- docs/editor/testing.md
Ref: https://github.com/microsoft/vscode-docs/issues/7905
> Add Copilot to Testing docs

- docs/editor/portable.md
- release-notes/v1_59.md
Fixes https://github.com/microsoft/vscode/issues/237948
> Include instructions for Linux sandboxing

- docs/editor/testing.md
fixes https://github.com/microsoft/vscode-docs/issues/7947
> Fix bookmark

- docs/getstarted/copilot-quickstart.md
- docs/getstarted/getting-started.md
- docs/getstarted/images/getting-started/code-action-fix-with-copilot.png
- docs/getstarted/images/getting-started/copilot-chat-intro.mp4
- docs/getstarted/introvideos.md
- docs/getstarted/keybindings.md
- docs/getstarted/locales.md
- docs/getstarted/settings.md
- docs/getstarted/telemetry.md
- docs/getstarted/themes.md
- docs/getstarted/tips-and-tricks.md
- Add link to Copilot Quickstart in "Getting Started" ToC section
- Add Copilot in VS Code tutorial
> Update Getting Started with Copilot

- docs/typescript/images/compiling/version-status-bar.png
- docs/typescript/typescript-compiling.md
Ref. https://github.com/microsoft/vscode-docs/pull/7967
> Update TypeScript version screenshot

- docs/toc.json
FIrst step in managing the ToC for Docs independently from article metadata and website infra.
> Add docs toc.json file

- docs/copilot/copilot-customization.md
- docs/copilot/copilot-settings.md
- docs/copilot/copilot-vscode-features.md
Implements https://github.com/microsoft/vscode-docs/issues/7974
> Add prompt files documentation

- docs/copilot/copilot-customization.md
- release-notes/v1_97.md
Fixes https://code.visualstudio.com/docs/copilot/workspace-context#_basic-index
> Release note fixes

- docs/editor/images/intellisense/intellisense.mp4
- docs/editor/images/intellisense/intellisense_docs.gif
- docs/editor/images/intellisense/intellisense_docs.mp4
- docs/editor/images/intellisense/intellisense_icons.png
- docs/editor/images/intellisense/intellisense_packagejson.gif
- docs/editor/images/intellisense/intellisense_packagejson.mp4
- docs/editor/images/intellisense/paramater_info.png
- docs/editor/images/intellisense/tabCompletion.gif
- docs/editor/images/intellisense/tabCompletion.mp4
- docs/editor/intellisense.md
- docs/toc.json
Fixes https://github.com/microsoft/vscode-docs/issues/7986
> Refresh Intellisense doc

- docs/setup/enterprise.md
Add a couple commas to help the JSON display properly.
> Enterprise doc typo

- docs/copilot/ai-powered-suggestions.md
- release-notes/v1_97.md
Update with the exact setting name with capitalization.
> Update setting info

- docs/copilot/faq.md
Fixes https://github.com/microsoft/vscode-docs/issues/8024
> Fix Copilot Free target URL

- .gitattributes
- docs/copilot/ai-powered-suggestions.md
- docs/copilot/faq.md
- docs/copilot/images/overview/change-completions-model.png
- docs/copilot/images/overview/configure-completions.png
Issue tracking: https://github.com/github/copilot/issues/15386
Per gpt-4o-copilot release: https://github.com/github/releases/issues/5319
> add docs on changing completions model

- docs/copilot/copilot-settings.md
- docs/cpp/config-clang-mac.md
- docs/cpp/config-linux.md
- docs/cpp/config-mingw.md
- docs/cpp/config-msvc.md
- docs/cpp/config-wsl.md
- docs/editor/debugging.md
- docs/editor/tasks.md
- docs/editor/workspaces/multi-root-workspaces.md
- docs/python/settings-reference.md
- docs/python/testing.md
- docs/reference/images/variables-reference/run-input-example.gif
- docs/reference/variables-reference.md
- docs/terminal/advanced.md
- docs/terminal/profiles.md
- docs/toc.json
Fixes https://github.com/microsoft/vscode-docs/issues/7951
> Move variables article to Reference ToC node

- docs/editor/intellisense.md
Fixes https://github.com/microsoft/vscode-docs/issues/8053
> Add color styling to completion icons

- docs/languages/images/powershell/PowerShellExtension.png
- docs/languages/powershell.md
Update docs for PowerShell extension
- Fixes AB#376104
- Fixes #5142
Note: Tick the boxes below that apply to this pull request by putting an `x` between the square brackets.
Please mark anything not applicable to this PR `NA`.
- If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready
> Fixes #5142 - Update docs for PowerShell extension

- docs/cpp/cmake-quickstart.md
"and select and **C++**" => "and select **C++**"
> Small grammar correction

- docs/copilot/copilot-edits.md
Might be worth getting this updated before the release as we see users being confused about this.
> Preview note for agent mode

- docs/terminal/appearance.md
> Add full variable reference for tab text

- docs/terminal/advanced.md
> Document terminal.integrated.hideOnLastClosed

- docs/terminal/basics.md
> Update guidance around macOS invalid key sound

- docs/terminal/advanced.md
Part of microsoft/vscode#126209
See microsoft/vscode#239335
> Mark localEcho settings as preview

- api/extension-guides/command.md
Fixes https://github.com/microsoft/vscode-docs/issues/8128
> Add command title naming convention

- docs/terminal/images/shell-integration/recent-command.png
Fixes https://github.com/microsoft/vscode-docs/issues/8084
> Update screenshot for run recent command

- api/extension-guides/prompt-tsx.md
Fixes https://github.com/microsoft/vscode-docs/issues/8107
> Update unsupported SystemMessage references

- docs/remote/tunnels.md
> Update server doc

- docs/getstarted/tips-and-tricks.md
Fixes https://github.com/microsoft/vscode-docs/issues/8162
> Fix image link

- docs/setup/enterprise.md
ref: https://github.com/microsoft/vscode/issues/148942
> Enterprise: macOS Configuration Policy

- build/sitemap.xml
- docs/copilot/copilot-edits.md
- docs/copilot/images/copilot-edits/agent-mode-tools.png
- docs/copilot/images/mcp-servers/agent-mode-refresh-tools.png
- docs/copilot/images/mcp-servers/agent-mode-select-tools.png
- docs/copilot/images/mcp-servers/chat-mode-agent.png
- docs/copilot/images/mcp-servers/mcp-error-loading-tool.png
- docs/copilot/images/mcp-servers/mcp-list-servers.png
- docs/copilot/images/mcp-servers/mcp-server-config-lenses.png
- docs/copilot/images/mcp-servers/mcp-server-error-output.png
- docs/copilot/images/mcp-servers/mcp-tool-confirmation.png
- docs/copilot/mcp-servers.md
- docs/toc.json
Implements https://github.com/microsoft/vscode-docs/issues/8151
> MCP docs initial draft

- build/sitemap.xml
- docs/copilot/ai-language-models.md
- docs/copilot/ai-powered-suggestions.md
- docs/copilot/copilot-chat.md
- docs/copilot/images/ai-language-models/model-dropdown-change-model.png
- docs/copilot/images/ai-language-models/model-provider-quick-pick.png
- docs/copilot/images/ai-language-models/ollama-installed-models-quick-pick.png
- docs/copilot/images/ai-language-models/reconfigure-model-provider.png
- docs/toc.json
Fixes https://github.com/microsoft/vscode-docs/issues/8170
> Change model docs (includes BYOK)

- docs/setup/enterprise.md
ref https://github.com/microsoft/vscode-internalbacklog/issues/5375
> Enterprise: Document 1.99 Policies

- blogs/2024/04/15/vscode-day.md
- blogs/2024/04/15/vscodeday-promo.png
- blogs/2024/05/08/wasm.md
- blogs/2024/06/07/wasm-part2.md
- blogs/2024/06/24/extensions-are-all-you-need.md
- blogs/2024/11/12/introducing-copilot-edits.md
- blogs/2024/11/15/introducing-github-copilot-for-azure.md
- blogs/2024/11/15/quickstart-create.png
- blogs/2024/12/18/free-github-copilot.md
- blogs/2025/02/12/next-edit-suggestions.md
- blogs/2025/02/24/introducing-copilot-agent-mode.md
- blogs/2025/03/26/custom-instructions.md
- blogs/2025/04/07/agentMode.md
Add social images for blog posts (2024-2025), to be included in RSS feed.
> Add blog post social images

- docs/setup/enterprise.md
https://github.com/microsoft/vscode-docs/issues/8258
> fixes https://github.com/microsoft/vscode-docs/issues/8258

- docs/getstarted/userinterface.md
Fixes https://github.com/microsoft/vscode-docs/issues/8268
> Add info about using modifier to copy editor tab

- api/extension-guides/tools.md
Fixes https://github.com/microsoft/vscode-docs/issues/8290
> Fix docs links

- docs/configure/telemetry.md
Fixes https://github.com/microsoft/vscode/issues/245710
> Update instructions for showing telemetry events

- docs/copilot/language-models.md
Ref: https://github.com/microsoft/vscode-docs/pull/8299
> Update availability for BYOK

- docs/copilot/copilot-customization.md
Fixes https://github.com/microsoft/vscode-docs/issues/8240
> Update Customize Copilot intro and structure

- docs/csharp/cs-dev-kit-faq.md
Context:
https://github.com/microsoft/vscode-dotnettools/issues/1858
> Add FAQ entry for TUnit test discovery issue in Test Explorer

- docs/configure/extensions/extension-marketplace.md
Fixes https://github.com/microsoft/vscode-docs/issues/7819
Ref: https://github.com/microsoft/vscode-docs/pull/8319
/cc @melonchomp
> Document VSCODE_EXTENSIONS environment variable

- docs/copilot/ai-powered-suggestions.md
For parity with https://docs.github.com/en/copilot/using-github-copilot/ai-models/changing-the-ai-model-for-copilot-code-completion#changing-the-ai-model-for-code-completion, updated with Copilot menu
> updated completions model selection instructions

- build/sitemap.xml
- docs/copilot/guides/images/notebooks-with-ai/agent-mode-create-new-notebook.png
- docs/copilot/guides/images/notebooks-with-ai/notebook-agent-mode-data-analysis.png
- docs/copilot/guides/images/notebooks-with-ai/notebook-ask-mode-add-cell-output.png
- docs/copilot/guides/images/notebooks-with-ai/notebook-ask-mode-explain-chart.png
- docs/copilot/guides/images/notebooks-with-ai/notebook-edit-mode-plot-prices.png
- docs/copilot/guides/images/notebooks-with-ai/notebook-inline-chat-response.png
- docs/copilot/guides/images/notebooks-with-ai/notebook-inline-chat.png
- docs/copilot/guides/notebooks-with-ai.md
- docs/toc.json
Fixes https://github.com/microsoft/vscode-docs/issues/8239
> Edit notebooks with AI

- release-notes/v1_100.md
Fixes https://github.com/microsoft/vscode-docs/issues/8352
> Fix links in release notes

- docs/copilot/chat/chat-ask-mode.md
- docs/copilot/chat/copilot-chat.md
Fixes https://github.com/microsoft/vscode-copilot-release/issues/9365
> Fix Quick Chat command ID

- docs/copilot/ai-powered-suggestions.md
Updated based on https://github.com/VSCodeVim/Vim/issues/9459#issuecomment-2884649566
> Update NES vim note

- docs/configure/settings-sync.md
**Switching Accounts** paragraph: This confused me today, I skimmed and missed that what the text was saying was to turn off sync, which in my mind became sign off and sign on again (where you can in fact, try to use another account, not successfully). I did not realize that there were, in fact, a turn off sync command. So, adding this clarification on specifically what command is intended.
[Others](https://github.com/microsoft/vscode/issues/186224) [have](https://github.com/microsoft/vscode/issues/104934) [been](https://stackoverflow.com/questions/79000832/re-sign-in-to-vs-code-using-github-instead-of-microsoft/79000868#79000868) confused too.
> Update settings-sync.md: Adds command title for turning off sync

- docs/languages/cpp.md
- docs/languages/images/cpp/helloworld-terminal-output.png
- docs/languages/images/cpp/run-play-button.png
- docs/languages/images/cpp/select-gcc-compiler.png
Fixes https://github.com/microsoft/vscode-docs/issues/8438
> Update screenshots and indentation

- api/extension-guides/tools.md
Fixes https://github.com/microsoft/vscode-docs/issues/8452
> Fix links in API docs

- api/ux-guidelines/images/examples/quick-pick-multi-select.png
> Update multi-select quickpick image

- docs/intelligentapps/agentbuilder.md
- docs/intelligentapps/images/promptbuilder/add_function_call.png
- docs/intelligentapps/images/promptbuilder/function_call_card.png
- docs/intelligentapps/images/promptbuilder/function_call_eval.png
- Add function calling instructions
- Update alt texts for screenshots
> Refresh AITK Agent Builder Page

- release-notes/v1_101.md
As per the title, this PR fixes some typos in the 1.101 release notes.
> Fix typos in 1.101 release notes

- docs/terminal/basics.md
> Document terminal column selection

- release-notes/v1_102.md
> Mention awesome-copilot

- blogs/2025/07/17/copilot-coding-agent.md
Link to GitHub docs was broken. This PR repairs it.
> Fix broken coding agent link

- docs/editing/workspaces/images/workspace-trust/workspace-trust-dialog.png
Fixes https://github.com/microsoft/vscode-docs/issues/8716
> Fix screenshot

- docs/intelligentapps/images/modelconversion/cloud_conversion_history.png
- docs/intelligentapps/images/modelconversion/cloud_conversion_run.png
- docs/intelligentapps/images/modelconversion/cloud_download.png
- docs/intelligentapps/images/modelconversion/provisioning.png
- docs/intelligentapps/modelconversion.md
- Add a documentation for new feature 'cloud conversion' of model conversion in AI Toolkit
> Add AI Toolkit model conversion new feature doc

- build/sitemap.xml
- docs/copilot/chat/chat-agent-mode.md
- docs/copilot/copilot-tips-and-tricks.md
- docs/copilot/customization/mcp-servers.md
- docs/copilot/customization/overview.md
- docs/copilot/overview.md
- docs/copilot/security.md
- docs/toc.json
- Add AI security article
- Fix invalid crosslinks
Implements https://github.com/microsoft/vscode-docs/issues/8571
> Add security documentation

- .github/instructions/blog-writing.instructions.md
- .github/prompts/review-blog.prompt.md
Introduce guidelines for writing blog posts on the VS Code website, including metadata requirements, content structure, and writing style. A prompt for reviewing blog posts for clarity and adherence to these guidelines is also included.
> Add instructions and prompt for blog writing

- docs/copilot/chat/chat-agent-mode.md
> Remove statement about inline commands

- docs/copilot/copilot-coding-agent.md
- docs/copilot/images/copilot-coding-agent/coding-agent-todo.png
Update based on https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_104.md and feedback (fixes https://github.com/microsoft/vscode/issues/264943).
> Coding agent doc updates
